In [36]:
# from logit_model import *
import statsmodels.api as sm
import matplotlib.pyplot as plt
from tqdm import tqdm
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [37]:
import sys
import os

# Add parent directory to sys.path
parent_dir = os.path.abspath(os.path.join(os.getcwd(), os.pardir))
sys.path.append(parent_dir)

In [38]:
import pandas as pd

In [39]:
import package_files.benefits_defns as benefits_defns

In [40]:
import importlib 
importlib.reload(benefits_defns)
from package_files.benefits_defns import *

In [41]:
benefits4

['EDU_ASSISTANCE',
 'WLB',
 'PAID_LEAVE',
 'HEALTH_WELLBEING',
 'PARENTAL_LEAVE',
 'CULTURE']

In [31]:
from package_files.logit_model import *

In [32]:
path = '../data/us_10m_nointernship_ai_skills_benefits.parquet.gzip'

In [33]:
if path[-3:] == 'csv:':
    df = pd.read_csv(path)
elif path[-3:] == 'zip':
    df = pd.read_parquet(path)

In [34]:
df.columns

Index(['ID', 'CITY_NAME', 'COUNTY_NAME', 'STATE_NAME', 'NAICS_2022_2',
       'NAICS_2022_2_NAME', 'MIN_EDULEVELS_NAME', 'EMPLOYMENT_TYPE',
       'EMPLOYMENT_TYPE_NAME', 'IS_INTERNSHIP', 'REMOTE_TYPE',
       'REMOTE_TYPE_NAME', 'SKILLS', 'SKILLS_NAME', 'POSTED',
       'LAST_UPDATED_DATE', 'ONET', 'ONET_NAME', 'ONET_2019', 'ONET_2019_NAME',
       'SOC_2021_2_NAME', 'SOC_2021_2', 'MIN_YEARS_EXPERIENCE', 'COMPANY',
       'COMPANY_NAME', 'COMPANY_RAW', 'AI ROLE', 'wfh_wham_prob', 'wfh_wham',
       'YEAR', 'EDU_ASSISTANCE', 'WLB', 'PAID_LEAVE', 'HEALTH_WELLBEING',
       'PARENTAL_LEAVE', 'CULTURE', 'EXPERIENCE_BUCKET', 'SALARY',
       'LOG_SALARY'],
      dtype='object')

In [15]:
occupations_select = ['Architecture and Engineering Occupations','Arts, Design, Entertainment, Sports, and Media Occupations','Business and Financial Operations Occupations','Community and Social Service Occupations','Computer and Mathematical Occupations',
'Educational Instruction and Library Occupations',
'Healthcare Practitioners and Technical Occupations',
'Legal Occupations',
'Life, Physical, and Social Science Occupations',
'Management Occupations', 
'Office and Administrative Support Occupations',
'Personal Care and Service Occupations', 'Production Occupations',
'Sales and Related Occupations',
'Transportation and Material Moving Occupations',
]

In [16]:
df_select = df[df[occupation].isin(occupations_select)]

In [17]:
years = df['YEAR'].unique()

In [21]:
years

array([2019, 2021, 2022, 2020, 2018, 2023], dtype=int32)

In [20]:
df_select[df_select[occupation] == 'Architecture and Engineering Occupations'].groupby('YEAR').count()

,ID,CITY_NAME,COUNTY_NAME,STATE_NAME,NAICS_2022_2,NAICS_2022_2_NAME,MIN_EDULEVELS_NAME,EMPLOYMENT_TYPE,EMPLOYMENT_TYPE_NAME,IS_INTERNSHIP,...,wfh_wham,EDU_ASSISTANCE,WLB,LEAVE,HEALTH_WELLBEING,PARENTAL_LEAVE,CULTURE,EXPERIENCE_BUCKET,SALARY,LOG_SALARY
YEAR,,,,,,,,,,,,,,,,,,,,,
2018,40569,40569,40543,40569,40569,40569,40569,40569,40569,40569,...,15,40569,40569,40569,40569,40569,40569,40569,4994,4994
2019,42432,42432,42409,42432,42432,42432,42432,42432,42432,42432,...,41213,42432,42432,42432,42432,42432,42432,42432,4920,4920
2020,33522,33522,33514,33522,33522,33522,33522,33522,33522,33522,...,33182,33522,33522,33522,33522,33522,33522,33522,5104,5104
2021,42098,42098,42078,42098,42098,42098,42098,42098,42098,42098,...,41963,42098,42098,42098,42098,42098,42098,42098,7372,7372
2022,57103,57103,57083,57103,57103,57103,57103,57103,57103,57103,...,56350,57103,57103,57103,57103,57103,57103,57103,10769,10769
2023,46241,46241,46235,46241,46241,46241,46241,46241,46241,46241,...,45933,46241,46241,46241,46241,46241,46241,46241,15691,15691

In [36]:
def get_occ_year_data(df, occ, year):
    """
    Filter the DataFrame to include only rows with the specified occupation and year.

    Args:
        df (pd.DataFrame): The input DataFrame containing the data.
        occ (str): The occupation to filter by.
        year (int): The year to filter by.

    Returns:
        pd.DataFrame: A new DataFrame containing only the rows that match the specified occupation and year.
    """
    df_occ_year = df[(df[occupation] == occ) & (df['YEAR'] == year)].copy()
    return df_occ_year

In [39]:
models_dict = {}
for benefit in benefits4[2:]:
    print(benefit)
    for occ, year in tqdm([(occ, year) for occ in occupations_select for year in years]):
        print(occ, year)
        df_occ_year = get_occ_year_data(df_select, occ, year)
        # print length of df_occ_year
        print("df length:", len(df_occ_year))
        model = run_logit_model(df_occ_year, dependent = benefit, predictor = 'AI ROLE', cat_controls = [education, experience], ref_category = {education: "No Education Listed", experience: 'None Listed'})
        models_dict[(benefit, occ, year)] = model

LEAVE

  0%|          | 0/90 [00:00<?, ?it/s]

Architecture and Engineering Occupations 2019

  1%|          | 1/90 [00:00<01:18,  1.14it/s]

df length: 42432
Optimization terminated successfully.
         Current function value: 0.355468
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:                42432
Model:                          Logit   Df Residuals:                    42420
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.006437
Time:                        23:53:45   Log-Likelihood:                -15083.
converged:                       True   LL-Null:                       -15181.
Covariance Type:            nonrobust   LLR p-value:                 6.605e-36
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.0735      0.032    -65.617      0.000      -2.135      -2.012
AI ROLE                         -0.3017      0.126     -2.400      0.016      -0.548      -0.055
Associate degree                 0.0306      0.062      0.490      0.624      -0.092       0.153
Bachelor's degree               -0.1821      0.038     -4.803      0.000      -0.256      -0.108
High school or GED              -0.1056      0.052     -2.018      0.044      -0.208      -0.003
Master's degree                 -0.4636      0.123     -3.783      0.000      -0.704      -0.223
Ph.D. or professional degree    -0.6915      0.239     -2.888      0.004      -1.161      -0.222
0 years                          0.5001      0.087      5.732      0.000       0.329       0.671
1-2 years                        0.3660      0.047      7.772      0.000       0.274       0.458
11-20 years                     -0.3140      0.133     -2.369      0.018      -0.574      -0.054
3-5 years                        0.3007      0.039      7.660      0.000       0.224       0.378
6-10 years                      -0.0418      0.053     -0.791      0.429      -0.145       0.062
================================================================================================
Architecture and Engineering Occupations 2021

  2%|▏         | 2/90 [00:01<01:19,  1.10it/s]

df length: 42098
Optimization terminated successfully.
         Current function value: 0.499071
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:                42098
Model:                          Logit   Df Residuals:                    42086
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.007952
Time:                        23:53:46   Log-Likelihood:                -21010.
converged:                       True   LL-Null:                       -21178.
Covariance Type:            nonrobust   LLR p-value:                 1.474e-65
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.4315      0.026    -55.350      0.000      -1.482      -1.381
AI ROLE                         -0.6245      0.104     -5.991      0.000      -0.829      -0.420
Associate degree                 0.3554      0.048      7.364      0.000       0.261       0.450
Bachelor's degree                0.0031      0.032      0.098      0.922      -0.060       0.066
High school or GED               0.3803      0.038      9.922      0.000       0.305       0.455
Master's degree                 -0.1539      0.099     -1.559      0.119      -0.347       0.040
Ph.D. or professional degree    -0.4818      0.185     -2.606      0.009      -0.844      -0.119
0 years                          0.2955      0.070      4.208      0.000       0.158       0.433
1-2 years                        0.0258      0.038      0.685      0.493      -0.048       0.099
11-20 years                      0.0316      0.083      0.378      0.705      -0.132       0.195
3-5 years                       -0.0045      0.032     -0.142      0.887      -0.066       0.057
6-10 years                      -0.2430      0.043     -5.670      0.000      -0.327      -0.159
================================================================================================
Architecture and Engineering Occupations 2022

  3%|▎         | 3/90 [00:02<01:18,  1.10it/s]

df length: 57103
Optimization terminated successfully.
         Current function value: 0.530178
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:                57103
Model:                          Logit   Df Residuals:                    57091
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01079
Time:                        23:53:47   Log-Likelihood:                -30275.
converged:                       True   LL-Null:                       -30605.
Covariance Type:            nonrobust   LLR p-value:                1.636e-134
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.5242      0.022    -68.457      0.000      -1.568      -1.481
AI ROLE                         -0.4123      0.075     -5.486      0.000      -0.560      -0.265
Associate degree                 0.4290      0.041     10.344      0.000       0.348       0.510
Bachelor's degree                0.2204      0.027      8.173      0.000       0.168       0.273
High school or GED               0.6239      0.034     18.498      0.000       0.558       0.690
Master's degree                 -0.3757      0.091     -4.140      0.000      -0.554      -0.198
Ph.D. or professional degree    -0.2406      0.152     -1.582      0.114      -0.539       0.058
0 years                          0.3678      0.060      6.173      0.000       0.251       0.485
1-2 years                        0.2285      0.031      7.315      0.000       0.167       0.290
11-20 years                      0.0218      0.064      0.342      0.732      -0.103       0.147
3-5 years                        0.1252      0.027      4.706      0.000       0.073       0.177
6-10 years                       0.0069      0.034      0.204      0.838      -0.059       0.073
================================================================================================
Architecture and Engineering Occupations 2020

  4%|▍         | 4/90 [00:03<01:07,  1.27it/s]

df length: 33522
Optimization terminated successfully.
         Current function value: 0.442662
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:                33522
Model:                          Logit   Df Residuals:                    33510
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.008715
Time:                        23:53:47   Log-Likelihood:                -14839.
converged:                       True   LL-Null:                       -14969.
Covariance Type:            nonrobust   LLR p-value:                 1.432e-49
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.6252      0.030    -54.452      0.000      -1.684      -1.567
AI ROLE                         -0.5160      0.134     -3.841      0.000      -0.779      -0.253
Associate degree                 0.0202      0.060      0.335      0.738      -0.098       0.138
Bachelor's degree               -0.2639      0.037     -7.072      0.000      -0.337      -0.191
High school or GED               0.1379      0.046      2.977      0.003       0.047       0.229
Master's degree                 -0.5093      0.118     -4.303      0.000      -0.741      -0.277
Ph.D. or professional degree    -0.8979      0.241     -3.723      0.000      -1.371      -0.425
0 years                          0.3449      0.095      3.636      0.000       0.159       0.531
1-2 years                        0.1761      0.047      3.766      0.000       0.084       0.268
11-20 years                     -0.0720      0.107     -0.670      0.503      -0.282       0.139
3-5 years                        0.3060      0.038      8.116      0.000       0.232       0.380
6-10 years                      -0.0768      0.052     -1.477      0.140      -0.179       0.025
================================================================================================
Architecture and Engineering Occupations 2018

  6%|▌         | 5/90 [00:03<01:01,  1.37it/s]

df length: 40569
Optimization terminated successfully.
         Current function value: 0.283368
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:                40569
Model:                          Logit   Df Residuals:                    40557
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.004533
Time:                        23:53:48   Log-Likelihood:                -11496.
converged:                       True   LL-Null:                       -11548.
Covariance Type:            nonrobust   LLR p-value:                 2.087e-17
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.5160      0.037    -67.836      0.000      -2.589      -2.443
AI ROLE                         -0.2996      0.165     -1.818      0.069      -0.623       0.023
Associate degree                -0.0648      0.075     -0.867      0.386      -0.211       0.082
Bachelor's degree               -0.1042      0.045     -2.294      0.022      -0.193      -0.015
High school or GED               0.0013      0.063      0.021      0.983      -0.122       0.124
Master's degree                 -0.2643      0.137     -1.930      0.054      -0.533       0.004
Ph.D. or professional degree    -1.1208      0.385     -2.910      0.004      -1.876      -0.366
0 years                          0.6264      0.103      6.064      0.000       0.424       0.829
1-2 years                        0.3095      0.057      5.447      0.000       0.198       0.421
11-20 years                      0.3062      0.132      2.328      0.020       0.048       0.564
3-5 years                        0.3116      0.047      6.651      0.000       0.220       0.403
6-10 years                       0.0239      0.065      0.369      0.712      -0.103       0.151
================================================================================================
Architecture and Engineering Occupations 2023

  7%|▋         | 6/90 [00:04<00:57,  1.45it/s]

df length: 46241
Optimization terminated successfully.
         Current function value: 0.608641
         Iterations 5
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:                46241
Model:                          Logit   Df Residuals:                    46229
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.006857
Time:                        23:53:48   Log-Likelihood:                -28144.
converged:                       True   LL-Null:                       -28338.
Covariance Type:            nonrobust   LLR p-value:                 1.586e-76
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.1518      0.023    -49.618      0.000      -1.197      -1.106
AI ROLE                         -0.2041      0.071     -2.872      0.004      -0.343      -0.065
Associate degree                 0.3220      0.043      7.509      0.000       0.238       0.406
Bachelor's degree                0.2381      0.027      8.793      0.000       0.185       0.291
High school or GED               0.4059      0.036     11.430      0.000       0.336       0.475
Master's degree                 -0.0951      0.085     -1.115      0.265      -0.262       0.072
Ph.D. or professional degree    -0.3392      0.147     -2.314      0.021      -0.626      -0.052
0 years                          0.3738      0.059      6.317      0.000       0.258       0.490
1-2 years                        0.2671      0.032      8.284      0.000       0.204       0.330
11-20 years                      0.1334      0.061      2.195      0.028       0.014       0.253
3-5 years                        0.1849      0.027      6.907      0.000       0.132       0.237
6-10 years                       0.0480      0.034      1.429      0.153      -0.018       0.114
================================================================================================
Arts, Design, Entertainment, Sports, and Media Occupations 2019

  8%|▊         | 7/90 [00:05<00:55,  1.49it/s]

df length: 40594
Optimization terminated successfully.
         Current function value: 0.291234
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:                40594
Model:                          Logit   Df Residuals:                    40582
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01154
Time:                        23:53:49   Log-Likelihood:                -11822.
converged:                       True   LL-Null:                       -11960.
Covariance Type:            nonrobust   LLR p-value:                 1.002e-52
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.6249      0.030    -88.827      0.000      -2.683      -2.567
AI ROLE                         -0.0536      0.197     -0.272      0.785      -0.439       0.332
Associate degree                 0.7873      0.087      9.048      0.000       0.617       0.958
Bachelor's degree                0.2964      0.046      6.509      0.000       0.207       0.386
High school or GED               0.2982      0.049      6.079      0.000       0.202       0.394
Master's degree                 -0.2190      0.186     -1.180      0.238      -0.583       0.145
Ph.D. or professional degree     0.1731      0.304      0.569      0.569      -0.423       0.769
0 years                         -0.7494      0.159     -4.718      0.000      -1.061      -0.438
1-2 years                        0.2813      0.048      5.875      0.000       0.187       0.375
11-20 years                     -0.2371      0.227     -1.042      0.297      -0.683       0.209
3-5 years                        0.3257      0.049      6.650      0.000       0.230       0.422
6-10 years                      -0.0589      0.091     -0.644      0.519      -0.238       0.120
================================================================================================
Arts, Design, Entertainment, Sports, and Media Occupations 2021

  9%|▉         | 8/90 [00:05<00:54,  1.52it/s]

df length: 49779
Optimization terminated successfully.
         Current function value: 0.433297
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:                49779
Model:                          Logit   Df Residuals:                    49767
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01926
Time:                        23:53:50   Log-Likelihood:                -21569.
converged:                       True   LL-Null:                       -21993.
Covariance Type:            nonrobust   LLR p-value:                1.286e-174
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.9715      0.020    -96.490      0.000      -2.012      -1.931
AI ROLE                         -0.2929      0.149     -1.962      0.050      -0.585      -0.000
Associate degree                 0.9626      0.065     14.729      0.000       0.834       1.091
Bachelor's degree                0.5768      0.033     17.233      0.000       0.511       0.642
High school or GED               0.6611      0.031     21.199      0.000       0.600       0.722
Master's degree                  0.0957      0.148      0.646      0.518      -0.195       0.386
Ph.D. or professional degree    -0.3916      0.316     -1.238      0.216      -1.012       0.228
0 years                         -0.9471      0.096     -9.849      0.000      -1.136      -0.759
1-2 years                       -0.0884      0.035     -2.541      0.011      -0.157      -0.020
11-20 years                      0.0628      0.168      0.373      0.709      -0.267       0.393
3-5 years                        0.1470      0.037      4.014      0.000       0.075       0.219
6-10 years                      -0.1476      0.065     -2.271      0.023      -0.275      -0.020
================================================================================================
Arts, Design, Entertainment, Sports, and Media Occupations 2022

 10%|█         | 9/90 [00:06<00:53,  1.52it/s]

df length: 54182
Optimization terminated successfully.
         Current function value: 0.455619
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:                54182
Model:                          Logit   Df Residuals:                    54170
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02224
Time:                        23:53:50   Log-Likelihood:                -24686.
converged:                       True   LL-Null:                       -25248.
Covariance Type:            nonrobust   LLR p-value:                5.619e-234
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.8857      0.018   -103.946      0.000      -1.921      -1.850
AI ROLE                          0.0221      0.112      0.196      0.844      -0.198       0.242
Associate degree                 0.6143      0.062      9.943      0.000       0.493       0.735
Bachelor's degree                0.3871      0.031     12.503      0.000       0.326       0.448
High school or GED               0.7697      0.030     25.317      0.000       0.710       0.829
Master's degree                 -0.0691      0.138     -0.501      0.616      -0.339       0.201
Ph.D. or professional degree     0.4403      0.206      2.138      0.033       0.037       0.844
0 years                         -0.8405      0.090     -9.289      0.000      -1.018      -0.663
1-2 years                        0.1303      0.033      3.938      0.000       0.065       0.195
11-20 years                      0.0039      0.151      0.026      0.979      -0.292       0.300
3-5 years                        0.3629      0.033     11.040      0.000       0.298       0.427
6-10 years                       0.1118      0.056      2.006      0.045       0.003       0.221
================================================================================================
Arts, Design, Entertainment, Sports, and Media Occupations 2020

 11%|█         | 10/90 [00:07<00:51,  1.55it/s]

df length: 39617
Optimization terminated successfully.
         Current function value: 0.333295
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:                39617
Model:                          Logit   Df Residuals:                    39605
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01422
Time:                        23:53:51   Log-Likelihood:                -13204.
converged:                       True   LL-Null:                       -13395.
Covariance Type:            nonrobust   LLR p-value:                 6.875e-75
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.3334      0.027    -87.566      0.000      -2.386      -2.281
AI ROLE                         -0.3288      0.226     -1.457      0.145      -0.771       0.113
Associate degree                 0.8333      0.089      9.405      0.000       0.660       1.007
Bachelor's degree                0.3616      0.045      8.057      0.000       0.274       0.450
High school or GED               0.0810      0.042      1.923      0.055      -0.002       0.164
Master's degree                 -0.5902      0.227     -2.598      0.009      -1.035      -0.145
Ph.D. or professional degree     0.2063      0.298      0.692      0.489      -0.378       0.790
0 years                         -0.7797      0.116     -6.702      0.000      -1.008      -0.552
1-2 years                        0.2618      0.046      5.737      0.000       0.172       0.351
11-20 years                      0.2586      0.219      1.179      0.239      -0.171       0.689
3-5 years                        0.3206      0.049      6.545      0.000       0.225       0.417
6-10 years                       0.0887      0.085      1.043      0.297      -0.078       0.255
================================================================================================
Arts, Design, Entertainment, Sports, and Media Occupations 2018

 12%|█▏        | 11/90 [00:07<00:50,  1.58it/s]

df length: 37105
Optimization terminated successfully.
         Current function value: 0.257059
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:                37105
Model:                          Logit   Df Residuals:                    37093
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.003856
Time:                        23:53:51   Log-Likelihood:                -9538.2
converged:                       True   LL-Null:                       -9575.1
Covariance Type:            nonrobust   LLR p-value:                 2.267e-11
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.6575      0.031    -84.958      0.000      -2.719      -2.596
AI ROLE                          0.0289      0.271      0.107      0.915      -0.502       0.559
Associate degree                 0.1709      0.110      1.547      0.122      -0.046       0.387
Bachelor's degree               -0.0026      0.052     -0.051      0.959      -0.104       0.099
High school or GED              -0.0124      0.059     -0.212      0.832      -0.127       0.102
Master's degree                 -0.9535      0.285     -3.347      0.001      -1.512      -0.395
Ph.D. or professional degree    -0.7501      0.457     -1.641      0.101      -1.646       0.146
0 years                         -0.1332      0.182     -0.731      0.465      -0.490       0.224
1-2 years                        0.2778      0.055      5.054      0.000       0.170       0.386
11-20 years                     -0.8021      0.340     -2.360      0.018      -1.468      -0.136
3-5 years                        0.2501      0.058      4.314      0.000       0.136       0.364
6-10 years                       0.2203      0.094      2.339      0.019       0.036       0.405
================================================================================================
Arts, Design, Entertainment, Sports, and Media Occupations 2023

 13%|█▎        | 12/90 [00:08<00:49,  1.59it/s]

df length: 40306
Optimization terminated successfully.
         Current function value: 0.493842
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:                40306
Model:                          Logit   Df Residuals:                    40294
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.03807
Time:                        23:53:52   Log-Likelihood:                -19905.
converged:                       True   LL-Null:                       -20693.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.8274      0.020    -91.737      0.000      -1.866      -1.788
AI ROLE                         -0.1847      0.110     -1.677      0.094      -0.401       0.031
Associate degree                 0.8505      0.066     12.945      0.000       0.722       0.979
Bachelor's degree                0.5663      0.034     16.889      0.000       0.501       0.632
High school or GED               0.8277      0.034     24.321      0.000       0.761       0.894
Master's degree                 -0.0450      0.151     -0.298      0.765      -0.341       0.251
Ph.D. or professional degree     0.8163      0.193      4.237      0.000       0.439       1.194
0 years                         -0.2313      0.081     -2.846      0.004      -0.391      -0.072
1-2 years                        0.3480      0.036      9.679      0.000       0.278       0.419
11-20 years                      0.1405      0.157      0.896      0.370      -0.167       0.448
3-5 years                        0.5647      0.037     15.460      0.000       0.493       0.636
6-10 years                       0.5492      0.057      9.701      0.000       0.438       0.660
================================================================================================
Business and Financial Operations Occupations 2019
df length: 141921
Optimization terminated successfully.
         Current function value: 0.361859
         Iterations 7

 14%|█▍        | 13/90 [00:09<00:55,  1.39it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:               141921
Model:                          Logit   Df Residuals:                   141909
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.005926
Time:                        23:53:53   Log-Likelihood:                -51355.
converged:                       True   LL-Null:                       -51661.
Covariance Type:            nonrobust   LLR p-value:                3.321e-124
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.0709      0.016   -126.231      0.000      -2.103      -2.039
AI ROLE                         -0.2210      0.075     -2.932      0.003      -0.369      -0.073
Associate degree                 0.4123      0.040     10.319      0.000       0.334       0.491
Bachelor's degree                0.0319      0.020      1.571      0.116      -0.008       0.072
High school or GED               0.2048      0.028      7.340      0.000       0.150       0.260
Master's degree                 -0.3380      0.080     -4.234      0.000      -0.495      -0.182
Ph.D. or professional degree    -0.8606      0.225     -3.830      0.000      -1.301      -0.420
0 years                          0.2586      0.058      4.466      0.000       0.145       0.372
1-2 years                        0.1774      0.023      7.852      0.000       0.133       0.222
11-20 years                     -0.3953      0.099     -3.976      0.000      -0.590      -0.200
3-5 years                        0.0313      0.021      1.462      0.144      -0.011       0.073
6-10 years                      -0.4299      0.036    -12.075      0.000      -0.500      -0.360
================================================================================================
Business and Financial Operations Occupations 2021
df length: 158377
Optimization terminated successfully.
         Current function value: 0.528101
         Iterations 6

 16%|█▌        | 14/90 [00:10<00:59,  1.27it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:               158377
Model:                          Logit   Df Residuals:                   158365
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.009746
Time:                        23:53:54   Log-Likelihood:                -83639.
converged:                       True   LL-Null:                       -84462.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.4557      0.013   -112.906      0.000      -1.481      -1.430
AI ROLE                         -0.1378      0.046     -2.975      0.003      -0.229      -0.047
Associate degree                 0.6255      0.029     21.485      0.000       0.568       0.683
Bachelor's degree                0.1909      0.015     12.469      0.000       0.161       0.221
High school or GED               0.5793      0.019     30.177      0.000       0.542       0.617
Master's degree                 -0.3520      0.065     -5.439      0.000      -0.479      -0.225
Ph.D. or professional degree    -0.7125      0.139     -5.120      0.000      -0.985      -0.440
0 years                         -0.0653      0.048     -1.375      0.169      -0.158       0.028
1-2 years                        0.0939      0.017      5.650      0.000       0.061       0.126
11-20 years                     -0.4022      0.072     -5.608      0.000      -0.543      -0.262
3-5 years                        0.0556      0.016      3.574      0.000       0.025       0.086
6-10 years                      -0.2217      0.024     -9.076      0.000      -0.270      -0.174
================================================================================================
Business and Financial Operations Occupations 2022
df length: 182061
Optimization terminated successfully.
         Current function value: 0.559613
         Iterations 6

 17%|█▋        | 15/90 [00:11<01:03,  1.18it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:               182061
Model:                          Logit   Df Residuals:                   182049
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.009885
Time:                        23:53:55   Log-Likelihood:            -1.0188e+05
converged:                       True   LL-Null:                   -1.0290e+05
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.3682      0.012   -118.679      0.000      -1.391      -1.346
AI ROLE                         -0.2686      0.041     -6.534      0.000      -0.349      -0.188
Associate degree                 0.4603      0.027     17.182      0.000       0.408       0.513
Bachelor's degree                0.1971      0.014     14.158      0.000       0.170       0.224
High school or GED               0.5106      0.018     28.105      0.000       0.475       0.546
Master's degree                 -0.2278      0.055     -4.154      0.000      -0.335      -0.120
Ph.D. or professional degree    -1.1535      0.137     -8.399      0.000      -1.423      -0.884
0 years                         -0.0663      0.042     -1.585      0.113      -0.148       0.016
1-2 years                        0.2718      0.015     17.798      0.000       0.242       0.302
11-20 years                     -0.2587      0.058     -4.464      0.000      -0.372      -0.145
3-5 years                        0.1720      0.014     12.025      0.000       0.144       0.200
6-10 years                      -0.0781      0.021     -3.683      0.000      -0.120      -0.037
================================================================================================
Business and Financial Operations Occupations 2020
df length: 125072
Optimization terminated successfully.
         Current function value: 0.456211
         Iterations 7

 18%|█▊        | 16/90 [00:12<01:02,  1.18it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:               125072
Model:                          Logit   Df Residuals:                   125060
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01619
Time:                        23:53:56   Log-Likelihood:                -57059.
converged:                       True   LL-Null:                       -57998.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.6177      0.015   -110.576      0.000      -1.646      -1.589
AI ROLE                         -0.4479      0.073     -6.102      0.000      -0.592      -0.304
Associate degree                 0.4565      0.037     12.407      0.000       0.384       0.529
Bachelor's degree               -0.0289      0.018     -1.579      0.114      -0.065       0.007
High school or GED               0.4295      0.024     18.004      0.000       0.383       0.476
Master's degree                 -0.6422      0.084     -7.670      0.000      -0.806      -0.478
Ph.D. or professional degree    -0.9758      0.204     -4.786      0.000      -1.375      -0.576
0 years                          0.8687      0.041     21.438      0.000       0.789       0.948
1-2 years                        0.1310      0.021      6.266      0.000       0.090       0.172
11-20 years                     -0.5882      0.097     -6.039      0.000      -0.779      -0.397
3-5 years                        0.0191      0.019      0.988      0.323      -0.019       0.057
6-10 years                      -0.4862      0.033    -14.646      0.000      -0.551      -0.421
================================================================================================
Business and Financial Operations Occupations 2018
df length: 139740
Optimization terminated successfully.
         Current function value: 0.296485
         Iterations 7

 19%|█▉        | 17/90 [00:12<01:02,  1.16it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:               139740
Model:                          Logit   Df Residuals:                   139728
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.003409
Time:                        23:53:57   Log-Likelihood:                -41431.
converged:                       True   LL-Null:                       -41572.
Covariance Type:            nonrobust   LLR p-value:                 2.642e-54
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.3597      0.019   -126.392      0.000      -2.396      -2.323
AI ROLE                         -0.0545      0.081     -0.676      0.499      -0.213       0.103
Associate degree                 0.2388      0.048      4.994      0.000       0.145       0.333
Bachelor's degree               -0.0488      0.023     -2.091      0.037      -0.095      -0.003
High school or GED               0.1017      0.033      3.066      0.002       0.037       0.167
Master's degree                 -0.2437      0.086     -2.824      0.005      -0.413      -0.075
Ph.D. or professional degree    -0.4395      0.216     -2.036      0.042      -0.863      -0.016
0 years                          0.0671      0.079      0.848      0.396      -0.088       0.222
1-2 years                        0.2165      0.026      8.205      0.000       0.165       0.268
11-20 years                     -0.2800      0.109     -2.560      0.010      -0.494      -0.066
3-5 years                        0.0331      0.025      1.341      0.180      -0.015       0.082
6-10 years                      -0.2802      0.039     -7.227      0.000      -0.356      -0.204
================================================================================================
Business and Financial Operations Occupations 2023
df length: 124651
Optimization terminated successfully.
         Current function value: 0.616553
         Iterations 6

 20%|██        | 18/90 [00:13<01:01,  1.18it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:               124651
Model:                          Logit   Df Residuals:                   124639
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01190
Time:                        23:53:58   Log-Likelihood:                -76854.
converged:                       True   LL-Null:                       -77780.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.1721      0.013    -89.880      0.000      -1.198      -1.147
AI ROLE                         -0.1911      0.046     -4.111      0.000      -0.282      -0.100
Associate degree                 0.4917      0.030     16.129      0.000       0.432       0.551
Bachelor's degree                0.2262      0.016     14.343      0.000       0.195       0.257
High school or GED               0.3984      0.021     19.269      0.000       0.358       0.439
Master's degree                 -0.0504      0.056     -0.901      0.368      -0.160       0.059
Ph.D. or professional degree    -0.7016      0.120     -5.853      0.000      -0.937      -0.467
0 years                          0.0265      0.047      0.563      0.573      -0.066       0.119
1-2 years                        0.3981      0.018     22.504      0.000       0.363       0.433
11-20 years                      0.0728      0.056      1.291      0.197      -0.038       0.183
3-5 years                        0.3550      0.016     21.710      0.000       0.323       0.387
6-10 years                       0.1844      0.023      8.133      0.000       0.140       0.229
================================================================================================
Community and Social Service Occupations 2019

 21%|██        | 19/90 [00:14<00:54,  1.30it/s]

df length: 30528
Optimization terminated successfully.
         Current function value: 0.476994
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:                30528
Model:                          Logit   Df Residuals:                    30516
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.009992
Time:                        23:53:58   Log-Likelihood:                -14562.
converged:                       True   LL-Null:                       -14709.
Covariance Type:            nonrobust   LLR p-value:                 1.656e-56
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.8194      0.034    -53.760      0.000      -1.886      -1.753
AI ROLE                         -1.0185      0.468     -2.179      0.029      -1.935      -0.102
Associate degree                 0.2219      0.071      3.106      0.002       0.082       0.362
Bachelor's degree                0.4797      0.044     10.950      0.000       0.394       0.566
High school or GED               0.3445      0.046      7.517      0.000       0.255       0.434
Master's degree                  0.2520      0.049      5.176      0.000       0.157       0.347
Ph.D. or professional degree     0.1623      0.191      0.851      0.395      -0.211       0.536
0 years                          0.5837      0.092      6.377      0.000       0.404       0.763
1-2 years                        0.2404      0.034      7.032      0.000       0.173       0.307
11-20 years                     -0.3386      0.442     -0.765      0.444      -1.206       0.528
3-5 years                       -0.1790      0.047     -3.829      0.000      -0.271      -0.087
6-10 years                       0.0590      0.116      0.507      0.612      -0.169       0.287
================================================================================================
Community and Social Service Occupations 2021

 22%|██▏       | 20/90 [00:14<00:50,  1.39it/s]

df length: 39363
Optimization terminated successfully.
         Current function value: 0.617772
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:                39363
Model:                          Logit   Df Residuals:                    39351
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01547
Time:                        23:53:59   Log-Likelihood:                -24317.
converged:                       True   LL-Null:                       -24699.
Covariance Type:            nonrobust   LLR p-value:                9.814e-157
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.3018      0.026    -50.719      0.000      -1.352      -1.252
AI ROLE                         -2.0440      0.517     -3.957      0.000      -3.056      -1.032
Associate degree                 0.5905      0.051     11.567      0.000       0.490       0.691
Bachelor's degree                0.6797      0.034     20.098      0.000       0.613       0.746
High school or GED               0.7525      0.033     22.546      0.000       0.687       0.818
Master's degree                  0.6004      0.036     16.652      0.000       0.530       0.671
Ph.D. or professional degree     0.5559      0.102      5.443      0.000       0.356       0.756
0 years                          0.3386      0.071      4.740      0.000       0.199       0.479
1-2 years                        0.1023      0.026      3.996      0.000       0.052       0.152
11-20 years                     -0.7484      0.371     -2.017      0.044      -1.476      -0.021
3-5 years                       -0.0872      0.034     -2.572      0.010      -0.154      -0.021
6-10 years                      -0.1718      0.101     -1.696      0.090      -0.370       0.027
================================================================================================
Community and Social Service Occupations 2022

 23%|██▎       | 21/90 [00:15<00:47,  1.46it/s]

df length: 46564
Optimization terminated successfully.
         Current function value: 0.635642
         Iterations 5
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:                46564
Model:                          Logit   Df Residuals:                    46552
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01451
Time:                        23:53:59   Log-Likelihood:                -29598.
converged:                       True   LL-Null:                       -30034.
Covariance Type:            nonrobust   LLR p-value:                7.686e-180
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.0838      0.022    -49.999      0.000      -1.126      -1.041
AI ROLE                         -0.9064      0.243     -3.736      0.000      -1.382      -0.431
Associate degree                 0.6224      0.044     14.027      0.000       0.535       0.709
Bachelor's degree                0.5055      0.029     17.273      0.000       0.448       0.563
High school or GED               0.6196      0.030     20.861      0.000       0.561       0.678
Master's degree                  0.2768      0.032      8.601      0.000       0.214       0.340
Ph.D. or professional degree    -0.0532      0.087     -0.615      0.539      -0.223       0.116
0 years                         -0.1168      0.060     -1.960      0.050      -0.234   -2.88e-06
1-2 years                        0.2317      0.023     10.004      0.000       0.186       0.277
11-20 years                     -0.1534      0.253     -0.606      0.545      -0.650       0.343
3-5 years                        0.0858      0.031      2.807      0.005       0.026       0.146
6-10 years                      -0.1247      0.087     -1.441      0.150      -0.294       0.045
================================================================================================
Community and Social Service Occupations 2020

 24%|██▍       | 22/90 [00:16<00:44,  1.54it/s]

df length: 30962
Optimization terminated successfully.
         Current function value: 0.553996
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:                30962
Model:                          Logit   Df Residuals:                    30950
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01097
Time:                        23:54:00   Log-Likelihood:                -17153.
converged:                       True   LL-Null:                       -17343.
Covariance Type:            nonrobust   LLR p-value:                 7.881e-75
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.5357      0.030    -50.502      0.000      -1.595      -1.476
AI ROLE                         -0.6168      0.412     -1.497      0.134      -1.425       0.191
Associate degree                 0.3564      0.063      5.640      0.000       0.233       0.480
Bachelor's degree                0.5595      0.040     13.969      0.000       0.481       0.638
High school or GED               0.5047      0.041     12.405      0.000       0.425       0.584
Master's degree                  0.4202      0.043      9.727      0.000       0.336       0.505
Ph.D. or professional degree    -0.1145      0.163     -0.704      0.481      -0.433       0.204
0 years                          0.5761      0.086      6.694      0.000       0.407       0.745
1-2 years                        0.1560      0.031      5.056      0.000       0.096       0.216
11-20 years                     -0.5688      0.446     -1.276      0.202      -1.442       0.305
3-5 years                       -0.0720      0.042     -1.732      0.083      -0.153       0.009
6-10 years                      -0.2087      0.122     -1.708      0.088      -0.448       0.031
================================================================================================
Community and Social Service Occupations 2018

 26%|██▌       | 23/90 [00:16<00:41,  1.61it/s]

df length: 25206
Optimization terminated successfully.
         Current function value: 0.392867
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:                25206
Model:                          Logit   Df Residuals:                    25194
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.006106
Time:                        23:54:00   Log-Likelihood:                -9902.6
converged:                       True   LL-Null:                       -9963.4
Covariance Type:            nonrobust   LLR p-value:                 8.387e-21
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.1631      0.042    -52.056      0.000      -2.245      -2.082
AI ROLE                          0.2979      0.388      0.767      0.443      -0.463       1.059
Associate degree                 0.3918      0.085      4.629      0.000       0.226       0.558
Bachelor's degree                0.4475      0.055      8.169      0.000       0.340       0.555
High school or GED               0.3854      0.059      6.563      0.000       0.270       0.501
Master's degree                  0.2899      0.060      4.820      0.000       0.172       0.408
Ph.D. or professional degree     0.0462      0.260      0.177      0.859      -0.464       0.557
0 years                          0.5114      0.125      4.103      0.000       0.267       0.756
1-2 years                        0.0827      0.043      1.903      0.057      -0.002       0.168
11-20 years                     -0.3452      0.474     -0.729      0.466      -1.274       0.583
3-5 years                       -0.1720      0.057     -2.996      0.003      -0.284      -0.059
6-10 years                      -0.1619      0.161     -1.003      0.316      -0.478       0.154
================================================================================================
Community and Social Service Occupations 2023

 27%|██▋       | 24/90 [00:17<00:40,  1.63it/s]

df length: 43218
Optimization terminated successfully.
         Current function value: 0.656072
         Iterations 5
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:                43218
Model:                          Logit   Df Residuals:                    43206
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01318
Time:                        23:54:01   Log-Likelihood:                -28354.
converged:                       True   LL-Null:                       -28733.
Covariance Type:            nonrobust   LLR p-value:                3.024e-155
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -0.8842      0.022    -39.860      0.000      -0.928      -0.841
AI ROLE                         -0.1574      0.228     -0.689      0.491      -0.605       0.290
Associate degree                 0.6231      0.046     13.536      0.000       0.533       0.713
Bachelor's degree                0.5196      0.030     17.194      0.000       0.460       0.579
High school or GED               0.5288      0.031     17.149      0.000       0.468       0.589
Master's degree                  0.3341      0.032     10.524      0.000       0.272       0.396
Ph.D. or professional degree    -0.3414      0.071     -4.824      0.000      -0.480      -0.203
0 years                         -0.2073      0.070     -2.977      0.003      -0.344      -0.071
1-2 years                        0.1792      0.024      7.619      0.000       0.133       0.225
11-20 years                      0.1879      0.229      0.821      0.411      -0.260       0.636
3-5 years                        0.0053      0.032      0.168      0.867      -0.056       0.067
6-10 years                      -0.1917      0.089     -2.157      0.031      -0.366      -0.018
================================================================================================
Computer and Mathematical Occupations 2019
df length: 187188
Optimization terminated successfully.
         Current function value: 0.291176
         Iterations 7

 28%|██▊       | 25/90 [00:18<00:47,  1.38it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:               187188
Model:                          Logit   Df Residuals:                   187176
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.05561
Time:                        23:54:02   Log-Likelihood:                -54505.
converged:                       True   LL-Null:                       -57714.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.5842      0.016   -160.289      0.000      -2.616      -2.553
AI ROLE                          0.0061      0.033      0.189      0.850      -0.058       0.070
Associate degree                 0.2971      0.041      7.209      0.000       0.216       0.378
Bachelor's degree                0.0838      0.019      4.435      0.000       0.047       0.121
High school or GED               0.3037      0.037      8.305      0.000       0.232       0.375
Master's degree                  0.0055      0.062      0.090      0.928      -0.116       0.127
Ph.D. or professional degree    -0.2419      0.154     -1.570      0.116      -0.544       0.060
0 years                          2.8110      0.037     75.615      0.000       2.738       2.884
1-2 years                        0.3975      0.027     14.633      0.000       0.344       0.451
11-20 years                     -0.1338      0.070     -1.904      0.057      -0.271       0.004
3-5 years                        0.2636      0.021     12.314      0.000       0.222       0.306
6-10 years                      -0.1842      0.028     -6.556      0.000      -0.239      -0.129
================================================================================================
Computer and Mathematical Occupations 2021
df length: 175692
Optimization terminated successfully.
         Current function value: 0.415578
         Iterations 6

 29%|██▉       | 26/90 [00:19<00:50,  1.26it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:               175692
Model:                          Logit   Df Residuals:                   175680
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.04452
Time:                        23:54:03   Log-Likelihood:                -73014.
converged:                       True   LL-Null:                       -76416.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.1088      0.014   -146.427      0.000      -2.137      -2.081
AI ROLE                          0.0115      0.024      0.476      0.634      -0.036       0.059
Associate degree                 1.1213      0.029     38.646      0.000       1.064       1.178
Bachelor's degree                0.4191      0.017     25.298      0.000       0.387       0.452
High school or GED               0.8980      0.027     33.567      0.000       0.846       0.950
Master's degree                 -0.0040      0.052     -0.078      0.938      -0.106       0.098
Ph.D. or professional degree     0.5485      0.098      5.572      0.000       0.356       0.741
0 years                          1.8142      0.040     45.292      0.000       1.736       1.893
1-2 years                        0.2766      0.022     12.692      0.000       0.234       0.319
11-20 years                     -0.4873      0.054     -9.078      0.000      -0.593      -0.382
3-5 years                        0.0511      0.018      2.884      0.004       0.016       0.086
6-10 years                      -0.1692      0.022     -7.816      0.000      -0.212      -0.127
================================================================================================
Computer and Mathematical Occupations 2022
df length: 203321
Optimization terminated successfully.
         Current function value: 0.482279
         Iterations 6

 30%|███       | 27/90 [00:20<00:54,  1.15it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:               203321
Model:                          Logit   Df Residuals:                   203309
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01021
Time:                        23:54:04   Log-Likelihood:                -98057.
converged:                       True   LL-Null:                       -99069.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.8006      0.012   -148.443      0.000      -1.824      -1.777
AI ROLE                          0.0144      0.019      0.740      0.460      -0.024       0.052
Associate degree                 0.4117      0.028     14.639      0.000       0.357       0.467
Bachelor's degree                0.2222      0.014     16.229      0.000       0.195       0.249
High school or GED               0.4310      0.024     18.211      0.000       0.385       0.477
Master's degree                 -0.0769      0.041     -1.862      0.063      -0.158       0.004
Ph.D. or professional degree    -0.3340      0.106     -3.161      0.002      -0.541      -0.127
0 years                          0.5355      0.046     11.685      0.000       0.446       0.625
1-2 years                        0.4263      0.019     22.555      0.000       0.389       0.463
11-20 years                     -0.1434      0.041     -3.464      0.001      -0.224      -0.062
3-5 years                        0.3418      0.015     22.591      0.000       0.312       0.372
6-10 years                       0.0743      0.018      4.123      0.000       0.039       0.110
================================================================================================
Computer and Mathematical Occupations 2020
df length: 157708
Optimization terminated successfully.
         Current function value: 0.312567
         Iterations 7

 31%|███       | 28/90 [00:21<00:54,  1.13it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:               157708
Model:                          Logit   Df Residuals:                   157696
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.04228
Time:                        23:54:05   Log-Likelihood:                -49294.
converged:                       True   LL-Null:                       -51470.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.4417      0.017   -147.315      0.000      -2.474      -2.409
AI ROLE                         -0.0939      0.034     -2.743      0.006      -0.161      -0.027
Associate degree                 1.0641      0.035     30.153      0.000       0.995       1.133
Bachelor's degree                0.2361      0.020     11.617      0.000       0.196       0.276
High school or GED               0.5699      0.036     15.977      0.000       0.500       0.640
Master's degree                 -0.0816      0.066     -1.230      0.219      -0.212       0.048
Ph.D. or professional degree    -0.0524      0.152     -0.345      0.730      -0.350       0.246
0 years                          1.7928      0.045     40.053      0.000       1.705       1.881
1-2 years                        0.2625      0.028      9.412      0.000       0.208       0.317
11-20 years                     -0.3628      0.070     -5.156      0.000      -0.501      -0.225
3-5 years                        0.0312      0.022      1.398      0.162      -0.013       0.075
6-10 years                      -0.3222      0.028    -11.359      0.000      -0.378      -0.267
================================================================================================
Computer and Mathematical Occupations 2018
df length: 178714
Optimization terminated successfully.
         Current function value: 0.250564
         Iterations 7

 32%|███▏      | 29/90 [00:22<00:56,  1.09it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:               178714
Model:                          Logit   Df Residuals:                   178702
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.008043
Time:                        23:54:06   Log-Likelihood:                -44779.
converged:                       True   LL-Null:                       -45142.
Covariance Type:            nonrobust   LLR p-value:                1.334e-148
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.7835      0.018   -155.149      0.000      -2.819      -2.748
AI ROLE                          0.1149      0.037      3.100      0.002       0.042       0.188
Associate degree                 0.2561      0.049      5.251      0.000       0.161       0.352
Bachelor's degree                0.0865      0.022      4.021      0.000       0.044       0.129
High school or GED               0.1905      0.043      4.423      0.000       0.106       0.275
Master's degree                  0.1089      0.065      1.683      0.092      -0.018       0.236
Ph.D. or professional degree    -0.2957      0.178     -1.665      0.096      -0.644       0.052
0 years                          1.4211      0.061     23.392      0.000       1.302       1.540
1-2 years                        0.2071      0.032      6.519      0.000       0.145       0.269
11-20 years                     -0.2681      0.085     -3.162      0.002      -0.434      -0.102
3-5 years                        0.2529      0.024     10.620      0.000       0.206       0.300
6-10 years                      -0.0601      0.030     -1.987      0.047      -0.119      -0.001
================================================================================================
Computer and Mathematical Occupations 2023
df length: 127390
Optimization terminated successfully.
         Current function value: 0.552235
         Iterations 6

 33%|███▎      | 30/90 [00:23<00:53,  1.11it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:               127390
Model:                          Logit   Df Residuals:                   127378
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01363
Time:                        23:54:07   Log-Likelihood:                -70349.
converged:                       True   LL-Null:                       -71322.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.5903      0.014   -109.844      0.000      -1.619      -1.562
AI ROLE                          0.1365      0.022      6.122      0.000       0.093       0.180
Associate degree                 0.4617      0.032     14.410      0.000       0.399       0.524
Bachelor's degree                0.4479      0.016     27.761      0.000       0.416       0.480
High school or GED               0.5224      0.027     19.450      0.000       0.470       0.575
Master's degree                  0.3170      0.045      7.012      0.000       0.228       0.406
Ph.D. or professional degree    -0.2189      0.116     -1.890      0.059      -0.446       0.008
0 years                          0.1579      0.062      2.559      0.010       0.037       0.279
1-2 years                        0.3793      0.022     16.936      0.000       0.335       0.423
11-20 years                     -0.0817      0.042     -1.952      0.051      -0.164       0.000
3-5 years                        0.2750      0.018     15.537      0.000       0.240       0.310
6-10 years                       0.0981      0.020      4.907      0.000       0.059       0.137
================================================================================================
Educational Instruction and Library Occupations 2019

 34%|███▍      | 31/90 [00:23<00:48,  1.23it/s]

df length: 45660
Optimization terminated successfully.
         Current function value: 0.359850
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:                45660
Model:                          Logit   Df Residuals:                    45648
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.04105
Time:                        23:54:07   Log-Likelihood:                -16431.
converged:                       True   LL-Null:                       -17134.
Covariance Type:            nonrobust   LLR p-value:                4.330e-295
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.1938      0.026    -83.670      0.000      -2.245      -2.142
AI ROLE                         -0.3834      0.272     -1.410      0.159      -0.916       0.150
Associate degree                 0.5907      0.052     11.458      0.000       0.490       0.692
Bachelor's degree               -0.1413      0.039     -3.627      0.000      -0.218      -0.065
High school or GED               0.6751      0.039     17.209      0.000       0.598       0.752
Master's degree                 -0.4407      0.068     -6.479      0.000      -0.574      -0.307
Ph.D. or professional degree    -1.3155      0.148     -8.915      0.000      -1.605      -1.026
0 years                         -0.1461      0.115     -1.270      0.204      -0.371       0.079
1-2 years                        0.7618      0.035     21.779      0.000       0.693       0.830
11-20 years                      0.5882      0.348      1.689      0.091      -0.094       1.271
3-5 years                       -0.0080      0.058     -0.137      0.891      -0.122       0.106
6-10 years                      -0.3964      0.153     -2.593      0.010      -0.696      -0.097
================================================================================================
Educational Instruction and Library Occupations 2021

 36%|███▌      | 32/90 [00:24<00:44,  1.32it/s]

df length: 54703
Optimization terminated successfully.
         Current function value: 0.474073
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:                54703
Model:                          Logit   Df Residuals:                    54691
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.05326
Time:                        23:54:08   Log-Likelihood:                -25933.
converged:                       True   LL-Null:                       -27392.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.7758      0.021    -84.887      0.000      -1.817      -1.735
AI ROLE                         -1.0455      0.269     -3.888      0.000      -1.573      -0.519
Associate degree                 0.8560      0.040     21.377      0.000       0.778       0.935
Bachelor's degree                0.1603      0.031      5.161      0.000       0.099       0.221
High school or GED               1.0997      0.029     38.431      0.000       1.044       1.156
Master's degree                 -0.6528      0.066     -9.938      0.000      -0.782      -0.524
Ph.D. or professional degree    -1.3141      0.135     -9.750      0.000      -1.578      -1.050
0 years                          0.1561      0.067      2.315      0.021       0.024       0.288
1-2 years                        0.2600      0.030      8.563      0.000       0.200       0.320
11-20 years                     -0.4824      0.312     -1.545      0.122      -1.094       0.130
3-5 years                       -0.2368      0.046     -5.196      0.000      -0.326      -0.147
6-10 years                      -0.3100      0.104     -2.969      0.003      -0.515      -0.105
================================================================================================
Educational Instruction and Library Occupations 2022

 37%|███▋      | 33/90 [00:24<00:41,  1.38it/s]

df length: 62895
Optimization terminated successfully.
         Current function value: 0.497505
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:                62895
Model:                          Logit   Df Residuals:                    62883
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.06493
Time:                        23:54:09   Log-Likelihood:                -31291.
converged:                       True   LL-Null:                       -33463.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.5959      0.019    -82.893      0.000      -1.634      -1.558
AI ROLE                         -0.5472      0.172     -3.173      0.002      -0.885      -0.209
Associate degree                 0.5527      0.039     14.021      0.000       0.475       0.630
Bachelor's degree                0.3079      0.027     11.472      0.000       0.255       0.360
High school or GED               1.2781      0.027     47.882      0.000       1.226       1.330
Master's degree                 -0.7552      0.055    -13.747      0.000      -0.863      -0.648
Ph.D. or professional degree    -1.0056      0.091    -11.055      0.000      -1.184      -0.827
0 years                         -0.9761      0.051    -19.035      0.000      -1.077      -0.876
1-2 years                        0.2267      0.026      8.588      0.000       0.175       0.278
11-20 years                     -0.2861      0.229     -1.251      0.211      -0.734       0.162
3-5 years                       -0.2101      0.039     -5.386      0.000      -0.286      -0.134
6-10 years                      -0.2111      0.088     -2.395      0.017      -0.384      -0.038
================================================================================================
Educational Instruction and Library Occupations 2020

 38%|███▊      | 34/90 [00:25<00:38,  1.45it/s]

df length: 42631
Optimization terminated successfully.
         Current function value: 0.427666
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:                42631
Model:                          Logit   Df Residuals:                    42619
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.03763
Time:                        23:54:09   Log-Likelihood:                -18232.
converged:                       True   LL-Null:                       -18945.
Covariance Type:            nonrobust   LLR p-value:                3.486e-299
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.7824      0.023    -77.214      0.000      -1.828      -1.737
AI ROLE                         -0.7124      0.330     -2.161      0.031      -1.359      -0.066
Associate degree                 0.6377      0.046     13.953      0.000       0.548       0.727
Bachelor's degree               -0.1604      0.036     -4.469      0.000      -0.231      -0.090
High school or GED               0.5552      0.036     15.446      0.000       0.485       0.626
Master's degree                 -0.9242      0.076    -12.113      0.000      -1.074      -0.775
Ph.D. or professional degree    -1.4074      0.142     -9.895      0.000      -1.686      -1.129
0 years                          0.3937      0.093      4.211      0.000       0.210       0.577
1-2 years                        0.5494      0.035     15.735      0.000       0.481       0.618
11-20 years                     -0.0366      0.381     -0.096      0.923      -0.784       0.710
3-5 years                       -0.1354      0.055     -2.466      0.014      -0.243      -0.028
6-10 years                      -0.5092      0.140     -3.626      0.000      -0.784      -0.234
================================================================================================
Educational Instruction and Library Occupations 2018

 39%|███▉      | 35/90 [00:26<00:36,  1.51it/s]

df length: 41745
Optimization terminated successfully.
         Current function value: 0.268159
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:                41745
Model:                          Logit   Df Residuals:                    41733
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.03531
Time:                        23:54:10   Log-Likelihood:                -11194.
converged:                       True   LL-Null:                       -11604.
Covariance Type:            nonrobust   LLR p-value:                1.316e-168
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.6986      0.032    -84.683      0.000      -2.761      -2.636
AI ROLE                         -1.3830      0.587     -2.357      0.018      -2.533      -0.233
Associate degree                 0.2935      0.072      4.092      0.000       0.153       0.434
Bachelor's degree                0.0182      0.048      0.382      0.703      -0.075       0.112
High school or GED               0.4539      0.051      8.896      0.000       0.354       0.554
Master's degree                 -0.6197      0.090     -6.860      0.000      -0.797      -0.443
Ph.D. or professional degree    -0.9043      0.158     -5.717      0.000      -1.214      -0.594
0 years                         -0.1337      0.177     -0.755      0.451      -0.481       0.214
1-2 years                        0.9755      0.044     22.190      0.000       0.889       1.062
11-20 years                     -0.3681      0.724     -0.508      0.611      -1.787       1.051
3-5 years                        0.0793      0.074      1.076      0.282      -0.065       0.224
6-10 years                       0.3040      0.149      2.033      0.042       0.011       0.597
================================================================================================
Educational Instruction and Library Occupations 2023

 40%|████      | 36/90 [00:26<00:35,  1.53it/s]

df length: 56729
Optimization terminated successfully.
         Current function value: 0.527569
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:                56729
Model:                          Logit   Df Residuals:                    56717
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.03333
Time:                        23:54:11   Log-Likelihood:                -29928.
converged:                       True   LL-Null:                       -30960.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.3460      0.018    -75.232      0.000      -1.381      -1.311
AI ROLE                         -0.1664      0.131     -1.266      0.205      -0.424       0.091
Associate degree                 0.2387      0.040      5.980      0.000       0.160       0.317
Bachelor's degree               -0.0784      0.027     -2.922      0.003      -0.131      -0.026
High school or GED               0.7252      0.027     26.712      0.000       0.672       0.778
Master's degree                 -0.7427      0.049    -15.025      0.000      -0.840      -0.646
Ph.D. or professional degree    -0.9140      0.078    -11.689      0.000      -1.067      -0.761
0 years                          0.2434      0.051      4.765      0.000       0.143       0.343
1-2 years                        0.4081      0.028     14.731      0.000       0.354       0.462
11-20 years                     -0.4703      0.218     -2.159      0.031      -0.897      -0.043
3-5 years                        0.1154      0.038      3.052      0.002       0.041       0.189
6-10 years                       0.0303      0.086      0.353      0.724      -0.138       0.199
================================================================================================
Healthcare Practitioners and Technical Occupations 2019
df length: 177733
Optimization terminated successfully.
         Current function value: 0.374313
         Iterations 6

 41%|████      | 37/90 [00:27<00:39,  1.35it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:               177733
Model:                          Logit   Df Residuals:                   177721
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.005983
Time:                        23:54:11   Log-Likelihood:                -66528.
converged:                       True   LL-Null:                       -66928.
Covariance Type:            nonrobust   LLR p-value:                1.217e-164
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.9979      0.011   -179.631      0.000      -2.020      -1.976
AI ROLE                         -0.3390      0.250     -1.357      0.175      -0.829       0.151
Associate degree                 0.3689      0.021     17.652      0.000       0.328       0.410
Bachelor's degree               -0.1530      0.024     -6.337      0.000      -0.200      -0.106
High school or GED               0.1251      0.022      5.611      0.000       0.081       0.169
Master's degree                  0.3247      0.036      8.975      0.000       0.254       0.396
Ph.D. or professional degree     0.3589      0.044      8.136      0.000       0.272       0.445
0 years                          0.5523      0.042     13.217      0.000       0.470       0.634
1-2 years                       -0.0698      0.016     -4.281      0.000      -0.102      -0.038
11-20 years                      1.0111      0.176      5.738      0.000       0.666       1.356
3-5 years                       -0.2001      0.029     -6.862      0.000      -0.257      -0.143
6-10 years                       0.1581      0.095      1.658      0.097      -0.029       0.345
================================================================================================
Healthcare Practitioners and Technical Occupations 2021
df length: 235145
Optimization terminated successfully.
         Current function value: 0.537470
         Iterations 6

 42%|████▏     | 38/90 [00:28<00:43,  1.19it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:               235145
Model:                          Logit   Df Residuals:                   235133
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01244
Time:                        23:54:13   Log-Likelihood:            -1.2638e+05
converged:                       True   LL-Null:                   -1.2798e+05
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.3965      0.008   -170.183      0.000      -1.413      -1.380
AI ROLE                         -0.8784      0.184     -4.767      0.000      -1.240      -0.517
Associate degree                 0.6273      0.013     46.811      0.000       0.601       0.654
Bachelor's degree                0.0945      0.016      5.818      0.000       0.063       0.126
High school or GED               0.4476      0.014     31.153      0.000       0.419       0.476
Master's degree                  0.3604      0.025     14.479      0.000       0.312       0.409
Ph.D. or professional degree     0.6438      0.030     21.487      0.000       0.585       0.703
0 years                         -0.5063      0.039    -13.149      0.000      -0.582      -0.431
1-2 years                       -0.0257      0.011     -2.394      0.017      -0.047      -0.005
11-20 years                      1.4897      0.142     10.467      0.000       1.211       1.769
3-5 years                        0.1295      0.019      6.895      0.000       0.093       0.166
6-10 years                      -0.0597      0.073     -0.823      0.410      -0.202       0.082
================================================================================================
Healthcare Practitioners and Technical Occupations 2022
df length: 293272
Optimization terminated successfully.
         Current function value: 0.565625
         Iterations 6

 43%|████▎     | 39/90 [00:29<00:48,  1.05it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:               293272
Model:                          Logit   Df Residuals:                   293260
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.009534
Time:                        23:54:14   Log-Likelihood:            -1.6588e+05
converged:                       True   LL-Null:                   -1.6748e+05
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.2182      0.007   -177.628      0.000      -1.232      -1.205
AI ROLE                         -0.6121      0.165     -3.702      0.000      -0.936      -0.288
Associate degree                 0.5247      0.012     45.402      0.000       0.502       0.547
Bachelor's degree                0.1669      0.014     12.050      0.000       0.140       0.194
High school or GED               0.4195      0.013     31.963      0.000       0.394       0.445
Master's degree                  0.3626      0.023     15.503      0.000       0.317       0.408
Ph.D. or professional degree     0.3288      0.027     12.115      0.000       0.276       0.382
0 years                         -0.5720      0.032    -18.117      0.000      -0.634      -0.510
1-2 years                       -0.0729      0.009     -7.800      0.000      -0.091      -0.055
11-20 years                      1.5582      0.136     11.491      0.000       1.292       1.824
3-5 years                        0.1193      0.017      7.166      0.000       0.087       0.152
6-10 years                       0.3637      0.055      6.658      0.000       0.257       0.471
================================================================================================
Healthcare Practitioners and Technical Occupations 2020
df length: 208848
Optimization terminated successfully.
         Current function value: 0.424190
         Iterations 6

 44%|████▍     | 40/90 [00:30<00:48,  1.03it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:               208848
Model:                          Logit   Df Residuals:                   208836
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01375
Time:                        23:54:15   Log-Likelihood:                -88591.
converged:                       True   LL-Null:                       -89826.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.7750      0.010   -185.440      0.000      -1.794      -1.756
AI ROLE                         -0.3542      0.226     -1.566      0.117      -0.798       0.089
Associate degree                 0.6784      0.017     39.745      0.000       0.645       0.712
Bachelor's degree               -0.0228      0.022     -1.040      0.298      -0.066       0.020
High school or GED               0.3893      0.019     20.907      0.000       0.353       0.426
Master's degree                  0.2356      0.035      6.821      0.000       0.168       0.303
Ph.D. or professional degree     0.5772      0.034     16.977      0.000       0.511       0.644
0 years                          0.0786      0.040      1.954      0.051      -0.000       0.157
1-2 years                       -0.2674      0.014    -19.705      0.000      -0.294      -0.241
11-20 years                      1.5957      0.128     12.506      0.000       1.346       1.846
3-5 years                       -0.1823      0.026     -7.029      0.000      -0.233      -0.131
6-10 years                      -0.3801      0.099     -3.829      0.000      -0.575      -0.186
================================================================================================
Healthcare Practitioners and Technical Occupations 2018
df length: 178552
Optimization terminated successfully.
         Current function value: 0.313503
         Iterations 7

 46%|████▌     | 41/90 [00:31<00:47,  1.04it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:               178552
Model:                          Logit   Df Residuals:                   178540
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01152
Time:                        23:54:16   Log-Likelihood:                -55977.
converged:                       True   LL-Null:                       -56629.
Covariance Type:            nonrobust   LLR p-value:                3.565e-273
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.2745      0.013   -181.190      0.000      -2.299      -2.250
AI ROLE                         -0.3734      0.288     -1.297      0.195      -0.938       0.191
Associate degree                 0.6404      0.022     28.935      0.000       0.597       0.684
Bachelor's degree               -0.0855      0.028     -3.067      0.002      -0.140      -0.031
High school or GED               0.2238      0.025      8.831      0.000       0.174       0.273
Master's degree                  0.1726      0.045      3.803      0.000       0.084       0.262
Ph.D. or professional degree     0.4695      0.043     10.805      0.000       0.384       0.555
0 years                          0.3859      0.048      8.012      0.000       0.292       0.480
1-2 years                       -0.2766      0.018    -15.038      0.000      -0.313      -0.241
11-20 years                      0.5575      0.306      1.825      0.068      -0.041       1.156
3-5 years                       -0.3067      0.033     -9.304      0.000      -0.371      -0.242
6-10 years                      -0.0538      0.108     -0.497      0.619      -0.266       0.158
================================================================================================
Healthcare Practitioners and Technical Occupations 2023
df length: 286144
Optimization terminated successfully.
         Current function value: 0.609764
         Iterations 5

 47%|████▋     | 42/90 [00:33<00:48,  1.02s/it]

                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:               286144
Model:                          Logit   Df Residuals:                   286132
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01291
Time:                        23:54:17   Log-Likelihood:            -1.7448e+05
converged:                       True   LL-Null:                   -1.7676e+05
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.0117      0.007   -155.631      0.000      -1.024      -0.999
AI ROLE                         -0.5208      0.156     -3.333      0.001      -0.827      -0.215
Associate degree                 0.6437      0.011     56.991      0.000       0.622       0.666
Bachelor's degree                0.3728      0.013     28.436      0.000       0.347       0.399
High school or GED               0.4236      0.013     32.699      0.000       0.398       0.449
Master's degree                  0.4242      0.023     18.614      0.000       0.380       0.469
Ph.D. or professional degree     0.2837      0.026     10.741      0.000       0.232       0.335
0 years                         -0.4967      0.027    -18.294      0.000      -0.550      -0.443
1-2 years                       -0.0671      0.009     -7.426      0.000      -0.085      -0.049
11-20 years                      0.9552      0.111      8.641      0.000       0.739       1.172
3-5 years                        0.1152      0.016      7.087      0.000       0.083       0.147
6-10 years                       0.5226      0.050     10.495      0.000       0.425       0.620
================================================================================================
Legal Occupations 2019

 48%|████▊     | 43/90 [00:33<00:41,  1.14it/s]

df length: 10618
Optimization terminated successfully.
         Current function value: 0.428131
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:                10618
Model:                          Logit   Df Residuals:                    10606
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01537
Time:                        23:54:17   Log-Likelihood:                -4545.9
converged:                       True   LL-Null:                       -4616.9
Covariance Type:            nonrobust   LLR p-value:                 6.506e-25
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.8059      0.046    -39.662      0.000      -1.895      -1.717
AI ROLE                         -0.7840      0.467     -1.678      0.093      -1.700       0.132
Associate degree                 0.5940      0.114      5.189      0.000       0.370       0.818
Bachelor's degree                0.1774      0.080      2.223      0.026       0.021       0.334
High school or GED               0.6417      0.084      7.616      0.000       0.477       0.807
Master's degree                  0.3186      0.229      1.390      0.165      -0.131       0.768
Ph.D. or professional degree     0.3449      0.085      4.076      0.000       0.179       0.511
0 years                          0.9465      0.186      5.080      0.000       0.581       1.312
1-2 years                        0.0316      0.070      0.452      0.652      -0.105       0.169
11-20 years                     -1.3287      0.728     -1.824      0.068      -2.756       0.099
3-5 years                       -0.1433      0.067     -2.133      0.033      -0.275      -0.012
6-10 years                      -0.6003      0.138     -4.340      0.000      -0.871      -0.329
================================================================================================
Legal Occupations 2021

 49%|████▉     | 44/90 [00:34<00:35,  1.31it/s]

df length: 13410
Optimization terminated successfully.
         Current function value: 0.586282
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:                13410
Model:                          Logit   Df Residuals:                    13398
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.03905
Time:                        23:54:18   Log-Likelihood:                -7862.0
converged:                       True   LL-Null:                       -8181.5
Covariance Type:            nonrobust   LLR p-value:                6.612e-130
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.1002      0.035    -31.865      0.000      -1.168      -1.033
AI ROLE                         -0.7320      0.286     -2.561      0.010      -1.292      -0.172
Associate degree                 0.9234      0.080     11.541      0.000       0.767       1.080
Bachelor's degree                0.3013      0.058      5.168      0.000       0.187       0.416
High school or GED               1.0707      0.053     20.046      0.000       0.966       1.175
Master's degree                 -0.2505      0.235     -1.066      0.286      -0.711       0.210
Ph.D. or professional degree    -0.0692      0.065     -1.058      0.290      -0.197       0.059
0 years                          0.5025      0.145      3.462      0.001       0.218       0.787
1-2 years                        0.1289      0.051      2.515      0.012       0.028       0.229
11-20 years                     -0.4763      0.290     -1.645      0.100      -1.044       0.091
3-5 years                       -0.0883      0.048     -1.840      0.066      -0.182       0.006
6-10 years                      -0.3865      0.090     -4.309      0.000      -0.562      -0.211
================================================================================================
Legal Occupations 2022

 50%|█████     | 45/90 [00:34<00:31,  1.43it/s]

df length: 14411
Optimization terminated successfully.
         Current function value: 0.633848
         Iterations 5
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:                14411
Model:                          Logit   Df Residuals:                    14399
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02030
Time:                        23:54:18   Log-Likelihood:                -9134.4
converged:                       True   LL-Null:                       -9323.6
Covariance Type:            nonrobust   LLR p-value:                 2.273e-74
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -0.7582      0.031    -24.687      0.000      -0.818      -0.698
AI ROLE                         -0.0085      0.222     -0.038      0.970      -0.443       0.426
Associate degree                 0.6792      0.080      8.539      0.000       0.523       0.835
Bachelor's degree               -0.0916      0.054     -1.712      0.087      -0.197       0.013
High school or GED               0.5772      0.055     10.442      0.000       0.469       0.686
Master's degree                 -0.2464      0.169     -1.454      0.146      -0.578       0.086
Ph.D. or professional degree    -0.1281      0.056     -2.292      0.022      -0.238      -0.019
0 years                          0.2739      0.132      2.083      0.037       0.016       0.532
1-2 years                        0.3426      0.047      7.305      0.000       0.251       0.435
11-20 years                      0.2473      0.202      1.224      0.221      -0.149       0.643
3-5 years                        0.0385      0.044      0.872      0.383      -0.048       0.125
6-10 years                      -0.4823      0.083     -5.834      0.000      -0.644      -0.320
================================================================================================
Legal Occupations 2020

 51%|█████     | 46/90 [00:35<00:28,  1.56it/s]

df length: 10122
Optimization terminated successfully.
         Current function value: 0.534187
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:                10122
Model:                          Logit   Df Residuals:                    10110
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01846
Time:                        23:54:19   Log-Likelihood:                -5407.0
converged:                       True   LL-Null:                       -5508.7
Covariance Type:            nonrobust   LLR p-value:                 1.461e-37
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.2579      0.040    -31.590      0.000      -1.336      -1.180
AI ROLE                         -1.3331      0.601     -2.218      0.027      -2.511      -0.155
Associate degree                 0.7011      0.098      7.143      0.000       0.509       0.893
Bachelor's degree                0.0194      0.075      0.258      0.797      -0.128       0.167
High school or GED               0.6269      0.074      8.502      0.000       0.482       0.771
Master's degree                  0.2251      0.208      1.081      0.279      -0.183       0.633
Ph.D. or professional degree     0.1335      0.080      1.676      0.094      -0.023       0.290
0 years                          0.3850      0.204      1.890      0.059      -0.014       0.784
1-2 years                        0.1511      0.062      2.433      0.015       0.029       0.273
11-20 years                     -0.5678      0.349     -1.628      0.103      -1.251       0.116
3-5 years                       -0.2006      0.059     -3.422      0.001      -0.315      -0.086
6-10 years                      -0.6381      0.120     -5.315      0.000      -0.873      -0.403
================================================================================================
Legal Occupations 2018

 52%|█████▏    | 47/90 [00:35<00:26,  1.65it/s]

df length: 9145
Optimization terminated successfully.
         Current function value: 0.294780
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:                 9145
Model:                          Logit   Df Residuals:                     9133
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.008074
Time:                        23:54:19   Log-Likelihood:                -2695.8
converged:                       True   LL-Null:                       -2717.7
Covariance Type:            nonrobust   LLR p-value:                 7.613e-06
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.5623      0.067    -38.283      0.000      -2.694      -2.431
AI ROLE                          0.2587      0.441      0.586      0.558      -0.606       1.124
Associate degree                 0.1838      0.186      0.989      0.323      -0.180       0.548
Bachelor's degree                0.2098      0.103      2.028      0.043       0.007       0.413
High school or GED               0.3196      0.125      2.549      0.011       0.074       0.565
Master's degree                  0.5819      0.284      2.049      0.040       0.025       1.138
Ph.D. or professional degree     0.4657      0.109      4.284      0.000       0.253       0.679
0 years                          0.7881      0.291      2.708      0.007       0.218       1.358
1-2 years                        0.2184      0.099      2.207      0.027       0.024       0.412
11-20 years                     -1.5036      1.016     -1.480      0.139      -3.494       0.487
3-5 years                       -0.0071      0.093     -0.076      0.939      -0.190       0.176
6-10 years                       0.1641      0.144      1.137      0.256      -0.119       0.447
================================================================================================
Legal Occupations 2023

 53%|█████▎    | 48/90 [00:36<00:23,  1.75it/s]

df length: 11385
Optimization terminated successfully.
         Current function value: 0.672799
         Iterations 5
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:                11385
Model:                          Logit   Df Residuals:                    11373
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.009512
Time:                        23:54:20   Log-Likelihood:                -7659.8
converged:                       True   LL-Null:                       -7733.4
Covariance Type:            nonrobust   LLR p-value:                 5.788e-26
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -0.4272      0.034    -12.702      0.000      -0.493      -0.361
AI ROLE                         -0.0249      0.221     -0.113      0.910      -0.458       0.408
Associate degree                 0.4089      0.086      4.764      0.000       0.241       0.577
Bachelor's degree               -0.1570      0.060     -2.624      0.009      -0.274      -0.040
High school or GED               0.2768      0.064      4.300      0.000       0.151       0.403
Master's degree                 -0.6447      0.196     -3.288      0.001      -1.029      -0.260
Ph.D. or professional degree    -0.1829      0.055     -3.331      0.001      -0.290      -0.075
0 years                          0.2898      0.142      2.047      0.041       0.012       0.567
1-2 years                        0.3263      0.051      6.354      0.000       0.226       0.427
11-20 years                      0.4246      0.238      1.781      0.075      -0.043       0.892
3-5 years                        0.0811      0.048      1.701      0.089      -0.012       0.175
6-10 years                      -0.0842      0.082     -1.030      0.303      -0.245       0.076
================================================================================================
Life, Physical, and Social Science Occupations 2019

 54%|█████▍    | 49/90 [00:36<00:23,  1.76it/s]

df length: 19301
Optimization terminated successfully.
         Current function value: 0.393234
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:                19301
Model:                          Logit   Df Residuals:                    19289
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01511
Time:                        23:54:21   Log-Likelihood:                -7589.8
converged:                       True   LL-Null:                       -7706.2
Covariance Type:            nonrobust   LLR p-value:                 1.069e-43
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.0395      0.045    -45.807      0.000      -2.127      -1.952
AI ROLE                         -0.6369      0.215     -2.963      0.003      -1.058      -0.216
Associate degree                 0.0987      0.107      0.921      0.357      -0.111       0.309
Bachelor's degree                0.0319      0.059      0.541      0.589      -0.084       0.148
High school or GED               0.4866      0.066      7.397      0.000       0.358       0.616
Master's degree                  0.3988      0.082      4.868      0.000       0.238       0.559
Ph.D. or professional degree    -0.2241      0.095     -2.364      0.018      -0.410      -0.038
0 years                          0.7344      0.112      6.536      0.000       0.514       0.955
1-2 years                        0.3375      0.054      6.215      0.000       0.231       0.444
11-20 years                     -0.6179      0.291     -2.124      0.034      -1.188      -0.048
3-5 years                        0.0812      0.059      1.379      0.168      -0.034       0.197
6-10 years                      -0.3799      0.101     -3.753      0.000      -0.578      -0.181
================================================================================================
Life, Physical, and Social Science Occupations 2021

 56%|█████▌    | 50/90 [00:37<00:22,  1.76it/s]

df length: 25175
Optimization terminated successfully.
         Current function value: 0.502651
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:                25175
Model:                          Logit   Df Residuals:                    25163
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01171
Time:                        23:54:21   Log-Likelihood:                -12654.
converged:                       True   LL-Null:                       -12804.
Covariance Type:            nonrobust   LLR p-value:                 9.489e-58
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.6012      0.033    -48.246      0.000      -1.666      -1.536
AI ROLE                         -0.5198      0.138     -3.772      0.000      -0.790      -0.250
Associate degree                 0.6006      0.072      8.330      0.000       0.459       0.742
Bachelor's degree                0.2418      0.045      5.425      0.000       0.154       0.329
High school or GED               0.6393      0.050     12.785      0.000       0.541       0.737
Master's degree                  0.0215      0.068      0.317      0.751      -0.111       0.154
Ph.D. or professional degree    -0.0337      0.068     -0.499      0.617      -0.166       0.099
0 years                          0.1230      0.091      1.356      0.175      -0.055       0.301
1-2 years                        0.1477      0.041      3.567      0.000       0.067       0.229
11-20 years                      0.0876      0.153      0.573      0.567      -0.212       0.387
3-5 years                        0.0303      0.044      0.688      0.491      -0.056       0.117
6-10 years                      -0.1323      0.069     -1.905      0.057      -0.268       0.004
================================================================================================
Life, Physical, and Social Science Occupations 2022

 57%|█████▋    | 51/90 [00:37<00:22,  1.76it/s]

df length: 30329
Optimization terminated successfully.
         Current function value: 0.542004
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:                30329
Model:                          Logit   Df Residuals:                    30317
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01049
Time:                        23:54:22   Log-Likelihood:                -16438.
converged:                       True   LL-Null:                       -16613.
Covariance Type:            nonrobust   LLR p-value:                 4.601e-68
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.4189      0.029    -48.149      0.000      -1.477      -1.361
AI ROLE                         -0.4811      0.106     -4.560      0.000      -0.688      -0.274
Associate degree                 0.5176      0.062      8.297      0.000       0.395       0.640
Bachelor's degree                0.2201      0.038      5.728      0.000       0.145       0.295
High school or GED               0.5063      0.045     11.295      0.000       0.418       0.594
Master's degree                  0.2099      0.057      3.653      0.000       0.097       0.323
Ph.D. or professional degree    -0.0857      0.059     -1.463      0.143      -0.201       0.029
0 years                          0.0318      0.078      0.410      0.682      -0.120       0.184
1-2 years                        0.2343      0.036      6.503      0.000       0.164       0.305
11-20 years                     -0.2257      0.140     -1.616      0.106      -0.499       0.048
3-5 years                        0.0924      0.037      2.472      0.013       0.019       0.166
6-10 years                      -0.2266      0.060     -3.770      0.000      -0.344      -0.109
================================================================================================
Life, Physical, and Social Science Occupations 2020

 58%|█████▊    | 52/90 [00:38<00:21,  1.77it/s]

df length: 20260
Optimization terminated successfully.
         Current function value: 0.424085
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:                20260
Model:                          Logit   Df Residuals:                    20248
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01183
Time:                        23:54:22   Log-Likelihood:                -8592.0
converged:                       True   LL-Null:                       -8694.8
Covariance Type:            nonrobust   LLR p-value:                 4.918e-38
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.7287      0.037    -46.156      0.000      -1.802      -1.655
AI ROLE                         -0.7111      0.214     -3.325      0.001      -1.130      -0.292
Associate degree                 0.2274      0.090      2.522      0.012       0.051       0.404
Bachelor's degree               -0.1211      0.054     -2.255      0.024      -0.226      -0.016
High school or GED               0.3261      0.060      5.437      0.000       0.209       0.444
Master's degree                 -0.3772      0.086     -4.382      0.000      -0.546      -0.208
Ph.D. or professional degree    -0.4092      0.084     -4.872      0.000      -0.574      -0.245
0 years                          0.6207      0.111      5.594      0.000       0.403       0.838
1-2 years                        0.2392      0.051      4.670      0.000       0.139       0.340
11-20 years                     -0.3258      0.239     -1.362      0.173      -0.795       0.143
3-5 years                        0.0193      0.056      0.343      0.731      -0.091       0.129
6-10 years                      -0.0396      0.088     -0.453      0.651      -0.211       0.132
================================================================================================
Life, Physical, and Social Science Occupations 2018

 59%|█████▉    | 53/90 [00:38<00:20,  1.78it/s]

df length: 19078
Optimization terminated successfully.
         Current function value: 0.310672
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:                19078
Model:                          Logit   Df Residuals:                    19066
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01401
Time:                        23:54:23   Log-Likelihood:                -5927.0
converged:                       True   LL-Null:                       -6011.2
Covariance Type:            nonrobust   LLR p-value:                 2.422e-30
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.5451      0.053    -48.360      0.000      -2.648      -2.442
AI ROLE                         -0.5494      0.277     -1.981      0.048      -1.093      -0.006
Associate degree                 0.2943      0.122      2.413      0.016       0.055       0.533
Bachelor's degree                0.1078      0.070      1.538      0.124      -0.030       0.245
High school or GED               0.6524      0.078      8.383      0.000       0.500       0.805
Master's degree                  0.2976      0.101      2.956      0.003       0.100       0.495
Ph.D. or professional degree    -0.0646      0.108     -0.597      0.550      -0.277       0.147
0 years                          0.6306      0.139      4.538      0.000       0.358       0.903
1-2 years                        0.3747      0.064      5.812      0.000       0.248       0.501
11-20 years                     -0.3468      0.302     -1.148      0.251      -0.939       0.245
3-5 years                        0.1498      0.069      2.182      0.029       0.015       0.284
6-10 years                      -0.1414      0.113     -1.254      0.210      -0.362       0.080
================================================================================================
Life, Physical, and Social Science Occupations 2023

 60%|██████    | 54/90 [00:39<00:20,  1.78it/s]

df length: 26051
Optimization terminated successfully.
         Current function value: 0.588741
         Iterations 5
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:                26051
Model:                          Logit   Df Residuals:                    26039
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01147
Time:                        23:54:23   Log-Likelihood:                -15337.
converged:                       True   LL-Null:                       -15515.
Covariance Type:            nonrobust   LLR p-value:                 1.408e-69
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.2158      0.030    -40.385      0.000      -1.275      -1.157
AI ROLE                         -0.2694      0.114     -2.360      0.018      -0.493      -0.046
Associate degree                 0.4405      0.066      6.676      0.000       0.311       0.570
Bachelor's degree                0.2406      0.039      6.142      0.000       0.164       0.317
High school or GED               0.3925      0.046      8.503      0.000       0.302       0.483
Master's degree                  0.1071      0.057      1.872      0.061      -0.005       0.219
Ph.D. or professional degree    -0.2555      0.056     -4.550      0.000      -0.366      -0.145
0 years                          0.1765      0.076      2.336      0.019       0.028       0.325
1-2 years                        0.1773      0.037      4.747      0.000       0.104       0.251
11-20 years                      0.3868      0.136      2.839      0.005       0.120       0.654
3-5 years                        0.3134      0.038      8.175      0.000       0.238       0.389
6-10 years                       0.1729      0.058      3.005      0.003       0.060       0.286
================================================================================================
Management Occupations 2019
df length: 174325
Optimization terminated successfully.
         Current function value: 0.419303
         Iterations 7

 61%|██████    | 55/90 [00:40<00:24,  1.46it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:               174325
Model:                          Logit   Df Residuals:                   174313
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01060
Time:                        23:54:24   Log-Likelihood:                -73095.
converged:                       True   LL-Null:                       -73878.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.6821      0.012   -137.536      0.000      -1.706      -1.658
AI ROLE                         -0.6175      0.077     -8.047      0.000      -0.768      -0.467
Associate degree                 0.2736      0.031      8.806      0.000       0.213       0.334
Bachelor's degree               -0.2243      0.017    -13.087      0.000      -0.258      -0.191
High school or GED               0.0423      0.020      2.072      0.038       0.002       0.082
Master's degree                 -0.0913      0.040     -2.285      0.022      -0.170      -0.013
Ph.D. or professional degree    -0.9277      0.106     -8.754      0.000      -1.135      -0.720
0 years                          0.3313      0.068      4.879      0.000       0.198       0.464
1-2 years                        0.2632      0.019     13.590      0.000       0.225       0.301
11-20 years                     -0.6951      0.071     -9.854      0.000      -0.833      -0.557
3-5 years                        0.1219      0.018      6.916      0.000       0.087       0.156
6-10 years                      -0.3204      0.025    -12.708      0.000      -0.370      -0.271
================================================================================================
Management Occupations 2021
df length: 220041
Optimization terminated successfully.
         Current function value: 0.572950
         Iterations 6

 62%|██████▏   | 56/90 [00:41<00:27,  1.25it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:               220041
Model:                          Logit   Df Residuals:                   220029
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01431
Time:                        23:54:25   Log-Likelihood:            -1.2607e+05
converged:                       True   LL-Null:                   -1.2790e+05
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.1648      0.009   -123.572      0.000      -1.183      -1.146
AI ROLE                         -0.6660      0.047    -14.046      0.000      -0.759      -0.573
Associate degree                 0.4955      0.024     20.916      0.000       0.449       0.542
Bachelor's degree                0.0096      0.013      0.753      0.451      -0.015       0.035
High school or GED               0.4284      0.014     30.834      0.000       0.401       0.456
Master's degree                 -0.1055      0.031     -3.389      0.001      -0.166      -0.044
Ph.D. or professional degree    -0.2602      0.059     -4.386      0.000      -0.377      -0.144
0 years                          0.7697      0.041     18.906      0.000       0.690       0.849
1-2 years                        0.2511      0.014     17.734      0.000       0.223       0.279
11-20 years                     -0.5382      0.045    -12.001      0.000      -0.626      -0.450
3-5 years                        0.1465      0.013     11.422      0.000       0.121       0.172
6-10 years                      -0.1774      0.017    -10.256      0.000      -0.211      -0.143
================================================================================================
Management Occupations 2022
df length: 258812
Optimization terminated successfully.
         Current function value: 0.597339
         Iterations 5

 63%|██████▎   | 57/90 [00:42<00:29,  1.11it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:               258812
Model:                          Logit   Df Residuals:                   258800
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01065
Time:                        23:54:27   Log-Likelihood:            -1.5460e+05
converged:                       True   LL-Null:                   -1.5626e+05
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.0538      0.008   -126.575      0.000      -1.070      -1.037
AI ROLE                         -0.4853      0.038    -12.713      0.000      -0.560      -0.411
Associate degree                 0.3179      0.022     14.748      0.000       0.276       0.360
Bachelor's degree               -0.0631      0.011     -5.599      0.000      -0.085      -0.041
High school or GED               0.2564      0.013     19.789      0.000       0.231       0.282
Master's degree                 -0.1654      0.027     -6.066      0.000      -0.219      -0.112
Ph.D. or professional degree    -0.3040      0.054     -5.628      0.000      -0.410      -0.198
0 years                         -0.1663      0.044     -3.810      0.000      -0.252      -0.081
1-2 years                        0.4219      0.013     33.137      0.000       0.397       0.447
11-20 years                     -0.2018      0.037     -5.423      0.000      -0.275      -0.129
3-5 years                        0.2779      0.012     23.958      0.000       0.255       0.301
6-10 years                      -0.0020      0.015     -0.129      0.897      -0.032       0.028
================================================================================================
Management Occupations 2020
df length: 162514
Optimization terminated successfully.
         Current function value: 0.504219
         Iterations 6

 64%|██████▍   | 58/90 [00:43<00:29,  1.10it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:               162514
Model:                          Logit   Df Residuals:                   162502
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01770
Time:                        23:54:27   Log-Likelihood:                -81943.
converged:                       True   LL-Null:                       -83419.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.2258      0.011   -110.726      0.000      -1.248      -1.204
AI ROLE                         -0.8477      0.073    -11.676      0.000      -0.990      -0.705
Associate degree                 0.1266      0.031      4.138      0.000       0.067       0.186
Bachelor's degree               -0.2903      0.016    -18.259      0.000      -0.321      -0.259
High school or GED               0.0756      0.018      4.300      0.000       0.041       0.110
Master's degree                 -0.3152      0.039     -8.187      0.000      -0.391      -0.240
Ph.D. or professional degree    -0.8643      0.078    -11.014      0.000      -1.018      -0.710
0 years                          1.0789      0.044     24.515      0.000       0.993       1.165
1-2 years                        0.1311      0.018      7.279      0.000       0.096       0.166
11-20 years                     -0.8499      0.065    -13.114      0.000      -0.977      -0.723
3-5 years                        0.1083      0.016      6.725      0.000       0.077       0.140
6-10 years                      -0.4138      0.023    -17.639      0.000      -0.460      -0.368
================================================================================================
Management Occupations 2018
df length: 169177
Optimization terminated successfully.
         Current function value: 0.339414
         Iterations 7

 66%|██████▌   | 59/90 [00:44<00:28,  1.08it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:               169177
Model:                          Logit   Df Residuals:                   169165
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.009332
Time:                        23:54:28   Log-Likelihood:                -57421.
converged:                       True   LL-Null:                       -57962.
Covariance Type:            nonrobust   LLR p-value:                4.841e-225
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.1166      0.015   -145.844      0.000      -2.145      -2.088
AI ROLE                         -0.3176      0.085     -3.751      0.000      -0.484      -0.152
Associate degree                 0.3833      0.035     10.900      0.000       0.314       0.452
Bachelor's degree               -0.1812      0.020     -9.053      0.000      -0.220      -0.142
High school or GED              -0.0601      0.025     -2.412      0.016      -0.109      -0.011
Master's degree                 -0.2313      0.049     -4.714      0.000      -0.327      -0.135
Ph.D. or professional degree    -0.5483      0.108     -5.082      0.000      -0.760      -0.337
0 years                          0.2555      0.081      3.152      0.002       0.097       0.414
1-2 years                        0.3378      0.023     14.750      0.000       0.293       0.383
11-20 years                     -0.4691      0.080     -5.871      0.000      -0.626      -0.312
3-5 years                        0.2242      0.021     10.848      0.000       0.184       0.265
6-10 years                      -0.2716      0.029     -9.314      0.000      -0.329      -0.214
================================================================================================
Management Occupations 2023
df length: 201898
Optimization terminated successfully.
         Current function value: 0.652277
         Iterations 5

 67%|██████▋   | 60/90 [00:45<00:28,  1.06it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:               201898
Model:                          Logit   Df Residuals:                   201886
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.006003
Time:                        23:54:29   Log-Likelihood:            -1.3169e+05
converged:                       True   LL-Null:                   -1.3249e+05
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -0.7071      0.009    -80.306      0.000      -0.724      -0.690
AI ROLE                         -0.2329      0.040     -5.806      0.000      -0.312      -0.154
Associate degree                 0.2506      0.023     10.772      0.000       0.205       0.296
Bachelor's degree               -0.0571      0.012     -4.725      0.000      -0.081      -0.033
High school or GED               0.1022      0.014      7.387      0.000       0.075       0.129
Master's degree                 -0.2643      0.028     -9.321      0.000      -0.320      -0.209
Ph.D. or professional degree    -0.4666      0.056     -8.306      0.000      -0.577      -0.357
0 years                          0.0021      0.043      0.048      0.962      -0.083       0.087
1-2 years                        0.3377      0.014     24.869      0.000       0.311       0.364
11-20 years                     -0.0219      0.036     -0.600      0.548      -0.093       0.050
3-5 years                        0.3073      0.012     24.643      0.000       0.283       0.332
6-10 years                       0.1147      0.016      7.047      0.000       0.083       0.147
================================================================================================
Office and Administrative Support Occupations 2019
df length: 185082
Optimization terminated successfully.
         Current function value: 0.421625
         Iterations 6

 68%|██████▊   | 61/90 [00:46<00:27,  1.05it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:               185082
Model:                          Logit   Df Residuals:                   185070
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.004365
Time:                        23:54:30   Log-Likelihood:                -78035.
converged:                       True   LL-Null:                       -78377.
Covariance Type:            nonrobust   LLR p-value:                1.257e-139
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.8547      0.011   -169.142      0.000      -1.876      -1.833
AI ROLE                         -0.4087      0.150     -2.729      0.006      -0.702      -0.115
Associate degree                 0.4185      0.028     14.882      0.000       0.363       0.474
Bachelor's degree                0.0463      0.022      2.070      0.038       0.002       0.090
High school or GED               0.3148      0.015     21.242      0.000       0.286       0.344
Master's degree                  0.1857      0.101      1.836      0.066      -0.013       0.384
Ph.D. or professional degree     0.0313      0.200      0.157      0.876      -0.361       0.424
0 years                         -0.2273      0.040     -5.640      0.000      -0.306      -0.148
1-2 years                       -0.0487      0.016     -3.099      0.002      -0.079      -0.018
11-20 years                     -0.0004      0.154     -0.002      0.998      -0.302       0.302
3-5 years                       -0.0176      0.021     -0.828      0.408      -0.059       0.024
6-10 years                      -0.3898      0.058     -6.721      0.000      -0.504      -0.276
================================================================================================
Office and Administrative Support Occupations 2021
df length: 223691
Optimization terminated successfully.
         Current function value: 0.590641
         Iterations 6

 69%|██████▉   | 62/90 [00:47<00:27,  1.01it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:               223691
Model:                          Logit   Df Residuals:                   223679
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01269
Time:                        23:54:31   Log-Likelihood:            -1.3212e+05
converged:                       True   LL-Null:                   -1.3382e+05
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.1817      0.009   -138.839      0.000      -1.198      -1.165
AI ROLE                         -0.4058      0.095     -4.270      0.000      -0.592      -0.219
Associate degree                 0.6269      0.022     28.898      0.000       0.584       0.669
Bachelor's degree                0.1794      0.018     10.107      0.000       0.145       0.214
High school or GED               0.5477      0.011     51.053      0.000       0.527       0.569
Master's degree                 -0.3510      0.090     -3.902      0.000      -0.527      -0.175
Ph.D. or professional degree     0.2908      0.150      1.937      0.053      -0.003       0.585
0 years                         -0.0925      0.025     -3.734      0.000      -0.141      -0.044
1-2 years                       -0.0554      0.011     -4.893      0.000      -0.078      -0.033
11-20 years                     -0.6654      0.141     -4.723      0.000      -0.941      -0.389
3-5 years                       -0.1195      0.016     -7.474      0.000      -0.151      -0.088
6-10 years                      -0.5645      0.045    -12.515      0.000      -0.653      -0.476
================================================================================================
Office and Administrative Support Occupations 2022
df length: 238205
Optimization terminated successfully.
         Current function value: 0.616845
         Iterations 5

 70%|███████   | 63/90 [00:48<00:27,  1.01s/it]

                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:               238205
Model:                          Logit   Df Residuals:                   238193
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.006835
Time:                        23:54:33   Log-Likelihood:            -1.4694e+05
converged:                       True   LL-Null:                   -1.4795e+05
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -0.9671      0.008   -128.043      0.000      -0.982      -0.952
AI ROLE                         -0.5189      0.084     -6.202      0.000      -0.683      -0.355
Associate degree                 0.3862      0.020     18.942      0.000       0.346       0.426
Bachelor's degree               -0.0003      0.016     -0.016      0.987      -0.032       0.031
High school or GED               0.3232      0.010     32.102      0.000       0.304       0.343
Master's degree                 -0.2693      0.072     -3.725      0.000      -0.411      -0.128
Ph.D. or professional degree     0.4435      0.109      4.053      0.000       0.229       0.658
0 years                         -0.1371      0.024     -5.711      0.000      -0.184      -0.090
1-2 years                        0.1169      0.011     10.956      0.000       0.096       0.138
11-20 years                     -0.4666      0.119     -3.911      0.000      -0.700      -0.233
3-5 years                        0.0447      0.015      3.073      0.002       0.016       0.073
6-10 years                      -0.2853      0.036     -7.931      0.000      -0.356      -0.215
================================================================================================
Office and Administrative Support Occupations 2020
df length: 175927
Optimization terminated successfully.
         Current function value: 0.525769
         Iterations 6

 71%|███████   | 64/90 [00:49<00:25,  1.01it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:               175927
Model:                          Logit   Df Residuals:                   175915
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.006968
Time:                        23:54:33   Log-Likelihood:                -92497.
converged:                       True   LL-Null:                       -93146.
Covariance Type:            nonrobust   LLR p-value:                1.191e-271
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.4191      0.010   -145.900      0.000      -1.438      -1.400
AI ROLE                         -0.2934      0.140     -2.092      0.036      -0.568      -0.018
Associate degree                 0.5098      0.027     18.956      0.000       0.457       0.563
Bachelor's degree                0.0781      0.022      3.625      0.000       0.036       0.120
High school or GED               0.3409      0.013     26.598      0.000       0.316       0.366
Master's degree                 -0.0222      0.101     -0.220      0.826      -0.220       0.175
Ph.D. or professional degree    -0.5791      0.217     -2.665      0.008      -1.005      -0.153
0 years                          0.3505      0.024     14.365      0.000       0.303       0.398
1-2 years                       -0.0570      0.014     -3.984      0.000      -0.085      -0.029
11-20 years                     -0.6895      0.158     -4.364      0.000      -0.999      -0.380
3-5 years                       -0.0756      0.020     -3.828      0.000      -0.114      -0.037
6-10 years                      -0.5651      0.058     -9.712      0.000      -0.679      -0.451
================================================================================================
Office and Administrative Support Occupations 2018
df length: 173712
Optimization terminated successfully.
         Current function value: 0.327695
         Iterations 7

 72%|███████▏  | 65/90 [00:50<00:24,  1.02it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:               173712
Model:                          Logit   Df Residuals:                   173700
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.003311
Time:                        23:54:34   Log-Likelihood:                -56925.
converged:                       True   LL-Null:                       -57114.
Covariance Type:            nonrobust   LLR p-value:                 2.640e-74
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.3280      0.013   -175.280      0.000      -2.354      -2.302
AI ROLE                         -0.0911      0.178     -0.512      0.608      -0.440       0.257
Associate degree                 0.2115      0.035      6.054      0.000       0.143       0.280
Bachelor's degree                0.0783      0.027      2.877      0.004       0.025       0.132
High school or GED               0.3130      0.018     17.105      0.000       0.277       0.349
Master's degree                  0.0481      0.135      0.356      0.722      -0.217       0.313
Ph.D. or professional degree    -0.1126      0.253     -0.445      0.657      -0.609       0.384
0 years                         -0.1571      0.052     -3.013      0.003      -0.259      -0.055
1-2 years                        0.0412      0.019      2.133      0.033       0.003       0.079
11-20 years                     -0.4387      0.221     -1.982      0.047      -0.873      -0.005
3-5 years                        0.0384      0.026      1.494      0.135      -0.012       0.089
6-10 years                      -0.1793      0.067     -2.674      0.007      -0.311      -0.048
================================================================================================
Office and Administrative Support Occupations 2023
df length: 177048
Optimization terminated successfully.
         Current function value: 0.654751
         Iterations 5

 73%|███████▎  | 66/90 [00:51<00:22,  1.05it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:               177048
Model:                          Logit   Df Residuals:                   177036
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.004651
Time:                        23:54:35   Log-Likelihood:            -1.1592e+05
converged:                       True   LL-Null:                   -1.1646e+05
Covariance Type:            nonrobust   LLR p-value:                2.110e-225
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -0.6844      0.008    -82.330      0.000      -0.701      -0.668
AI ROLE                         -0.4772      0.088     -5.450      0.000      -0.649      -0.306
Associate degree                 0.3248      0.023     13.896      0.000       0.279       0.371
Bachelor's degree                0.1127      0.018      6.337      0.000       0.078       0.148
High school or GED               0.2159      0.011     19.287      0.000       0.194       0.238
Master's degree                  0.0794      0.069      1.158      0.247      -0.055       0.214
Ph.D. or professional degree    -0.1056      0.127     -0.831      0.406      -0.355       0.143
0 years                         -0.3403      0.026    -13.244      0.000      -0.391      -0.290
1-2 years                        0.1275      0.012     10.723      0.000       0.104       0.151
11-20 years                     -0.1947      0.107     -1.824      0.068      -0.404       0.014
3-5 years                        0.0725      0.016      4.493      0.000       0.041       0.104
6-10 years                      -0.0780      0.038     -2.048      0.041      -0.153      -0.003
================================================================================================
Personal Care and Service Occupations 2019

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
 74%|███████▍  | 67/90 [00:52<00:19,  1.17it/s]

df length: 25875
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.302691
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:                25875
Model:                          Logit   Df Residuals:                    25863
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01463
Time:                        23:54:36   Log-Likelihood:                -7832.1
converged:                      False   LL-Null:                       -7948.4
Covariance Type:            nonrobust   LLR p-value:                 1.238e-43
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.5041      0.029    -87.452      0.000      -2.560      -2.448
AI ROLE                         -0.5343      1.047     -0.511      0.610      -2.586       1.517
Associate degree                 1.1329      0.112     10.106      0.000       0.913       1.353
Bachelor's degree                0.3831      0.096      4.008      0.000       0.196       0.570
High school or GED               0.2915      0.052      5.618      0.000       0.190       0.393
Master's degree                  0.6402      0.348      1.842      0.066      -0.041       1.322
Ph.D. or professional degree   -50.5278   1.11e+11  -4.57e-10      1.000   -2.17e+11    2.17e+11
0 years                          0.4537      0.145      3.135      0.002       0.170       0.737
1-2 years                        0.3374      0.060      5.633      0.000       0.220       0.455
11-20 years                      0.2106      0.749      0.281      0.779      -1.258       1.679
3-5 years                        0.4407      0.102      4.313      0.000       0.240       0.641
6-10 years                      -0.4016      0.397     -1.013      0.311      -1.179       0.376
================================================================================================
Personal Care and Service Occupations 2021

 76%|███████▌  | 68/90 [00:52<00:16,  1.30it/s]

df length: 28728
Optimization terminated successfully.
         Current function value: 0.495673
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:                28728
Model:                          Logit   Df Residuals:                    28716
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01347
Time:                        23:54:36   Log-Likelihood:                -14240.
converged:                       True   LL-Null:                       -14434.
Covariance Type:            nonrobust   LLR p-value:                 1.384e-76
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.6099      0.021    -78.039      0.000      -1.650      -1.569
AI ROLE                         -0.2786      0.629     -0.443      0.658      -1.512       0.955
Associate degree                 1.0083      0.093     10.824      0.000       0.826       1.191
Bachelor's degree                0.4630      0.069      6.690      0.000       0.327       0.599
High school or GED               0.5176      0.033     15.849      0.000       0.454       0.582
Master's degree                  0.0500      0.262      0.191      0.848      -0.463       0.563
Ph.D. or professional degree    -0.9754      1.038     -0.940      0.347      -3.010       1.059
0 years                          0.1258      0.096      1.306      0.192      -0.063       0.315
1-2 years                        0.0088      0.040      0.221      0.825      -0.069       0.086
11-20 years                      0.2600      0.471      0.552      0.581      -0.664       1.184
3-5 years                        0.2501      0.069      3.619      0.000       0.115       0.385
6-10 years                      -0.3584      0.271     -1.323      0.186      -0.889       0.173
================================================================================================
Personal Care and Service Occupations 2022

 77%|███████▋  | 69/90 [00:53<00:14,  1.40it/s]

df length: 32448
Optimization terminated successfully.
         Current function value: 0.556638
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:                32448
Model:                          Logit   Df Residuals:                    32436
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.008396
Time:                        23:54:37   Log-Likelihood:                -18062.
converged:                       True   LL-Null:                       -18215.
Covariance Type:            nonrobust   LLR p-value:                 5.107e-59
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.2699      0.017    -74.179      0.000      -1.303      -1.236
AI ROLE                         -2.0126      0.730     -2.756      0.006      -3.444      -0.582
Associate degree                 0.7988      0.084      9.470      0.000       0.633       0.964
Bachelor's degree                0.2808      0.061      4.634      0.000       0.162       0.400
High school or GED               0.3217      0.030     10.778      0.000       0.263       0.380
Master's degree                 -0.2959      0.297     -0.995      0.320      -0.879       0.287
Ph.D. or professional degree     0.3146      0.533      0.590      0.555      -0.731       1.360
0 years                          0.2912      0.081      3.593      0.000       0.132       0.450
1-2 years                        0.1193      0.036      3.355      0.001       0.050       0.189
11-20 years                     -0.3397      0.421     -0.808      0.419      -1.164       0.485
3-5 years                        0.2806      0.058      4.864      0.000       0.168       0.394
6-10 years                       0.2620      0.183      1.432      0.152      -0.097       0.621
================================================================================================
Personal Care and Service Occupations 2020

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
 78%|███████▊  | 70/90 [00:53<00:13,  1.47it/s]

df length: 24654
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.396916
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:                24654
Model:                          Logit   Df Residuals:                    24642
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01727
Time:                        23:54:38   Log-Likelihood:                -9785.6
converged:                      False   LL-Null:                       -9957.5
Covariance Type:            nonrobust   LLR p-value:                 4.799e-67
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.0682      0.025    -83.062      0.000      -2.117      -2.019
AI ROLE                         -0.7466      1.043     -0.716      0.474      -2.791       1.298
Associate degree                 1.0235      0.113      9.049      0.000       0.802       1.245
Bachelor's degree                0.6662      0.084      7.948      0.000       0.502       0.831
High school or GED               0.4593      0.042     10.809      0.000       0.376       0.543
Master's degree                  0.3017      0.388      0.778      0.436      -0.458       1.061
Ph.D. or professional degree   -18.0393   6544.322     -0.003      0.998   -1.28e+04    1.28e+04
0 years                          0.1815      0.140      1.299      0.194      -0.092       0.455
1-2 years                        0.1834      0.052      3.525      0.000       0.081       0.285
11-20 years                      1.1243      0.505      2.226      0.026       0.135       2.114
3-5 years                        0.5484      0.081      6.759      0.000       0.389       0.707
6-10 years                      -0.7529      0.352     -2.136      0.033      -1.444      -0.062
================================================================================================
Personal Care and Service Occupations 2018

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
 79%|███████▉  | 71/90 [00:54<00:12,  1.52it/s]

df length: 25428
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.225458
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:                25428
Model:                          Logit   Df Residuals:                    25416
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02075
Time:                        23:54:38   Log-Likelihood:                -5732.9
converged:                      False   LL-Null:                       -5854.4
Covariance Type:            nonrobust   LLR p-value:                 8.196e-46
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.9923      0.035    -85.877      0.000      -3.061      -2.924
AI ROLE                         -0.0497      1.057     -0.047      0.963      -2.122       2.023
Associate degree                 1.4134      0.132     10.676      0.000       1.154       1.673
Bachelor's degree                0.5935      0.119      4.978      0.000       0.360       0.827
High school or GED               0.4782      0.065      7.388      0.000       0.351       0.605
Master's degree                  0.9705      0.366      2.653      0.008       0.254       1.687
Ph.D. or professional degree   -21.4412   5.64e+04     -0.000      1.000   -1.11e+05    1.11e+05
0 years                          0.4119      0.207      1.994      0.046       0.007       0.817
1-2 years                        0.2393      0.075      3.187      0.001       0.092       0.386
11-20 years                      1.0414      0.643      1.620      0.105      -0.219       2.302
3-5 years                        0.5029      0.123      4.079      0.000       0.261       0.745
6-10 years                      -0.5772      0.393     -1.469      0.142      -1.347       0.193
================================================================================================
Personal Care and Service Occupations 2023

 80%|████████  | 72/90 [00:55<00:11,  1.60it/s]

df length: 25603
Optimization terminated successfully.
         Current function value: 0.595052
         Iterations 5
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:                25603
Model:                          Logit   Df Residuals:                    25591
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.007440
Time:                        23:54:39   Log-Likelihood:                -15235.
converged:                       True   LL-Null:                       -15349.
Covariance Type:            nonrobust   LLR p-value:                 9.186e-43
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.0765      0.019    -57.888      0.000      -1.113      -1.040
AI ROLE                         -0.3564      0.432     -0.825      0.410      -1.203       0.491
Associate degree                 0.3318      0.098      3.373      0.001       0.139       0.525
Bachelor's degree                0.2247      0.064      3.518      0.000       0.100       0.350
High school or GED               0.3117      0.032      9.789      0.000       0.249       0.374
Master's degree                  0.1656      0.238      0.697      0.486      -0.300       0.631
Ph.D. or professional degree     0.4929      0.573      0.861      0.389      -0.630       1.615
0 years                          0.4777      0.081      5.927      0.000       0.320       0.636
1-2 years                        0.1098      0.038      2.918      0.004       0.036       0.184
11-20 years                      0.0562      0.289      0.195      0.846      -0.510       0.622
3-5 years                        0.4128      0.061      6.740      0.000       0.293       0.533
6-10 years                       0.0911      0.200      0.455      0.649      -0.301       0.484
================================================================================================
Production Occupations 2019

 81%|████████  | 73/90 [00:55<00:10,  1.59it/s]

df length: 52795
Optimization terminated successfully.
         Current function value: 0.409539
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:                52795
Model:                          Logit   Df Residuals:                    52783
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.003290
Time:                        23:54:39   Log-Likelihood:                -21622.
converged:                       True   LL-Null:                       -21693.
Covariance Type:            nonrobust   LLR p-value:                 4.517e-25
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.7954      0.019    -95.947      0.000      -1.832      -1.759
AI ROLE                         -0.4178      0.317     -1.316      0.188      -1.040       0.204
Associate degree                -0.0699      0.078     -0.895      0.371      -0.223       0.083
Bachelor's degree               -0.2906      0.054     -5.409      0.000      -0.396      -0.185
High school or GED               0.0415      0.027      1.528      0.127      -0.012       0.095
Master's degree                 -1.3012      0.256     -5.078      0.000      -1.803      -0.799
Ph.D. or professional degree     0.0322      0.384      0.084      0.933      -0.720       0.784
0 years                          0.2200      0.072      3.036      0.002       0.078       0.362
1-2 years                        0.1153      0.033      3.471      0.001       0.050       0.180
11-20 years                     -0.3623      0.333     -1.088      0.277      -1.015       0.290
3-5 years                        0.0156      0.040      0.392      0.695      -0.062       0.093
6-10 years                      -0.3944      0.100     -3.937      0.000      -0.591      -0.198
================================================================================================
Production Occupations 2021

 82%|████████▏ | 74/90 [00:56<00:10,  1.54it/s]

df length: 77544
Optimization terminated successfully.
         Current function value: 0.566280
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:                77544
Model:                          Logit   Df Residuals:                    77532
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.008770
Time:                        23:54:40   Log-Likelihood:                -43912.
converged:                       True   LL-Null:                       -44300.
Covariance Type:            nonrobust   LLR p-value:                1.603e-159
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.2087      0.013    -93.108      0.000      -1.234      -1.183
AI ROLE                         -0.4039      0.179     -2.255      0.024      -0.755      -0.053
Associate degree                 0.1111      0.056      1.983      0.047       0.001       0.221
Bachelor's degree               -0.0770      0.038     -2.026      0.043      -0.151      -0.003
High school or GED               0.4211      0.018     23.709      0.000       0.386       0.456
Master's degree                 -0.7922      0.143     -5.547      0.000      -1.072      -0.512
Ph.D. or professional degree     0.2993      0.286      1.045      0.296      -0.262       0.861
0 years                         -0.1666      0.039     -4.295      0.000      -0.243      -0.091
1-2 years                       -0.0558      0.022     -2.502      0.012      -0.100      -0.012
11-20 years                     -0.7629      0.247     -3.087      0.002      -1.247      -0.278
3-5 years                        0.0075      0.028      0.268      0.789      -0.047       0.062
6-10 years                      -0.2954      0.067     -4.409      0.000      -0.427      -0.164
================================================================================================
Production Occupations 2022

 83%|████████▎ | 75/90 [00:57<00:09,  1.51it/s]

df length: 80132
Optimization terminated successfully.
         Current function value: 0.598966
         Iterations 5
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:                80132
Model:                          Logit   Df Residuals:                    80120
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.006096
Time:                        23:54:41   Log-Likelihood:                -47996.
converged:                       True   LL-Null:                       -48291.
Covariance Type:            nonrobust   LLR p-value:                3.502e-119
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.0315      0.012    -85.509      0.000      -1.055      -1.008
AI ROLE                         -0.2933      0.143     -2.048      0.041      -0.574      -0.013
Associate degree                 0.0440      0.051      0.865      0.387      -0.056       0.144
Bachelor's degree               -0.0178      0.034     -0.527      0.598      -0.084       0.048
High school or GED               0.3672      0.017     21.462      0.000       0.334       0.401
Master's degree                 -0.1638      0.102     -1.602      0.109      -0.364       0.037
Ph.D. or professional degree     0.5537      0.225      2.460      0.014       0.113       0.995
0 years                         -0.0761      0.036     -2.095      0.036      -0.147      -0.005
1-2 years                        0.0262      0.021      1.247      0.212      -0.015       0.067
11-20 years                      0.0487      0.156      0.313      0.754      -0.257       0.354
3-5 years                       -0.0230      0.025     -0.902      0.367      -0.073       0.027
6-10 years                      -0.2070      0.055     -3.765      0.000      -0.315      -0.099
================================================================================================
Production Occupations 2020

 84%|████████▍ | 76/90 [00:57<00:09,  1.52it/s]

df length: 59540
Optimization terminated successfully.
         Current function value: 0.510874
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:                59540
Model:                          Logit   Df Residuals:                    59528
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01961
Time:                        23:54:42   Log-Likelihood:                -30417.
converged:                       True   LL-Null:                       -31026.
Covariance Type:            nonrobust   LLR p-value:                4.319e-254
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.4714      0.016    -92.930      0.000      -1.502      -1.440
AI ROLE                         -0.1083      0.237     -0.458      0.647      -0.572       0.356
Associate degree                 0.8914      0.053     16.938      0.000       0.788       0.995
Bachelor's degree               -0.1955      0.048     -4.039      0.000      -0.290      -0.101
High school or GED               0.2873      0.022     13.192      0.000       0.245       0.330
Master's degree                 -0.6706      0.182     -3.692      0.000      -1.027      -0.315
Ph.D. or professional degree     0.4111      0.347      1.184      0.237      -0.270       1.092
0 years                          0.8014      0.036     22.117      0.000       0.730       0.872
1-2 years                       -0.0577      0.028     -2.053      0.040      -0.113      -0.003
11-20 years                     -0.7247      0.306     -2.367      0.018      -1.325      -0.125
3-5 years                       -0.0333      0.034     -0.970      0.332      -0.101       0.034
6-10 years                      -0.5163      0.088     -5.874      0.000      -0.689      -0.344
================================================================================================
Production Occupations 2018

 86%|████████▌ | 77/90 [00:58<00:08,  1.53it/s]

df length: 53697
Optimization terminated successfully.
         Current function value: 0.339054
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:                53697
Model:                          Logit   Df Residuals:                    53685
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.002132
Time:                        23:54:42   Log-Likelihood:                -18206.
converged:                       True   LL-Null:                       -18245.
Covariance Type:            nonrobust   LLR p-value:                 3.901e-12
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.1282      0.021   -103.772      0.000      -2.168      -2.088
AI ROLE                         -0.1501      0.332     -0.452      0.651      -0.801       0.501
Associate degree                -0.2652      0.094     -2.809      0.005      -0.450      -0.080
Bachelor's degree               -0.2476      0.059     -4.221      0.000      -0.363      -0.133
High school or GED               0.0408      0.031      1.313      0.189      -0.020       0.102
Master's degree                 -0.9996      0.284     -3.516      0.000      -1.557      -0.442
Ph.D. or professional degree    -1.0073      0.723     -1.393      0.164      -2.425       0.410
0 years                          0.2617      0.080      3.273      0.001       0.105       0.418
1-2 years                        0.0973      0.038      2.544      0.011       0.022       0.172
11-20 years                      0.1853      0.337      0.550      0.582      -0.475       0.846
3-5 years                       -0.0209      0.045     -0.465      0.642      -0.109       0.067
6-10 years                      -0.0550      0.098     -0.561      0.575      -0.247       0.137
================================================================================================
Production Occupations 2023

 87%|████████▋ | 78/90 [00:59<00:07,  1.53it/s]

df length: 63904
Optimization terminated successfully.
         Current function value: 0.641686
         Iterations 5
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:                63904
Model:                          Logit   Df Residuals:                    63892
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.002287
Time:                        23:54:43   Log-Likelihood:                -41006.
converged:                       True   LL-Null:                       -41100.
Covariance Type:            nonrobust   LLR p-value:                 2.331e-34
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -0.7409      0.013    -57.419      0.000      -0.766      -0.716
AI ROLE                         -0.3256      0.153     -2.123      0.034      -0.626      -0.025
Associate degree                 0.0594      0.052      1.133      0.257      -0.043       0.162
Bachelor's degree                0.0134      0.035      0.384      0.701      -0.055       0.082
High school or GED               0.1541      0.018      8.415      0.000       0.118       0.190
Master's degree                  0.5097      0.101      5.045      0.000       0.312       0.708
Ph.D. or professional degree    -0.4371      0.296     -1.477      0.140      -1.017       0.143
0 years                         -0.1063      0.041     -2.573      0.010      -0.187      -0.025
1-2 years                        0.1243      0.022      5.633      0.000       0.081       0.168
11-20 years                     -0.4611      0.183     -2.521      0.012      -0.820      -0.103
3-5 years                        0.0696      0.026      2.678      0.007       0.019       0.120
6-10 years                      -0.0990      0.056     -1.780      0.075      -0.208       0.010
================================================================================================
Sales and Related Occupations 2019
df length: 185705
Optimization terminated successfully.
         Current function value: 0.408885
         Iterations 7

 88%|████████▊ | 79/90 [00:59<00:08,  1.34it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:               185705
Model:                          Logit   Df Residuals:                   185693
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01254
Time:                        23:54:44   Log-Likelihood:                -75932.
converged:                       True   LL-Null:                       -76896.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.9082      0.010   -183.990      0.000      -1.928      -1.888
AI ROLE                         -0.4438      0.140     -3.172      0.002      -0.718      -0.170
Associate degree                 0.2766      0.041      6.712      0.000       0.196       0.357
Bachelor's degree                0.2984      0.021     14.465      0.000       0.258       0.339
High school or GED               0.4776      0.015     31.019      0.000       0.447       0.508
Master's degree                 -0.8748      0.151     -5.812      0.000      -1.170      -0.580
Ph.D. or professional degree    -0.4842      0.394     -1.230      0.219      -1.256       0.288
0 years                         -0.9955      0.043    -22.982      0.000      -1.080      -0.911
1-2 years                       -0.0820      0.017     -4.846      0.000      -0.115      -0.049
11-20 years                     -0.7995      0.188     -4.255      0.000      -1.168      -0.431
3-5 years                       -0.0691      0.024     -2.925      0.003      -0.115      -0.023
6-10 years                      -0.6150      0.059    -10.437      0.000      -0.731      -0.500
================================================================================================
Sales and Related Occupations 2021
df length: 207667
Optimization terminated successfully.
         Current function value: 0.576573
         Iterations 6

 89%|████████▉ | 80/90 [01:00<00:08,  1.23it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:               207667
Model:                          Logit   Df Residuals:                   207655
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01255
Time:                        23:54:45   Log-Likelihood:            -1.1974e+05
converged:                       True   LL-Null:                   -1.2126e+05
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.2125      0.008   -153.624      0.000      -1.228      -1.197
AI ROLE                         -0.4275      0.090     -4.746      0.000      -0.604      -0.251
Associate degree                 0.3784      0.033     11.520      0.000       0.314       0.443
Bachelor's degree                0.2254      0.017     13.544      0.000       0.193       0.258
High school or GED               0.4853      0.011     42.957      0.000       0.463       0.507
Master's degree                 -1.0504      0.094    -11.147      0.000      -1.235      -0.866
Ph.D. or professional degree    -0.8433      0.320     -2.632      0.008      -1.471      -0.215
0 years                         -0.2545      0.027     -9.506      0.000      -0.307      -0.202
1-2 years                        0.1129      0.013      8.962      0.000       0.088       0.138
11-20 years                     -0.5416      0.112     -4.822      0.000      -0.762      -0.321
3-5 years                        0.0336      0.018      1.863      0.062      -0.002       0.069
6-10 years                      -0.5719      0.046    -12.534      0.000      -0.661      -0.482
================================================================================================
Sales and Related Occupations 2022
df length: 216216
Optimization terminated successfully.
         Current function value: 0.599757
         Iterations 5

 90%|█████████ | 81/90 [01:01<00:07,  1.16it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:               216216
Model:                          Logit   Df Residuals:                   216204
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.007874
Time:                        23:54:46   Log-Likelihood:            -1.2968e+05
converged:                       True   LL-Null:                   -1.3071e+05
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.0221      0.007   -141.650      0.000      -1.036      -1.008
AI ROLE                         -0.3445      0.081     -4.244      0.000      -0.504      -0.185
Associate degree                 0.1751      0.030      5.765      0.000       0.116       0.235
Bachelor's degree                0.1327      0.016      8.338      0.000       0.101       0.164
High school or GED               0.2715      0.011     24.698      0.000       0.250       0.293
Master's degree                 -0.4115      0.073     -5.628      0.000      -0.555      -0.268
Ph.D. or professional degree    -0.5138      0.230     -2.231      0.026      -0.965      -0.062
0 years                         -0.5720      0.028    -20.333      0.000      -0.627      -0.517
1-2 years                        0.2069      0.012     17.010      0.000       0.183       0.231
11-20 years                     -0.4669      0.125     -3.728      0.000      -0.712      -0.221
3-5 years                        0.0913      0.017      5.375      0.000       0.058       0.125
6-10 years                      -0.2656      0.039     -6.780      0.000      -0.342      -0.189
================================================================================================
Sales and Related Occupations 2020
df length: 180255
Optimization terminated successfully.
         Current function value: 0.471249
         Iterations 7

 91%|█████████ | 82/90 [01:02<00:07,  1.12it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:               180255
Model:                          Logit   Df Residuals:                   180243
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01130
Time:                        23:54:47   Log-Likelihood:                -84945.
converged:                       True   LL-Null:                       -85916.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.6660      0.009   -180.012      0.000      -1.684      -1.648
AI ROLE                         -0.6375      0.129     -4.925      0.000      -0.891      -0.384
Associate degree                 0.7179      0.037     19.293      0.000       0.645       0.791
Bachelor's degree                0.4009      0.020     19.852      0.000       0.361       0.441
High school or GED               0.3466      0.014     24.628      0.000       0.319       0.374
Master's degree                 -1.5026      0.178     -8.446      0.000      -1.851      -1.154
Ph.D. or professional degree    -0.6080      0.371     -1.637      0.102      -1.336       0.120
0 years                         -0.5326      0.033    -16.244      0.000      -0.597      -0.468
1-2 years                        0.1375      0.016      8.841      0.000       0.107       0.168
11-20 years                     -1.0794      0.177     -6.092      0.000      -1.427      -0.732
3-5 years                        0.0128      0.023      0.566      0.571      -0.031       0.057
6-10 years                      -0.6130      0.059    -10.437      0.000      -0.728      -0.498
================================================================================================
Sales and Related Occupations 2018
df length: 170255
Optimization terminated successfully.
         Current function value: 0.352118
         Iterations 7

 92%|█████████▏| 83/90 [01:03<00:06,  1.10it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:               170255
Model:                          Logit   Df Residuals:                   170243
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01356
Time:                        23:54:48   Log-Likelihood:                -59950.
converged:                       True   LL-Null:                       -60774.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.2836      0.012   -184.217      0.000      -2.308      -2.259
AI ROLE                         -0.2539      0.159     -1.598      0.110      -0.565       0.058
Associate degree                 0.1046      0.048      2.184      0.029       0.011       0.198
Bachelor's degree                0.4565      0.023     19.487      0.000       0.411       0.502
High school or GED               0.6042      0.018     33.601      0.000       0.569       0.639
Master's degree                 -0.6816      0.194     -3.513      0.000      -1.062      -0.301
Ph.D. or professional degree    -0.3003      0.423     -0.710      0.478      -1.130       0.529
0 years                         -0.8807      0.063    -14.077      0.000      -1.003      -0.758
1-2 years                       -0.0260      0.019     -1.337      0.181      -0.064       0.012
11-20 years                     -1.1429      0.257     -4.454      0.000      -1.646      -0.640
3-5 years                       -0.0625      0.027     -2.319      0.020      -0.115      -0.010
6-10 years                      -0.6550      0.065    -10.047      0.000      -0.783      -0.527
================================================================================================
Sales and Related Occupations 2023
df length: 183257
Optimization terminated successfully.
         Current function value: 0.645124
         Iterations 5

 93%|█████████▎| 84/90 [01:04<00:05,  1.09it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:               183257
Model:                          Logit   Df Residuals:                   183245
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.008183
Time:                        23:54:49   Log-Likelihood:            -1.1822e+05
converged:                       True   LL-Null:                   -1.1920e+05
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -0.7244      0.007    -98.869      0.000      -0.739      -0.710
AI ROLE                         -0.2519      0.088     -2.858      0.004      -0.425      -0.079
Associate degree                 0.8375      0.030     28.353      0.000       0.780       0.895
Bachelor's degree                0.2570      0.017     15.275      0.000       0.224       0.290
High school or GED               0.1792      0.011     15.711      0.000       0.157       0.202
Master's degree                  0.5958      0.073      8.150      0.000       0.452       0.739
Ph.D. or professional degree    -0.5346      0.237     -2.256      0.024      -0.999      -0.070
0 years                         -0.4974      0.026    -19.242      0.000      -0.548      -0.447
1-2 years                        0.1107      0.013      8.641      0.000       0.086       0.136
11-20 years                     -0.0273      0.106     -0.258      0.796      -0.235       0.180
3-5 years                        0.1008      0.018      5.742      0.000       0.066       0.135
6-10 years                      -0.0953      0.040     -2.400      0.016      -0.173      -0.017
================================================================================================
Transportation and Material Moving Occupations 2019

 94%|█████████▍| 85/90 [01:05<00:04,  1.15it/s]

df length: 92120
Optimization terminated successfully.
         Current function value: 0.509786
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:                92120
Model:                          Logit   Df Residuals:                    92108
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.008581
Time:                        23:54:49   Log-Likelihood:                -46961.
converged:                       True   LL-Null:                       -47368.
Covariance Type:            nonrobust   LLR p-value:                3.200e-167
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.3630      0.011   -126.821      0.000      -1.384      -1.342
AI ROLE                         -0.5518      0.537     -1.028      0.304      -1.604       0.501
Associate degree                -0.4338      0.109     -3.993      0.000      -0.647      -0.221
Bachelor's degree               -0.2661      0.072     -3.708      0.000      -0.407      -0.125
High school or GED              -0.2499      0.018    -13.520      0.000      -0.286      -0.214
Master's degree                  0.1425      0.211      0.675      0.500      -0.271       0.556
Ph.D. or professional degree    -1.7165      0.728     -2.357      0.018      -3.144      -0.289
0 years                         -0.0732      0.041     -1.802      0.072      -0.153       0.006
1-2 years                        0.5113      0.020     24.956      0.000       0.471       0.551
11-20 years                     -0.2850      0.383     -0.744      0.457      -1.036       0.466
3-5 years                        0.4699      0.038     12.368      0.000       0.395       0.544
6-10 years                       0.1474      0.120      1.233      0.218      -0.087       0.382
================================================================================================
Transportation and Material Moving Occupations 2021
df length: 168157
Optimization terminated successfully.
         Current function value: 0.652853
         Iterations 6

 96%|█████████▌| 86/90 [01:06<00:03,  1.12it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:               168157
Model:                          Logit   Df Residuals:                   168145
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.007637
Time:                        23:54:50   Log-Likelihood:            -1.0978e+05
converged:                       True   LL-Null:                   -1.1063e+05
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -0.6534      0.007    -94.261      0.000      -0.667      -0.640
AI ROLE                         -1.5557      0.296     -5.253      0.000      -2.136      -0.975
Associate degree                 0.1819      0.076      2.389      0.017       0.033       0.331
Bachelor's degree                0.1246      0.054      2.313      0.021       0.019       0.230
High school or GED               0.4177      0.011     38.693      0.000       0.397       0.439
Master's degree                 -1.0931      0.186     -5.884      0.000      -1.457      -0.729
Ph.D. or professional degree    -0.0991      0.456     -0.218      0.828      -0.992       0.794
0 years                         -0.2229      0.023     -9.822      0.000      -0.267      -0.178
1-2 years                       -0.0576      0.013     -4.304      0.000      -0.084      -0.031
11-20 years                      0.3289      0.197      1.668      0.095      -0.058       0.715
3-5 years                       -0.0846      0.027     -3.076      0.002      -0.138      -0.031
6-10 years                      -0.3403      0.097     -3.517      0.000      -0.530      -0.151
================================================================================================
Transportation and Material Moving Occupations 2022
df length: 136730
Optimization terminated successfully.
         Current function value: 0.655710
         Iterations 5

 97%|█████████▋| 87/90 [01:07<00:02,  1.13it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:               136730
Model:                          Logit   Df Residuals:                   136718
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.002062
Time:                        23:54:51   Log-Likelihood:                -89655.
converged:                       True   LL-Null:                       -89840.
Covariance Type:            nonrobust   LLR p-value:                 1.122e-72
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -0.5462      0.007    -74.195      0.000      -0.561      -0.532
AI ROLE                         -0.5975      0.221     -2.707      0.007      -1.030      -0.165
Associate degree                 0.0084      0.069      0.122      0.903      -0.127       0.144
Bachelor's degree               -0.1552      0.052     -2.980      0.003      -0.257      -0.053
High school or GED              -0.0210      0.013     -1.632      0.103      -0.046       0.004
Master's degree                 -0.7374      0.155     -4.748      0.000      -1.042      -0.433
Ph.D. or professional degree     0.4395      0.381      1.155      0.248      -0.307       1.185
0 years                         -0.3619      0.026    -13.925      0.000      -0.413      -0.311
1-2 years                        0.1295      0.015      8.864      0.000       0.101       0.158
11-20 years                     -0.4062      0.214     -1.901      0.057      -0.825       0.013
3-5 years                        0.0670      0.027      2.448      0.014       0.013       0.121
6-10 years                      -0.0422      0.087     -0.487      0.626      -0.212       0.128
================================================================================================
Transportation and Material Moving Occupations 2020
df length: 141154
Optimization terminated successfully.
         Current function value: 0.588578
         Iterations 5

 98%|█████████▊| 88/90 [01:08<00:01,  1.15it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:               141154
Model:                          Logit   Df Residuals:                   141142
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02241
Time:                        23:54:52   Log-Likelihood:                -83080.
converged:                       True   LL-Null:                       -84985.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.1941      0.009   -139.789      0.000      -1.211      -1.177
AI ROLE                         -0.6060      0.422     -1.437      0.151      -1.432       0.220
Associate degree                 1.5737      0.064     24.672      0.000       1.449       1.699
Bachelor's degree                0.2225      0.064      3.466      0.001       0.097       0.348
High school or GED               0.6082      0.013     47.975      0.000       0.583       0.633
Master's degree                 -0.2395      0.201     -1.193      0.233      -0.633       0.154
Ph.D. or professional degree     0.0853      0.369      0.231      0.817      -0.638       0.809
0 years                          0.3566      0.016     22.050      0.000       0.325       0.388
1-2 years                        0.1010      0.016      6.140      0.000       0.069       0.133
11-20 years                      0.5986      0.194      3.088      0.002       0.219       0.978
3-5 years                        0.1299      0.033      3.886      0.000       0.064       0.195
6-10 years                      -0.1219      0.105     -1.166      0.244      -0.327       0.083
================================================================================================
Transportation and Material Moving Occupations 2018

 99%|█████████▉| 89/90 [01:08<00:00,  1.19it/s]

df length: 111268
Optimization terminated successfully.
         Current function value: 0.520100
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:               111268
Model:                          Logit   Df Residuals:                   111256
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01022
Time:                        23:54:53   Log-Likelihood:                -57871.
converged:                       True   LL-Null:                       -58468.
Covariance Type:            nonrobust   LLR p-value:                1.725e-249
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.2273      0.009   -136.204      0.000      -1.245      -1.210
AI ROLE                         -0.9647      0.527     -1.832      0.067      -1.997       0.068
Associate degree                -0.8286      0.133     -6.243      0.000      -1.089      -0.568
Bachelor's degree               -0.4303      0.079     -5.477      0.000      -0.584      -0.276
High school or GED              -0.5201      0.019    -27.105      0.000      -0.558      -0.483
Master's degree                  0.6728      0.192      3.506      0.000       0.297       1.049
Ph.D. or professional degree    -0.8312      0.435     -1.909      0.056      -1.684       0.022
0 years                          0.4081      0.034     12.061      0.000       0.342       0.474
1-2 years                        0.3108      0.019     16.133      0.000       0.273       0.349
11-20 years                     -1.3609      0.597     -2.279      0.023      -2.531      -0.190
3-5 years                       -0.0021      0.041     -0.052      0.958      -0.082       0.077
6-10 years                      -0.9786      0.134     -7.314      0.000      -1.241      -0.716
================================================================================================
Transportation and Material Moving Occupations 2023

100%|██████████| 90/90 [01:09<00:00,  1.29it/s]

df length: 110719
Optimization terminated successfully.
         Current function value: 0.672632
         Iterations 5
                           Logit Regression Results
==============================================================================
Dep. Variable:                  LEAVE   No. Observations:               110719
Model:                          Logit   Df Residuals:                   110707
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.003189
Time:                        23:54:53   Log-Likelihood:                -74473.
converged:                       True   LL-Null:                       -74711.
Covariance Type:            nonrobust   LLR p-value:                 3.304e-95
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -0.3805      0.008    -46.289      0.000      -0.397      -0.364
AI ROLE                         -0.5837      0.243     -2.399      0.016      -1.061      -0.107
Associate degree                 1.1275      0.061     18.410      0.000       1.007       1.247
Bachelor's degree                0.2235      0.048      4.646      0.000       0.129       0.318
High school or GED               0.0316      0.014      2.269      0.023       0.004       0.059
Master's degree                 -0.0151      0.171     -0.088      0.930      -0.350       0.320
Ph.D. or professional degree    -0.6620      0.387     -1.711      0.087      -1.420       0.096
0 years                         -0.2076      0.025     -8.274      0.000      -0.257      -0.158
1-2 years                       -0.0581      0.016     -3.669      0.000      -0.089      -0.027
11-20 years                      0.3417      0.213      1.606      0.108      -0.075       0.759
3-5 years                       -0.1012      0.031     -3.240      0.001      -0.162      -0.040
6-10 years                      -0.2969      0.086     -3.472      0.001      -0.465      -0.129
================================================================================================
HEALTH_WELLBEING

  0%|          | 0/90 [00:00<?, ?it/s]

Architecture and Engineering Occupations 2019

  1%|          | 1/90 [00:00<00:55,  1.61it/s]

df length: 42432
Optimization terminated successfully.
         Current function value: 0.133628
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:                42432
Model:                          Logit   Df Residuals:                    42420
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.03626
Time:                        23:54:54   Log-Likelihood:                -5670.1
converged:                       True   LL-Null:                       -5883.4
Covariance Type:            nonrobust   LLR p-value:                 1.316e-84
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.9032      0.073    -53.696      0.000      -4.046      -3.761
AI ROLE                         -0.5901      0.273     -2.164      0.030      -1.125      -0.056
Associate degree                 0.8285      0.129      6.398      0.000       0.575       1.082
Bachelor's degree                0.6857      0.086      8.004      0.000       0.518       0.854
High school or GED               1.6816      0.089     18.793      0.000       1.506       1.857
Master's degree                  0.6796      0.210      3.242      0.001       0.269       1.090
Ph.D. or professional degree     0.2764      0.420      0.659      0.510      -0.546       1.099
0 years                         -0.1254      0.160     -0.785      0.433      -0.439       0.188
1-2 years                       -0.5656      0.092     -6.150      0.000      -0.746      -0.385
11-20 years                     -0.0619      0.183     -0.339      0.735      -0.420       0.296
3-5 years                       -0.5011      0.073     -6.865      0.000      -0.644      -0.358
6-10 years                      -0.3032      0.090     -3.373      0.001      -0.479      -0.127
================================================================================================
Architecture and Engineering Occupations 2021

  2%|▏         | 2/90 [00:01<00:54,  1.61it/s]

df length: 42098
Optimization terminated successfully.
         Current function value: 0.156454
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:                42098
Model:                          Logit   Df Residuals:                    42086
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01610
Time:                        23:54:55   Log-Likelihood:                -6586.4
converged:                       True   LL-Null:                       -6694.2
Covariance Type:            nonrobust   LLR p-value:                 4.281e-40
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.8709      0.068    -56.678      0.000      -4.005      -3.737
AI ROLE                         -0.5459      0.218     -2.502      0.012      -0.973      -0.118
Associate degree                 0.4635      0.112      4.155      0.000       0.245       0.682
Bachelor's degree                0.6057      0.075      8.044      0.000       0.458       0.753
High school or GED               0.2283      0.098      2.335      0.020       0.037       0.420
Master's degree                 -0.0318      0.236     -0.134      0.893      -0.495       0.431
Ph.D. or professional degree     0.0727      0.389      0.187      0.852      -0.689       0.834
0 years                          0.9941      0.121      8.185      0.000       0.756       1.232
1-2 years                        0.2030      0.086      2.372      0.018       0.035       0.371
11-20 years                      0.6261      0.145      4.317      0.000       0.342       0.910
3-5 years                        0.3223      0.070      4.614      0.000       0.185       0.459
6-10 years                       0.2606      0.086      3.022      0.003       0.092       0.430
================================================================================================
Architecture and Engineering Occupations 2022

  3%|▎         | 3/90 [00:01<00:55,  1.57it/s]

df length: 57103
Optimization terminated successfully.
         Current function value: 0.183490
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:                57103
Model:                          Logit   Df Residuals:                    57091
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01515
Time:                        23:54:55   Log-Likelihood:                -10478.
converged:                       True   LL-Null:                       -10639.
Covariance Type:            nonrobust   LLR p-value:                 1.627e-62
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.7418      0.054    -68.873      0.000      -3.848      -3.635
AI ROLE                         -0.7886      0.183     -4.300      0.000      -1.148      -0.429
Associate degree                 0.7196      0.085      8.478      0.000       0.553       0.886
Bachelor's degree                0.6446      0.060     10.692      0.000       0.526       0.763
High school or GED               0.6262      0.075      8.356      0.000       0.479       0.773
Master's degree                 -0.0089      0.193     -0.046      0.963      -0.387       0.369
Ph.D. or professional degree    -0.2338      0.386     -0.606      0.544      -0.990       0.522
0 years                          0.5069      0.114      4.444      0.000       0.283       0.730
1-2 years                        0.3281      0.064      5.097      0.000       0.202       0.454
11-20 years                      0.2451      0.121      2.019      0.043       0.007       0.483
3-5 years                        0.3231      0.055      5.880      0.000       0.215       0.431
6-10 years                       0.2968      0.066      4.473      0.000       0.167       0.427
================================================================================================
Architecture and Engineering Occupations 2020

  4%|▍         | 4/90 [00:02<00:53,  1.61it/s]

df length: 33522
Optimization terminated successfully.
         Current function value: 0.128169
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:                33522
Model:                          Logit   Df Residuals:                    33510
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02101
Time:                        23:54:56   Log-Likelihood:                -4296.5
converged:                       True   LL-Null:                       -4388.7
Covariance Type:            nonrobust   LLR p-value:                 1.256e-33
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.1313      0.086    -47.854      0.000      -4.301      -3.962
AI ROLE                         -0.5205      0.308     -1.690      0.091      -1.124       0.083
Associate degree                 0.9952      0.138      7.201      0.000       0.724       1.266
Bachelor's degree                0.7091      0.100      7.116      0.000       0.514       0.904
High school or GED               1.3036      0.107     12.141      0.000       1.093       1.514
Master's degree                  0.4744      0.254      1.868      0.062      -0.023       0.972
Ph.D. or professional degree     0.5484      0.423      1.296      0.195      -0.281       1.378
0 years                          0.4593      0.171      2.679      0.007       0.123       0.795
1-2 years                       -0.1940      0.105     -1.851      0.064      -0.399       0.011
11-20 years                      0.3201      0.184      1.736      0.083      -0.041       0.682
3-5 years                       -0.1559      0.086     -1.817      0.069      -0.324       0.012
6-10 years                      -0.0303      0.106     -0.286      0.775      -0.238       0.178
================================================================================================
Architecture and Engineering Occupations 2018

  6%|▌         | 5/90 [00:03<00:52,  1.62it/s]

df length: 40569
Optimization terminated successfully.
         Current function value: 0.076214
         Iterations 9
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:                40569
Model:                          Logit   Df Residuals:                    40557
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.003517
Time:                        23:54:57   Log-Likelihood:                -3091.9
converged:                       True   LL-Null:                       -3102.8
Covariance Type:            nonrobust   LLR p-value:                   0.02574
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.3773      0.088    -49.602      0.000      -4.550      -4.204
AI ROLE                          0.2644      0.296      0.894      0.371      -0.315       0.844
Associate degree                 0.2400      0.174      1.378      0.168      -0.101       0.581
Bachelor's degree                0.2045      0.109      1.879      0.060      -0.009       0.418
High school or GED               0.5833      0.134      4.342      0.000       0.320       0.847
Master's degree                 -0.1049      0.331     -0.317      0.751      -0.754       0.544
Ph.D. or professional degree    -0.4408      0.715     -0.616      0.538      -1.843       0.961
0 years                         -0.1784      0.289     -0.617      0.537      -0.746       0.389
1-2 years                       -0.0975      0.133     -0.735      0.462      -0.358       0.162
11-20 years                     -0.1408      0.328     -0.429      0.668      -0.784       0.502
3-5 years                        0.0085      0.105      0.081      0.935      -0.197       0.214
6-10 years                      -0.0827      0.140     -0.589      0.556      -0.358       0.192
================================================================================================
Architecture and Engineering Occupations 2023

  7%|▋         | 6/90 [00:03<00:52,  1.61it/s]

df length: 46241
Optimization terminated successfully.
         Current function value: 0.227457
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:                46241
Model:                          Logit   Df Residuals:                    46229
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01771
Time:                        23:54:57   Log-Likelihood:                -10518.
converged:                       True   LL-Null:                       -10707.
Covariance Type:            nonrobust   LLR p-value:                 1.599e-74
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.5339      0.057    -62.539      0.000      -3.645      -3.423
AI ROLE                         -0.2584      0.140     -1.852      0.064      -0.532       0.015
Associate degree                 0.8224      0.084      9.817      0.000       0.658       0.987
Bachelor's degree                0.7442      0.060     12.317      0.000       0.626       0.863
High school or GED               0.5107      0.078      6.522      0.000       0.357       0.664
Master's degree                  0.4721      0.163      2.897      0.004       0.153       0.791
Ph.D. or professional degree    -0.0780      0.343     -0.228      0.820      -0.750       0.594
0 years                          0.5738      0.104      5.505      0.000       0.369       0.778
1-2 years                        0.2128      0.066      3.233      0.001       0.084       0.342
11-20 years                      0.3796      0.108      3.508      0.000       0.167       0.592
3-5 years                        0.3426      0.054      6.402      0.000       0.238       0.447
6-10 years                       0.4159      0.062      6.674      0.000       0.294       0.538
================================================================================================
Arts, Design, Entertainment, Sports, and Media Occupations 2019

  8%|▊         | 7/90 [00:04<00:51,  1.61it/s]

df length: 40594
Optimization terminated successfully.
         Current function value: 0.086919
         Iterations 9
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:                40594
Model:                          Logit   Df Residuals:                    40582
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02550
Time:                        23:54:58   Log-Likelihood:                -3528.4
converged:                       True   LL-Null:                       -3620.7
Covariance Type:            nonrobust   LLR p-value:                 1.105e-33
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.3669      0.066    -65.678      0.000      -4.497      -4.237
AI ROLE                          2.0074      0.178     11.273      0.000       1.658       2.356
Associate degree                 0.6354      0.215      2.958      0.003       0.214       1.056
Bachelor's degree                0.5828      0.099      5.866      0.000       0.388       0.777
High school or GED               0.7753      0.100      7.771      0.000       0.580       0.971
Master's degree                  0.2469      0.347      0.711      0.477      -0.434       0.928
Ph.D. or professional degree    -0.6407      1.009     -0.635      0.526      -2.619       1.338
0 years                         -0.6746      0.297     -2.270      0.023      -1.257      -0.092
1-2 years                       -0.4216      0.119     -3.543      0.000      -0.655      -0.188
11-20 years                     -0.0058      0.418     -0.014      0.989      -0.824       0.813
3-5 years                        0.1259      0.102      1.230      0.219      -0.075       0.326
6-10 years                      -0.1769      0.183     -0.968      0.333      -0.535       0.181
================================================================================================
Arts, Design, Entertainment, Sports, and Media Occupations 2021

  9%|▉         | 8/90 [00:04<00:51,  1.60it/s]

df length: 49779
Optimization terminated successfully.
         Current function value: 0.103100
         Iterations 9
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:                49779
Model:                          Logit   Df Residuals:                    49767
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02892
Time:                        23:54:58   Log-Likelihood:                -5132.2
converged:                       True   LL-Null:                       -5285.1
Covariance Type:            nonrobust   LLR p-value:                 5.685e-59
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.3131      0.057    -76.063      0.000      -4.424      -4.202
AI ROLE                         -0.4880      0.360     -1.355      0.175      -1.194       0.218
Associate degree                 0.2210      0.189      1.172      0.241      -0.149       0.591
Bachelor's degree                0.6781      0.079      8.631      0.000       0.524       0.832
High school or GED               0.1755      0.090      1.959      0.050   -5.49e-05       0.351
Master's degree                  0.5058      0.289      1.749      0.080      -0.061       1.073
Ph.D. or professional degree     1.2743      0.371      3.437      0.001       0.548       2.001
0 years                         -0.4295      0.257     -1.671      0.095      -0.933       0.074
1-2 years                        0.4154      0.085      4.870      0.000       0.248       0.583
11-20 years                      1.2190      0.267      4.567      0.000       0.696       1.742
3-5 years                        0.6470      0.085      7.618      0.000       0.481       0.813
6-10 years                       0.7333      0.125      5.885      0.000       0.489       0.978
================================================================================================
Arts, Design, Entertainment, Sports, and Media Occupations 2022

 10%|█         | 9/90 [00:05<00:51,  1.57it/s]

df length: 54182
Optimization terminated successfully.
         Current function value: 0.130931
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:                54182
Model:                          Logit   Df Residuals:                    54170
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.03496
Time:                        23:54:59   Log-Likelihood:                -7094.1
converged:                       True   LL-Null:                       -7351.1
Covariance Type:            nonrobust   LLR p-value:                3.349e-103
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.0793      0.046    -87.832      0.000      -4.170      -3.988
AI ROLE                          0.4824      0.178      2.717      0.007       0.134       0.830
Associate degree                 0.4143      0.133      3.127      0.002       0.155       0.674
Bachelor's degree                0.5659      0.065      8.700      0.000       0.438       0.693
High school or GED               0.1416      0.080      1.764      0.078      -0.016       0.299
Master's degree                  0.5482      0.226      2.431      0.015       0.106       0.990
Ph.D. or professional degree     1.0900      0.319      3.415      0.001       0.464       1.716
0 years                          0.3358      0.155      2.164      0.030       0.032       0.640
1-2 years                        0.6385      0.073      8.760      0.000       0.496       0.781
11-20 years                      1.6293      0.184      8.840      0.000       1.268       1.991
3-5 years                        0.7711      0.071     10.897      0.000       0.632       0.910
6-10 years                       0.8056      0.103      7.853      0.000       0.605       1.007
================================================================================================
Arts, Design, Entertainment, Sports, and Media Occupations 2020

 11%|█         | 10/90 [00:06<00:50,  1.60it/s]

df length: 39617
Optimization terminated successfully.
         Current function value: 0.076857
         Iterations 9
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:                39617
Model:                          Logit   Df Residuals:                    39605
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01416
Time:                        23:55:00   Log-Likelihood:                -3044.9
converged:                       True   LL-Null:                       -3088.6
Covariance Type:            nonrobust   LLR p-value:                 5.212e-14
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.5778      0.074    -61.729      0.000      -4.723      -4.432
AI ROLE                          0.1179      0.456      0.259      0.796      -0.776       1.012
Associate degree                 0.6989      0.235      2.974      0.003       0.238       1.159
Bachelor's degree                0.5325      0.114      4.652      0.000       0.308       0.757
High school or GED               0.4990      0.105      4.758      0.000       0.293       0.705
Master's degree                 -0.4616      0.586     -0.787      0.431      -1.611       0.687
Ph.D. or professional degree     0.3388      0.720      0.471      0.638      -1.071       1.749
0 years                         -0.5875      0.268     -2.190      0.029      -1.113      -0.062
1-2 years                        0.0515      0.123      0.418      0.676      -0.190       0.293
11-20 years                      0.4030      0.514      0.785      0.433      -0.603       1.409
3-5 years                        0.4620      0.120      3.860      0.000       0.227       0.697
6-10 years                       0.5685      0.181      3.146      0.002       0.214       0.923
================================================================================================
Arts, Design, Entertainment, Sports, and Media Occupations 2018

 12%|█▏        | 11/90 [00:06<00:48,  1.62it/s]

df length: 37105
Optimization terminated successfully.
         Current function value: 0.065595
         Iterations 10
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:                37105
Model:                          Logit   Df Residuals:                    37093
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01377
Time:                        23:55:00   Log-Likelihood:                -2433.9
converged:                       True   LL-Null:                       -2467.9
Covariance Type:            nonrobust   LLR p-value:                 2.939e-10
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.5255      0.075    -60.319      0.000      -4.673      -4.378
AI ROLE                          0.4428      0.462      0.959      0.338      -0.462       1.348
Associate degree                 0.2310      0.253      0.914      0.361      -0.264       0.726
Bachelor's degree                0.2848      0.114      2.492      0.013       0.061       0.509
High school or GED              -0.7058      0.185     -3.822      0.000      -1.068      -0.344
Master's degree                 -0.1969      0.464     -0.424      0.671      -1.106       0.712
Ph.D. or professional degree    -0.5301      1.007     -0.526      0.599      -2.504       1.444
0 years                          0.1247      0.418      0.298      0.765      -0.694       0.944
1-2 years                        0.1524      0.137      1.112      0.266      -0.116       0.421
11-20 years                     -1.2664      1.004     -1.261      0.207      -3.235       0.702
3-5 years                        0.2680      0.131      2.038      0.042       0.010       0.526
6-10 years                       0.6301      0.177      3.554      0.000       0.283       0.978
================================================================================================
Arts, Design, Entertainment, Sports, and Media Occupations 2023

 13%|█▎        | 12/90 [00:07<00:47,  1.63it/s]

df length: 40306
Optimization terminated successfully.
         Current function value: 0.215092
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:                40306
Model:                          Logit   Df Residuals:                    40294
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.006218
Time:                        23:55:01   Log-Likelihood:                -8669.5
converged:                       True   LL-Null:                       -8723.7
Covariance Type:            nonrobust   LLR p-value:                 3.681e-18
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.9161      0.032    -91.955      0.000      -2.978      -2.854
AI ROLE                         -0.4917      0.224     -2.191      0.028      -0.932      -0.052
Associate degree                -0.0370      0.126     -0.293      0.770      -0.284       0.210
Bachelor's degree                0.0571      0.058      0.984      0.325      -0.057       0.171
High school or GED              -0.2607      0.069     -3.797      0.000      -0.395      -0.126
Master's degree                 -0.3650      0.276     -1.320      0.187      -0.907       0.177
Ph.D. or professional degree     0.0683      0.367      0.186      0.852      -0.651       0.788
0 years                         -0.2296      0.142     -1.618      0.106      -0.508       0.049
1-2 years                        0.3902      0.062      6.285      0.000       0.269       0.512
11-20 years                      0.5087      0.243      2.094      0.036       0.032       0.985
3-5 years                        0.2394      0.067      3.579      0.000       0.108       0.370
6-10 years                       0.5295      0.095      5.585      0.000       0.344       0.715
================================================================================================
Business and Financial Operations Occupations 2019
df length: 141921
Optimization terminated successfully.
         Current function value: 0.126100
         Iterations 8

 14%|█▍        | 13/90 [00:08<00:54,  1.41it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:               141921
Model:                          Logit   Df Residuals:                   141909
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.007278
Time:                        23:55:02   Log-Likelihood:                -17896.
converged:                       True   LL-Null:                       -18027.
Covariance Type:            nonrobust   LLR p-value:                 7.034e-50
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.6404      0.033   -110.715      0.000      -3.705      -3.576
AI ROLE                         -0.0515      0.141     -0.366      0.714      -0.327       0.224
Associate degree                 0.2164      0.088      2.450      0.014       0.043       0.390
Bachelor's degree                0.2050      0.041      5.019      0.000       0.125       0.285
High school or GED               0.6105      0.051     11.967      0.000       0.511       0.710
Master's degree                 -0.4128      0.176     -2.341      0.019      -0.759      -0.067
Ph.D. or professional degree     0.4704      0.265      1.774      0.076      -0.049       0.990
0 years                          0.6480      0.089      7.256      0.000       0.473       0.823
1-2 years                       -0.1491      0.045     -3.288      0.001      -0.238      -0.060
11-20 years                     -0.4426      0.193     -2.290      0.022      -0.821      -0.064
3-5 years                       -0.1981      0.042     -4.707      0.000      -0.281      -0.116
6-10 years                      -0.3995      0.067     -5.948      0.000      -0.531      -0.268
================================================================================================
Business and Financial Operations Occupations 2021
df length: 158377
Optimization terminated successfully.
         Current function value: 0.186062
         Iterations 8

 16%|█▌        | 14/90 [00:09<01:00,  1.25it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:               158377
Model:                          Logit   Df Residuals:                   158365
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01634
Time:                        23:55:03   Log-Likelihood:                -29468.
converged:                       True   LL-Null:                       -29958.
Covariance Type:            nonrobust   LLR p-value:                5.438e-203
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.7374      0.031   -118.887      0.000      -3.799      -3.676
AI ROLE                          0.1793      0.077      2.339      0.019       0.029       0.329
Associate degree                 0.4548      0.066      6.929      0.000       0.326       0.583
Bachelor's degree                0.6132      0.034     18.128      0.000       0.547       0.679
High school or GED               0.8229      0.041     20.253      0.000       0.743       0.903
Master's degree                 -0.0964      0.135     -0.716      0.474      -0.360       0.168
Ph.D. or professional degree     0.3587      0.220      1.634      0.102      -0.072       0.789
0 years                          0.3371      0.089      3.769      0.000       0.162       0.512
1-2 years                        0.2235      0.035      6.419      0.000       0.155       0.292
11-20 years                      0.6110      0.105      5.825      0.000       0.405       0.817
3-5 years                        0.3258      0.032     10.222      0.000       0.263       0.388
6-10 years                       0.6003      0.041     14.526      0.000       0.519       0.681
================================================================================================
Business and Financial Operations Occupations 2022
df length: 182061
Optimization terminated successfully.
         Current function value: 0.211668
         Iterations 7

 17%|█▋        | 15/90 [00:10<01:05,  1.14it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:               182061
Model:                          Logit   Df Residuals:                   182049
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01757
Time:                        23:55:04   Log-Likelihood:                -38536.
converged:                       True   LL-Null:                       -39226.
Covariance Type:            nonrobust   LLR p-value:                6.005e-289
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.5856      0.027   -132.086      0.000      -3.639      -3.532
AI ROLE                         -0.1022      0.071     -1.442      0.149      -0.241       0.037
Associate degree                 0.4917      0.055      8.904      0.000       0.383       0.600
Bachelor's degree                0.6274      0.030     21.082      0.000       0.569       0.686
High school or GED               0.7569      0.037     20.564      0.000       0.685       0.829
Master's degree                  0.3719      0.096      3.868      0.000       0.183       0.560
Ph.D. or professional degree     0.1395      0.198      0.705      0.481      -0.248       0.527
0 years                          0.0604      0.085      0.707      0.479      -0.107       0.228
1-2 years                        0.2526      0.031      8.136      0.000       0.192       0.313
11-20 years                      0.4376      0.091      4.826      0.000       0.260       0.615
3-5 years                        0.4496      0.028     16.136      0.000       0.395       0.504
6-10 years                       0.5140      0.037     14.071      0.000       0.442       0.586
================================================================================================
Business and Financial Operations Occupations 2020
df length: 125072
Optimization terminated successfully.
         Current function value: 0.130150
         Iterations 8

 18%|█▊        | 16/90 [00:11<01:05,  1.13it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:               125072
Model:                          Logit   Df Residuals:                   125060
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02130
Time:                        23:55:05   Log-Likelihood:                -16278.
converged:                       True   LL-Null:                       -16632.
Covariance Type:            nonrobust   LLR p-value:                7.659e-145
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.6768      0.035   -106.413      0.000      -3.745      -3.609
AI ROLE                         -0.0796      0.147     -0.543      0.587      -0.367       0.208
Associate degree                 0.3025      0.088      3.455      0.001       0.131       0.474
Bachelor's degree                0.1377      0.042      3.242      0.001       0.054       0.221
High school or GED               0.6474      0.051     12.820      0.000       0.548       0.746
Master's degree                 -0.1546      0.168     -0.920      0.358      -0.484       0.175
Ph.D. or professional degree     0.1220      0.322      0.379      0.705      -0.510       0.754
0 years                          1.3582      0.064     21.089      0.000       1.232       1.484
1-2 years                       -0.0661      0.049     -1.361      0.174      -0.161       0.029
11-20 years                      0.0293      0.172      0.170      0.865      -0.309       0.367
3-5 years                       -0.0823      0.044     -1.854      0.064      -0.169       0.005
6-10 years                      -0.3266      0.073     -4.485      0.000      -0.469      -0.184
================================================================================================
Business and Financial Operations Occupations 2018
df length: 139740
Optimization terminated successfully.
         Current function value: 0.095144
         Iterations 8

 19%|█▉        | 17/90 [00:12<01:05,  1.11it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:               139740
Model:                          Logit   Df Residuals:                   139728
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.004895
Time:                        23:55:06   Log-Likelihood:                -13295.
converged:                       True   LL-Null:                       -13361.
Covariance Type:            nonrobust   LLR p-value:                 1.202e-22
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.8919      0.038   -103.589      0.000      -3.966      -3.818
AI ROLE                         -0.2847      0.186     -1.534      0.125      -0.648       0.079
Associate degree                 0.0450      0.101      0.443      0.657      -0.154       0.244
Bachelor's degree               -0.0811      0.047     -1.716      0.086      -0.174       0.012
High school or GED              -0.0619      0.070     -0.888      0.374      -0.198       0.075
Master's degree                 -0.2957      0.182     -1.622      0.105      -0.653       0.062
Ph.D. or professional degree     0.6015      0.275      2.187      0.029       0.063       1.141
0 years                          0.8978      0.112      7.985      0.000       0.677       1.118
1-2 years                        0.2002      0.054      3.715      0.000       0.095       0.306
11-20 years                     -0.4459      0.247     -1.806      0.071      -0.930       0.038
3-5 years                       -0.0162      0.051     -0.317      0.751      -0.117       0.084
6-10 years                      -0.4024      0.084     -4.776      0.000      -0.568      -0.237
================================================================================================
Business and Financial Operations Occupations 2023
df length: 124651
Optimization terminated successfully.
         Current function value: 0.262121
         Iterations 7

 20%|██        | 18/90 [00:13<01:04,  1.12it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:               124651
Model:                          Logit   Df Residuals:                   124639
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01512
Time:                        23:55:07   Log-Likelihood:                -32674.
converged:                       True   LL-Null:                       -33175.
Covariance Type:            nonrobust   LLR p-value:                3.347e-208
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.1192      0.027   -116.958      0.000      -3.171      -3.067
AI ROLE                          0.1259      0.073      1.734      0.083      -0.016       0.268
Associate degree                 0.3525      0.058      6.041      0.000       0.238       0.467
Bachelor's degree                0.4884      0.030     16.064      0.000       0.429       0.548
High school or GED               0.7673      0.037     20.946      0.000       0.695       0.839
Master's degree                  0.4691      0.091      5.147      0.000       0.290       0.648
Ph.D. or professional degree     0.3042      0.177      1.723      0.085      -0.042       0.650
0 years                         -0.4023      0.104     -3.869      0.000      -0.606      -0.199
1-2 years                        0.1511      0.033      4.618      0.000       0.087       0.215
11-20 years                      0.1873      0.096      1.955      0.051      -0.001       0.375
3-5 years                        0.3817      0.029     13.161      0.000       0.325       0.438
6-10 years                       0.3913      0.038     10.295      0.000       0.317       0.466
================================================================================================
Community and Social Service Occupations 2019

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
 21%|██        | 19/90 [00:13<00:57,  1.23it/s]

df length: 30528
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.164052
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:                30528
Model:                          Logit   Df Residuals:                    30516
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.008297
Time:                        23:55:07   Log-Likelihood:                -5008.2
converged:                      False   LL-Null:                       -5050.1
Covariance Type:            nonrobust   LLR p-value:                 2.699e-13
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.6322      0.074    -48.824      0.000      -3.778      -3.486
AI ROLE                          0.4878      0.519      0.940      0.347      -0.530       1.505
Associate degree                 0.6041      0.138      4.366      0.000       0.333       0.875
Bachelor's degree                0.5770      0.093      6.182      0.000       0.394       0.760
High school or GED               0.7273      0.093      7.801      0.000       0.545       0.910
Master's degree                  0.3075      0.105      2.919      0.004       0.101       0.514
Ph.D. or professional degree     0.4004      0.369      1.086      0.277      -0.322       1.123
0 years                          0.2511      0.180      1.394      0.163      -0.102       0.604
1-2 years                       -0.0524      0.070     -0.750      0.453      -0.189       0.085
11-20 years                    -18.8460   9174.338     -0.002      0.998    -1.8e+04     1.8e+04
3-5 years                       -0.0432      0.088     -0.489      0.625      -0.216       0.130
6-10 years                       0.0447      0.224      0.200      0.842      -0.395       0.484
================================================================================================
Community and Social Service Occupations 2021

 22%|██▏       | 20/90 [00:14<00:52,  1.33it/s]

df length: 39363
Optimization terminated successfully.
         Current function value: 0.204087
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:                39363
Model:                          Logit   Df Residuals:                    39351
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02210
Time:                        23:55:08   Log-Likelihood:                -8033.5
converged:                       True   LL-Null:                       -8215.1
Covariance Type:            nonrobust   LLR p-value:                 3.918e-71
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.3834      0.058    -58.743      0.000      -3.496      -3.270
AI ROLE                          1.2216      0.324      3.773      0.000       0.587       1.856
Associate degree                 0.1189      0.115      1.036      0.300      -0.106       0.344
Bachelor's degree                0.5337      0.071      7.484      0.000       0.394       0.673
High school or GED               0.2749      0.075      3.678      0.000       0.128       0.421
Master's degree                  0.4839      0.076      6.376      0.000       0.335       0.633
Ph.D. or professional degree    -0.3578      0.270     -1.325      0.185      -0.887       0.171
0 years                          0.3884      0.144      2.701      0.007       0.107       0.670
1-2 years                        0.0336      0.057      0.591      0.554      -0.078       0.145
11-20 years                     -0.0941      0.723     -0.130      0.896      -1.512       1.324
3-5 years                        0.8132      0.059     13.834      0.000       0.698       0.928
6-10 years                       0.1445      0.202      0.714      0.475      -0.252       0.541
================================================================================================
Community and Social Service Occupations 2022

 23%|██▎       | 21/90 [00:15<00:49,  1.40it/s]

df length: 46564
Optimization terminated successfully.
         Current function value: 0.216230
         Iterations 9
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:                46564
Model:                          Logit   Df Residuals:                    46552
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01285
Time:                        23:55:09   Log-Likelihood:                -10069.
converged:                       True   LL-Null:                       -10200.
Covariance Type:            nonrobust   LLR p-value:                 8.009e-50
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.0068      0.044    -68.381      0.000      -3.093      -2.921
AI ROLE                         -0.3483      0.459     -0.758      0.448      -1.248       0.552
Associate degree                 0.0125      0.091      0.137      0.891      -0.167       0.192
Bachelor's degree                0.1286      0.059      2.196      0.028       0.014       0.243
High school or GED               0.1291      0.061      2.133      0.033       0.010       0.248
Master's degree                 -0.1344      0.067     -1.993      0.046      -0.267      -0.002
Ph.D. or professional degree    -1.7713      0.382     -4.635      0.000      -2.520      -1.022
0 years                         -0.5902      0.163     -3.613      0.000      -0.910      -0.270
1-2 years                        0.2035      0.049      4.173      0.000       0.108       0.299
11-20 years                     -0.6138      0.718     -0.855      0.393      -2.021       0.794
3-5 years                        0.6583      0.056     11.848      0.000       0.549       0.767
6-10 years                       0.5078      0.149      3.405      0.001       0.215       0.800
================================================================================================
Community and Social Service Occupations 2020

 24%|██▍       | 22/90 [00:15<00:45,  1.49it/s]

df length: 30962
Optimization terminated successfully.
         Current function value: 0.163813
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:                30962
Model:                          Logit   Df Residuals:                    30950
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.005382
Time:                        23:55:09   Log-Likelihood:                -5072.0
converged:                       True   LL-Null:                       -5099.4
Covariance Type:            nonrobust   LLR p-value:                 8.109e-08
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.5886      0.072    -49.995      0.000      -3.729      -3.448
AI ROLE                          0.1398      0.725      0.193      0.847      -1.282       1.561
Associate degree                 0.6292      0.132      4.775      0.000       0.371       0.888
Bachelor's degree                0.5049      0.092      5.490      0.000       0.325       0.685
High school or GED               0.3935      0.095      4.159      0.000       0.208       0.579
Master's degree                  0.4795      0.098      4.906      0.000       0.288       0.671
Ph.D. or professional degree     0.5315      0.294      1.809      0.070      -0.044       1.107
0 years                          0.4549      0.176      2.589      0.010       0.111       0.799
1-2 years                        0.0071      0.069      0.103      0.918      -0.128       0.142
11-20 years                      0.2679      0.728      0.368      0.713      -1.160       1.696
3-5 years                       -0.0098      0.090     -0.109      0.913      -0.185       0.166
6-10 years                      -0.5785      0.324     -1.783      0.075      -1.214       0.057
================================================================================================
Community and Social Service Occupations 2018

 26%|██▌       | 23/90 [00:16<00:42,  1.57it/s]

df length: 25206
Optimization terminated successfully.
         Current function value: 0.139887
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:                25206
Model:                          Logit   Df Residuals:                    25194
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.006974
Time:                        23:55:10   Log-Likelihood:                -3526.0
converged:                       True   LL-Null:                       -3550.8
Covariance Type:            nonrobust   LLR p-value:                 7.607e-07
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.7466      0.084    -44.444      0.000      -3.912      -3.581
AI ROLE                          1.6704      0.414      4.031      0.000       0.858       2.483
Associate degree                 0.5439      0.161      3.373      0.001       0.228       0.860
Bachelor's degree                0.4752      0.109      4.345      0.000       0.261       0.689
High school or GED               0.3422      0.119      2.872      0.004       0.109       0.576
Master's degree                  0.5580      0.115      4.867      0.000       0.333       0.783
Ph.D. or professional degree    -0.6816      0.720     -0.947      0.344      -2.092       0.729
0 years                          0.4532      0.231      1.962      0.050       0.000       0.906
1-2 years                       -0.0521      0.085     -0.614      0.540      -0.218       0.114
11-20 years                      0.2161      0.725      0.298      0.766      -1.205       1.638
3-5 years                       -0.2168      0.111     -1.945      0.052      -0.435       0.002
6-10 years                      -0.0259      0.291     -0.089      0.929      -0.596       0.545
================================================================================================
Community and Social Service Occupations 2023

 27%|██▋       | 24/90 [00:16<00:41,  1.59it/s]

df length: 43218
Optimization terminated successfully.
         Current function value: 0.232096
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:                43218
Model:                          Logit   Df Residuals:                    43206
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01119
Time:                        23:55:10   Log-Likelihood:                -10031.
converged:                       True   LL-Null:                       -10144.
Covariance Type:            nonrobust   LLR p-value:                 1.784e-42
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.1004      0.049    -63.874      0.000      -3.196      -3.005
AI ROLE                          0.1682      0.397      0.424      0.672      -0.609       0.946
Associate degree                 0.4756      0.088      5.434      0.000       0.304       0.647
Bachelor's degree                0.3362      0.062      5.395      0.000       0.214       0.458
High school or GED               0.3053      0.064      4.746      0.000       0.179       0.431
Master's degree                  0.2412      0.066      3.651      0.000       0.112       0.371
Ph.D. or professional degree    -0.7647      0.200     -3.817      0.000      -1.157      -0.372
0 years                         -0.2380      0.159     -1.494      0.135      -0.550       0.074
1-2 years                        0.2718      0.047      5.769      0.000       0.179       0.364
11-20 years                      0.5007      0.397      1.260      0.208      -0.278       1.280
3-5 years                        0.4485      0.058      7.730      0.000       0.335       0.562
6-10 years                       0.6263      0.142      4.413      0.000       0.348       0.905
================================================================================================
Computer and Mathematical Occupations 2019
df length: 187188
Optimization terminated successfully.
         Current function value: 0.091583
         Iterations 8

 28%|██▊       | 25/90 [00:17<00:48,  1.34it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:               187188
Model:                          Logit   Df Residuals:                   187176
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02553
Time:                        23:55:11   Log-Likelihood:                -17143.
converged:                       True   LL-Null:                       -17592.
Covariance Type:            nonrobust   LLR p-value:                1.423e-185
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.4638      0.037   -119.948      0.000      -4.537      -4.391
AI ROLE                          0.1650      0.064      2.596      0.009       0.040       0.290
Associate degree                 0.6546      0.088      7.409      0.000       0.481       0.828
Bachelor's degree                0.5438      0.043     12.741      0.000       0.460       0.627
High school or GED               1.6075      0.057     28.316      0.000       1.496       1.719
Master's degree                  0.4565      0.123      3.724      0.000       0.216       0.697
Ph.D. or professional degree     0.4937      0.264      1.870      0.061      -0.024       1.011
0 years                         -0.3951      0.145     -2.718      0.007      -0.680      -0.110
1-2 years                        0.3706      0.052      7.118      0.000       0.269       0.473
11-20 years                      0.1909      0.115      1.662      0.096      -0.034       0.416
3-5 years                        0.0390      0.045      0.863      0.388      -0.050       0.128
6-10 years                      -0.0628      0.055     -1.152      0.249      -0.170       0.044
================================================================================================
Computer and Mathematical Occupations 2021
df length: 175692
Optimization terminated successfully.
         Current function value: 0.143176
         Iterations 8

 29%|██▉       | 26/90 [00:18<00:52,  1.21it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:               175692
Model:                          Logit   Df Residuals:                   175680
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02090
Time:                        23:55:12   Log-Likelihood:                -25155.
converged:                       True   LL-Null:                       -25692.
Covariance Type:            nonrobust   LLR p-value:                2.081e-223
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.1666      0.034   -121.504      0.000      -4.234      -4.099
AI ROLE                          0.1087      0.044      2.462      0.014       0.022       0.195
Associate degree                 0.5499      0.070      7.912      0.000       0.414       0.686
Bachelor's degree                0.6867      0.035     19.572      0.000       0.618       0.756
High school or GED               0.8310      0.056     14.930      0.000       0.722       0.940
Master's degree                  0.5110      0.090      5.662      0.000       0.334       0.688
Ph.D. or professional degree     0.7511      0.187      4.025      0.000       0.385       1.117
0 years                         -0.5051      0.142     -3.556      0.000      -0.784      -0.227
1-2 years                        0.6829      0.044     15.683      0.000       0.598       0.768
11-20 years                      0.1968      0.094      2.086      0.037       0.012       0.382
3-5 years                        0.3980      0.038     10.604      0.000       0.324       0.472
6-10 years                       0.3328      0.043      7.752      0.000       0.249       0.417
================================================================================================
Computer and Mathematical Occupations 2022
df length: 203321
Optimization terminated successfully.
         Current function value: 0.176291
         Iterations 8

 30%|███       | 27/90 [00:19<00:56,  1.11it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:               203321
Model:                          Logit   Df Residuals:                   203309
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02175
Time:                        23:55:13   Log-Likelihood:                -35844.
converged:                       True   LL-Null:                       -36641.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.9462      0.029   -136.092      0.000      -4.003      -3.889
AI ROLE                          0.0634      0.035      1.801      0.072      -0.006       0.132
Associate degree                 0.4117      0.059      6.953      0.000       0.296       0.528
Bachelor's degree                0.6414      0.029     22.377      0.000       0.585       0.698
High school or GED               0.4123      0.051      8.153      0.000       0.313       0.511
Master's degree                  0.3845      0.076      5.082      0.000       0.236       0.533
Ph.D. or professional degree     0.5301      0.166      3.186      0.001       0.204       0.856
0 years                          0.0172      0.118      0.146      0.884      -0.214       0.248
1-2 years                        0.6199      0.039     16.073      0.000       0.544       0.695
11-20 years                      0.1805      0.079      2.285      0.022       0.026       0.335
3-5 years                        0.6278      0.032     19.842      0.000       0.566       0.690
6-10 years                       0.5297      0.035     14.938      0.000       0.460       0.599
================================================================================================
Computer and Mathematical Occupations 2020
df length: 157708
Optimization terminated successfully.
         Current function value: 0.098691
         Iterations 8

 31%|███       | 28/90 [00:20<00:56,  1.09it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:               157708
Model:                          Logit   Df Residuals:                   157696
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02316
Time:                        23:55:14   Log-Likelihood:                -15564.
converged:                       True   LL-Null:                       -15933.
Covariance Type:            nonrobust   LLR p-value:                4.020e-151
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.4442      0.040   -111.209      0.000      -4.523      -4.366
AI ROLE                          0.0220      0.066      0.334      0.738      -0.107       0.151
Associate degree                 0.5105      0.098      5.186      0.000       0.318       0.703
Bachelor's degree                0.6258      0.045     13.954      0.000       0.538       0.714
High school or GED               1.4505      0.062     23.476      0.000       1.329       1.572
Master's degree                  0.6967      0.111      6.280      0.000       0.479       0.914
Ph.D. or professional degree     0.3834      0.294      1.303      0.193      -0.193       0.960
0 years                         -0.5545      0.181     -3.064      0.002      -0.909      -0.200
1-2 years                        0.4111      0.056      7.316      0.000       0.301       0.521
11-20 years                      0.5512      0.101      5.438      0.000       0.352       0.750
3-5 years                        0.0993      0.048      2.071      0.038       0.005       0.193
6-10 years                       0.0852      0.055      1.549      0.121      -0.023       0.193
================================================================================================
Computer and Mathematical Occupations 2018
df length: 178714
Optimization terminated successfully.
         Current function value: 0.065620
         Iterations 9

 32%|███▏      | 29/90 [00:21<00:57,  1.06it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:               178714
Model:                          Logit   Df Residuals:                   178702
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.006096
Time:                        23:55:15   Log-Likelihood:                -11727.
converged:                       True   LL-Null:                       -11799.
Covariance Type:            nonrobust   LLR p-value:                 2.674e-25
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.6425      0.043   -108.804      0.000      -4.726      -4.559
AI ROLE                          0.2812      0.079      3.540      0.000       0.126       0.437
Associate degree                 0.4978      0.102      4.859      0.000       0.297       0.699
Bachelor's degree                0.1743      0.050      3.476      0.001       0.076       0.273
High school or GED               0.1007      0.105      0.962      0.336      -0.104       0.306
Master's degree                  0.2579      0.141      1.833      0.067      -0.018       0.534
Ph.D. or professional degree    -0.1328      0.383     -0.346      0.729      -0.884       0.618
0 years                          0.0990      0.219      0.452      0.651      -0.331       0.529
1-2 years                        0.4748      0.067      7.039      0.000       0.343       0.607
11-20 years                     -0.6351      0.234     -2.711      0.007      -1.094      -0.176
3-5 years                        0.2040      0.056      3.663      0.000       0.095       0.313
6-10 years                      -0.0924      0.071     -1.302      0.193      -0.231       0.047
================================================================================================
Computer and Mathematical Occupations 2023
df length: 127390
Optimization terminated successfully.
         Current function value: 0.219355
         Iterations 7

 33%|███▎      | 30/90 [00:22<00:55,  1.09it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:               127390
Model:                          Logit   Df Residuals:                   127378
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01907
Time:                        23:55:16   Log-Likelihood:                -27944.
converged:                       True   LL-Null:                       -28487.
Covariance Type:            nonrobust   LLR p-value:                4.334e-226
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.5452      0.031   -113.544      0.000      -3.606      -3.484
AI ROLE                          0.2199      0.038      5.752      0.000       0.145       0.295
Associate degree                 0.4957      0.059      8.380      0.000       0.380       0.612
Bachelor's degree                0.5433      0.031     17.280      0.000       0.482       0.605
High school or GED               0.5276      0.051     10.407      0.000       0.428       0.627
Master's degree                  0.3690      0.084      4.410      0.000       0.205       0.533
Ph.D. or professional degree     0.4489      0.180      2.497      0.013       0.096       0.801
0 years                         -0.1685      0.143     -1.179      0.238      -0.449       0.112
1-2 years                        0.4868      0.043     11.278      0.000       0.402       0.571
11-20 years                      0.0562      0.082      0.686      0.493      -0.104       0.217
3-5 years                        0.6059      0.034     17.668      0.000       0.539       0.673
6-10 years                       0.3834      0.039      9.951      0.000       0.308       0.459
================================================================================================
Educational Instruction and Library Occupations 2019

 34%|███▍      | 31/90 [00:23<00:49,  1.20it/s]

df length: 45660
Optimization terminated successfully.
         Current function value: 0.137143
         Iterations 9
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:                45660
Model:                          Logit   Df Residuals:                    45648
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.07963
Time:                        23:55:17   Log-Likelihood:                -6262.0
converged:                       True   LL-Null:                       -6803.8
Covariance Type:            nonrobust   LLR p-value:                1.899e-225
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.2952      0.042    -78.821      0.000      -3.377      -3.213
AI ROLE                         -0.5602      0.513     -1.093      0.275      -1.565       0.445
Associate degree                -1.4500      0.132    -11.008      0.000      -1.708      -1.192
Bachelor's degree               -0.7099      0.064    -11.094      0.000      -0.835      -0.585
High school or GED              -1.1310      0.091    -12.489      0.000      -1.309      -0.954
Master's degree                 -0.8584      0.114     -7.549      0.000      -1.081      -0.636
Ph.D. or professional degree    -1.4556      0.248     -5.873      0.000      -1.941      -0.970
0 years                         -0.2826      0.273     -1.036      0.300      -0.817       0.252
1-2 years                        1.7500      0.058     30.280      0.000       1.637       1.863
11-20 years                     -0.2204      1.010     -0.218      0.827      -2.200       1.760
3-5 years                       -0.1779      0.139     -1.279      0.201      -0.451       0.095
6-10 years                       0.9448      0.202      4.673      0.000       0.549       1.341
================================================================================================
Educational Instruction and Library Occupations 2021

 36%|███▌      | 32/90 [00:23<00:44,  1.29it/s]

df length: 54703
Optimization terminated successfully.
         Current function value: 0.148144
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:                54703
Model:                          Logit   Df Residuals:                    54691
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01819
Time:                        23:55:17   Log-Likelihood:                -8103.9
converged:                       True   LL-Null:                       -8254.1
Covariance Type:            nonrobust   LLR p-value:                 7.720e-58
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.0317      0.035    -86.427      0.000      -3.100      -2.963
AI ROLE                          0.4478      0.288      1.555      0.120      -0.117       1.012
Associate degree                -0.9431      0.109     -8.650      0.000      -1.157      -0.729
Bachelor's degree               -0.4280      0.059     -7.295      0.000      -0.543      -0.313
High school or GED              -0.7681      0.069    -11.093      0.000      -0.904      -0.632
Master's degree                 -1.1115      0.132     -8.419      0.000      -1.370      -0.853
Ph.D. or professional degree    -1.4529      0.247     -5.879      0.000      -1.937      -0.969
0 years                         -0.4106      0.205     -2.007      0.045      -0.811      -0.010
1-2 years                        0.5630      0.064      8.824      0.000       0.438       0.688
11-20 years                      0.4780      0.461      1.037      0.300      -0.426       1.382
3-5 years                        0.2328      0.089      2.609      0.009       0.058       0.408
6-10 years                       0.2246      0.207      1.087      0.277      -0.181       0.630
================================================================================================
Educational Instruction and Library Occupations 2022

 37%|███▋      | 33/90 [00:24<00:42,  1.35it/s]

df length: 62895
Optimization terminated successfully.
         Current function value: 0.144403
         Iterations 9
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:                62895
Model:                          Logit   Df Residuals:                    62883
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02069
Time:                        23:55:18   Log-Likelihood:                -9082.3
converged:                       True   LL-Null:                       -9274.1
Covariance Type:            nonrobust   LLR p-value:                 1.719e-75
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.5147      0.043    -82.323      0.000      -3.598      -3.431
AI ROLE                         -0.7453      0.414     -1.802      0.072      -1.556       0.065
Associate degree                -0.1048      0.098     -1.066      0.286      -0.297       0.088
Bachelor's degree                0.4874      0.056      8.751      0.000       0.378       0.597
High school or GED               0.0103      0.068      0.152      0.879      -0.122       0.143
Master's degree                 -0.4798      0.113     -4.255      0.000      -0.701      -0.259
Ph.D. or professional degree    -0.7582      0.195     -3.886      0.000      -1.141      -0.376
0 years                         -1.2737      0.162     -7.884      0.000      -1.590      -0.957
1-2 years                        0.4205      0.055      7.609      0.000       0.312       0.529
11-20 years                     -1.6783      1.004     -1.671      0.095      -3.647       0.290
3-5 years                        0.0477      0.081      0.585      0.558      -0.112       0.207
6-10 years                       0.4590      0.159      2.894      0.004       0.148       0.770
================================================================================================
Educational Instruction and Library Occupations 2020

 38%|███▊      | 34/90 [00:25<00:39,  1.42it/s]

df length: 42631
Optimization terminated successfully.
         Current function value: 0.147837
         Iterations 9
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:                42631
Model:                          Logit   Df Residuals:                    42619
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.06723
Time:                        23:55:19   Log-Likelihood:                -6302.4
converged:                       True   LL-Null:                       -6756.7
Covariance Type:            nonrobust   LLR p-value:                9.007e-188
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.8521      0.036    -79.556      0.000      -2.922      -2.782
AI ROLE                         -1.0163      0.718     -1.416      0.157      -2.423       0.390
Associate degree                -1.6258      0.134    -12.146      0.000      -1.888      -1.363
Bachelor's degree               -1.0267      0.068    -15.164      0.000      -1.159      -0.894
High school or GED              -1.4635      0.094    -15.503      0.000      -1.648      -1.278
Master's degree                 -1.0996      0.126     -8.746      0.000      -1.346      -0.853
Ph.D. or professional degree    -1.8312      0.281     -6.508      0.000      -2.383      -1.280
0 years                         -0.2441      0.284     -0.861      0.389      -0.800       0.312
1-2 years                        1.3037      0.061     21.202      0.000       1.183       1.424
11-20 years                      0.4262      0.597      0.714      0.475      -0.744       1.596
3-5 years                       -0.9547      0.179     -5.326      0.000      -1.306      -0.603
6-10 years                       0.5027      0.233      2.160      0.031       0.046       0.959
================================================================================================
Educational Instruction and Library Occupations 2018

 39%|███▉      | 35/90 [00:25<00:37,  1.49it/s]

df length: 41745
Optimization terminated successfully.
         Current function value: 0.132155
         Iterations 9
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:                41745
Model:                          Logit   Df Residuals:                    41733
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.06589
Time:                        23:55:19   Log-Likelihood:                -5516.8
converged:                       True   LL-Null:                       -5905.9
Covariance Type:            nonrobust   LLR p-value:                8.863e-160
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.4907      0.045    -77.338      0.000      -3.579      -3.402
AI ROLE                         -0.9496      0.719     -1.321      0.187      -2.359       0.460
Associate degree                -1.2502      0.157     -7.945      0.000      -1.559      -0.942
Bachelor's degree               -0.5497      0.073     -7.482      0.000      -0.694      -0.406
High school or GED              -0.1087      0.078     -1.397      0.162      -0.261       0.044
Master's degree                 -0.8536      0.135     -6.340      0.000      -1.117      -0.590
Ph.D. or professional degree    -1.0812      0.242     -4.470      0.000      -1.555      -0.607
0 years                         -0.2677      0.339     -0.789      0.430      -0.933       0.397
1-2 years                        1.6246      0.063     25.918      0.000       1.502       1.747
11-20 years                      0.0983      1.013      0.097      0.923      -1.888       2.084
3-5 years                       -0.5114      0.171     -2.982      0.003      -0.847      -0.175
6-10 years                       0.3958      0.258      1.536      0.125      -0.109       0.901
================================================================================================
Educational Instruction and Library Occupations 2023

 40%|████      | 36/90 [00:26<00:35,  1.50it/s]

df length: 56729
Optimization terminated successfully.
         Current function value: 0.184968
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:                56729
Model:                          Logit   Df Residuals:                    56717
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01067
Time:                        23:55:20   Log-Likelihood:                -10493.
converged:                       True   LL-Null:                       -10606.
Covariance Type:            nonrobust   LLR p-value:                 2.360e-42
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.8915      0.033    -88.360      0.000      -2.956      -2.827
AI ROLE                         -0.0256      0.243     -0.105      0.916      -0.502       0.451
Associate degree                -0.5838      0.094     -6.185      0.000      -0.769      -0.399
Bachelor's degree               -0.0487      0.049     -0.987      0.324      -0.145       0.048
High school or GED              -0.2281      0.058     -3.907      0.000      -0.342      -0.114
Master's degree                 -0.7962      0.099     -8.021      0.000      -0.991      -0.602
Ph.D. or professional degree    -1.0200      0.163     -6.244      0.000      -1.340      -0.700
0 years                         -1.0812      0.175     -6.181      0.000      -1.424      -0.738
1-2 years                        0.2479      0.055      4.472      0.000       0.139       0.357
11-20 years                      0.0817      0.344      0.238      0.812      -0.592       0.755
3-5 years                        0.1182      0.074      1.591      0.112      -0.027       0.264
6-10 years                       0.3802      0.154      2.471      0.013       0.079       0.682
================================================================================================
Healthcare Practitioners and Technical Occupations 2019
df length: 177733
Optimization terminated successfully.
         Current function value: 0.111076
         Iterations 8

 41%|████      | 37/90 [00:27<00:40,  1.31it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:               177733
Model:                          Logit   Df Residuals:                   177721
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.006195
Time:                        23:55:21   Log-Likelihood:                -19742.
converged:                       True   LL-Null:                       -19865.
Covariance Type:            nonrobust   LLR p-value:                 1.808e-46
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.8069      0.025   -154.600      0.000      -3.855      -3.759
AI ROLE                          0.1044      0.455      0.229      0.819      -0.788       0.997
Associate degree                 0.4989      0.043     11.519      0.000       0.414       0.584
Bachelor's degree                0.0143      0.051      0.279      0.780      -0.086       0.115
High school or GED              -0.0257      0.052     -0.492      0.623      -0.128       0.077
Master's degree                  0.7098      0.067     10.670      0.000       0.579       0.840
Ph.D. or professional degree     0.1151      0.105      1.093      0.274      -0.091       0.321
0 years                         -0.0704      0.111     -0.635      0.525      -0.288       0.147
1-2 years                       -0.0395      0.035     -1.126      0.260      -0.108       0.029
11-20 years                      0.2295      0.456      0.503      0.615      -0.665       1.124
3-5 years                       -0.2584      0.064     -4.010      0.000      -0.385      -0.132
6-10 years                       0.7198      0.155      4.634      0.000       0.415       1.024
================================================================================================
Healthcare Practitioners and Technical Occupations 2021
df length: 235145
Optimization terminated successfully.
         Current function value: 0.155455
         Iterations 9

 42%|████▏     | 38/90 [00:28<00:45,  1.14it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:               235145
Model:                          Logit   Df Residuals:                   235133
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.004418
Time:                        23:55:22   Log-Likelihood:                -36554.
converged:                       True   LL-Null:                       -36717.
Covariance Type:            nonrobust   LLR p-value:                 6.267e-63
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.3064      0.018   -184.754      0.000      -3.341      -3.271
AI ROLE                          0.0624      0.296      0.211      0.833      -0.518       0.643
Associate degree                 0.1989      0.030      6.604      0.000       0.140       0.258
Bachelor's degree                0.0191      0.035      0.544      0.586      -0.050       0.088
High school or GED              -0.3193      0.038     -8.382      0.000      -0.394      -0.245
Master's degree                  0.2634      0.052      5.065      0.000       0.161       0.365
Ph.D. or professional degree     0.2902      0.065      4.434      0.000       0.162       0.418
0 years                         -0.0640      0.080     -0.801      0.423      -0.221       0.093
1-2 years                       -0.0647      0.025     -2.614      0.009      -0.113      -0.016
11-20 years                     -1.3239      0.711     -1.862      0.063      -2.717       0.069
3-5 years                        0.3600      0.038      9.434      0.000       0.285       0.435
6-10 years                       0.3237      0.140      2.315      0.021       0.050       0.598
================================================================================================
Healthcare Practitioners and Technical Occupations 2022
df length: 293272
Optimization terminated successfully.
         Current function value: 0.170837
         Iterations 7

 43%|████▎     | 39/90 [00:29<00:50,  1.02it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:               293272
Model:                          Logit   Df Residuals:                   293260
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.003331
Time:                        23:55:23   Log-Likelihood:                -50102.
converged:                       True   LL-Null:                       -50269.
Covariance Type:            nonrobust   LLR p-value:                 3.710e-65
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.2230      0.015   -214.804      0.000      -3.252      -3.194
AI ROLE                         -0.0869      0.309     -0.281      0.778      -0.693       0.519
Associate degree                 0.0736      0.026      2.810      0.005       0.022       0.125
Bachelor's degree                0.1349      0.029      4.697      0.000       0.079       0.191
High school or GED              -0.1379      0.032     -4.339      0.000      -0.200      -0.076
Master's degree                  0.1991      0.049      4.054      0.000       0.103       0.295
Ph.D. or professional degree     0.2798      0.056      5.022      0.000       0.171       0.389
0 years                         -0.2363      0.070     -3.373      0.001      -0.374      -0.099
1-2 years                        0.0244      0.021      1.179      0.238      -0.016       0.065
11-20 years                      0.2959      0.297      0.997      0.319      -0.286       0.878
3-5 years                        0.4463      0.032     13.748      0.000       0.383       0.510
6-10 years                       0.3052      0.114      2.670      0.008       0.081       0.529
================================================================================================
Healthcare Practitioners and Technical Occupations 2020
df length: 208848

 44%|████▍     | 40/90 [00:30<00:50,  1.01s/it]

Optimization terminated successfully.
         Current function value: 0.126219
         Iterations 9
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:               208848
Model:                          Logit   Df Residuals:                   208836
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.007162
Time:                        23:55:24   Log-Likelihood:                -26360.
converged:                       True   LL-Null:                       -26551.
Covariance Type:            nonrobust   LLR p-value:                 9.130e-75
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.6277      0.021   -171.561      0.000      -3.669      -3.586
AI ROLE                         -0.9635      0.712     -1.354      0.176      -2.358       0.431
Associate degree                 0.4206      0.038     11.022      0.000       0.346       0.495
Bachelor's degree               -0.1728      0.051     -3.364      0.001      -0.273      -0.072
High school or GED               0.3931      0.039      9.980      0.000       0.316       0.470
Master's degree                  0.6964      0.061     11.418      0.000       0.577       0.816
Ph.D. or professional degree     0.5133      0.071      7.181      0.000       0.373       0.653
0 years                          0.1260      0.086      1.469      0.142      -0.042       0.294
1-2 years                       -0.1756      0.030     -5.934      0.000      -0.234      -0.118
11-20 years                     -0.5459      0.505     -1.082      0.279      -1.535       0.443
3-5 years                       -0.1447      0.057     -2.520      0.012      -0.257      -0.032
6-10 years                      -0.0036      0.190     -0.019      0.985      -0.377       0.369
================================================================================================
Healthcare Practitioners and Technical Occupations 2018
df length: 178552

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
 46%|████▌     | 41/90 [00:32<00:53,  1.10s/it]

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.093195
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:               178552
Model:                          Logit   Df Residuals:                   178540
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.009725
Time:                        23:55:26   Log-Likelihood:                -16640.
converged:                      False   LL-Null:                       -16804.
Covariance Type:            nonrobust   LLR p-value:                 1.919e-63
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.9676      0.027   -146.326      0.000      -4.021      -3.914
AI ROLE                         -0.1892      0.583     -0.325      0.745      -1.331       0.953
Associate degree                 0.6899      0.046     14.941      0.000       0.599       0.780
Bachelor's degree                0.2067      0.056      3.707      0.000       0.097       0.316
High school or GED              -0.0271      0.061     -0.444      0.657      -0.147       0.093
Master's degree                  0.6834      0.079      8.607      0.000       0.528       0.839
Ph.D. or professional degree    -0.1018      0.118     -0.865      0.387      -0.332       0.129
0 years                         -0.4495      0.141     -3.197      0.001      -0.725      -0.174
1-2 years                       -0.3372      0.040     -8.449      0.000      -0.415      -0.259
11-20 years                    -12.6241    409.003     -0.031      0.975    -814.255     789.007
3-5 years                       -0.3318      0.069     -4.811      0.000      -0.467      -0.197
6-10 years                      -0.4333      0.262     -1.654      0.098      -0.947       0.080
================================================================================================
Healthcare Practitioners and Technical Occupations 2023
df length: 286144
Optimization terminated successfully.
         Current function value: 0.181961
         Iterations 7

 47%|████▋     | 42/90 [00:33<00:54,  1.13s/it]

                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:               286144
Model:                          Logit   Df Residuals:                   286132
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.003772
Time:                        23:55:27   Log-Likelihood:                -52067.
converged:                       True   LL-Null:                       -52264.
Covariance Type:            nonrobust   LLR p-value:                 9.908e-78
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.2120      0.015   -217.611      0.000      -3.241      -3.183
AI ROLE                          0.1733      0.286      0.606      0.544      -0.387       0.734
Associate degree                 0.2304      0.025      9.314      0.000       0.182       0.279
Bachelor's degree                0.2374      0.028      8.501      0.000       0.183       0.292
High school or GED              -0.0297      0.031     -0.972      0.331      -0.089       0.030
Master's degree                  0.1066      0.051      2.076      0.038       0.006       0.207
Ph.D. or professional degree    -0.0875      0.065     -1.339      0.180      -0.216       0.041
0 years                          0.5980      0.045     13.370      0.000       0.510       0.686
1-2 years                        0.1281      0.020      6.403      0.000       0.089       0.167
11-20 years                      0.5522      0.217      2.550      0.011       0.128       0.977
3-5 years                        0.1970      0.035      5.589      0.000       0.128       0.266
6-10 years                       0.2161      0.109      1.987      0.047       0.003       0.429
================================================================================================
Legal Occupations 2019

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/discrete/discrete_model.py:2385: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/discrete/discrete_model.py:2443: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q * linpred)))
 48%|████▊     | 43/90 [00:33<00:44,  1.05it/s]

df length: 10618
Warning: Maximum number of iterations has been exceeded.
         Current function value: inf
         Iterations: 35
Singular matrix
Legal Occupations 2021

 49%|████▉     | 44/90 [00:34<00:37,  1.23it/s]

df length: 13410
Optimization terminated successfully.
         Current function value: 0.136948
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:                13410
Model:                          Logit   Df Residuals:                    13398
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01508
Time:                        23:55:28   Log-Likelihood:                -1836.5
converged:                       True   LL-Null:                       -1864.6
Covariance Type:            nonrobust   LLR p-value:                 4.584e-08
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.7902      0.098    -38.607      0.000      -3.983      -3.598
AI ROLE                         -0.2636      0.592     -0.445      0.656      -1.423       0.896
Associate degree                 0.0987      0.246      0.401      0.689      -0.384       0.581
Bachelor's degree                0.4664      0.147      3.172      0.002       0.178       0.755
High school or GED               0.2971      0.151      1.965      0.049       0.001       0.594
Master's degree                  0.5838      0.465      1.256      0.209      -0.328       1.495
Ph.D. or professional degree     0.8293      0.137      6.061      0.000       0.561       1.097
0 years                          0.4005      0.351      1.139      0.255      -0.288       1.089
1-2 years                        0.2701      0.132      2.044      0.041       0.011       0.529
11-20 years                      0.4770      0.474      1.005      0.315      -0.453       1.407
3-5 years                       -0.0664      0.131     -0.508      0.611      -0.322       0.190
6-10 years                       0.3146      0.182      1.731      0.083      -0.042       0.671
================================================================================================
Legal Occupations 2022

 50%|█████     | 45/90 [00:34<00:32,  1.37it/s]

df length: 14411
Optimization terminated successfully.
         Current function value: 0.169309
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:                14411
Model:                          Logit   Df Residuals:                    14399
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01823
Time:                        23:55:28   Log-Likelihood:                -2439.9
converged:                       True   LL-Null:                       -2485.2
Covariance Type:            nonrobust   LLR p-value:                 1.274e-14
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.4316      0.079    -43.252      0.000      -3.587      -3.276
AI ROLE                          0.4802      0.383      1.254      0.210      -0.270       1.231
Associate degree                 0.0943      0.215      0.439      0.661      -0.327       0.515
Bachelor's degree                0.2682      0.129      2.084      0.037       0.016       0.521
High school or GED               0.4420      0.132      3.349      0.001       0.183       0.701
Master's degree                  0.0082      0.422      0.019      0.985      -0.820       0.836
Ph.D. or professional degree     0.8776      0.112      7.857      0.000       0.659       1.096
0 years                         -0.0352      0.331     -0.107      0.915      -0.684       0.613
1-2 years                        0.1155      0.113      1.025      0.305      -0.105       0.337
11-20 years                      1.2325      0.276      4.462      0.000       0.691       1.774
3-5 years                       -0.0549      0.107     -0.512      0.609      -0.265       0.155
6-10 years                      -0.2027      0.177     -1.145      0.252      -0.550       0.144
================================================================================================
Legal Occupations 2020

 51%|█████     | 46/90 [00:35<00:29,  1.51it/s]

df length: 10122
Optimization terminated successfully.
         Current function value: 0.106216
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:                10122
Model:                          Logit   Df Residuals:                    10110
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02399
Time:                        23:55:29   Log-Likelihood:                -1075.1
converged:                       True   LL-Null:                       -1101.5
Covariance Type:            nonrobust   LLR p-value:                 1.917e-07
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.9183      0.117    -33.495      0.000      -4.148      -3.689
AI ROLE                          0.9765      0.617      1.582      0.114      -0.233       2.186
Associate degree                 0.2145      0.321      0.667      0.504      -0.415       0.844
Bachelor's degree                0.1238      0.227      0.545      0.586      -0.322       0.569
High school or GED               0.7766      0.193      4.015      0.000       0.397       1.156
Master's degree                  1.4704      0.352      4.180      0.000       0.781       2.160
Ph.D. or professional degree     0.8258      0.192      4.305      0.000       0.450       1.202
0 years                          0.6555      0.434      1.511      0.131      -0.195       1.506
1-2 years                       -0.1073      0.177     -0.607      0.544      -0.454       0.239
11-20 years                      0.8373      0.488      1.715      0.086      -0.120       1.794
3-5 years                       -0.3757      0.172     -2.181      0.029      -0.713      -0.038
6-10 years                      -0.6192      0.328     -1.886      0.059      -1.263       0.024
================================================================================================
Legal Occupations 2018

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
 52%|█████▏    | 47/90 [00:36<00:26,  1.62it/s]

df length: 9145
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.100789
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:                 9145
Model:                          Logit   Df Residuals:                     9133
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.03456
Time:                        23:55:30   Log-Likelihood:                -921.72
converged:                      False   LL-Null:                       -954.71
Covariance Type:            nonrobust   LLR p-value:                 7.008e-10
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.3984      0.152    -28.924      0.000      -4.696      -4.100
AI ROLE                        -18.7900   9972.439     -0.002      0.998   -1.96e+04    1.95e+04
Associate degree                -0.4429      0.464     -0.954      0.340      -1.352       0.467
Bachelor's degree               -0.1943      0.230     -0.844      0.398      -0.645       0.257
High school or GED               0.6135      0.210      2.915      0.004       0.201       1.026
Master's degree                  1.0383      0.437      2.375      0.018       0.182       1.895
Ph.D. or professional degree     0.6295      0.200      3.154      0.002       0.238       1.021
0 years                          1.1255      0.533      2.110      0.035       0.080       2.171
1-2 years                        1.0240      0.188      5.456      0.000       0.656       1.392
11-20 years                   -176.1625   2.07e+38  -8.49e-37      1.000   -4.07e+38    4.07e+38
3-5 years                        0.3836      0.198      1.938      0.053      -0.004       0.772
6-10 years                       0.3778      0.303      1.246      0.213      -0.217       0.972
================================================================================================
Legal Occupations 2023

 53%|█████▎    | 48/90 [00:36<00:24,  1.73it/s]

df length: 11385
Optimization terminated successfully.
         Current function value: 0.190490
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:                11385
Model:                          Logit   Df Residuals:                    11373
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02219
Time:                        23:55:30   Log-Likelihood:                -2168.7
converged:                       True   LL-Null:                       -2217.9
Covariance Type:            nonrobust   LLR p-value:                 3.653e-16
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.4594      0.090    -38.603      0.000      -3.635      -3.284
AI ROLE                          1.1633      0.300      3.873      0.000       0.575       1.752
Associate degree                 0.1880      0.210      0.896      0.370      -0.223       0.599
Bachelor's degree                0.2202      0.141      1.566      0.117      -0.055       0.496
High school or GED               0.8371      0.129      6.480      0.000       0.584       1.090
Master's degree                 -0.2961      0.514     -0.576      0.564      -1.303       0.711
Ph.D. or professional degree     0.5952      0.116      5.151      0.000       0.369       0.822
0 years                          0.6001      0.281      2.139      0.032       0.050       1.150
1-2 years                        0.2403      0.121      1.985      0.047       0.003       0.478
11-20 years                      1.1256      0.370      3.044      0.002       0.401       1.850
3-5 years                        0.2229      0.114      1.963      0.050       0.000       0.445
6-10 years                       0.5762      0.161      3.585      0.000       0.261       0.891
================================================================================================
Life, Physical, and Social Science Occupations 2019

 54%|█████▍    | 49/90 [00:37<00:23,  1.75it/s]

df length: 19301
Optimization terminated successfully.
         Current function value: 0.158923
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:                19301
Model:                          Logit   Df Residuals:                    19289
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01877
Time:                        23:55:31   Log-Likelihood:                -3067.4
converged:                       True   LL-Null:                       -3126.1
Covariance Type:            nonrobust   LLR p-value:                 6.086e-20
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.3047      0.079    -41.847      0.000      -3.459      -3.150
AI ROLE                          0.1340      0.300      0.447      0.655      -0.454       0.722
Associate degree                 0.0554      0.210      0.264      0.792      -0.356       0.466
Bachelor's degree                0.1429      0.108      1.324      0.185      -0.069       0.355
High school or GED               0.7993      0.110      7.269      0.000       0.584       1.015
Master's degree                  0.4540      0.146      3.115      0.002       0.168       0.740
Ph.D. or professional degree    -0.4402      0.193     -2.276      0.023      -0.819      -0.061
0 years                          0.4707      0.184      2.559      0.011       0.110       0.831
1-2 years                       -0.1825      0.100     -1.822      0.068      -0.379       0.014
11-20 years                      0.0124      0.368      0.034      0.973      -0.709       0.734
3-5 years                       -0.4291      0.111     -3.858      0.000      -0.647      -0.211
6-10 years                      -0.5911      0.184     -3.215      0.001      -0.951      -0.231
================================================================================================
Life, Physical, and Social Science Occupations 2021

 56%|█████▌    | 50/90 [00:37<00:22,  1.76it/s]

df length: 25175
Optimization terminated successfully.
         Current function value: 0.177148
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:                25175
Model:                          Logit   Df Residuals:                    25163
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.009786
Time:                        23:55:31   Log-Likelihood:                -4459.7
converged:                       True   LL-Null:                       -4503.8
Covariance Type:            nonrobust   LLR p-value:                 3.837e-14
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.3861      0.069    -48.914      0.000      -3.522      -3.250
AI ROLE                          0.5165      0.173      2.992      0.003       0.178       0.855
Associate degree                -0.0608      0.173     -0.351      0.726      -0.400       0.279
Bachelor's degree                0.3169      0.090      3.538      0.000       0.141       0.492
High school or GED               0.1862      0.110      1.699      0.089      -0.029       0.401
Master's degree                  0.3828      0.123      3.100      0.002       0.141       0.625
Ph.D. or professional degree     0.2723      0.124      2.195      0.028       0.029       0.515
0 years                          0.6285      0.150      4.185      0.000       0.334       0.923
1-2 years                       -0.1807      0.091     -1.982      0.047      -0.359      -0.002
11-20 years                      0.6384      0.231      2.759      0.006       0.185       1.092
3-5 years                        0.2850      0.083      3.451      0.001       0.123       0.447
6-10 years                       0.1366      0.125      1.091      0.275      -0.109       0.382
================================================================================================
Life, Physical, and Social Science Occupations 2022

 57%|█████▋    | 51/90 [00:38<00:22,  1.75it/s]

df length: 30329
Optimization terminated successfully.
         Current function value: 0.221603
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:                30329
Model:                          Logit   Df Residuals:                    30317
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.001665
Time:                        23:55:32   Log-Likelihood:                -6721.0
converged:                       True   LL-Null:                       -6732.2
Covariance Type:            nonrobust   LLR p-value:                   0.02137
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.8783      0.052    -55.180      0.000      -2.981      -2.776
AI ROLE                          0.2353      0.148      1.589      0.112      -0.055       0.525
Associate degree                -0.0922      0.126     -0.729      0.466      -0.340       0.156
Bachelor's degree                0.1019      0.069      1.487      0.137      -0.032       0.236
High school or GED               0.1741      0.082      2.122      0.034       0.013       0.335
Master's degree                 -0.0619      0.107     -0.576      0.565      -0.272       0.149
Ph.D. or professional degree    -0.0558      0.102     -0.547      0.584      -0.256       0.144
0 years                         -0.0866      0.147     -0.589      0.556      -0.375       0.202
1-2 years                        0.0276      0.067      0.409      0.683      -0.105       0.160
11-20 years                      0.3711      0.203      1.829      0.067      -0.027       0.769
3-5 years                        0.0599      0.068      0.884      0.377      -0.073       0.193
6-10 years                       0.1775      0.097      1.832      0.067      -0.012       0.367
================================================================================================
Life, Physical, and Social Science Occupations 2020

 58%|█████▊    | 52/90 [00:38<00:21,  1.77it/s]

df length: 20260
Optimization terminated successfully.
         Current function value: 0.144567
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:                20260
Model:                          Logit   Df Residuals:                    20248
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02043
Time:                        23:55:32   Log-Likelihood:                -2928.9
converged:                       True   LL-Null:                       -2990.0
Covariance Type:            nonrobust   LLR p-value:                 6.607e-21
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.5930      0.084    -42.796      0.000      -3.758      -3.428
AI ROLE                          0.2902      0.271      1.071      0.284      -0.241       0.821
Associate degree                 0.2324      0.214      1.087      0.277      -0.187       0.652
Bachelor's degree                0.3169      0.116      2.743      0.006       0.091       0.543
High school or GED               0.7471      0.123      6.096      0.000       0.507       0.987
Master's degree                  1.0097      0.133      7.584      0.000       0.749       1.271
Ph.D. or professional degree     0.0650      0.170      0.383      0.701      -0.267       0.398
0 years                          0.7108      0.181      3.930      0.000       0.356       1.065
1-2 years                       -0.3774      0.111     -3.414      0.001      -0.594      -0.161
11-20 years                      0.7588      0.271      2.802      0.005       0.228       1.290
3-5 years                       -0.3908      0.115     -3.411      0.001      -0.615      -0.166
6-10 years                      -0.2240      0.168     -1.332      0.183      -0.554       0.106
================================================================================================
Life, Physical, and Social Science Occupations 2018

 59%|█████▉    | 53/90 [00:39<00:20,  1.78it/s]

df length: 19078
Optimization terminated successfully.
         Current function value: 0.125291
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:                19078
Model:                          Logit   Df Residuals:                    19066
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02018
Time:                        23:55:33   Log-Likelihood:                -2390.3
converged:                       True   LL-Null:                       -2439.5
Covariance Type:            nonrobust   LLR p-value:                 3.599e-16
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.6160      0.086    -42.126      0.000      -3.784      -3.448
AI ROLE                          0.1357      0.365      0.372      0.710      -0.579       0.851
Associate degree                -0.6545      0.276     -2.371      0.018      -1.195      -0.114
Bachelor's degree               -0.0841      0.116     -0.723      0.469      -0.312       0.144
High school or GED              -0.4993      0.169     -2.954      0.003      -0.831      -0.168
Master's degree                  0.5784      0.145      3.980      0.000       0.294       0.863
Ph.D. or professional degree    -0.5641      0.208     -2.710      0.007      -0.972      -0.156
0 years                          0.8102      0.234      3.466      0.001       0.352       1.268
1-2 years                        0.6274      0.109      5.735      0.000       0.413       0.842
11-20 years                     -0.2153      0.513     -0.420      0.675      -1.221       0.790
3-5 years                       -0.0573      0.132     -0.435      0.664      -0.316       0.201
6-10 years                      -0.3401      0.220     -1.549      0.121      -0.770       0.090
================================================================================================
Life, Physical, and Social Science Occupations 2023

 60%|██████    | 54/90 [00:39<00:20,  1.79it/s]

df length: 26051
Optimization terminated successfully.
         Current function value: 0.248153
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:                26051
Model:                          Logit   Df Residuals:                    26039
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.007754
Time:                        23:55:33   Log-Likelihood:                -6464.6
converged:                       True   LL-Null:                       -6515.2
Covariance Type:            nonrobust   LLR p-value:                 1.110e-16
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.6757      0.051    -52.066      0.000      -2.776      -2.575
AI ROLE                         -0.0270      0.193     -0.140      0.889      -0.404       0.351
Associate degree                -0.2952      0.128     -2.311      0.021      -0.546      -0.045
Bachelor's degree               -0.1481      0.068     -2.181      0.029      -0.281      -0.015
High school or GED              -0.0611      0.082     -0.746      0.456      -0.221       0.099
Master's degree                  0.0215      0.095      0.226      0.821      -0.165       0.208
Ph.D. or professional degree    -0.5814      0.108     -5.392      0.000      -0.793      -0.370
0 years                          0.0427      0.145      0.294      0.769      -0.241       0.327
1-2 years                        0.2229      0.067      3.307      0.001       0.091       0.355
11-20 years                      0.1987      0.256      0.776      0.438      -0.303       0.701
3-5 years                        0.3799      0.068      5.580      0.000       0.246       0.513
6-10 years                       0.6075      0.093      6.565      0.000       0.426       0.789
================================================================================================
Management Occupations 2019
df length: 174325
Optimization terminated successfully.
         Current function value: 0.125626
         Iterations 8

 61%|██████    | 55/90 [00:40<00:23,  1.47it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:               174325
Model:                          Logit   Df Residuals:                   174313
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.002514
Time:                        23:55:34   Log-Likelihood:                -21900.
converged:                       True   LL-Null:                       -21955.
Covariance Type:            nonrobust   LLR p-value:                 1.543e-18
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.6936      0.028   -129.783      0.000      -3.749      -3.638
AI ROLE                         -0.3392      0.148     -2.285      0.022      -0.630      -0.048
Associate degree                 0.1614      0.071      2.276      0.023       0.022       0.300
Bachelor's degree                0.0727      0.037      1.960      0.050   -5.81e-06       0.145
High school or GED              -0.0417      0.047     -0.879      0.380      -0.135       0.051
Master's degree                 -0.0422      0.089     -0.474      0.636      -0.217       0.133
Ph.D. or professional degree     0.0604      0.165      0.367      0.714      -0.262       0.383
0 years                          0.3836      0.146      2.624      0.009       0.097       0.670
1-2 years                        0.3482      0.042      8.213      0.000       0.265       0.431
11-20 years                     -0.0082      0.119     -0.070      0.945      -0.241       0.224
3-5 years                        0.1478      0.039      3.781      0.000       0.071       0.224
6-10 years                      -0.0509      0.052     -0.985      0.325      -0.152       0.050
================================================================================================
Management Occupations 2021
df length: 220041
Optimization terminated successfully.
         Current function value: 0.177552
         Iterations 7

 62%|██████▏   | 56/90 [00:41<00:26,  1.26it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:               220041
Model:                          Logit   Df Residuals:                   220029
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01150
Time:                        23:55:35   Log-Likelihood:                -39069.
converged:                       True   LL-Null:                       -39523.
Covariance Type:            nonrobust   LLR p-value:                7.817e-188
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.5568      0.024   -151.349      0.000      -3.603      -3.511
AI ROLE                          0.0143      0.076      0.188      0.851      -0.134       0.163
Associate degree                 0.1157      0.056      2.051      0.040       0.005       0.226
Bachelor's degree                0.2825      0.028     10.107      0.000       0.228       0.337
High school or GED               0.1550      0.033      4.652      0.000       0.090       0.220
Master's degree                  0.2623      0.061      4.330      0.000       0.144       0.381
Ph.D. or professional degree     1.0632      0.080     13.254      0.000       0.906       1.220
0 years                         -0.0780      0.120     -0.648      0.517      -0.314       0.158
1-2 years                        0.4172      0.032     12.899      0.000       0.354       0.481
11-20 years                      0.4425      0.074      5.982      0.000       0.298       0.587
3-5 years                        0.3879      0.029     13.450      0.000       0.331       0.444
6-10 years                       0.6083      0.033     18.283      0.000       0.543       0.673
================================================================================================
Management Occupations 2022
df length: 258812
Optimization terminated successfully.
         Current function value: 0.199782
         Iterations 7

 63%|██████▎   | 57/90 [00:43<00:29,  1.11it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:               258812
Model:                          Logit   Df Residuals:                   258800
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01290
Time:                        23:55:37   Log-Likelihood:                -51706.
converged:                       True   LL-Null:                       -52382.
Covariance Type:            nonrobust   LLR p-value:                3.633e-283
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.4282      0.020   -170.634      0.000      -3.468      -3.389
AI ROLE                          0.0373      0.063      0.597      0.551      -0.085       0.160
Associate degree                 0.2798      0.045      6.161      0.000       0.191       0.369
Bachelor's degree                0.3441      0.024     14.521      0.000       0.298       0.391
High school or GED               0.0958      0.030      3.217      0.001       0.037       0.154
Master's degree                  0.0678      0.056      1.214      0.225      -0.042       0.177
Ph.D. or professional degree     0.7251      0.082      8.844      0.000       0.564       0.886
0 years                          0.4768      0.082      5.813      0.000       0.316       0.638
1-2 years                        0.4142      0.028     14.740      0.000       0.359       0.469
11-20 years                      0.6532      0.059     11.034      0.000       0.537       0.769
3-5 years                        0.4306      0.025     17.292      0.000       0.382       0.479
6-10 years                       0.5971      0.029     20.660      0.000       0.540       0.654
================================================================================================
Management Occupations 2020
df length: 162514
Optimization terminated successfully.
         Current function value: 0.129772
         Iterations 8

 64%|██████▍   | 58/90 [00:43<00:29,  1.10it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:               162514
Model:                          Logit   Df Residuals:                   162502
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.008494
Time:                        23:55:37   Log-Likelihood:                -21090.
converged:                       True   LL-Null:                       -21270.
Covariance Type:            nonrobust   LLR p-value:                 9.649e-71
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.7054      0.029   -125.698      0.000      -3.763      -3.648
AI ROLE                         -0.5277      0.161     -3.287      0.001      -0.842      -0.213
Associate degree                 0.2000      0.074      2.717      0.007       0.056       0.344
Bachelor's degree                0.0424      0.039      1.098      0.272      -0.033       0.118
High school or GED               0.1151      0.044      2.626      0.009       0.029       0.201
Master's degree                  0.0825      0.086      0.956      0.339      -0.087       0.251
Ph.D. or professional degree    -0.5661      0.196     -2.888      0.004      -0.950      -0.182
0 years                          1.4722      0.075     19.541      0.000       1.325       1.620
1-2 years                        0.2732      0.044      6.176      0.000       0.186       0.360
11-20 years                      0.1850      0.112      1.658      0.097      -0.034       0.404
3-5 years                        0.2074      0.040      5.190      0.000       0.129       0.286
6-10 years                       0.0509      0.053      0.962      0.336      -0.053       0.155
================================================================================================
Management Occupations 2018
df length: 169177
Optimization terminated successfully.
         Current function value: 0.099882
         Iterations 8

 66%|██████▌   | 59/90 [00:44<00:28,  1.09it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:               169177
Model:                          Logit   Df Residuals:                   169165
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.005930
Time:                        23:55:38   Log-Likelihood:                -16898.
converged:                       True   LL-Null:                       -16999.
Covariance Type:            nonrobust   LLR p-value:                 3.443e-37
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.9839      0.033   -119.942      0.000      -4.049      -3.919
AI ROLE                         -0.5263      0.202     -2.601      0.009      -0.923      -0.130
Associate degree                 0.1376      0.080      1.723      0.085      -0.019       0.294
Bachelor's degree               -0.0809      0.043     -1.877      0.061      -0.165       0.004
High school or GED              -0.2970      0.059     -5.046      0.000      -0.412      -0.182
Master's degree                 -0.0053      0.098     -0.054      0.957      -0.198       0.187
Ph.D. or professional degree     0.1914      0.174      1.100      0.271      -0.150       0.532
0 years                          0.3554      0.179      1.987      0.047       0.005       0.706
1-2 years                        0.5225      0.050     10.487      0.000       0.425       0.620
11-20 years                     -0.1949      0.163     -1.193      0.233      -0.515       0.125
3-5 years                        0.3548      0.046      7.770      0.000       0.265       0.444
6-10 years                      -0.0432      0.062     -0.696      0.486      -0.165       0.078
================================================================================================
Management Occupations 2023
df length: 201898
Optimization terminated successfully.
         Current function value: 0.240228
         Iterations 7

 67%|██████▋   | 60/90 [00:45<00:28,  1.06it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:               201898
Model:                          Logit   Df Residuals:                   201886
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01351
Time:                        23:55:39   Log-Likelihood:                -48502.
converged:                       True   LL-Null:                       -49166.
Covariance Type:            nonrobust   LLR p-value:                3.387e-278
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.1678      0.020   -156.984      0.000      -3.207      -3.128
AI ROLE                          0.1911      0.064      2.972      0.003       0.065       0.317
Associate degree                 0.4086      0.044      9.341      0.000       0.323       0.494
Bachelor's degree                0.3844      0.024     15.885      0.000       0.337       0.432
High school or GED               0.2032      0.029      7.011      0.000       0.146       0.260
Master's degree                  0.1257      0.055      2.296      0.022       0.018       0.233
Ph.D. or professional degree     0.4585      0.091      5.039      0.000       0.280       0.637
0 years                          0.0861      0.093      0.924      0.355      -0.096       0.269
1-2 years                        0.3449      0.028     12.414      0.000       0.290       0.399
11-20 years                      0.5986      0.059     10.170      0.000       0.483       0.714
3-5 years                        0.4116      0.025     16.501      0.000       0.363       0.461
6-10 years                       0.5661      0.030     19.147      0.000       0.508       0.624
================================================================================================
Office and Administrative Support Occupations 2019
df length: 185082
Optimization terminated successfully.
         Current function value: 0.116577
         Iterations 8

 68%|██████▊   | 61/90 [00:46<00:27,  1.04it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:               185082
Model:                          Logit   Df Residuals:                   185070
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.003653
Time:                        23:55:40   Log-Likelihood:                -21576.
converged:                       True   LL-Null:                       -21655.
Covariance Type:            nonrobust   LLR p-value:                 3.118e-28
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.8481      0.026   -148.083      0.000      -3.899      -3.797
AI ROLE                         -0.2031      0.320     -0.634      0.526      -0.831       0.425
Associate degree                 0.1558      0.070      2.215      0.027       0.018       0.294
Bachelor's degree                0.1614      0.050      3.197      0.001       0.062       0.260
High school or GED               0.3703      0.034     10.933      0.000       0.304       0.437
Master's degree                  0.5892      0.195      3.028      0.002       0.208       0.971
Ph.D. or professional degree     0.4674      0.385      1.213      0.225      -0.288       1.222
0 years                          0.3661      0.073      4.982      0.000       0.222       0.510
1-2 years                       -0.0218      0.036     -0.605      0.545      -0.092       0.049
11-20 years                     -0.3435      0.413     -0.831      0.406      -1.153       0.466
3-5 years                        0.0210      0.048      0.435      0.663      -0.074       0.116
6-10 years                      -0.2810      0.131     -2.146      0.032      -0.538      -0.024
================================================================================================
Office and Administrative Support Occupations 2021
df length: 223691
Optimization terminated successfully.
         Current function value: 0.166004
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:               223691
Model:                          Logit   Df Residuals:                   223679
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.002792
Time:                        23:55:41   Log-Likelihood:                -37134.
converged:                       True   LL-Null:                       -37238.
Covariance Type:            nonrobust   LLR p-value:                 1.676e-38
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.3513      0.020   -168.207      0.000      -3.390      -3.312
AI ROLE                          0.1447      0.174      0.830      0.406      -0.197       0.486
Associate degree                 0.1698      0.053      3.221      0.001       0.067       0.273
Bachelor's degree                0.2918      0.039      7.565      0.000       0.216       0.367
High school or GED               0.3015      0.025     12.077      0.000       0.253       0.350
Master's degree                 -0.1024      0.193     -0.530      0.596      -0.481       0.276
Ph.D. or professional degree    -0.9278      0.582     -1.595      0.111      -2.068       0.212
0 years                         -0.1911      0.061     -3.127      0.002      -0.311      -0.071
1-2 years                       -0.0916      0.027     -3.451      0.001      -0.144      -0.040
11-20 years                     -0.3812      0.307     -1.241      0.215      -0.983       0.221
3-5 years                        0.0678      0.035      1.936      0.053      -0.001       0.136
6-10 years                       0.0891      0.084      1.064      0.287      -0.075       0.253
================================================================================================

 69%|██████▉   | 62/90 [00:47<00:27,  1.00it/s]

Office and Administrative Support Occupations 2022
df length: 238205
Optimization terminated successfully.
         Current function value: 0.176727
         Iterations 8

 70%|███████   | 63/90 [00:49<00:28,  1.04s/it]

                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:               238205
Model:                          Logit   Df Residuals:                   238193
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.006012
Time:                        23:55:43   Log-Likelihood:                -42097.
converged:                       True   LL-Null:                       -42352.
Covariance Type:            nonrobust   LLR p-value:                3.389e-102
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.3518      0.018   -182.211      0.000      -3.388      -3.316
AI ROLE                          0.0927      0.147      0.633      0.527      -0.195       0.380
Associate degree                 0.3616      0.044      8.196      0.000       0.275       0.448
Bachelor's degree                0.3793      0.033     11.374      0.000       0.314       0.445
High school or GED               0.2305      0.024      9.690      0.000       0.184       0.277
Master's degree                  0.2034      0.145      1.406      0.160      -0.080       0.487
Ph.D. or professional degree     0.5286      0.221      2.393      0.017       0.096       0.962
0 years                         -0.2864      0.064     -4.505      0.000      -0.411      -0.162
1-2 years                        0.1508      0.024      6.186      0.000       0.103       0.199
11-20 years                     -0.0568      0.236     -0.241      0.810      -0.519       0.405
3-5 years                        0.2745      0.031      8.914      0.000       0.214       0.335
6-10 years                       0.4178      0.063      6.636      0.000       0.294       0.541
================================================================================================
Office and Administrative Support Occupations 2020
df length: 175927
Optimization terminated successfully.
         Current function value: 0.130790
         Iterations 8

 71%|███████   | 64/90 [00:50<00:26,  1.02s/it]

                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:               175927
Model:                          Logit   Df Residuals:                   175915
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.03078
Time:                        23:55:44   Log-Likelihood:                -23009.
converged:                       True   LL-Null:                       -23740.
Covariance Type:            nonrobust   LLR p-value:                6.441e-307
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.8615      0.026   -147.758      0.000      -3.913      -3.810
AI ROLE                         -0.0546      0.322     -0.170      0.865      -0.686       0.577
Associate degree                 0.4200      0.070      6.031      0.000       0.284       0.557
Bachelor's degree                0.3172      0.053      5.992      0.000       0.213       0.421
High school or GED               0.5172      0.032     16.406      0.000       0.455       0.579
Master's degree                  0.7783      0.190      4.103      0.000       0.407       1.150
Ph.D. or professional degree     0.5499      0.386      1.426      0.154      -0.206       1.306
0 years                          1.4541      0.040     36.778      0.000       1.377       1.532
1-2 years                       -0.1982      0.038     -5.233      0.000      -0.272      -0.124
11-20 years                     -0.2043      0.339     -0.602      0.547      -0.870       0.461
3-5 years                       -0.0410      0.050     -0.828      0.408      -0.138       0.056
6-10 years                       0.0116      0.121      0.096      0.924      -0.226       0.250
================================================================================================
Office and Administrative Support Occupations 2018
df length: 173712
Optimization terminated successfully.
         Current function value: 0.099328
         Iterations 9

 72%|███████▏  | 65/90 [00:51<00:25,  1.01s/it]

                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:               173712
Model:                          Logit   Df Residuals:                   173700
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.003378
Time:                        23:55:45   Log-Likelihood:                -17254.
converged:                       True   LL-Null:                       -17313.
Covariance Type:            nonrobust   LLR p-value:                 7.321e-20
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.0256      0.029   -140.822      0.000      -4.082      -3.970
AI ROLE                          0.4931      0.295      1.673      0.094      -0.085       1.071
Associate degree                -0.1841      0.085     -2.167      0.030      -0.351      -0.018
Bachelor's degree                0.1672      0.056      2.983      0.003       0.057       0.277
High school or GED               0.2286      0.039      5.862      0.000       0.152       0.305
Master's degree                  0.3822      0.248      1.543      0.123      -0.103       0.868
Ph.D. or professional degree    -0.2875      0.582     -0.494      0.622      -1.429       0.854
0 years                          0.3826      0.090      4.235      0.000       0.206       0.560
1-2 years                        0.1708      0.041      4.212      0.000       0.091       0.250
11-20 years                     -0.8511      0.581     -1.464      0.143      -1.991       0.289
3-5 years                        0.0135      0.056      0.241      0.810      -0.097       0.124
6-10 years                      -0.5829      0.174     -3.353      0.001      -0.924      -0.242
================================================================================================
Office and Administrative Support Occupations 2023
df length: 177048
Optimization terminated successfully.
         Current function value: 0.222455
         Iterations 7

 73%|███████▎  | 66/90 [00:52<00:23,  1.01it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:               177048
Model:                          Logit   Df Residuals:                   177036
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.006718
Time:                        23:55:46   Log-Likelihood:                -39385.
converged:                       True   LL-Null:                       -39652.
Covariance Type:            nonrobust   LLR p-value:                3.281e-107
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.9977      0.018   -164.388      0.000      -3.033      -2.962
AI ROLE                         -0.5944      0.201     -2.960      0.003      -0.988      -0.201
Associate degree                 0.3951      0.045      8.707      0.000       0.306       0.484
Bachelor's degree                0.5307      0.033     15.913      0.000       0.465       0.596
High school or GED               0.2529      0.024     10.673      0.000       0.206       0.299
Master's degree                  0.6195      0.116      5.320      0.000       0.391       0.848
Ph.D. or professional degree    -0.2484      0.308     -0.807      0.420      -0.852       0.355
0 years                         -0.4276      0.062     -6.915      0.000      -0.549      -0.306
1-2 years                        0.1007      0.024      4.173      0.000       0.053       0.148
11-20 years                      0.0447      0.191      0.233      0.815      -0.330       0.420
3-5 years                        0.0922      0.032      2.907      0.004       0.030       0.154
6-10 years                       0.1705      0.068      2.517      0.012       0.038       0.303
================================================================================================
Personal Care and Service Occupations 2019

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
 74%|███████▍  | 67/90 [00:52<00:20,  1.13it/s]

df length: 25875
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.092621
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:                25875
Model:                          Logit   Df Residuals:                    25863
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02129
Time:                        23:55:46   Log-Likelihood:                -2396.6
converged:                      False   LL-Null:                       -2448.7
Covariance Type:            nonrobust   LLR p-value:                 2.570e-17
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.2223      0.063    -66.950      0.000      -4.346      -4.099
AI ROLE                          1.2319      1.055      1.167      0.243      -0.836       3.300
Associate degree                 1.3618      0.202      6.755      0.000       0.967       1.757
Bachelor's degree                0.9939      0.164      6.044      0.000       0.672       1.316
High school or GED               0.2932      0.111      2.632      0.008       0.075       0.511
Master's degree                 -0.0506      1.013     -0.050      0.960      -2.036       1.935
Ph.D. or professional degree   -14.1172   2735.262     -0.005      0.996   -5375.132    5346.897
0 years                          0.8977      0.244      3.680      0.000       0.420       1.376
1-2 years                        0.3933      0.120      3.278      0.001       0.158       0.628
11-20 years                      0.9856      1.035      0.952      0.341      -1.044       3.015
3-5 years                       -0.2711      0.259     -1.045      0.296      -0.779       0.237
6-10 years                       0.1202      0.597      0.201      0.840      -1.050       1.290
================================================================================================
Personal Care and Service Occupations 2021

 76%|███████▌  | 68/90 [00:53<00:17,  1.25it/s]

df length: 28728
Optimization terminated successfully.
         Current function value: 0.109963
         Iterations 28
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:                28728
Model:                          Logit   Df Residuals:                    28716
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01016
Time:                        23:55:47   Log-Likelihood:                -3159.0
converged:                       True   LL-Null:                       -3191.4
Covariance Type:            nonrobust   LLR p-value:                 1.165e-09
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.8908      0.055    -71.169      0.000      -3.998      -3.784
AI ROLE                          1.5594      0.751      2.077      0.038       0.088       3.031
Associate degree                 0.4407      0.249      1.773      0.076      -0.046       0.928
Bachelor's degree                0.8522      0.144      5.934      0.000       0.571       1.134
High school or GED               0.1416      0.090      1.578      0.115      -0.034       0.318
Master's degree                 -0.8403      1.008     -0.833      0.405      -2.816       1.136
Ph.D. or professional degree   -70.5385    3.8e+15  -1.86e-14      1.000   -7.45e+15    7.45e+15
0 years                          0.4014      0.228      1.764      0.078      -0.045       0.848
1-2 years                        0.0274      0.106      0.259      0.796      -0.180       0.235
11-20 years                      1.7691      0.620      2.853      0.004       0.554       2.984
3-5 years                        0.4653      0.157      2.958      0.003       0.157       0.774
6-10 years                       0.3227      0.519      0.622      0.534      -0.695       1.340
================================================================================================
Personal Care and Service Occupations 2022

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
 77%|███████▋  | 69/90 [00:53<00:15,  1.31it/s]

df length: 32448
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.140145
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:                32448
Model:                          Logit   Df Residuals:                    32436
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.007267
Time:                        23:55:47   Log-Likelihood:                -4547.4
converged:                      False   LL-Null:                       -4580.7
Covariance Type:            nonrobust   LLR p-value:                 5.443e-10
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.5404      0.043    -83.147      0.000      -3.624      -3.457
AI ROLE                          0.2827      0.732      0.386      0.700      -1.153       1.718
Associate degree                 0.5878      0.178      3.296      0.001       0.238       0.937
Bachelor's degree                0.5955      0.122      4.876      0.000       0.356       0.835
High school or GED              -0.0320      0.077     -0.416      0.677      -0.183       0.119
Master's degree                  0.5263      0.517      1.018      0.308      -0.487       1.539
Ph.D. or professional degree     1.3949      0.755      1.847      0.065      -0.085       2.875
0 years                          0.3735      0.188      1.984      0.047       0.004       0.742
1-2 years                        0.2568      0.084      3.042      0.002       0.091       0.422
11-20 years                    -11.1047    233.585     -0.048      0.962    -468.923     446.714
3-5 years                        0.3494      0.129      2.709      0.007       0.097       0.602
6-10 years                       0.1002      0.423      0.237      0.813      -0.729       0.930
================================================================================================
Personal Care and Service Occupations 2020

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
 78%|███████▊  | 70/90 [00:54<00:14,  1.38it/s]

df length: 24654
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.098665
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:                24654
Model:                          Logit   Df Residuals:                    24642
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01405
Time:                        23:55:48   Log-Likelihood:                -2432.5
converged:                      False   LL-Null:                       -2467.2
Covariance Type:            nonrobust   LLR p-value:                 1.625e-10
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.0617      0.061    -66.750      0.000      -4.181      -3.942
AI ROLE                        -13.9533   1852.379     -0.008      0.994   -3644.548    3616.642
Associate degree                 0.5420      0.284      1.912      0.056      -0.014       1.098
Bachelor's degree                0.9143      0.168      5.448      0.000       0.585       1.243
High school or GED               0.2288      0.107      2.139      0.032       0.019       0.438
Master's degree                  0.6750      0.727      0.928      0.353      -0.750       2.100
Ph.D. or professional degree   -13.6925   2355.462     -0.006      0.995   -4630.313    4602.928
0 years                          0.1595      0.343      0.465      0.642      -0.513       0.832
1-2 years                        0.0436      0.132      0.330      0.742      -0.216       0.303
11-20 years                    -14.5071   2208.654     -0.007      0.995   -4343.390    4314.376
3-5 years                        0.7310      0.168      4.347      0.000       0.401       1.061
6-10 years                       0.9407      0.405      2.321      0.020       0.146       1.735
================================================================================================
Personal Care and Service Occupations 2018

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
 79%|███████▉  | 71/90 [00:55<00:13,  1.44it/s]

df length: 25428
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.079123
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:                25428
Model:                          Logit   Df Residuals:                    25416
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.03196
Time:                        23:55:49   Log-Likelihood:                -2011.9
converged:                      False   LL-Null:                       -2078.3
Covariance Type:            nonrobust   LLR p-value:                 4.652e-23
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.4613      0.070    -63.822      0.000      -4.598      -4.324
AI ROLE                         -2.0136      5.509     -0.366      0.715     -12.812       8.784
Associate degree                 1.1626      0.273      4.253      0.000       0.627       1.698
Bachelor's degree                1.7522      0.162     10.842      0.000       1.435       2.069
High school or GED               0.4930      0.127      3.882      0.000       0.244       0.742
Master's degree                  0.3105      1.013      0.306      0.759      -1.676       2.297
Ph.D. or professional degree   -13.8215   2802.198     -0.005      0.996   -5506.029    5478.386
0 years                          0.7861      0.318      2.469      0.014       0.162       1.410
1-2 years                        0.1946      0.138      1.407      0.159      -0.076       0.466
11-20 years                    -16.2821   4859.821     -0.003      0.997   -9541.356    9508.791
3-5 years                       -0.1832      0.256     -0.717      0.474      -0.684       0.318
6-10 years                      -0.7494      0.722     -1.038      0.299      -2.164       0.666
================================================================================================
Personal Care and Service Occupations 2023

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
 80%|████████  | 72/90 [00:55<00:12,  1.48it/s]

df length: 25603
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.165807
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:                25603
Model:                          Logit   Df Residuals:                    25591
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01118
Time:                        23:55:49   Log-Likelihood:                -4245.1
converged:                      False   LL-Null:                       -4293.1
Covariance Type:            nonrobust   LLR p-value:                 1.113e-15
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.3490      0.044    -75.414      0.000      -3.436      -3.262
AI ROLE                          0.2683      0.738      0.364      0.716      -1.178       1.714
Associate degree                 0.6874      0.184      3.734      0.000       0.327       1.048
Bachelor's degree                0.9064      0.112      8.066      0.000       0.686       1.127
High school or GED               0.0950      0.076      1.249      0.212      -0.054       0.244
Master's degree                 -0.4502      0.718     -0.627      0.530      -1.857       0.956
Ph.D. or professional degree   -13.8110   1420.210     -0.010      0.992   -2797.371    2769.749
0 years                          0.6145      0.160      3.837      0.000       0.301       0.928
1-2 years                        0.1130      0.085      1.323      0.186      -0.054       0.280
11-20 years                     -0.2592      0.724     -0.358      0.720      -1.678       1.159
3-5 years                        0.2500      0.130      1.916      0.055      -0.006       0.506
6-10 years                       0.0777      0.425      0.183      0.855      -0.755       0.910
================================================================================================
Production Occupations 2019

 81%|████████  | 73/90 [00:56<00:11,  1.44it/s]

df length: 52795
Optimization terminated successfully.
         Current function value: 0.127687
         Iterations 10
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:                52795
Model:                          Logit   Df Residuals:                    52783
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02215
Time:                        23:55:50   Log-Likelihood:                -6741.2
converged:                       True   LL-Null:                       -6893.9
Covariance Type:            nonrobust   LLR p-value:                 6.281e-59
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.8145      0.045    -84.852      0.000      -3.903      -3.726
AI ROLE                          0.0493      0.588      0.084      0.933      -1.104       1.202
Associate degree                 0.3183      0.181      1.754      0.079      -0.037       0.674
Bachelor's degree                0.2225      0.121      1.841      0.066      -0.014       0.459
High school or GED               0.8329      0.057     14.580      0.000       0.721       0.945
Master's degree                 -2.0415      1.003     -2.036      0.042      -4.007      -0.076
Ph.D. or professional degree    -0.0094      1.011     -0.009      0.993      -1.991       1.973
0 years                          0.3921      0.128      3.060      0.002       0.141       0.643
1-2 years                       -0.2448      0.070     -3.491      0.000      -0.382      -0.107
11-20 years                      0.6367      0.426      1.495      0.135      -0.198       1.471
3-5 years                       -0.6767      0.099     -6.859      0.000      -0.870      -0.483
6-10 years                      -0.4656      0.205     -2.271      0.023      -0.867      -0.064
================================================================================================
Production Occupations 2021

 82%|████████▏ | 74/90 [00:57<00:11,  1.40it/s]

df length: 77544
Optimization terminated successfully.
         Current function value: 0.146075
         Iterations 9
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:                77544
Model:                          Logit   Df Residuals:                    77532
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.002907
Time:                        23:55:51   Log-Likelihood:                -11327.
converged:                       True   LL-Null:                       -11360.
Covariance Type:            nonrobust   LLR p-value:                 6.828e-10
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.4726      0.032   -109.536      0.000      -3.535      -3.410
AI ROLE                          0.0660      0.342      0.193      0.847      -0.605       0.737
Associate degree                 0.3493      0.115      3.044      0.002       0.124       0.574
Bachelor's degree                0.2676      0.079      3.400      0.001       0.113       0.422
High school or GED               0.0151      0.044      0.341      0.733      -0.071       0.102
Master's degree                 -1.1238      0.451     -2.493      0.013      -2.007      -0.240
Ph.D. or professional degree     0.9617      0.468      2.053      0.040       0.043       1.880
0 years                          0.2358      0.086      2.729      0.006       0.066       0.405
1-2 years                        0.1924      0.053      3.641      0.000       0.089       0.296
11-20 years                     -0.0295      0.458     -0.065      0.949      -0.927       0.868
3-5 years                        0.1748      0.065      2.684      0.007       0.047       0.302
6-10 years                       0.0746      0.143      0.522      0.602      -0.206       0.355
================================================================================================
Production Occupations 2022

 83%|████████▎ | 75/90 [00:58<00:11,  1.36it/s]

df length: 80132
Optimization terminated successfully.
         Current function value: 0.172150
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:                80132
Model:                          Logit   Df Residuals:                    80120
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.006579
Time:                        23:55:52   Log-Likelihood:                -13795.
converged:                       True   LL-Null:                       -13886.
Covariance Type:            nonrobust   LLR p-value:                 2.820e-33
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.3640      0.029   -114.922      0.000      -3.421      -3.307
AI ROLE                          0.0217      0.267      0.081      0.935      -0.502       0.546
Associate degree                 0.3500      0.106      3.293      0.001       0.142       0.558
Bachelor's degree                0.5731      0.066      8.695      0.000       0.444       0.702
High school or GED               0.3674      0.040      9.242      0.000       0.289       0.445
Master's degree                  0.6422      0.177      3.623      0.000       0.295       0.990
Ph.D. or professional degree     0.0486      0.589      0.083      0.934      -1.106       1.203
0 years                         -0.0281      0.084     -0.334      0.739      -0.193       0.137
1-2 years                       -0.0701      0.049     -1.435      0.151      -0.166       0.026
11-20 years                      0.7267      0.235      3.096      0.002       0.267       1.187
3-5 years                        0.1126      0.054      2.076      0.038       0.006       0.219
6-10 years                       0.1870      0.103      1.818      0.069      -0.015       0.389
================================================================================================
Production Occupations 2020

 84%|████████▍ | 76/90 [00:58<00:10,  1.39it/s]

df length: 59540
Optimization terminated successfully.
         Current function value: 0.134458
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:                59540
Model:                          Logit   Df Residuals:                    59528
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                  0.1250
Time:                        23:55:52   Log-Likelihood:                -8005.6
converged:                       True   LL-Null:                       -9149.2
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.9283      0.043    -91.453      0.000      -4.012      -3.844
AI ROLE                          0.1996      0.518      0.385      0.700      -0.815       1.215
Associate degree                 2.3359      0.077     30.274      0.000       2.185       2.487
Bachelor's degree                0.3223      0.120      2.686      0.007       0.087       0.558
High school or GED               0.5442      0.053     10.236      0.000       0.440       0.648
Master's degree                  0.3282      0.361      0.910      0.363      -0.379       1.035
Ph.D. or professional degree     1.0423      0.726      1.436      0.151      -0.381       2.465
0 years                          1.7627      0.057     31.087      0.000       1.652       1.874
1-2 years                       -0.2474      0.072     -3.456      0.001      -0.388      -0.107
11-20 years                      0.1415      0.517      0.274      0.784      -0.872       1.155
3-5 years                       -0.5455      0.093     -5.855      0.000      -0.728      -0.363
6-10 years                      -0.9198      0.239     -3.852      0.000      -1.388      -0.452
================================================================================================
Production Occupations 2018

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
 86%|████████▌ | 77/90 [00:59<00:09,  1.38it/s]

df length: 53697
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.089863
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:                53697
Model:                          Logit   Df Residuals:                    53685
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.007650
Time:                        23:55:53   Log-Likelihood:                -4825.4
converged:                      False   LL-Null:                       -4862.6
Covariance Type:            nonrobust   LLR p-value:                 1.767e-11
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.0996      0.049    -83.154      0.000      -4.196      -4.003
AI ROLE                          0.7350      0.513      1.433      0.152      -0.270       1.740
Associate degree                -0.2127      0.214     -0.992      0.321      -0.633       0.208
Bachelor's degree               -0.2425      0.138     -1.756      0.079      -0.513       0.028
High school or GED               0.0615      0.072      0.860      0.390      -0.079       0.202
Master's degree                -17.0532   2211.153     -0.008      0.994   -4350.833    4316.726
Ph.D. or professional degree     0.1159      1.016      0.114      0.909      -1.876       2.108
0 years                          0.7287      0.154      4.745      0.000       0.428       1.030
1-2 years                        0.4419      0.082      5.394      0.000       0.281       0.603
11-20 years                    -44.6967   4.46e+09     -1e-08      1.000   -8.74e+09    8.74e+09
3-5 years                       -0.0025      0.108     -0.023      0.981      -0.214       0.209
6-10 years                      -0.3059      0.268     -1.141      0.254      -0.831       0.219
================================================================================================
Production Occupations 2023
df length: 63904
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.204166
         Iterations: 35

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
 87%|████████▋ | 78/90 [01:00<00:09,  1.33it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:                63904
Model:                          Logit   Df Residuals:                    63892
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.007130
Time:                        23:55:54   Log-Likelihood:                -13047.
converged:                      False   LL-Null:                       -13141.
Covariance Type:            nonrobust   LLR p-value:                 3.044e-34
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.0736      0.029   -105.415      0.000      -3.131      -3.016
AI ROLE                         -0.1453      0.312     -0.466      0.641      -0.757       0.466
Associate degree                 0.3239      0.107      3.019      0.003       0.114       0.534
Bachelor's degree                0.5576      0.067      8.374      0.000       0.427       0.688
High school or GED               0.3026      0.040      7.621      0.000       0.225       0.380
Master's degree                  1.5064      0.135     11.138      0.000       1.241       1.771
Ph.D. or professional degree   -30.4886   2.47e+06  -1.24e-05      1.000   -4.83e+06    4.83e+06
0 years                         -0.1597      0.093     -1.719      0.086      -0.342       0.022
1-2 years                       -0.0186      0.047     -0.396      0.692      -0.111       0.074
11-20 years                      0.1166      0.294      0.397      0.691      -0.459       0.692
3-5 years                       -0.0389      0.055     -0.711      0.477      -0.146       0.068
6-10 years                      -0.1268      0.113     -1.122      0.262      -0.348       0.095
================================================================================================
Sales and Related Occupations 2019
df length: 185705
Optimization terminated successfully.
         Current function value: 0.112064
         Iterations 9

 88%|████████▊ | 79/90 [01:01<00:09,  1.21it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:               185705
Model:                          Logit   Df Residuals:                   185693
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.005859
Time:                        23:55:55   Log-Likelihood:                -20811.
converged:                       True   LL-Null:                       -20934.
Covariance Type:            nonrobust   LLR p-value:                 2.698e-46
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.7560      0.023   -160.313      0.000      -3.802      -3.710
AI ROLE                         -0.0774      0.272     -0.285      0.776      -0.610       0.455
Associate degree                 0.0037      0.105      0.036      0.971      -0.201       0.209
Bachelor's degree                0.3952      0.045      8.759      0.000       0.307       0.484
High school or GED               0.2549      0.036      7.076      0.000       0.184       0.325
Master's degree                 -0.4278      0.292     -1.466      0.143      -1.000       0.144
Ph.D. or professional degree    -0.6364      1.006     -0.633      0.527      -2.608       1.335
0 years                         -1.0429      0.109     -9.590      0.000      -1.256      -0.830
1-2 years                       -0.1803      0.040     -4.519      0.000      -0.259      -0.102
11-20 years                     -0.4268      0.359     -1.189      0.234      -1.130       0.277
3-5 years                       -0.1751      0.055     -3.211      0.001      -0.282      -0.068
6-10 years                      -0.6314      0.134     -4.706      0.000      -0.894      -0.368
================================================================================================
Sales and Related Occupations 2021
df length: 207667

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
 89%|████████▉ | 80/90 [01:02<00:10,  1.01s/it]

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.156107
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:               207667
Model:                          Logit   Df Residuals:                   207655
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.004626
Time:                        23:55:56   Log-Likelihood:                -32418.
converged:                      False   LL-Null:                       -32569.
Covariance Type:            nonrobust   LLR p-value:                 4.559e-58
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.2885      0.018   -183.476      0.000      -3.324      -3.253
AI ROLE                         -0.2152      0.184     -1.167      0.243      -0.577       0.146
Associate degree                -0.2449      0.089     -2.753      0.006      -0.419      -0.071
Bachelor's degree                0.0855      0.038      2.271      0.023       0.012       0.159
High school or GED               0.0325      0.027      1.200      0.230      -0.021       0.086
Master's degree                 -0.9386      0.226     -4.152      0.000      -1.382      -0.496
Ph.D. or professional degree   -16.5921   2000.811     -0.008      0.993   -3938.110    3904.926
0 years                         -0.8918      0.088    -10.135      0.000      -1.064      -0.719
1-2 years                        0.0239      0.030      0.787      0.431      -0.036       0.083
11-20 years                      0.5145      0.176      2.928      0.003       0.170       0.859
3-5 years                        0.0575      0.042      1.368      0.171      -0.025       0.140
6-10 years                       0.6642      0.070      9.517      0.000       0.527       0.801
================================================================================================
Sales and Related Occupations 2022
df length: 216216

 90%|█████████ | 81/90 [01:03<00:09,  1.03s/it]

Optimization terminated successfully.
         Current function value: 0.173852
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:               216216
Model:                          Logit   Df Residuals:                   216204
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.008194
Time:                        23:55:57   Log-Likelihood:                -37590.
converged:                       True   LL-Null:                       -37900.
Covariance Type:            nonrobust   LLR p-value:                4.331e-126
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.2613      0.017   -192.789      0.000      -3.294      -3.228
AI ROLE                          0.2014      0.140      1.442      0.149      -0.072       0.475
Associate degree                 0.0923      0.073      1.261      0.207      -0.051       0.236
Bachelor's degree                0.5450      0.033     16.656      0.000       0.481       0.609
High school or GED               0.2697      0.025     10.640      0.000       0.220       0.319
Master's degree                  0.4200      0.130      3.238      0.001       0.166       0.674
Ph.D. or professional degree     0.6297      0.346      1.818      0.069      -0.049       1.308
0 years                         -1.0391      0.088    -11.872      0.000      -1.211      -0.868
1-2 years                       -0.1026      0.028     -3.637      0.000      -0.158      -0.047
11-20 years                     -0.6110      0.294     -2.077      0.038      -1.188      -0.034
3-5 years                        0.0180      0.036      0.498      0.618      -0.053       0.089
6-10 years                       0.2009      0.068      2.955      0.003       0.068       0.334
================================================================================================
Sales and Related Occupations 2020
df length: 180255
Optimization terminated successfully.
         Current function value: 0.115965
         Iterations 9

 91%|█████████ | 82/90 [01:04<00:08,  1.02s/it]

                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:               180255
Model:                          Logit   Df Residuals:                   180243
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.003656
Time:                        23:55:58   Log-Likelihood:                -20903.
converged:                       True   LL-Null:                       -20980.
Covariance Type:            nonrobust   LLR p-value:                 2.985e-27
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.7716      0.023   -165.016      0.000      -3.816      -3.727
AI ROLE                          0.2220      0.219      1.012      0.311      -0.208       0.652
Associate degree                 0.0590      0.112      0.525      0.599      -0.161       0.279
Bachelor's degree                0.2733      0.050      5.423      0.000       0.175       0.372
High school or GED               0.2860      0.035      8.273      0.000       0.218       0.354
Master's degree                 -1.1880      0.410     -2.894      0.004      -1.993      -0.384
Ph.D. or professional degree    -0.7549      1.006     -0.750      0.453      -2.727       1.218
0 years                          0.1522      0.063      2.413      0.016       0.029       0.276
1-2 years                       -0.1861      0.042     -4.457      0.000      -0.268      -0.104
11-20 years                      0.7613      0.209      3.636      0.000       0.351       1.172
3-5 years                       -0.1242      0.058     -2.138      0.033      -0.238      -0.010
6-10 years                       0.3984      0.101      3.951      0.000       0.201       0.596
================================================================================================
Sales and Related Occupations 2018
df length: 170255

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
 92%|█████████▏| 83/90 [01:06<00:07,  1.09s/it]

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.102294
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:               170255
Model:                          Logit   Df Residuals:                   170243
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.002295
Time:                        23:56:00   Log-Likelihood:                -17416.
converged:                      False   LL-Null:                       -17456.
Covariance Type:            nonrobust   LLR p-value:                 1.391e-12
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.8271      0.025   -152.702      0.000      -3.876      -3.778
AI ROLE                         -0.7655      0.450     -1.699      0.089      -1.648       0.117
Associate degree                -0.4066      0.122     -3.338      0.001      -0.645      -0.168
Bachelor's degree                0.2498      0.050      4.991      0.000       0.152       0.348
High school or GED               0.0480      0.041      1.179      0.238      -0.032       0.128
Master's degree                 -0.2946      0.337     -0.874      0.382      -0.955       0.366
Ph.D. or professional degree   -14.2742    934.216     -0.015      0.988   -1845.304    1816.755
0 years                         -0.4492      0.121     -3.723      0.000      -0.686      -0.213
1-2 years                       -0.0462      0.044     -1.040      0.299      -0.133       0.041
11-20 years                     -0.5814      0.452     -1.286      0.198      -1.467       0.305
3-5 years                       -0.2205      0.063     -3.486      0.000      -0.344      -0.097
6-10 years                      -0.5590      0.141     -3.966      0.000      -0.835      -0.283
================================================================================================
Sales and Related Occupations 2023
df length: 183257
Optimization terminated successfully.
         Current function value: 0.229755
         Iterations 9

 93%|█████████▎| 84/90 [01:07<00:06,  1.06s/it]

                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:               183257
Model:                          Logit   Df Residuals:                   183245
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01536
Time:                        23:56:01   Log-Likelihood:                -42104.
converged:                       True   LL-Null:                       -42761.
Covariance Type:            nonrobust   LLR p-value:                4.584e-275
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.9178      0.016   -188.095      0.000      -2.948      -2.887
AI ROLE                         -0.4882      0.186     -2.625      0.009      -0.853      -0.124
Associate degree                 0.7958      0.049     16.148      0.000       0.699       0.892
Bachelor's degree                0.7937      0.029     27.085      0.000       0.736       0.851
High school or GED               0.2259      0.023      9.636      0.000       0.180       0.272
Master's degree                  1.2371      0.103     11.958      0.000       1.034       1.440
Ph.D. or professional degree    -1.6763      1.005     -1.668      0.095      -3.646       0.294
0 years                         -0.8729      0.069    -12.634      0.000      -1.008      -0.737
1-2 years                        0.0095      0.025      0.381      0.703      -0.040       0.059
11-20 years                     -0.4778      0.221     -2.161      0.031      -0.911      -0.044
3-5 years                        0.0217      0.032      0.671      0.502      -0.042       0.085
6-10 years                      -0.0483      0.068     -0.710      0.478      -0.182       0.085
================================================================================================
Transportation and Material Moving Occupations 2019
df length: 92120
Optimization terminated successfully.
         Current function value: 0.139749
         Iterations 25

 94%|█████████▍| 85/90 [01:07<00:04,  1.00it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:                92120
Model:                          Logit   Df Residuals:                    92108
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01868
Time:                        23:56:01   Log-Likelihood:                -12874.
converged:                       True   LL-Null:                       -13119.
Covariance Type:            nonrobust   LLR p-value:                 4.136e-98
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.7117      0.028   -134.826      0.000      -3.766      -3.658
AI ROLE                          0.1880      1.021      0.184      0.854      -1.813       2.189
Associate degree                -0.4566      0.283     -1.615      0.106      -1.011       0.097
Bachelor's degree               -0.6657      0.219     -3.035      0.002      -1.096      -0.236
High school or GED               0.2251      0.040      5.693      0.000       0.148       0.303
Master's degree                -39.4597   1.97e+08     -2e-07      1.000   -3.86e+08    3.86e+08
Ph.D. or professional degree    -0.1965      1.016     -0.193      0.847      -2.189       1.796
0 years                          0.7666      0.072     10.612      0.000       0.625       0.908
1-2 years                        0.8257      0.043     19.412      0.000       0.742       0.909
11-20 years                     -0.1258      1.012     -0.124      0.901      -2.109       1.858
3-5 years                        0.1002      0.101      0.991      0.321      -0.098       0.298
6-10 years                       0.2285      0.296      0.771      0.441      -0.352       0.809
================================================================================================
Transportation and Material Moving Occupations 2021
df length: 168157

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/discrete/discrete_model.py:2385: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/discrete/discrete_model.py:2443: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q * linpred)))
 96%|█████████▌| 86/90 [01:09<00:04,  1.02s/it]

Warning: Maximum number of iterations has been exceeded.
         Current function value: inf
         Iterations: 35
Singular matrix
Transportation and Material Moving Occupations 2022
df length: 136730

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
 97%|█████████▋| 87/90 [01:10<00:03,  1.04s/it]

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.206776
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:               136730
Model:                          Logit   Df Residuals:                   136718
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.001533
Time:                        23:56:04   Log-Likelihood:                -28272.
converged:                      False   LL-Null:                       -28316.
Covariance Type:            nonrobust   LLR p-value:                 6.983e-14
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.8521      0.016   -182.025      0.000      -2.883      -2.821
AI ROLE                         -0.2145      0.459     -0.467      0.640      -1.114       0.685
Associate degree                -0.5099      0.197     -2.594      0.009      -0.895      -0.125
Bachelor's degree                0.0909      0.110      0.828      0.408      -0.124       0.306
High school or GED               0.0932      0.027      3.421      0.001       0.040       0.147
Master's degree                 -0.0142      0.286     -0.050      0.960      -0.574       0.546
Ph.D. or professional degree   -18.9111   1.04e+04     -0.002      0.999   -2.04e+04    2.03e+04
0 years                         -0.3387      0.059     -5.711      0.000      -0.455      -0.222
1-2 years                       -0.1513      0.033     -4.651      0.000      -0.215      -0.088
11-20 years                      0.3613      0.349      1.034      0.301      -0.323       1.046
3-5 years                       -0.2671      0.064     -4.150      0.000      -0.393      -0.141
6-10 years                      -0.2779      0.203     -1.372      0.170      -0.675       0.119
================================================================================================
Transportation and Material Moving Occupations 2020
df length: 141154

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
 98%|█████████▊| 88/90 [01:11<00:02,  1.06s/it]

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.223471
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:               141154
Model:                          Logit   Df Residuals:                   141142
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                  0.1743
Time:                        23:56:05   Log-Likelihood:                -31544.
converged:                      False   LL-Null:                       -38202.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.5727      0.020   -176.551      0.000      -3.612      -3.533
AI ROLE                         -0.7725      1.023     -0.755      0.450      -2.778       1.233
Associate degree                 3.0540      0.070     43.401      0.000       2.916       3.192
Bachelor's degree                0.2004      0.195      1.030      0.303      -0.181       0.582
High school or GED               1.5872      0.023     69.637      0.000       1.543       1.632
Master's degree                -27.3686   4.19e+05  -6.54e-05      1.000    -8.2e+05     8.2e+05
Ph.D. or professional degree     0.8978      0.734      1.223      0.221      -0.541       2.336
0 years                          1.3967      0.023     60.792      0.000       1.352       1.442
1-2 years                       -0.6566      0.040    -16.404      0.000      -0.735      -0.578
11-20 years                     -0.4900      0.596     -0.822      0.411      -1.658       0.678
3-5 years                       -1.0070      0.092    -10.942      0.000      -1.187      -0.827
6-10 years                      -1.1142      0.313     -3.557      0.000      -1.728      -0.500
================================================================================================
Transportation and Material Moving Occupations 2018
df length: 111268

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
 99%|█████████▉| 89/90 [01:12<00:01,  1.03s/it]

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.149010
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:               111268
Model:                          Logit   Df Residuals:                   111256
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.004012
Time:                        23:56:06   Log-Likelihood:                -16580.
converged:                      False   LL-Null:                       -16647.
Covariance Type:            nonrobust   LLR p-value:                 3.309e-23
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.3261      0.021   -161.589      0.000      -3.366      -3.286
AI ROLE                         -9.1384     80.612     -0.113      0.910    -167.135     148.858
Associate degree                -1.4273      0.451     -3.168      0.002      -2.310      -0.544
Bachelor's degree               -0.7427      0.218     -3.405      0.001      -1.170      -0.315
High school or GED              -0.3011      0.043     -7.062      0.000      -0.385      -0.218
Master's degree                 -1.4818      1.005     -1.475      0.140      -3.451       0.487
Ph.D. or professional degree     0.0979      0.722      0.136      0.892      -1.317       1.513
0 years                          0.3497      0.073      4.779      0.000       0.206       0.493
1-2 years                        0.2718      0.043      6.392      0.000       0.188       0.355
11-20 years                    -14.7975   1408.029     -0.011      0.992   -2774.485    2744.890
3-5 years                       -0.0058      0.094     -0.062      0.951      -0.190       0.178
6-10 years                      -0.2888      0.254     -1.135      0.257      -0.788       0.210
================================================================================================
Transportation and Material Moving Occupations 2023
df length: 110719

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
100%|██████████| 90/90 [01:13<00:00,  1.23it/s]

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.225641
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:       HEALTH_WELLBEING   No. Observations:               110719
Model:                          Logit   Df Residuals:                   110707
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01263
Time:                        23:56:07   Log-Likelihood:                -24983.
converged:                      False   LL-Null:                       -25302.
Covariance Type:            nonrobust   LLR p-value:                6.374e-130
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.8452      0.018   -161.639      0.000      -2.880      -2.811
AI ROLE                         -0.3162      0.466     -0.679      0.497      -1.229       0.596
Associate degree                 1.5341      0.073     20.905      0.000       1.390       1.678
Bachelor's degree                1.1529      0.070     16.447      0.000       1.016       1.290
High school or GED               0.3217      0.028     11.508      0.000       0.267       0.376
Master's degree                  0.1729      0.345      0.502      0.616      -0.503       0.849
Ph.D. or professional degree   -13.8892    740.411     -0.019      0.985   -1465.069    1437.290
0 years                         -0.3542      0.058     -6.096      0.000      -0.468      -0.240
1-2 years                       -0.1288      0.033     -3.921      0.000      -0.193      -0.064
11-20 years                      0.1327      0.377      0.352      0.725      -0.605       0.871
3-5 years                       -0.1787      0.062     -2.871      0.004      -0.301      -0.057
6-10 years                      -0.3159      0.164     -1.925      0.054      -0.638       0.006
================================================================================================
PARENTAL_LEAVE

  0%|          | 0/90 [00:00<?, ?it/s]

Architecture and Engineering Occupations 2019

  1%|          | 1/90 [00:00<00:56,  1.56it/s]

df length: 42432
Optimization terminated successfully.
         Current function value: 0.045532
         Iterations 9
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:                42432
Model:                          Logit   Df Residuals:                    42420
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.004666
Time:                        23:56:07   Log-Likelihood:                -1932.0
converged:                       True   LL-Null:                       -1941.1
Covariance Type:            nonrobust   LLR p-value:                   0.07894
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.9432      0.117    -42.174      0.000      -5.173      -4.713
AI ROLE                          0.9583      0.257      3.734      0.000       0.455       1.461
Associate degree                -0.0912      0.247     -0.369      0.712      -0.576       0.394
Bachelor's degree               -0.0269      0.140     -0.192      0.847      -0.301       0.247
High school or GED               0.0994      0.187      0.531      0.595      -0.267       0.466
Master's degree                  0.1874      0.342      0.549      0.583      -0.482       0.857
Ph.D. or professional degree     0.0829      0.595      0.139      0.889      -1.083       1.249
0 years                         -0.3168      0.422     -0.750      0.453      -1.145       0.511
1-2 years                        0.2860      0.167      1.713      0.087      -0.041       0.613
11-20 years                     -0.2772      0.462     -0.600      0.549      -1.183       0.629
3-5 years                        0.1345      0.142      0.948      0.343      -0.144       0.413
6-10 years                      -0.0347      0.186     -0.187      0.851      -0.398       0.329
================================================================================================
Architecture and Engineering Occupations 2021

  2%|▏         | 2/90 [00:01<00:55,  1.58it/s]

df length: 42098
Optimization terminated successfully.
         Current function value: 0.119681
         Iterations 9
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:                42098
Model:                          Logit   Df Residuals:                    42086
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.006821
Time:                        23:56:08   Log-Likelihood:                -5038.3
converged:                       True   LL-Null:                       -5072.9
Covariance Type:            nonrobust   LLR p-value:                 1.727e-10
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.0721      0.077    -52.741      0.000      -4.223      -3.921
AI ROLE                          0.2232      0.187      1.195      0.232      -0.143       0.589
Associate degree                 0.5035      0.132      3.816      0.000       0.245       0.762
Bachelor's degree                0.5361      0.089      6.005      0.000       0.361       0.711
High school or GED               0.6519      0.104      6.268      0.000       0.448       0.856
Master's degree                  0.7633      0.202      3.781      0.000       0.368       1.159
Ph.D. or professional degree    -0.9094      0.714     -1.274      0.203      -2.309       0.490
0 years                          0.1096      0.181      0.606      0.544      -0.245       0.464
1-2 years                        0.0420      0.095      0.443      0.658      -0.144       0.228
11-20 years                     -0.2144      0.224     -0.955      0.340      -0.654       0.226
3-5 years                        0.0436      0.079      0.550      0.583      -0.112       0.199
6-10 years                      -0.0741      0.103     -0.717      0.473      -0.277       0.128
================================================================================================
Architecture and Engineering Occupations 2022

  3%|▎         | 3/90 [00:01<00:56,  1.53it/s]

df length: 57103
Optimization terminated successfully.
         Current function value: 0.166477
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:                57103
Model:                          Logit   Df Residuals:                    57091
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.007050
Time:                        23:56:09   Log-Likelihood:                -9506.3
converged:                       True   LL-Null:                       -9573.8
Covariance Type:            nonrobust   LLR p-value:                 1.693e-23
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.6267      0.053    -68.622      0.000      -3.730      -3.523
AI ROLE                          0.2283      0.124      1.841      0.066      -0.015       0.471
Associate degree                 0.2774      0.099      2.815      0.005       0.084       0.471
Bachelor's degree                0.5269      0.061      8.609      0.000       0.407       0.647
High school or GED               0.5658      0.077      7.389      0.000       0.416       0.716
Master's degree                  0.2357      0.172      1.372      0.170      -0.101       0.572
Ph.D. or professional degree     0.2923      0.288      1.016      0.310      -0.272       0.856
0 years                         -0.0374      0.140     -0.267      0.790      -0.312       0.237
1-2 years                        0.1042      0.068      1.538      0.124      -0.029       0.237
11-20 years                     -0.3320      0.152     -2.186      0.029      -0.630      -0.034
3-5 years                        0.0852      0.057      1.498      0.134      -0.026       0.197
6-10 years                       0.1271      0.069      1.851      0.064      -0.007       0.262
================================================================================================
Architecture and Engineering Occupations 2020

  4%|▍         | 4/90 [00:02<00:54,  1.57it/s]

df length: 33522
Optimization terminated successfully.
         Current function value: 0.069186
         Iterations 9
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:                33522
Model:                          Logit   Df Residuals:                    33510
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01043
Time:                        23:56:09   Log-Likelihood:                -2319.2
converged:                       True   LL-Null:                       -2343.7
Covariance Type:            nonrobust   LLR p-value:                 9.835e-07
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.7130      0.114    -41.426      0.000      -4.936      -4.490
AI ROLE                         -0.0478      0.344     -0.139      0.890      -0.723       0.627
Associate degree                 0.6314      0.191      3.313      0.001       0.258       1.005
Bachelor's degree                0.2370      0.135      1.756      0.079      -0.027       0.501
High school or GED               0.7217      0.152      4.735      0.000       0.423       1.020
Master's degree                  1.1289      0.244      4.623      0.000       0.650       1.607
Ph.D. or professional degree     0.5404      0.518      1.043      0.297      -0.475       1.556
0 years                         -0.5220      0.420     -1.244      0.214      -1.345       0.301
1-2 years                        0.2955      0.142      2.088      0.037       0.018       0.573
11-20 years                      0.0698      0.319      0.219      0.827      -0.555       0.694
3-5 years                        0.0788      0.126      0.627      0.531      -0.168       0.325
6-10 years                       0.0386      0.161      0.239      0.811      -0.278       0.355
================================================================================================
Architecture and Engineering Occupations 2018

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
  6%|▌         | 5/90 [00:03<00:55,  1.53it/s]

df length: 40569
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.018609
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:                40569
Model:                          Logit   Df Residuals:                    40557
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02180
Time:                        23:56:10   Log-Likelihood:                -754.96
converged:                      False   LL-Null:                       -771.78
Covariance Type:            nonrobust   LLR p-value:                 0.0004130
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -6.6530      0.262    -25.353      0.000      -7.167      -6.139
AI ROLE                         -0.7399      1.009     -0.734      0.463      -2.717       1.237
Associate degree                 0.5500      0.462      1.190      0.234      -0.356       1.455
Bachelor's degree                0.8315      0.295      2.816      0.005       0.253       1.410
High school or GED               1.3083      0.335      3.900      0.000       0.651       1.966
Master's degree                  0.5357      0.756      0.709      0.478      -0.946       2.017
Ph.D. or professional degree     2.2589      0.634      3.563      0.000       1.016       3.502
0 years                         -1.0614      1.017     -1.044      0.297      -3.055       0.932
1-2 years                       -0.2588      0.332     -0.780      0.435      -0.909       0.392
11-20 years                    -14.0809    780.139     -0.018      0.986   -1543.125    1514.963
3-5 years                        0.1972      0.239      0.824      0.410      -0.272       0.666
6-10 years                       0.3442      0.288      1.193      0.233      -0.221       0.910
================================================================================================
Architecture and Engineering Occupations 2023

  7%|▋         | 6/90 [00:03<00:54,  1.55it/s]

df length: 46241
Optimization terminated successfully.
         Current function value: 0.244391
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:                46241
Model:                          Logit   Df Residuals:                    46229
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01529
Time:                        23:56:11   Log-Likelihood:                -11301.
converged:                       True   LL-Null:                       -11476.
Covariance Type:            nonrobust   LLR p-value:                 1.478e-68
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.2924      0.052    -63.844      0.000      -3.394      -3.191
AI ROLE                          0.2706      0.106      2.552      0.011       0.063       0.478
Associate degree                 0.3579      0.090      3.982      0.000       0.182       0.534
Bachelor's degree                0.7771      0.056     13.770      0.000       0.666       0.888
High school or GED               0.5242      0.073      7.165      0.000       0.381       0.668
Master's degree                  0.9052      0.130      6.950      0.000       0.650       1.160
Ph.D. or professional degree     0.5499      0.232      2.369      0.018       0.095       1.005
0 years                         -0.1835      0.124     -1.478      0.139      -0.427       0.060
1-2 years                        0.2709      0.059      4.626      0.000       0.156       0.386
11-20 years                      0.1685      0.104      1.625      0.104      -0.035       0.372
3-5 years                        0.0533      0.051      1.053      0.292      -0.046       0.152
6-10 years                       0.2480      0.058      4.276      0.000       0.134       0.362
================================================================================================
Arts, Design, Entertainment, Sports, and Media Occupations 2019

  8%|▊         | 7/90 [00:04<00:52,  1.58it/s]

df length: 40594
Optimization terminated successfully.
         Current function value: 0.056665
         Iterations 10
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:                40594
Model:                          Logit   Df Residuals:                    40582
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01408
Time:                        23:56:11   Log-Likelihood:                -2300.3
converged:                       True   LL-Null:                       -2333.1
Covariance Type:            nonrobust   LLR p-value:                 7.949e-10
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.7625      0.081    -58.595      0.000      -4.922      -4.603
AI ROLE                         -0.0970      0.508     -0.191      0.848      -1.092       0.898
Associate degree                 0.3312      0.259      1.279      0.201      -0.176       0.839
Bachelor's degree                0.2565      0.120      2.137      0.033       0.021       0.492
High school or GED              -0.4126      0.169     -2.438      0.015      -0.744      -0.081
Master's degree                 -0.3274      0.510     -0.643      0.521      -1.326       0.671
Ph.D. or professional degree     0.7805      0.589      1.324      0.185      -0.375       1.936
0 years                         -0.9250      0.585     -1.581      0.114      -2.072       0.222
1-2 years                        0.2105      0.142      1.483      0.138      -0.068       0.489
11-20 years                     -1.1240      1.005     -1.119      0.263      -3.093       0.845
3-5 years                        0.5536      0.129      4.303      0.000       0.301       0.806
6-10 years                       0.3531      0.217      1.630      0.103      -0.071       0.778
================================================================================================
Arts, Design, Entertainment, Sports, and Media Occupations 2021

  9%|▉         | 8/90 [00:05<00:52,  1.56it/s]

df length: 49779
Optimization terminated successfully.
         Current function value: 0.108841
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:                49779
Model:                          Logit   Df Residuals:                    49767
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01816
Time:                        23:56:12   Log-Likelihood:                -5418.0
converged:                       True   LL-Null:                       -5518.2
Covariance Type:            nonrobust   LLR p-value:                 5.983e-37
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.0762      0.051    -79.673      0.000      -4.176      -3.976
AI ROLE                          0.5067      0.233      2.172      0.030       0.050       0.964
Associate degree                 0.3020      0.161      1.877      0.061      -0.013       0.617
Bachelor's degree                0.2758      0.076      3.639      0.000       0.127       0.424
High school or GED              -0.1179      0.087     -1.359      0.174      -0.288       0.052
Master's degree                 -0.2900      0.362     -0.800      0.423      -1.000       0.420
Ph.D. or professional degree    -0.4450      0.715     -0.622      0.534      -1.847       0.957
0 years                          0.0993      0.197      0.503      0.615      -0.288       0.486
1-2 years                        0.4244      0.083      5.084      0.000       0.261       0.588
11-20 years                      1.0591      0.292      3.628      0.000       0.487       1.631
3-5 years                        0.7355      0.082      8.949      0.000       0.574       0.897
6-10 years                       0.6679      0.129      5.184      0.000       0.415       0.920
================================================================================================
Arts, Design, Entertainment, Sports, and Media Occupations 2022

 10%|█         | 9/90 [00:05<00:52,  1.55it/s]

df length: 54182
Optimization terminated successfully.
         Current function value: 0.128666
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:                54182
Model:                          Logit   Df Residuals:                    54170
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02864
Time:                        23:56:12   Log-Likelihood:                -6971.4
converged:                       True   LL-Null:                       -7176.9
Covariance Type:            nonrobust   LLR p-value:                 2.658e-81
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.9410      0.044    -89.260      0.000      -4.028      -3.854
AI ROLE                          0.4747      0.184      2.579      0.010       0.114       0.835
Associate degree                -0.1538      0.150     -1.023      0.306      -0.449       0.141
Bachelor's degree                0.0750      0.065      1.150      0.250      -0.053       0.203
High school or GED              -0.0631      0.080     -0.791      0.429      -0.220       0.093
Master's degree                 -0.0460      0.260     -0.177      0.860      -0.556       0.464
Ph.D. or professional degree     0.6500      0.350      1.855      0.064      -0.037       1.337
0 years                         -0.4660      0.223     -2.087      0.037      -0.904      -0.028
1-2 years                        0.6557      0.075      8.706      0.000       0.508       0.803
11-20 years                      0.6759      0.300      2.255      0.024       0.088       1.264
3-5 years                        1.0594      0.069     15.317      0.000       0.924       1.195
6-10 years                       1.0811      0.101     10.674      0.000       0.883       1.280
================================================================================================
Arts, Design, Entertainment, Sports, and Media Occupations 2020

 11%|█         | 10/90 [00:06<00:50,  1.58it/s]

df length: 39617
Optimization terminated successfully.
         Current function value: 0.064381
         Iterations 9
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:                39617
Model:                          Logit   Df Residuals:                    39605
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02553
Time:                        23:56:13   Log-Likelihood:                -2550.6
converged:                       True   LL-Null:                       -2617.4
Covariance Type:            nonrobust   LLR p-value:                 3.186e-23
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.6449      0.077    -60.075      0.000      -4.796      -4.493
AI ROLE                          0.5130      0.389      1.317      0.188      -0.250       1.276
Associate degree                -0.1067      0.302     -0.354      0.724      -0.698       0.485
Bachelor's degree                0.1911      0.116      1.644      0.100      -0.037       0.419
High school or GED              -0.4490      0.138     -3.251      0.001      -0.720      -0.178
Master's degree                 -1.1314      0.715     -1.583      0.114      -2.533       0.270
Ph.D. or professional degree     0.0591      0.721      0.082      0.935      -1.354       1.472
0 years                         -0.2579      0.329     -0.785      0.432      -0.902       0.386
1-2 years                        0.4778      0.132      3.625      0.000       0.219       0.736
11-20 years                      1.5236      0.375      4.064      0.000       0.789       2.258
3-5 years                        0.7454      0.129      5.783      0.000       0.493       0.998
6-10 years                       1.0727      0.176      6.079      0.000       0.727       1.419
================================================================================================
Arts, Design, Entertainment, Sports, and Media Occupations 2018

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/discrete/discrete_model.py:2385: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/discrete/discrete_model.py:2443: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q * linpred)))
 12%|█▏        | 11/90 [00:07<00:49,  1.59it/s]

df length: 37105
Warning: Maximum number of iterations has been exceeded.
         Current function value: inf
         Iterations: 35
Singular matrix
Arts, Design, Entertainment, Sports, and Media Occupations 2023

 13%|█▎        | 12/90 [00:07<00:47,  1.64it/s]

df length: 40306
Optimization terminated successfully.
         Current function value: 0.175206
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:                40306
Model:                          Logit   Df Residuals:                    40294
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.04815
Time:                        23:56:14   Log-Likelihood:                -7061.9
converged:                       True   LL-Null:                       -7419.1
Covariance Type:            nonrobust   LLR p-value:                4.331e-146
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.7307      0.044    -84.282      0.000      -3.817      -3.644
AI ROLE                          0.2864      0.167      1.715      0.086      -0.041       0.614
Associate degree                 0.6684      0.117      5.705      0.000       0.439       0.898
Bachelor's degree                0.6551      0.062     10.539      0.000       0.533       0.777
High school or GED               0.1510      0.078      1.927      0.054      -0.003       0.304
Master's degree                 -0.0647      0.288     -0.224      0.823      -0.630       0.501
Ph.D. or professional degree     0.9667      0.309      3.130      0.002       0.361       1.572
0 years                          0.5072      0.139      3.648      0.000       0.235       0.780
1-2 years                        0.6970      0.070      9.914      0.000       0.559       0.835
11-20 years                      1.2586      0.208      6.041      0.000       0.850       1.667
3-5 years                        0.8777      0.068     12.852      0.000       0.744       1.012
6-10 years                       1.1173      0.092     12.198      0.000       0.938       1.297
================================================================================================
Business and Financial Operations Occupations 2019
df length: 141921
Optimization terminated successfully.
         Current function value: 0.066374
         Iterations 9

 14%|█▍        | 13/90 [00:08<00:55,  1.39it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:               141921
Model:                          Logit   Df Residuals:                   141909
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.008145
Time:                        23:56:15   Log-Likelihood:                -9419.9
converged:                       True   LL-Null:                       -9497.2
Covariance Type:            nonrobust   LLR p-value:                 1.623e-27
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.7128      0.054    -87.661      0.000      -4.818      -4.607
AI ROLE                          0.2962      0.167      1.778      0.075      -0.030       0.623
Associate degree                 0.1572      0.138      1.142      0.253      -0.113       0.427
Bachelor's degree                0.4703      0.062      7.581      0.000       0.349       0.592
High school or GED               0.0838      0.093      0.898      0.369      -0.099       0.267
Master's degree                  0.4038      0.189      2.132      0.033       0.033       0.775
Ph.D. or professional degree    -0.7095      0.711     -0.998      0.318      -2.103       0.684
0 years                         -0.3325      0.223     -1.489      0.137      -0.770       0.105
1-2 years                        0.3558      0.064      5.555      0.000       0.230       0.481
11-20 years                     -0.2837      0.273     -1.040      0.298      -0.818       0.251
3-5 years                       -0.0056      0.064     -0.089      0.929      -0.130       0.119
6-10 years                      -0.3518      0.102     -3.463      0.001      -0.551      -0.153
================================================================================================
Business and Financial Operations Occupations 2021
df length: 158377
Optimization terminated successfully.
         Current function value: 0.143736
         Iterations 8

 16%|█▌        | 14/90 [00:09<01:00,  1.25it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:               158377
Model:                          Logit   Df Residuals:                   158365
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.009379
Time:                        23:56:16   Log-Likelihood:                -22764.
converged:                       True   LL-Null:                       -22980.
Covariance Type:            nonrobust   LLR p-value:                 1.556e-85
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.8206      0.034   -113.961      0.000      -3.886      -3.755
AI ROLE                          0.8245      0.071     11.677      0.000       0.686       0.963
Associate degree                 0.4177      0.070      5.942      0.000       0.280       0.555
Bachelor's degree                0.4022      0.037     10.858      0.000       0.330       0.475
High school or GED               0.1699      0.051      3.358      0.001       0.071       0.269
Master's degree                  0.3395      0.120      2.836      0.005       0.105       0.574
Ph.D. or professional degree     0.1422      0.256      0.556      0.578      -0.359       0.643
0 years                          0.0384      0.118      0.325      0.745      -0.193       0.270
1-2 years                        0.3199      0.039      8.157      0.000       0.243       0.397
11-20 years                      0.0099      0.151      0.066      0.948      -0.286       0.306
3-5 years                        0.2517      0.037      6.831      0.000       0.180       0.324
6-10 years                      -0.0474      0.057     -0.834      0.405      -0.159       0.064
================================================================================================
Business and Financial Operations Occupations 2022
df length: 182061
Optimization terminated successfully.
         Current function value: 0.202292
         Iterations 8

 17%|█▋        | 15/90 [00:10<01:06,  1.13it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:               182061
Model:                          Logit   Df Residuals:                   182049
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01012
Time:                        23:56:17   Log-Likelihood:                -36829.
converged:                       True   LL-Null:                       -37206.
Covariance Type:            nonrobust   LLR p-value:                2.409e-154
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.4100      0.026   -133.544      0.000      -3.460      -3.360
AI ROLE                          0.3528      0.062      5.726      0.000       0.232       0.474
Associate degree                 0.3502      0.055      6.334      0.000       0.242       0.459
Bachelor's degree                0.4358      0.029     15.104      0.000       0.379       0.492
High school or GED               0.3414      0.039      8.837      0.000       0.266       0.417
Master's degree                  0.4315      0.089      4.832      0.000       0.256       0.606
Ph.D. or professional degree    -0.7508      0.281     -2.673      0.008      -1.301      -0.200
0 years                         -0.2125      0.096     -2.215      0.027      -0.400      -0.024
1-2 years                        0.2142      0.031      6.824      0.000       0.153       0.276
11-20 years                     -0.0110      0.109     -0.101      0.919      -0.225       0.203
3-5 years                        0.3728      0.028     13.245      0.000       0.318       0.428
6-10 years                       0.2127      0.040      5.375      0.000       0.135       0.290
================================================================================================
Business and Financial Operations Occupations 2020
df length: 125072
Optimization terminated successfully.
         Current function value: 0.087757
         Iterations 9

 18%|█▊        | 16/90 [00:11<01:06,  1.12it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:               125072
Model:                          Logit   Df Residuals:                   125060
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.009166
Time:                        23:56:18   Log-Likelihood:                -10976.
converged:                       True   LL-Null:                       -11078.
Covariance Type:            nonrobust   LLR p-value:                 1.710e-37
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.3918      0.048    -91.471      0.000      -4.486      -4.298
AI ROLE                          0.4573      0.136      3.362      0.001       0.191       0.724
Associate degree                 0.3751      0.116      3.236      0.001       0.148       0.602
Bachelor's degree                0.5321      0.055      9.685      0.000       0.424       0.640
High school or GED               0.0781      0.084      0.933      0.351      -0.086       0.242
Master's degree                  0.3351      0.185      1.811      0.070      -0.028       0.698
Ph.D. or professional degree    -0.2169      0.505     -0.430      0.667      -1.206       0.773
0 years                          0.0432      0.151      0.286      0.775      -0.254       0.340
1-2 years                        0.2210      0.060      3.697      0.000       0.104       0.338
11-20 years                     -0.5236      0.272     -1.923      0.054      -1.057       0.010
3-5 years                        0.0981      0.055      1.778      0.075      -0.010       0.206
6-10 years                      -0.4649      0.095     -4.884      0.000      -0.651      -0.278
================================================================================================
Business and Financial Operations Occupations 2018
df length: 139740
Optimization terminated successfully.
         Current function value: 0.034809
         Iterations 10

 19%|█▉        | 17/90 [00:12<01:06,  1.10it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:               139740
Model:                          Logit   Df Residuals:                   139728
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.008799
Time:                        23:56:19   Log-Likelihood:                -4864.2
converged:                       True   LL-Null:                       -4907.4
Covariance Type:            nonrobust   LLR p-value:                 8.573e-14
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -5.5298      0.082    -67.657      0.000      -5.690      -5.370
AI ROLE                         -0.0875      0.293     -0.299      0.765      -0.661       0.486
Associate degree                 0.3251      0.201      1.616      0.106      -0.069       0.719
Bachelor's degree                0.5803      0.094      6.149      0.000       0.395       0.765
High school or GED              -0.1243      0.159     -0.783      0.433      -0.435       0.187
Master's degree                  0.1694      0.328      0.517      0.605      -0.473       0.812
Ph.D. or professional degree     0.6642      0.585      1.135      0.257      -0.483       1.811
0 years                         -0.3171      0.360     -0.880      0.379      -1.023       0.389
1-2 years                        0.2062      0.100      2.068      0.039       0.011       0.402
11-20 years                     -0.5893      0.454     -1.299      0.194      -1.478       0.300
3-5 years                        0.0643      0.092      0.702      0.482      -0.115       0.244
6-10 years                      -0.4826      0.152     -3.171      0.002      -0.781      -0.184
================================================================================================
Business and Financial Operations Occupations 2023
df length: 124651
Optimization terminated successfully.
         Current function value: 0.260142
         Iterations 7

 20%|██        | 18/90 [00:13<01:05,  1.10it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:               124651
Model:                          Logit   Df Residuals:                   124639
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01973
Time:                        23:56:20   Log-Likelihood:                -32427.
converged:                       True   LL-Null:                       -33080.
Covariance Type:            nonrobust   LLR p-value:                2.749e-273
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.2331      0.028   -116.416      0.000      -3.288      -3.179
AI ROLE                          0.3969      0.064      6.156      0.000       0.271       0.523
Associate degree                 0.5286      0.056      9.436      0.000       0.419       0.638
Bachelor's degree                0.6394      0.031     20.824      0.000       0.579       0.700
High school or GED               0.3134      0.042      7.542      0.000       0.232       0.395
Master's degree                  0.5757      0.088      6.523      0.000       0.403       0.749
Ph.D. or professional degree    -0.2087      0.224     -0.931      0.352      -0.648       0.231
0 years                          0.0815      0.090      0.905      0.365      -0.095       0.258
1-2 years                        0.3005      0.033      9.055      0.000       0.235       0.365
11-20 years                      0.5705      0.084      6.799      0.000       0.406       0.735
3-5 years                        0.3945      0.030     13.163      0.000       0.336       0.453
6-10 years                       0.5305      0.038     14.144      0.000       0.457       0.604
================================================================================================
Community and Social Service Occupations 2019

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
 21%|██        | 19/90 [00:14<00:58,  1.21it/s]

df length: 30528
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.126411
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:                30528
Model:                          Logit   Df Residuals:                    30516
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01134
Time:                        23:56:21   Log-Likelihood:                -3859.1
converged:                      False   LL-Null:                       -3903.3
Covariance Type:            nonrobust   LLR p-value:                 3.226e-14
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.0892      0.093    -44.191      0.000      -4.271      -3.908
AI ROLE                         -0.6989      1.010     -0.692      0.489      -2.679       1.281
Associate degree                 0.5831      0.172      3.396      0.001       0.247       0.920
Bachelor's degree                0.8729      0.111      7.870      0.000       0.656       1.090
High school or GED               0.4814      0.121      3.979      0.000       0.244       0.719
Master's degree                  0.5813      0.123      4.735      0.000       0.341       0.822
Ph.D. or professional degree     1.0042      0.353      2.843      0.004       0.312       1.697
0 years                         -0.5604      0.324     -1.731      0.083      -1.195       0.074
1-2 years                       -0.0062      0.082     -0.076      0.940      -0.166       0.154
11-20 years                    -27.1399   6.41e+05  -4.24e-05      1.000   -1.26e+06    1.26e+06
3-5 years                        0.0793      0.098      0.806      0.421      -0.114       0.272
6-10 years                      -0.4914      0.325     -1.511      0.131      -1.129       0.146
================================================================================================
Community and Social Service Occupations 2021

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/discrete/discrete_model.py:2385: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
 22%|██▏       | 20/90 [00:14<00:53,  1.32it/s]

df length: 39363
Optimization terminated successfully.
         Current function value: 0.185121
         Iterations 21
Singular matrix
Community and Social Service Occupations 2022

 23%|██▎       | 21/90 [00:15<00:49,  1.39it/s]

df length: 46564
Optimization terminated successfully.
         Current function value: 0.216124
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:                46564
Model:                          Logit   Df Residuals:                    46552
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.008147
Time:                        23:56:22   Log-Likelihood:                -10064.
converged:                       True   LL-Null:                       -10146.
Covariance Type:            nonrobust   LLR p-value:                 1.080e-29
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.0793      0.046    -66.990      0.000      -3.169      -2.989
AI ROLE                          0.0334      0.392      0.085      0.932      -0.734       0.801
Associate degree                 0.4293      0.088      4.878      0.000       0.257       0.602
Bachelor's degree                0.4561      0.059      7.667      0.000       0.339       0.573
High school or GED               0.2744      0.063      4.378      0.000       0.152       0.397
Master's degree                  0.0738      0.069      1.068      0.286      -0.062       0.209
Ph.D. or professional degree    -1.2667      0.322     -3.940      0.000      -1.897      -0.637
0 years                         -0.3946      0.143     -2.756      0.006      -0.675      -0.114
1-2 years                        0.0489      0.048      1.024      0.306      -0.045       0.142
11-20 years                      0.5261      0.399      1.317      0.188      -0.257       1.309
3-5 years                        0.1956      0.059      3.315      0.001       0.080       0.311
6-10 years                       0.1034      0.162      0.639      0.523      -0.214       0.420
================================================================================================
Community and Social Service Occupations 2020

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
 24%|██▍       | 22/90 [00:15<00:47,  1.44it/s]

df length: 30962
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.153015
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:                30962
Model:                          Logit   Df Residuals:                    30950
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01853
Time:                        23:56:23   Log-Likelihood:                -4737.7
converged:                      False   LL-Null:                       -4827.1
Covariance Type:            nonrobust   LLR p-value:                 1.753e-32
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.9668      0.087    -45.663      0.000      -4.137      -3.797
AI ROLE                         -0.6314      1.013     -0.623      0.533      -2.616       1.354
Associate degree                 0.8378      0.152      5.524      0.000       0.541       1.135
Bachelor's degree                1.1286      0.103     10.990      0.000       0.927       1.330
High school or GED               0.6497      0.110      5.888      0.000       0.433       0.866
Master's degree                  0.9817      0.109      9.021      0.000       0.768       1.195
Ph.D. or professional degree   -15.2315    889.118     -0.017      0.986   -1757.871    1727.408
0 years                         -0.1577      0.232     -0.679      0.497      -0.613       0.298
1-2 years                       -0.1710      0.071     -2.391      0.017      -0.311      -0.031
11-20 years                     -2.2526      2.344     -0.961      0.337      -6.847       2.341
3-5 years                       -0.0877      0.090     -0.972      0.331      -0.265       0.089
6-10 years                      -0.0561      0.247     -0.227      0.820      -0.540       0.428
================================================================================================
Community and Social Service Occupations 2018

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
 26%|██▌       | 23/90 [00:16<00:44,  1.50it/s]

df length: 25206
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.115875
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:                25206
Model:                          Logit   Df Residuals:                    25194
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01839
Time:                        23:56:23   Log-Likelihood:                -2920.7
converged:                      False   LL-Null:                       -2975.5
Covariance Type:            nonrobust   LLR p-value:                 2.376e-18
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.4516      0.115    -38.607      0.000      -4.678      -4.226
AI ROLE                          0.5882      0.729      0.807      0.420      -0.840       2.017
Associate degree                 0.8832      0.188      4.708      0.000       0.516       1.251
Bachelor's degree                0.9112      0.136      6.681      0.000       0.644       1.178
High school or GED               0.5642      0.152      3.721      0.000       0.267       0.861
Master's degree                  0.9024      0.143      6.318      0.000       0.622       1.182
Ph.D. or professional degree     0.9475      0.470      2.015      0.044       0.026       1.869
0 years                         -0.1098      0.364     -0.302      0.763      -0.822       0.603
1-2 years                        0.2496      0.094      2.644      0.008       0.065       0.435
11-20 years                    -19.5765   1.62e+04     -0.001      0.999   -3.17e+04    3.17e+04
3-5 years                        0.3072      0.112      2.743      0.006       0.088       0.527
6-10 years                      -1.5893      0.713     -2.228      0.026      -2.987      -0.191
================================================================================================
Community and Social Service Occupations 2023

 27%|██▋       | 24/90 [00:17<00:43,  1.53it/s]

df length: 43218
Optimization terminated successfully.
         Current function value: 0.258817
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:                43218
Model:                          Logit   Df Residuals:                    43206
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.008297
Time:                        23:56:24   Log-Likelihood:                -11186.
converged:                       True   LL-Null:                       -11279.
Covariance Type:            nonrobust   LLR p-value:                 3.378e-34
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.5345      0.039    -64.978      0.000      -2.611      -2.458
AI ROLE                          0.0021      0.396      0.005      0.996      -0.774       0.778
Associate degree                 0.1586      0.082      1.937      0.053      -0.002       0.319
Bachelor's degree                0.1817      0.053      3.401      0.001       0.077       0.286
High school or GED              -0.2381      0.060     -3.985      0.000      -0.355      -0.121
Master's degree                 -0.0217      0.058     -0.375      0.708      -0.135       0.092
Ph.D. or professional degree    -1.3262      0.202     -6.570      0.000      -1.722      -0.931
0 years                         -0.5874      0.164     -3.583      0.000      -0.909      -0.266
1-2 years                       -0.0760      0.045     -1.697      0.090      -0.164       0.012
11-20 years                      0.0258      0.426      0.061      0.952      -0.809       0.861
3-5 years                        0.2202      0.054      4.047      0.000       0.114       0.327
6-10 years                       0.0313      0.157      0.199      0.842      -0.277       0.339
================================================================================================
Computer and Mathematical Occupations 2019
df length: 187188
Optimization terminated successfully.
         Current function value: 0.053149
         Iterations 9

 28%|██▊       | 25/90 [00:18<00:50,  1.30it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:               187188
Model:                          Logit   Df Residuals:                   187176
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.008129
Time:                        23:56:25   Log-Likelihood:                -9948.9
converged:                       True   LL-Null:                       -10030.
Covariance Type:            nonrobust   LLR p-value:                 3.135e-29
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.8407      0.046   -105.334      0.000      -4.931      -4.751
AI ROLE                          0.6412      0.072      8.919      0.000       0.500       0.782
Associate degree                 0.1414      0.137      1.034      0.301      -0.127       0.409
Bachelor's degree                0.2606      0.055      4.747      0.000       0.153       0.368
High school or GED               0.0169      0.125      0.135      0.892      -0.228       0.262
Master's degree                  0.2645      0.153      1.733      0.083      -0.035       0.564
Ph.D. or professional degree     0.7916      0.258      3.067      0.002       0.286       1.297
0 years                         -0.8042      0.255     -3.156      0.002      -1.304      -0.305
1-2 years                        0.1980      0.078      2.553      0.011       0.046       0.350
11-20 years                     -0.1640      0.189     -0.866      0.387      -0.535       0.207
3-5 years                        0.0625      0.060      1.038      0.299      -0.055       0.180
6-10 years                      -0.3281      0.079     -4.141      0.000      -0.483      -0.173
================================================================================================
Computer and Mathematical Occupations 2021
df length: 175692
Optimization terminated successfully.
         Current function value: 0.148456
         Iterations 9

 29%|██▉       | 26/90 [00:19<00:54,  1.18it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:               175692
Model:                          Logit   Df Residuals:                   175680
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.009088
Time:                        23:56:26   Log-Likelihood:                -26083.
converged:                       True   LL-Null:                       -26322.
Covariance Type:            nonrobust   LLR p-value:                 1.267e-95
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.6416      0.028   -129.992      0.000      -3.696      -3.587
AI ROLE                          0.5202      0.039     13.508      0.000       0.445       0.596
Associate degree                -0.0760      0.076     -1.005      0.315      -0.224       0.072
Bachelor's degree                0.1546      0.031      4.981      0.000       0.094       0.215
High school or GED               0.3687      0.055      6.726      0.000       0.261       0.476
Master's degree                 -0.1142      0.092     -1.240      0.215      -0.295       0.066
Ph.D. or professional degree     0.0292      0.198      0.147      0.883      -0.360       0.418
0 years                         -0.9710      0.173     -5.610      0.000      -1.310      -0.632
1-2 years                        0.3542      0.043      8.147      0.000       0.269       0.439
11-20 years                     -0.1367      0.102     -1.339      0.181      -0.337       0.063
3-5 years                        0.2957      0.034      8.596      0.000       0.228       0.363
6-10 years                       0.0759      0.042      1.826      0.068      -0.006       0.157
================================================================================================
Computer and Mathematical Occupations 2022
df length: 203321
Optimization terminated successfully.
         Current function value: 0.206088
         Iterations 7

 30%|███       | 27/90 [00:20<00:57,  1.10it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:               203321
Model:                          Logit   Df Residuals:                   203309
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.009626
Time:                        23:56:27   Log-Likelihood:                -41902.
converged:                       True   LL-Null:                       -42309.
Covariance Type:            nonrobust   LLR p-value:                1.410e-167
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.2191      0.022   -148.617      0.000      -3.262      -3.177
AI ROLE                          0.5058      0.029     17.737      0.000       0.450       0.562
Associate degree                -0.4447      0.066     -6.742      0.000      -0.574      -0.315
Bachelor's degree                0.1479      0.024      6.257      0.000       0.102       0.194
High school or GED               0.1482      0.044      3.390      0.001       0.063       0.234
Master's degree                 -0.0568      0.067     -0.849      0.396      -0.188       0.074
Ph.D. or professional degree    -0.3515      0.177     -1.990      0.047      -0.698      -0.005
0 years                         -0.2663      0.114     -2.337      0.019      -0.490      -0.043
1-2 years                        0.2769      0.035      8.011      0.000       0.209       0.345
11-20 years                      0.0272      0.071      0.381      0.703      -0.113       0.167
3-5 years                        0.3856      0.027     14.544      0.000       0.334       0.438
6-10 years                       0.2066      0.031      6.651      0.000       0.146       0.268
================================================================================================
Computer and Mathematical Occupations 2020
df length: 157708
Optimization terminated successfully.
         Current function value: 0.072527
         Iterations 9

 31%|███       | 28/90 [00:21<00:57,  1.07it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:               157708
Model:                          Logit   Df Residuals:                   157696
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.007812
Time:                        23:56:28   Log-Likelihood:                -11438.
converged:                       True   LL-Null:                       -11528.
Covariance Type:            nonrobust   LLR p-value:                 9.648e-33
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.5628      0.043   -104.996      0.000      -4.648      -4.478
AI ROLE                          0.3966      0.069      5.784      0.000       0.262       0.531
Associate degree                 0.1264      0.125      1.010      0.313      -0.119       0.372
Bachelor's degree                0.3653      0.051      7.214      0.000       0.266       0.464
High school or GED               0.3150      0.099      3.182      0.001       0.121       0.509
Master's degree                  0.4524      0.128      3.533      0.000       0.201       0.703
Ph.D. or professional degree    -0.1396      0.383     -0.365      0.715      -0.890       0.611
0 years                         -0.5573      0.235     -2.376      0.017      -1.017      -0.098
1-2 years                        0.3828      0.069      5.568      0.000       0.248       0.518
11-20 years                     -0.0857      0.160     -0.537      0.591      -0.398       0.227
3-5 years                        0.1064      0.056      1.900      0.057      -0.003       0.216
6-10 years                      -0.1801      0.069     -2.595      0.009      -0.316      -0.044
================================================================================================
Computer and Mathematical Occupations 2018
df length: 178714
Optimization terminated successfully.
         Current function value: 0.032648
         Iterations 10

 32%|███▏      | 29/90 [00:22<00:58,  1.04it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:               178714
Model:                          Logit   Df Residuals:                   178702
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.007855
Time:                        23:56:29   Log-Likelihood:                -5834.6
converged:                       True   LL-Null:                       -5880.8
Covariance Type:            nonrobust   LLR p-value:                 5.663e-15
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -5.5321      0.066    -84.434      0.000      -5.661      -5.404
AI ROLE                          0.5088      0.108      4.698      0.000       0.297       0.721
Associate degree                -0.0170      0.204     -0.084      0.933      -0.416       0.382
Bachelor's degree                0.3962      0.076      5.195      0.000       0.247       0.546
High school or GED              -0.1243      0.183     -0.678      0.498      -0.484       0.235
Master's degree                  0.1847      0.222      0.833      0.405      -0.250       0.619
Ph.D. or professional degree     0.5393      0.417      1.292      0.196      -0.279       1.357
0 years                          0.1037      0.324      0.320      0.749      -0.532       0.739
1-2 years                        0.4240      0.102      4.171      0.000       0.225       0.623
11-20 years                     -0.4472      0.309     -1.447      0.148      -1.053       0.159
3-5 years                        0.0542      0.085      0.639      0.523      -0.112       0.221
6-10 years                      -0.1871      0.106     -1.759      0.079      -0.396       0.021
================================================================================================
Computer and Mathematical Occupations 2023
df length: 127390
Optimization terminated successfully.
         Current function value: 0.290347
         Iterations 7

 33%|███▎      | 30/90 [00:23<00:55,  1.08it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:               127390
Model:                          Logit   Df Residuals:                   127378
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02033
Time:                        23:56:30   Log-Likelihood:                -36987.
converged:                       True   LL-Null:                       -37755.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.0005      0.025   -122.184      0.000      -3.049      -2.952
AI ROLE                          0.5139      0.029     17.511      0.000       0.456       0.571
Associate degree                 0.1301      0.056      2.325      0.020       0.020       0.240
Bachelor's degree                0.5588      0.026     21.837      0.000       0.509       0.609
High school or GED               0.2011      0.046      4.329      0.000       0.110       0.292
Master's degree                  0.3787      0.067      5.687      0.000       0.248       0.509
Ph.D. or professional degree     0.2054      0.156      1.314      0.189      -0.101       0.512
0 years                         -0.0411      0.108     -0.380      0.704      -0.253       0.171
1-2 years                        0.2865      0.036      7.875      0.000       0.215       0.358
11-20 years                      0.1231      0.063      1.948      0.051      -0.001       0.247
3-5 years                        0.3343      0.028     11.875      0.000       0.279       0.390
6-10 years                       0.4104      0.030     13.557      0.000       0.351       0.470
================================================================================================
Educational Instruction and Library Occupations 2019

 34%|███▍      | 31/90 [00:23<00:49,  1.19it/s]

df length: 45660
Optimization terminated successfully.
         Current function value: 0.054882
         Iterations 9
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:                45660
Model:                          Logit   Df Residuals:                    45648
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02420
Time:                        23:56:30   Log-Likelihood:                -2505.9
converged:                       True   LL-Null:                       -2568.1
Covariance Type:            nonrobust   LLR p-value:                 2.458e-21
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -5.3350      0.113    -47.031      0.000      -5.557      -5.113
AI ROLE                         -0.7227      1.005     -0.719      0.472      -2.693       1.248
Associate degree                 1.2679      0.173      7.337      0.000       0.929       1.607
Bachelor's degree                0.9912      0.136      7.286      0.000       0.725       1.258
High school or GED               0.9061      0.155      5.863      0.000       0.603       1.209
Master's degree                  0.0214      0.253      0.085      0.932      -0.474       0.516
Ph.D. or professional degree     0.1181      0.353      0.334      0.738      -0.574       0.810
0 years                         -0.2969      0.415     -0.716      0.474      -1.109       0.516
1-2 years                        0.3091      0.116      2.657      0.008       0.081       0.537
11-20 years                      0.5089      1.012      0.503      0.615      -1.474       2.492
3-5 years                        0.3118      0.153      2.032      0.042       0.011       0.613
6-10 years                      -0.2746      0.454     -0.604      0.546      -1.165       0.616
================================================================================================
Educational Instruction and Library Occupations 2021

 36%|███▌      | 32/90 [00:24<00:45,  1.28it/s]

df length: 54703
Optimization terminated successfully.
         Current function value: 0.093771
         Iterations 9
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:                54703
Model:                          Logit   Df Residuals:                    54691
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02649
Time:                        23:56:31   Log-Likelihood:                -5129.6
converged:                       True   LL-Null:                       -5269.1
Covariance Type:            nonrobust   LLR p-value:                 2.164e-53
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.7666      0.080    -59.538      0.000      -4.924      -4.610
AI ROLE                         -0.2154      0.507     -0.425      0.671      -1.209       0.778
Associate degree                 1.0185      0.129      7.907      0.000       0.766       1.271
Bachelor's degree                1.0923      0.097     11.227      0.000       0.902       1.283
High school or GED               1.3150      0.096     13.664      0.000       1.126       1.504
Master's degree                  0.3799      0.173      2.202      0.028       0.042       0.718
Ph.D. or professional degree     0.4240      0.251      1.690      0.091      -0.068       0.916
0 years                         -0.4160      0.235     -1.772      0.076      -0.876       0.044
1-2 years                        0.1908      0.081      2.357      0.018       0.032       0.349
11-20 years                     -0.6530      1.007     -0.649      0.517      -2.626       1.320
3-5 years                       -0.0747      0.117     -0.637      0.524      -0.304       0.155
6-10 years                       0.1532      0.243      0.631      0.528      -0.322       0.629
================================================================================================
Educational Instruction and Library Occupations 2022

 37%|███▋      | 33/90 [00:25<00:42,  1.34it/s]

df length: 62895
Optimization terminated successfully.
         Current function value: 0.118781
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:                62895
Model:                          Logit   Df Residuals:                    62883
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01877
Time:                        23:56:32   Log-Likelihood:                -7470.7
converged:                       True   LL-Null:                       -7613.6
Covariance Type:            nonrobust   LLR p-value:                 8.584e-55
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.1774      0.058    -71.761      0.000      -4.291      -4.063
AI ROLE                          0.2383      0.296      0.804      0.421      -0.343       0.819
Associate degree                 0.6670      0.104      6.427      0.000       0.464       0.870
Bachelor's degree                0.7353      0.072     10.153      0.000       0.593       0.877
High school or GED               0.9211      0.075     12.296      0.000       0.774       1.068
Master's degree                  0.0989      0.123      0.803      0.422      -0.143       0.340
Ph.D. or professional degree     0.0691      0.183      0.378      0.706      -0.289       0.428
0 years                         -0.7110      0.140     -5.087      0.000      -0.985      -0.437
1-2 years                        0.2366      0.064      3.684      0.000       0.111       0.362
11-20 years                     -0.2081      0.585     -0.355      0.722      -1.355       0.939
3-5 years                        0.1721      0.086      1.992      0.046       0.003       0.341
6-10 years                       0.3200      0.182      1.763      0.078      -0.036       0.676
================================================================================================
Educational Instruction and Library Occupations 2020

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
 38%|███▊      | 34/90 [00:25<00:40,  1.38it/s]

df length: 42631
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.065520
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:                42631
Model:                          Logit   Df Residuals:                    42619
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01762
Time:                        23:56:32   Log-Likelihood:                -2793.2
converged:                      False   LL-Null:                       -2843.3
Covariance Type:            nonrobust   LLR p-value:                 1.631e-16
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.8077      0.090    -53.350      0.000      -4.984      -4.631
AI ROLE                         -8.2416     49.036     -0.168      0.867    -104.350      87.866
Associate degree                 0.6921      0.161      4.298      0.000       0.376       1.008
Bachelor's degree                0.6347      0.118      5.382      0.000       0.404       0.866
High school or GED               0.7225      0.128      5.641      0.000       0.471       0.973
Master's degree                 -0.1769      0.233     -0.758      0.448      -0.634       0.280
Ph.D. or professional degree    -1.6771      0.713     -2.351      0.019      -3.075      -0.279
0 years                         -0.6561      0.453     -1.449      0.147      -1.543       0.231
1-2 years                        0.2733      0.112      2.430      0.015       0.053       0.494
11-20 years                      0.3601      1.011      0.356      0.722      -1.621       2.341
3-5 years                        0.1274      0.155      0.822      0.411      -0.176       0.431
6-10 years                      -0.9314      0.583     -1.599      0.110      -2.073       0.210
================================================================================================
Educational Instruction and Library Occupations 2018

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
 39%|███▉      | 35/90 [00:26<00:38,  1.42it/s]

df length: 41745
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.029872
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:                41745
Model:                          Logit   Df Residuals:                    41733
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02454
Time:                        23:56:33   Log-Likelihood:                -1247.0
converged:                      False   LL-Null:                       -1278.4
Covariance Type:            nonrobust   LLR p-value:                 2.847e-09
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -5.9628      0.149    -39.908      0.000      -6.256      -5.670
AI ROLE                          0.1019      1.010      0.101      0.920      -1.877       2.081
Associate degree                 0.6718      0.273      2.458      0.014       0.136       1.207
Bachelor's degree                0.6459      0.191      3.384      0.001       0.272       1.020
High school or GED               0.2648      0.243      1.091      0.275      -0.211       0.741
Master's degree                  0.3369      0.284      1.188      0.235      -0.219       0.893
Ph.D. or professional degree     0.4215      0.407      1.035      0.301      -0.377       1.220
0 years                         -0.7339      1.007     -0.729      0.466      -2.707       1.240
1-2 years                        0.8745      0.171      5.110      0.000       0.539       1.210
11-20 years                    -12.8588   1428.155     -0.009      0.993   -2811.991    2786.273
3-5 years                        0.7152      0.217      3.301      0.001       0.291       1.140
6-10 years                       1.0458      0.396      2.641      0.008       0.270       1.822
================================================================================================
Educational Instruction and Library Occupations 2023

 40%|████      | 36/90 [00:27<00:37,  1.45it/s]

df length: 56729
Optimization terminated successfully.
         Current function value: 0.123206
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:                56729
Model:                          Logit   Df Residuals:                    56717
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.03087
Time:                        23:56:34   Log-Likelihood:                -6989.4
converged:                       True   LL-Null:                       -7212.0
Covariance Type:            nonrobust   LLR p-value:                 1.490e-88
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.2350      0.058    -72.498      0.000      -4.349      -4.120
AI ROLE                          0.2926      0.266      1.099      0.272      -0.229       0.814
Associate degree                 0.4812      0.109      4.402      0.000       0.267       0.695
Bachelor's degree                0.7861      0.072     10.989      0.000       0.646       0.926
High school or GED               0.6570      0.079      8.303      0.000       0.502       0.812
Master's degree                  0.2483      0.117      2.125      0.034       0.019       0.477
Ph.D. or professional degree    -0.2265      0.210     -1.079      0.281      -0.638       0.185
0 years                          1.2899      0.087     14.810      0.000       1.119       1.461
1-2 years                        0.4723      0.068      6.957      0.000       0.339       0.605
11-20 years                      0.4718      0.388      1.215      0.224      -0.289       1.233
3-5 years                        0.4501      0.085      5.311      0.000       0.284       0.616
6-10 years                       0.3388      0.197      1.719      0.086      -0.047       0.725
================================================================================================
Healthcare Practitioners and Technical Occupations 2019
df length: 177733

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/discrete/discrete_model.py:2385: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/discrete/discrete_model.py:2443: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q * linpred)))
 41%|████      | 37/90 [00:28<00:43,  1.21it/s]

Warning: Maximum number of iterations has been exceeded.
         Current function value: inf
         Iterations: 35
Singular matrix
Healthcare Practitioners and Technical Occupations 2021
df length: 235145
Optimization terminated successfully.
         Current function value: 0.100518
         Iterations 10

 42%|████▏     | 38/90 [00:29<00:48,  1.08it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:               235145
Model:                          Logit   Df Residuals:                   235133
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02439
Time:                        23:56:36   Log-Likelihood:                -23636.
converged:                       True   LL-Null:                       -24227.
Covariance Type:            nonrobust   LLR p-value:                1.489e-246
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.9048      0.024   -162.611      0.000      -3.952      -3.858
AI ROLE                         -1.7886      1.003     -1.784      0.074      -3.754       0.177
Associate degree                 0.8415      0.036     23.435      0.000       0.771       0.912
Bachelor's degree               -0.3543      0.060     -5.917      0.000      -0.472      -0.237
High school or GED               0.6763      0.039     17.359      0.000       0.600       0.753
Master's degree                 -0.5079      0.107     -4.759      0.000      -0.717      -0.299
Ph.D. or professional degree     0.5477      0.081      6.774      0.000       0.389       0.706
0 years                         -1.2393      0.153     -8.114      0.000      -1.539      -0.940
1-2 years                       -0.5224      0.034    -15.505      0.000      -0.588      -0.456
11-20 years                     -1.5416      1.003     -1.537      0.124      -3.508       0.424
3-5 years                       -0.1108      0.056     -1.991      0.046      -0.220      -0.002
6-10 years                      -0.0237      0.208     -0.114      0.909      -0.432       0.385
================================================================================================
Healthcare Practitioners and Technical Occupations 2022
df length: 293272
Optimization terminated successfully.
         Current function value: 0.134618
         Iterations 9

 43%|████▎     | 39/90 [00:30<00:52,  1.04s/it]

                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:               293272
Model:                          Logit   Df Residuals:                   293260
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01669
Time:                        23:56:37   Log-Likelihood:                -39480.
converged:                       True   LL-Null:                       -40150.
Covariance Type:            nonrobust   LLR p-value:                1.049e-280
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.6679      0.018   -199.827      0.000      -3.704      -3.632
AI ROLE                         -0.3130      0.386     -0.811      0.417      -1.069       0.443
Associate degree                 0.7483      0.028     27.086      0.000       0.694       0.802
Bachelor's degree                0.2534      0.036      7.017      0.000       0.183       0.324
High school or GED               0.7439      0.030     24.420      0.000       0.684       0.804
Master's degree                 -0.3510      0.082     -4.259      0.000      -0.512      -0.189
Ph.D. or professional degree     0.2707      0.070      3.844      0.000       0.133       0.409
0 years                         -0.6688      0.086     -7.805      0.000      -0.837      -0.501
1-2 years                       -0.2541      0.024    -10.410      0.000      -0.302      -0.206
11-20 years                     -1.9651      1.003     -1.960      0.050      -3.930      -0.000
3-5 years                        0.0586      0.040      1.456      0.145      -0.020       0.138
6-10 years                       1.0558      0.090     11.688      0.000       0.879       1.233
================================================================================================
Healthcare Practitioners and Technical Occupations 2020
df length: 208848

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
 44%|████▍     | 40/90 [00:32<00:58,  1.16s/it]

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.051735
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:               208848
Model:                          Logit   Df Residuals:                   208836
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01596
Time:                        23:56:39   Log-Likelihood:                -10805.
converged:                      False   LL-Null:                       -10980.
Covariance Type:            nonrobust   LLR p-value:                 1.982e-68
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.4458      0.033   -135.922      0.000      -4.510      -4.382
AI ROLE                         -0.6486      1.004     -0.646      0.518      -2.616       1.319
Associate degree                -0.2340      0.082     -2.867      0.004      -0.394      -0.074
Bachelor's degree               -0.0814      0.082     -0.994      0.320      -0.242       0.079
High school or GED               0.1214      0.071      1.707      0.088      -0.018       0.261
Master's degree                  0.1872      0.122      1.537      0.124      -0.052       0.426
Ph.D. or professional degree     0.8471      0.094      9.022      0.000       0.663       1.031
0 years                         -0.8536      0.221     -3.866      0.000      -1.286      -0.421
1-2 years                       -0.8004      0.058    -13.702      0.000      -0.915      -0.686
11-20 years                    -15.5509   1375.835     -0.011      0.991   -2712.137    2681.035
3-5 years                       -0.2971      0.098     -3.047      0.002      -0.488      -0.106
6-10 years                      -0.1384      0.320     -0.432      0.666      -0.766       0.490
================================================================================================
Healthcare Practitioners and Technical Occupations 2018
df length: 178552

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
 46%|████▌     | 41/90 [00:33<00:58,  1.20s/it]

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.027516
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:               178552
Model:                          Logit   Df Residuals:                   178540
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.05717
Time:                        23:56:40   Log-Likelihood:                -4913.0
converged:                      False   LL-Null:                       -5210.9
Covariance Type:            nonrobust   LLR p-value:                1.118e-120
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -5.2381      0.053    -99.341      0.000      -5.341      -5.135
AI ROLE                          1.9699      0.423      4.652      0.000       1.140       2.800
Associate degree                -0.8218      0.184     -4.456      0.000      -1.183      -0.460
Bachelor's degree               -0.1664      0.140     -1.191      0.234      -0.440       0.107
High school or GED               1.2822      0.081     15.886      0.000       1.124       1.440
Master's degree                  0.1052      0.211      0.498      0.618      -0.309       0.519
Ph.D. or professional degree     0.7985      0.153      5.230      0.000       0.499       1.098
0 years                         -2.2400      0.580     -3.864      0.000      -3.376      -1.104
1-2 years                       -1.4023      0.111    -12.667      0.000      -1.619      -1.185
11-20 years                    -18.4856    1.3e+04     -0.001      0.999   -2.55e+04    2.55e+04
3-5 years                       -0.7556      0.159     -4.742      0.000      -1.068      -0.443
6-10 years                     -16.2760   1244.806     -0.013      0.990   -2456.051    2423.499
================================================================================================
Healthcare Practitioners and Technical Occupations 2023
df length: 286144
Optimization terminated successfully.
         Current function value: 0.211451
         Iterations 8

 47%|████▋     | 42/90 [00:34<00:57,  1.20s/it]

                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:               286144
Model:                          Logit   Df Residuals:                   286132
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02535
Time:                        23:56:41   Log-Likelihood:                -60505.
converged:                       True   LL-Null:                       -62079.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.1257      0.014   -221.566      0.000      -3.153      -3.098
AI ROLE                         -0.6098      0.343     -1.777      0.076      -1.282       0.063
Associate degree                 0.8976      0.021     42.675      0.000       0.856       0.939
Bachelor's degree                0.6391      0.025     25.526      0.000       0.590       0.688
High school or GED               0.6637      0.025     26.797      0.000       0.615       0.712
Master's degree                 -0.5305      0.070     -7.617      0.000      -0.667      -0.394
Ph.D. or professional degree     0.5180      0.050     10.420      0.000       0.421       0.615
0 years                         -0.0770      0.048     -1.619      0.105      -0.170       0.016
1-2 years                       -0.2275      0.019    -12.137      0.000      -0.264      -0.191
11-20 years                     -0.9976      0.383     -2.606      0.009      -1.748      -0.247
3-5 years                        0.0640      0.031      2.089      0.037       0.004       0.124
6-10 years                       1.4512      0.060     24.297      0.000       1.334       1.568
================================================================================================
Legal Occupations 2019

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
 48%|████▊     | 43/90 [00:35<00:47,  1.01s/it]

df length: 10618
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.086837
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:                10618
Model:                          Logit   Df Residuals:                    10606
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01135
Time:                        23:56:42   Log-Likelihood:                -922.03
converged:                      False   LL-Null:                       -932.62
Covariance Type:            nonrobust   LLR p-value:                   0.03163
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.1860      0.129    -32.440      0.000      -4.439      -3.933
AI ROLE                         -0.2643      1.012     -0.261      0.794      -2.249       1.720
Associate degree                 0.0577      0.397      0.145      0.884      -0.721       0.836
Bachelor's degree                0.5201      0.206      2.523      0.012       0.116       0.924
High school or GED               0.7369      0.227      3.250      0.001       0.293       1.181
Master's degree                 -0.5965      1.010     -0.590      0.555      -2.577       1.384
Ph.D. or professional degree     0.6528      0.214      3.044      0.002       0.233       1.073
0 years                          0.0448      0.596      0.075      0.940      -1.123       1.212
1-2 years                       -0.3182      0.209     -1.523      0.128      -0.728       0.091
11-20 years                    -14.3053   1358.033     -0.011      0.992   -2676.000    2647.389
3-5 years                       -0.1416      0.181     -0.781      0.435      -0.497       0.214
6-10 years                      -0.1455      0.316     -0.460      0.645      -0.765       0.474
================================================================================================
Legal Occupations 2021

 49%|████▉     | 44/90 [00:35<00:39,  1.17it/s]

df length: 13410
Optimization terminated successfully.
         Current function value: 0.168240
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:                13410
Model:                          Logit   Df Residuals:                    13398
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.007463
Time:                        23:56:42   Log-Likelihood:                -2256.1
converged:                       True   LL-Null:                       -2273.1
Covariance Type:            nonrobust   LLR p-value:                 0.0003715
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.5031      0.086    -40.929      0.000      -3.671      -3.335
AI ROLE                          0.1149      0.464      0.248      0.804      -0.794       1.023
Associate degree                 0.4795      0.185      2.595      0.009       0.117       0.842
Bachelor's degree                0.4165      0.130      3.215      0.001       0.163       0.670
High school or GED               0.4914      0.125      3.924      0.000       0.246       0.737
Master's degree                  0.5002      0.425      1.176      0.240      -0.334       1.334
Ph.D. or professional degree     0.5140      0.131      3.928      0.000       0.258       0.771
0 years                          0.1182      0.349      0.339      0.735      -0.565       0.801
1-2 years                        0.0984      0.120      0.818      0.413      -0.137       0.334
11-20 years                      0.1378      0.521      0.264      0.792      -0.884       1.160
3-5 years                        0.1752      0.108      1.620      0.105      -0.037       0.387
6-10 years                       0.0546      0.182      0.299      0.765      -0.303       0.412
================================================================================================
Legal Occupations 2022

 50%|█████     | 45/90 [00:36<00:33,  1.32it/s]

df length: 14411
Optimization terminated successfully.
         Current function value: 0.200277
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:                14411
Model:                          Logit   Df Residuals:                    14399
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01083
Time:                        23:56:43   Log-Likelihood:                -2886.2
converged:                       True   LL-Null:                       -2917.8
Covariance Type:            nonrobust   LLR p-value:                 2.346e-09
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.3123      0.074    -44.503      0.000      -3.458      -3.166
AI ROLE                          0.7285      0.326      2.233      0.026       0.089       1.368
Associate degree                -0.0786      0.199     -0.395      0.693      -0.468       0.311
Bachelor's degree                0.2441      0.111      2.206      0.027       0.027       0.461
High school or GED               0.5328      0.112      4.739      0.000       0.312       0.753
Master's degree                  0.3949      0.306      1.291      0.197      -0.204       0.994
Ph.D. or professional degree     0.3808      0.109      3.486      0.000       0.167       0.595
0 years                          0.4265      0.267      1.597      0.110      -0.097       0.950
1-2 years                        0.2472      0.106      2.339      0.019       0.040       0.454
11-20 years                      0.5579      0.360      1.548      0.122      -0.148       1.264
3-5 years                        0.4039      0.095      4.260      0.000       0.218       0.590
6-10 years                       0.2377      0.156      1.528      0.127      -0.067       0.543
================================================================================================
Legal Occupations 2020

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
 51%|█████     | 46/90 [00:36<00:30,  1.46it/s]

df length: 10122
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.119739
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:                10122
Model:                          Logit   Df Residuals:                    10110
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01209
Time:                        23:56:43   Log-Likelihood:                -1212.0
converged:                      False   LL-Null:                       -1226.8
Covariance Type:            nonrobust   LLR p-value:                  0.001793
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.9435      0.116    -33.850      0.000      -4.172      -3.715
AI ROLE                        -21.5047   4.06e+04     -0.001      1.000   -7.96e+04    7.95e+04
Associate degree                 0.1980      0.296      0.668      0.504      -0.382       0.778
Bachelor's degree                0.3703      0.187      1.984      0.047       0.004       0.736
High school or GED               0.5680      0.191      2.971      0.003       0.193       0.943
Master's degree                  0.3980      0.518      0.768      0.442      -0.618       1.414
Ph.D. or professional degree     0.6796      0.179      3.787      0.000       0.328       1.031
0 years                          0.9363      0.405      2.311      0.021       0.142       1.730
1-2 years                        0.2092      0.168      1.246      0.213      -0.120       0.538
11-20 years                      0.4697      0.607      0.774      0.439      -0.720       1.660
3-5 years                        0.0972      0.156      0.623      0.533      -0.208       0.403
6-10 years                       0.0228      0.268      0.085      0.932      -0.503       0.548
================================================================================================
Legal Occupations 2018

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
 52%|█████▏    | 47/90 [00:37<00:27,  1.58it/s]

df length: 9145
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.055259
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:                 9145
Model:                          Logit   Df Residuals:                     9133
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.05176
Time:                        23:56:44   Log-Likelihood:                -505.34
converged:                      False   LL-Null:                       -532.93
Covariance Type:            nonrobust   LLR p-value:                 7.206e-08
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -5.4794      0.246    -22.254      0.000      -5.962      -4.997
AI ROLE                          1.5880      0.619      2.567      0.010       0.375       2.801
Associate degree               -17.8584   4162.277     -0.004      0.997   -8175.771    8140.054
Bachelor's degree                0.9065      0.248      3.648      0.000       0.419       1.393
High school or GED               0.1015      0.383      0.265      0.791      -0.649       0.852
Master's degree                 -0.0161      1.023     -0.016      0.987      -2.022       1.990
Ph.D. or professional degree     0.6664      0.298      2.235      0.025       0.082       1.251
0 years                          1.8060      0.633      2.855      0.004       0.566       3.046
1-2 years                        1.1807      0.288      4.096      0.000       0.616       1.746
11-20 years                    -56.7832   3.68e+12  -1.54e-11      1.000   -7.22e+12    7.22e+12
3-5 years                        0.6445      0.293      2.201      0.028       0.070       1.219
6-10 years                       0.6677      0.414      1.612      0.107      -0.144       1.479
================================================================================================
Legal Occupations 2023

 53%|█████▎    | 48/90 [00:37<00:24,  1.70it/s]

df length: 11385
Optimization terminated successfully.
         Current function value: 0.265580
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:                11385
Model:                          Logit   Df Residuals:                    11373
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01850
Time:                        23:56:44   Log-Likelihood:                -3023.6
converged:                       True   LL-Null:                       -3080.6
Covariance Type:            nonrobust   LLR p-value:                 2.956e-19
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.9072      0.071    -41.169      0.000      -3.046      -2.769
AI ROLE                          1.2432      0.252      4.930      0.000       0.749       1.737
Associate degree                 0.0352      0.175      0.201      0.841      -0.308       0.379
Bachelor's degree                0.4383      0.104      4.235      0.000       0.235       0.641
High school or GED               0.4029      0.118      3.409      0.001       0.171       0.634
Master's degree                  0.9954      0.246      4.053      0.000       0.514       1.477
Ph.D. or professional degree     0.4336      0.095      4.551      0.000       0.247       0.620
0 years                          0.1620      0.269      0.603      0.546      -0.365       0.689
1-2 years                        0.0521      0.103      0.506      0.613      -0.150       0.254
11-20 years                      0.9333      0.326      2.865      0.004       0.295       1.572
3-5 years                        0.3865      0.088      4.385      0.000       0.214       0.559
6-10 years                       0.4530      0.134      3.384      0.001       0.191       0.715
================================================================================================
Life, Physical, and Social Science Occupations 2019

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
 54%|█████▍    | 49/90 [00:38<00:24,  1.71it/s]

df length: 19301
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.047346
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:                19301
Model:                          Logit   Df Residuals:                    19289
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01334
Time:                        23:56:45   Log-Likelihood:                -913.82
converged:                      False   LL-Null:                       -926.17
Covariance Type:            nonrobust   LLR p-value:                   0.01004
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -5.3406      0.209    -25.593      0.000      -5.750      -4.932
AI ROLE                          0.0046      0.590      0.008      0.994      -1.153       1.162
Associate degree                 1.0009      0.385      2.601      0.009       0.247       1.755
Bachelor's degree                0.8276      0.252      3.285      0.001       0.334       1.321
High school or GED               0.7233      0.292      2.477      0.013       0.151       1.296
Master's degree                  1.2014      0.304      3.950      0.000       0.605       1.798
Ph.D. or professional degree     0.6394      0.348      1.836      0.066      -0.043       1.322
0 years                          0.1810      0.432      0.419      0.675      -0.665       1.027
1-2 years                       -0.0766      0.205     -0.373      0.709      -0.479       0.326
11-20 years                    -36.9099   7.41e+07  -4.98e-07      1.000   -1.45e+08    1.45e+08
3-5 years                       -0.4029      0.230     -1.755      0.079      -0.853       0.047
6-10 years                      -0.1673      0.312     -0.536      0.592      -0.780       0.445
================================================================================================
Life, Physical, and Social Science Occupations 2021

 56%|█████▌    | 50/90 [00:38<00:23,  1.73it/s]

df length: 25175
Optimization terminated successfully.
         Current function value: 0.120449
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:                25175
Model:                          Logit   Df Residuals:                    25163
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02115
Time:                        23:56:45   Log-Likelihood:                -3032.3
converged:                       True   LL-Null:                       -3097.8
Covariance Type:            nonrobust   LLR p-value:                 1.060e-22
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.3345      0.111    -39.181      0.000      -4.551      -4.118
AI ROLE                          0.0611      0.246      0.248      0.804      -0.422       0.544
Associate degree                 1.5190      0.174      8.752      0.000       1.179       1.859
Bachelor's degree                0.9386      0.133      7.051      0.000       0.678       1.199
High school or GED               0.8338      0.154      5.427      0.000       0.533       1.135
Master's degree                  1.1822      0.163      7.272      0.000       0.864       1.501
Ph.D. or professional degree     1.2283      0.157      7.831      0.000       0.921       1.536
0 years                         -0.1480      0.236     -0.627      0.531      -0.611       0.315
1-2 years                       -0.4021      0.113     -3.563      0.000      -0.623      -0.181
11-20 years                      0.1133      0.331      0.343      0.732      -0.535       0.762
3-5 years                       -0.1255      0.106     -1.189      0.235      -0.332       0.081
6-10 years                       0.1491      0.143      1.043      0.297      -0.131       0.429
================================================================================================
Life, Physical, and Social Science Occupations 2022

 57%|█████▋    | 51/90 [00:39<00:22,  1.74it/s]

df length: 30329
Optimization terminated successfully.
         Current function value: 0.152155
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:                30329
Model:                          Logit   Df Residuals:                    30317
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01512
Time:                        23:56:46   Log-Likelihood:                -4614.7
converged:                       True   LL-Null:                       -4685.6
Covariance Type:            nonrobust   LLR p-value:                 7.404e-25
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.9050      0.082    -47.665      0.000      -4.066      -3.744
AI ROLE                          0.5293      0.152      3.489      0.000       0.232       0.827
Associate degree                 0.8946      0.141      6.355      0.000       0.619       1.171
Bachelor's degree                0.6007      0.098      6.121      0.000       0.408       0.793
High school or GED               0.4118      0.120      3.430      0.001       0.176       0.647
Master's degree                  0.4674      0.140      3.341      0.001       0.193       0.742
Ph.D. or professional degree     0.8884      0.120      7.407      0.000       0.653       1.124
0 years                          0.2819      0.166      1.703      0.089      -0.043       0.606
1-2 years                       -0.0231      0.089     -0.260      0.795      -0.197       0.151
11-20 years                      0.8329      0.210      3.968      0.000       0.422       1.244
3-5 years                        0.2604      0.083      3.147      0.002       0.098       0.423
6-10 years                       0.2274      0.120      1.896      0.058      -0.008       0.462
================================================================================================
Life, Physical, and Social Science Occupations 2020

 58%|█████▊    | 52/90 [00:39<00:21,  1.76it/s]

df length: 20260
Optimization terminated successfully.
         Current function value: 0.058423
         Iterations 9
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:                20260
Model:                          Logit   Df Residuals:                    20248
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01753
Time:                        23:56:47   Log-Likelihood:                -1183.7
converged:                       True   LL-Null:                       -1204.8
Covariance Type:            nonrobust   LLR p-value:                 1.466e-05
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.9564      0.162    -30.629      0.000      -5.274      -4.639
AI ROLE                          0.8532      0.352      2.425      0.015       0.164       1.543
Associate degree                 1.5025      0.260      5.780      0.000       0.993       2.012
Bachelor's degree                0.6694      0.208      3.226      0.001       0.263       1.076
High school or GED               0.5499      0.248      2.220      0.026       0.064       1.035
Master's degree                  0.4531      0.295      1.538      0.124      -0.125       1.031
Ph.D. or professional degree     0.4892      0.276      1.774      0.076      -0.051       1.030
0 years                         -0.7140      0.590     -1.209      0.227      -1.871       0.443
1-2 years                       -0.4295      0.198     -2.169      0.030      -0.818      -0.041
11-20 years                     -0.9401      1.010     -0.930      0.352      -2.920       1.040
3-5 years                       -0.0263      0.178     -0.148      0.882      -0.374       0.322
6-10 years                      -0.0471      0.267     -0.176      0.860      -0.571       0.477
================================================================================================
Life, Physical, and Social Science Occupations 2018

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
 59%|█████▉    | 53/90 [00:40<00:21,  1.75it/s]

df length: 19078
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.028681
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:                19078
Model:                          Logit   Df Residuals:                    19066
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02488
Time:                        23:56:47   Log-Likelihood:                -547.18
converged:                      False   LL-Null:                       -561.14
Covariance Type:            nonrobust   LLR p-value:                  0.003330
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -5.9043      0.260    -22.688      0.000      -6.414      -5.394
AI ROLE                          0.2752      0.724      0.380      0.704      -1.145       1.695
Associate degree               -11.2650    167.754     -0.067      0.946    -340.056     317.526
Bachelor's degree                0.5956      0.319      1.867      0.062      -0.030       1.221
High school or GED               0.4030      0.400      1.007      0.314      -0.381       1.187
Master's degree                  0.4634      0.460      1.007      0.314      -0.438       1.365
Ph.D. or professional degree     0.8961      0.389      2.304      0.021       0.134       1.659
0 years                          0.7660      0.541      1.416      0.157      -0.294       1.826
1-2 years                       -0.1725      0.329     -0.525      0.599      -0.816       0.471
11-20 years                    -23.5864   1.35e+05     -0.000      1.000   -2.64e+05    2.64e+05
3-5 years                        0.5407      0.268      2.021      0.043       0.016       1.065
6-10 years                      -0.2580      0.495     -0.521      0.602      -1.228       0.712
================================================================================================
Life, Physical, and Social Science Occupations 2023

 60%|██████    | 54/90 [00:41<00:20,  1.76it/s]

df length: 26051
Optimization terminated successfully.
         Current function value: 0.221449
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:                26051
Model:                          Logit   Df Residuals:                    26039
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.05732
Time:                        23:56:48   Log-Likelihood:                -5769.0
converged:                       True   LL-Null:                       -6119.7
Covariance Type:            nonrobust   LLR p-value:                2.525e-143
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.5113      0.075    -46.718      0.000      -3.659      -3.364
AI ROLE                         -0.2407      0.174     -1.383      0.167      -0.582       0.100
Associate degree                 0.9321      0.135      6.900      0.000       0.667       1.197
Bachelor's degree                0.8575      0.089      9.617      0.000       0.683       1.032
High school or GED               0.3727      0.114      3.281      0.001       0.150       0.595
Master's degree                  0.4563      0.131      3.492      0.000       0.200       0.712
Ph.D. or professional degree     1.9689      0.090     21.947      0.000       1.793       2.145
0 years                         -0.2734      0.167     -1.637      0.102      -0.601       0.054
1-2 years                       -0.4149      0.079     -5.238      0.000      -0.570      -0.260
11-20 years                      0.7698      0.198      3.890      0.000       0.382       1.158
3-5 years                        0.2176      0.069      3.133      0.002       0.081       0.354
6-10 years                       0.3035      0.098      3.109      0.002       0.112       0.495
================================================================================================
Management Occupations 2019
df length: 174325
Optimization terminated successfully.
         Current function value: 0.068940
         Iterations 9

 61%|██████    | 55/90 [00:42<00:24,  1.45it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:               174325
Model:                          Logit   Df Residuals:                   174313
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.002209
Time:                        23:56:49   Log-Likelihood:                -12018.
converged:                       True   LL-Null:                       -12045.
Covariance Type:            nonrobust   LLR p-value:                 1.647e-07
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.3857      0.040   -109.382      0.000      -4.464      -4.307
AI ROLE                          0.3776      0.150      2.526      0.012       0.085       0.671
Associate degree                -0.3054      0.126     -2.424      0.015      -0.552      -0.058
Bachelor's degree                0.0895      0.053      1.691      0.091      -0.014       0.193
High school or GED              -0.1662      0.072     -2.300      0.021      -0.308      -0.025
Master's degree                  0.1554      0.116      1.337      0.181      -0.072       0.383
Ph.D. or professional degree    -0.5017      0.305     -1.645      0.100      -1.100       0.096
0 years                         -0.2604      0.281     -0.927      0.354      -0.811       0.290
1-2 years                        0.0327      0.067      0.492      0.623      -0.098       0.163
11-20 years                     -0.3870      0.195     -1.988      0.047      -0.768      -0.006
3-5 years                        0.1454      0.055      2.637      0.008       0.037       0.253
6-10 years                      -0.0280      0.072     -0.391      0.696      -0.168       0.112
================================================================================================
Management Occupations 2021
df length: 220041

 62%|██████▏   | 56/90 [00:43<00:27,  1.23it/s]

Optimization terminated successfully.
         Current function value: 0.147979
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:               220041
Model:                          Logit   Df Residuals:                   220029
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.005227
Time:                        23:56:50   Log-Likelihood:                -32562.
converged:                       True   LL-Null:                       -32733.
Covariance Type:            nonrobust   LLR p-value:                 1.103e-66
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.6208      0.025   -146.631      0.000      -3.669      -3.572
AI ROLE                          0.3198      0.078      4.119      0.000       0.168       0.472
Associate degree                 0.3410      0.056      6.083      0.000       0.231       0.451
Bachelor's degree                0.1728      0.031      5.608      0.000       0.112       0.233
High school or GED               0.0516      0.037      1.402      0.161      -0.021       0.124
Master's degree                  0.1260      0.070      1.802      0.072      -0.011       0.263
Ph.D. or professional degree    -0.4632      0.168     -2.761      0.006      -0.792      -0.134
0 years                         -0.7508      0.174     -4.318      0.000      -1.092      -0.410
1-2 years                        0.2536      0.036      7.060      0.000       0.183       0.324
11-20 years                      0.0700      0.093      0.755      0.451      -0.112       0.252
3-5 years                        0.3163      0.031     10.102      0.000       0.255       0.378
6-10 years                       0.2633      0.039      6.744      0.000       0.187       0.340
================================================================================================
Management Occupations 2022
df length: 258812
Optimization terminated successfully.
         Current function value: 0.191056
         Iterations 8

 63%|██████▎   | 57/90 [00:44<00:30,  1.08it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:               258812
Model:                          Logit   Df Residuals:                   258800
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01025
Time:                        23:56:51   Log-Likelihood:                -49447.
converged:                       True   LL-Null:                       -49959.
Covariance Type:            nonrobust   LLR p-value:                1.314e-212
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.3540      0.020   -170.444      0.000      -3.393      -3.315
AI ROLE                          0.4177      0.056      7.498      0.000       0.309       0.527
Associate degree                 0.0598      0.048      1.237      0.216      -0.035       0.155
Bachelor's degree                0.1840      0.024      7.729      0.000       0.137       0.231
High school or GED              -0.0577      0.031     -1.888      0.059      -0.118       0.002
Master's degree                 -0.0486      0.057     -0.851      0.395      -0.160       0.063
Ph.D. or professional degree    -0.1957      0.118     -1.662      0.096      -0.426       0.035
0 years                         -0.5382      0.131     -4.123      0.000      -0.794      -0.282
1-2 years                        0.3249      0.029     11.136      0.000       0.268       0.382
11-20 years                      0.3810      0.067      5.666      0.000       0.249       0.513
3-5 years                        0.4662      0.025     18.541      0.000       0.417       0.515
6-10 years                       0.5448      0.030     18.280      0.000       0.486       0.603
================================================================================================
Management Occupations 2020
df length: 162514
Optimization terminated successfully.
         Current function value: 0.091839
         Iterations 9

 64%|██████▍   | 58/90 [00:45<00:30,  1.07it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:               162514
Model:                          Logit   Df Residuals:                   162502
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.002632
Time:                        23:56:52   Log-Likelihood:                -14925.
converged:                       True   LL-Null:                       -14964.
Covariance Type:            nonrobust   LLR p-value:                 2.536e-12
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.0787      0.036   -114.243      0.000      -4.149      -4.009
AI ROLE                          0.1125      0.142      0.793      0.428      -0.166       0.391
Associate degree                -0.1167      0.103     -1.129      0.259      -0.319       0.086
Bachelor's degree                0.0654      0.047      1.392      0.164      -0.027       0.157
High school or GED              -0.0812      0.058     -1.391      0.164      -0.196       0.033
Master's degree                  0.1140      0.102      1.116      0.265      -0.086       0.314
Ph.D. or professional degree    -0.2342      0.201     -1.167      0.243      -0.627       0.159
0 years                         -1.3981      0.335     -4.168      0.000      -2.056      -0.741
1-2 years                        0.1674      0.056      2.977      0.003       0.057       0.278
11-20 years                     -0.0720      0.148     -0.487      0.626      -0.362       0.218
3-5 years                        0.1757      0.049      3.598      0.000       0.080       0.271
6-10 years                       0.1944      0.061      3.210      0.001       0.076       0.313
================================================================================================
Management Occupations 2018
df length: 169177
Optimization terminated successfully.
         Current function value: 0.038946
         Iterations 10

 66%|██████▌   | 59/90 [00:46<00:29,  1.05it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:               169177
Model:                          Logit   Df Residuals:                   169165
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.003284
Time:                        23:56:53   Log-Likelihood:                -6588.7
converged:                       True   LL-Null:                       -6610.5
Covariance Type:            nonrobust   LLR p-value:                 9.171e-06
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -5.1802      0.060    -86.504      0.000      -5.298      -5.063
AI ROLE                         -0.1057      0.281     -0.377      0.706      -0.655       0.444
Associate degree                -0.3704      0.203     -1.826      0.068      -0.768       0.027
Bachelor's degree                0.2887      0.078      3.705      0.000       0.136       0.441
High school or GED               0.1490      0.102      1.464      0.143      -0.050       0.349
Master's degree                  0.2685      0.171      1.573      0.116      -0.066       0.603
Ph.D. or professional degree     0.1696      0.339      0.500      0.617      -0.496       0.835
0 years                         -0.7927      0.503     -1.574      0.115      -1.779       0.194
1-2 years                       -0.0744      0.098     -0.758      0.448      -0.267       0.118
11-20 years                     -0.6114      0.308     -1.983      0.047      -1.216      -0.007
3-5 years                        0.1238      0.078      1.578      0.114      -0.030       0.277
6-10 years                      -0.1285      0.101     -1.267      0.205      -0.327       0.070
================================================================================================
Management Occupations 2023
df length: 201898
Optimization terminated successfully.
         Current function value: 0.258377
         Iterations 7

 67%|██████▋   | 60/90 [00:47<00:29,  1.03it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:               201898
Model:                          Logit   Df Residuals:                   201886
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01709
Time:                        23:56:54   Log-Likelihood:                -52166.
converged:                       True   LL-Null:                       -53073.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.9804      0.019   -159.193      0.000      -3.017      -2.944
AI ROLE                          0.4848      0.054      8.908      0.000       0.378       0.591
Associate degree                 0.5382      0.040     13.414      0.000       0.460       0.617
Bachelor's degree                0.3897      0.023     17.054      0.000       0.345       0.434
High school or GED               0.0111      0.029      0.385      0.700      -0.046       0.068
Master's degree                  0.1500      0.051      2.940      0.003       0.050       0.250
Ph.D. or professional degree     0.1558      0.096      1.624      0.104      -0.032       0.344
0 years                          0.2931      0.080      3.656      0.000       0.136       0.450
1-2 years                        0.1384      0.027      5.037      0.000       0.085       0.192
11-20 years                      0.7799      0.051     15.162      0.000       0.679       0.881
3-5 years                        0.3133      0.024     13.230      0.000       0.267       0.360
6-10 years                       0.5743      0.027     20.896      0.000       0.520       0.628
================================================================================================
Office and Administrative Support Occupations 2019
df length: 185082
Optimization terminated successfully.
         Current function value: 0.055495
         Iterations 9

 68%|██████▊   | 61/90 [00:48<00:29,  1.00s/it]

                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:               185082
Model:                          Logit   Df Residuals:                   185070
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.009124
Time:                        23:56:55   Log-Likelihood:                -10271.
converged:                       True   LL-Null:                       -10366.
Covariance Type:            nonrobust   LLR p-value:                 1.318e-34
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.8863      0.042   -115.162      0.000      -4.969      -4.803
AI ROLE                          0.5499      0.322      1.708      0.088      -0.081       1.181
Associate degree                 0.2656      0.102      2.596      0.009       0.065       0.466
Bachelor's degree                0.6489      0.068      9.578      0.000       0.516       0.782
High school or GED               0.1142      0.057      2.014      0.044       0.003       0.225
Master's degree                  0.9810      0.249      3.933      0.000       0.492       1.470
Ph.D. or professional degree     0.0922      0.712      0.130      0.897      -1.303       1.487
0 years                         -0.2828      0.166     -1.700      0.089      -0.609       0.043
1-2 years                        0.3499      0.054      6.448      0.000       0.244       0.456
11-20 years                     -0.2853      0.582     -0.490      0.624      -1.427       0.856
3-5 years                        0.1720      0.073      2.361      0.018       0.029       0.315
6-10 years                      -0.4628      0.207     -2.237      0.025      -0.868      -0.057
================================================================================================
Office and Administrative Support Occupations 2021
df length: 223691
Optimization terminated successfully.
         Current function value: 0.117029
         Iterations 9

 69%|██████▉   | 62/90 [00:49<00:29,  1.07s/it]

                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:               223691
Model:                          Logit   Df Residuals:                   223679
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.008622
Time:                        23:56:56   Log-Likelihood:                -26178.
converged:                       True   LL-Null:                       -26406.
Covariance Type:            nonrobust   LLR p-value:                 1.058e-90
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.9667      0.026   -150.087      0.000      -4.019      -3.915
AI ROLE                          0.9392      0.144      6.537      0.000       0.658       1.221
Associate degree                 0.4250      0.063      6.793      0.000       0.302       0.548
Bachelor's degree                0.6850      0.045     15.281      0.000       0.597       0.773
High school or GED               0.4208      0.032     12.989      0.000       0.357       0.484
Master's degree                  0.0537      0.234      0.230      0.818      -0.404       0.512
Ph.D. or professional degree    -0.7757      0.711     -1.091      0.275      -2.169       0.618
0 years                         -0.4080      0.087     -4.692      0.000      -0.578      -0.238
1-2 years                       -0.0312      0.033     -0.956      0.339      -0.095       0.033
11-20 years                     -0.4394      0.359     -1.223      0.221      -1.144       0.265
3-5 years                        0.1246      0.042      2.977      0.003       0.043       0.207
6-10 years                       0.2154      0.092      2.344      0.019       0.035       0.395
================================================================================================
Office and Administrative Support Occupations 2022
df length: 238205
Optimization terminated successfully.
         Current function value: 0.152074
         Iterations 8

 70%|███████   | 63/90 [00:50<00:30,  1.11s/it]

                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:               238205
Model:                          Logit   Df Residuals:                   238193
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.008597
Time:                        23:56:57   Log-Likelihood:                -36225.
converged:                       True   LL-Null:                       -36539.
Covariance Type:            nonrobust   LLR p-value:                1.266e-127
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.6190      0.021   -174.491      0.000      -3.660      -3.578
AI ROLE                          0.4060      0.136      2.979      0.003       0.139       0.673
Associate degree                 0.3504      0.050      7.046      0.000       0.253       0.448
Bachelor's degree                0.5676      0.035     16.007      0.000       0.498       0.637
High school or GED               0.2786      0.027     10.509      0.000       0.227       0.331
Master's degree                  0.4635      0.144      3.224      0.001       0.182       0.745
Ph.D. or professional degree    -0.0472      0.322     -0.147      0.883      -0.677       0.583
0 years                         -0.0859      0.065     -1.322      0.186      -0.213       0.041
1-2 years                        0.1569      0.027      5.830      0.000       0.104       0.210
11-20 years                      0.4319      0.201      2.154      0.031       0.039       0.825
3-5 years                        0.2698      0.034      8.003      0.000       0.204       0.336
6-10 years                       0.5112      0.065      7.894      0.000       0.384       0.638
================================================================================================
Office and Administrative Support Occupations 2020
df length: 175927
Optimization terminated successfully.
         Current function value: 0.073137
         Iterations 9

 71%|███████   | 64/90 [00:51<00:28,  1.10s/it]

                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:               175927
Model:                          Logit   Df Residuals:                   175915
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.007479
Time:                        23:56:59   Log-Likelihood:                -12867.
converged:                       True   LL-Null:                       -12964.
Covariance Type:            nonrobust   LLR p-value:                 1.360e-35
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.3736      0.035   -125.336      0.000      -4.442      -4.305
AI ROLE                          0.5656      0.296      1.911      0.056      -0.014       1.146
Associate degree                 0.3512      0.093      3.771      0.000       0.169       0.534
Bachelor's degree                0.6512      0.063     10.370      0.000       0.528       0.774
High school or GED               0.1024      0.048      2.151      0.031       0.009       0.196
Master's degree                  0.7334      0.249      2.948      0.003       0.246       1.221
Ph.D. or professional degree    -0.9553      1.003     -0.952      0.341      -2.921       1.011
0 years                         -0.8241      0.138     -5.975      0.000      -1.094      -0.554
1-2 years                       -0.0311      0.050     -0.621      0.535      -0.129       0.067
11-20 years                     -0.6947      0.505     -1.375      0.169      -1.685       0.296
3-5 years                        0.0023      0.065      0.035      0.972      -0.125       0.130
6-10 years                       0.1235      0.140      0.883      0.377      -0.151       0.398
================================================================================================
Office and Administrative Support Occupations 2018
df length: 173712

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
 72%|███████▏  | 65/90 [00:53<00:29,  1.17s/it]

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.027561
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:               173712
Model:                          Logit   Df Residuals:                   173700
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01697
Time:                        23:57:00   Log-Likelihood:                -4787.6
converged:                      False   LL-Null:                       -4870.2
Covariance Type:            nonrobust   LLR p-value:                 1.116e-29
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -5.8241      0.068    -85.567      0.000      -5.958      -5.691
AI ROLE                          0.5263      0.507      1.038      0.299      -0.467       1.520
Associate degree                 0.1227      0.169      0.727      0.467      -0.208       0.453
Bachelor's degree                0.8659      0.104      8.327      0.000       0.662       1.070
High school or GED               0.2051      0.092      2.225      0.026       0.024       0.386
Master's degree                  1.6760      0.300      5.587      0.000       1.088       2.264
Ph.D. or professional degree     0.3588      1.005      0.357      0.721      -1.611       2.329
0 years                         -1.7419      0.580     -3.002      0.003      -2.879      -0.605
1-2 years                        0.3621      0.087      4.174      0.000       0.192       0.532
11-20 years                    -17.8772   5291.412     -0.003      0.997   -1.04e+04    1.04e+04
3-5 years                        0.2433      0.110      2.207      0.027       0.027       0.459
6-10 years                       0.4182      0.212      1.976      0.048       0.003       0.833
================================================================================================
Office and Administrative Support Occupations 2023
df length: 177048
Optimization terminated successfully.
         Current function value: 0.209654
         Iterations 7

 73%|███████▎  | 66/90 [00:54<00:26,  1.12s/it]

                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:               177048
Model:                          Logit   Df Residuals:                   177036
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01536
Time:                        23:57:01   Log-Likelihood:                -37119.
converged:                       True   LL-Null:                       -37698.
Covariance Type:            nonrobust   LLR p-value:                1.863e-241
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.2048      0.020   -160.968      0.000      -3.244      -3.166
AI ROLE                          0.2974      0.135      2.200      0.028       0.032       0.562
Associate degree                 0.8208      0.044     18.860      0.000       0.736       0.906
Bachelor's degree                0.9357      0.033     28.380      0.000       0.871       1.000
High school or GED               0.3834      0.025     15.085      0.000       0.334       0.433
Master's degree                  0.4721      0.136      3.471      0.001       0.206       0.739
Ph.D. or professional degree    -0.0359      0.308     -0.117      0.907      -0.640       0.568
0 years                          0.0348      0.054      0.648      0.517      -0.070       0.140
1-2 years                       -0.0244      0.026     -0.953      0.340      -0.075       0.026
11-20 years                     -0.0347      0.186     -0.186      0.852      -0.400       0.330
3-5 years                        0.0641      0.032      2.002      0.045       0.001       0.127
6-10 years                       0.2779      0.063      4.430      0.000       0.155       0.401
================================================================================================
Personal Care and Service Occupations 2019

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/discrete/discrete_model.py:2385: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/discrete/discrete_model.py:2443: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q * linpred)))
 74%|███████▍  | 67/90 [00:54<00:22,  1.04it/s]

df length: 25875
Warning: Maximum number of iterations has been exceeded.
         Current function value: inf
         Iterations: 35
Singular matrix
Personal Care and Service Occupations 2021

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
 76%|███████▌  | 68/90 [00:55<00:18,  1.17it/s]

df length: 28728
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.076828
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:                28728
Model:                          Logit   Df Residuals:                    28716
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.008124
Time:                        23:57:02   Log-Likelihood:                -2207.1
converged:                      False   LL-Null:                       -2225.2
Covariance Type:            nonrobust   LLR p-value:                 0.0001595
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.4379      0.071    -62.326      0.000      -4.577      -4.298
AI ROLE                        -21.0271   6.94e+04     -0.000      1.000   -1.36e+05    1.36e+05
Associate degree                 0.8584      0.275      3.123      0.002       0.320       1.397
Bachelor's degree                0.4862      0.219      2.225      0.026       0.058       0.914
High school or GED               0.5309      0.106      4.992      0.000       0.322       0.739
Master's degree                 -0.1780      1.009     -0.176      0.860      -2.155       1.799
Ph.D. or professional degree   -19.4108   4.01e+04     -0.000      1.000   -7.86e+04    7.85e+04
0 years                          0.0019      0.325      0.006      0.995      -0.635       0.639
1-2 years                        0.0227      0.128      0.178      0.859      -0.227       0.273
11-20 years                      1.0425      1.024      1.018      0.309      -0.964       3.049
3-5 years                        0.1378      0.221      0.623      0.533      -0.295       0.571
6-10 years                       0.1557      0.722      0.216      0.829      -1.259       1.570
================================================================================================
Personal Care and Service Occupations 2022

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
 77%|███████▋  | 69/90 [00:56<00:16,  1.27it/s]

df length: 32448
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.095150
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:                32448
Model:                          Logit   Df Residuals:                    32436
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01747
Time:                        23:57:03   Log-Likelihood:                -3087.4
converged:                      False   LL-Null:                       -3142.3
Covariance Type:            nonrobust   LLR p-value:                 1.989e-18
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.2025      0.058    -72.033      0.000      -4.317      -4.088
AI ROLE                          0.0251      1.024      0.025      0.980      -1.982       2.032
Associate degree                 0.9051      0.229      3.954      0.000       0.456       1.354
Bachelor's degree                1.1796      0.143      8.260      0.000       0.900       1.459
High school or GED               0.5823      0.091      6.388      0.000       0.404       0.761
Master's degree                 -0.1116      1.010     -0.110      0.912      -2.091       1.868
Ph.D. or professional degree   -18.8073   2.48e+04     -0.001      0.999   -4.86e+04    4.86e+04
0 years                          0.5554      0.203      2.730      0.006       0.157       0.954
1-2 years                       -0.0490      0.108     -0.453      0.650      -0.261       0.163
11-20 years                    -10.0378    161.304     -0.062      0.950    -326.187     306.112
3-5 years                       -0.3063      0.194     -1.582      0.114      -0.686       0.073
6-10 years                       0.8964      0.341      2.631      0.009       0.229       1.564
================================================================================================
Personal Care and Service Occupations 2020

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
 78%|███████▊  | 70/90 [00:56<00:14,  1.36it/s]

df length: 24654
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.065548
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:                24654
Model:                          Logit   Df Residuals:                    24642
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.002981
Time:                        23:57:03   Log-Likelihood:                -1616.0
converged:                      False   LL-Null:                       -1620.8
Covariance Type:            nonrobust   LLR p-value:                    0.5609
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.3457      0.071    -61.385      0.000      -4.484      -4.207
AI ROLE                        -12.8118   1421.558     -0.009      0.993   -2799.015    2773.391
Associate degree                -0.6002      0.588     -1.021      0.307      -1.752       0.552
Bachelor's degree                0.1821      0.274      0.663      0.507      -0.356       0.720
High school or GED              -0.2637      0.149     -1.772      0.076      -0.556       0.028
Master's degree                  0.3802      1.014      0.375      0.708      -1.607       2.368
Ph.D. or professional degree    -9.9864    458.703     -0.022      0.983    -909.028     889.056
0 years                          0.4697      0.389      1.208      0.227      -0.293       1.232
1-2 years                       -0.0893      0.188     -0.476      0.634      -0.457       0.279
11-20 years                    -14.4534   2893.238     -0.005      0.996   -5685.096    5656.189
3-5 years                        0.2686      0.278      0.967      0.334      -0.276       0.813
6-10 years                       0.4355      0.727      0.599      0.549      -0.990       1.861
================================================================================================
Personal Care and Service Occupations 2018

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
 79%|███████▉  | 71/90 [00:57<00:13,  1.43it/s]

df length: 25428
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.021122
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:                25428
Model:                          Logit   Df Residuals:                    25416
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01733
Time:                        23:57:04   Log-Likelihood:                -537.08
converged:                      False   LL-Null:                       -546.55
Covariance Type:            nonrobust   LLR p-value:                   0.06216
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -5.9164      0.144    -41.083      0.000      -6.199      -5.634
AI ROLE                        -13.6556   3971.575     -0.003      0.997   -7797.800    7770.488
Associate degree               -16.3430   2890.724     -0.006      0.995   -5682.058    5649.372
Bachelor's degree               -0.1747      0.629     -0.278      0.781      -1.407       1.057
High school or GED               0.5477      0.262      2.093      0.036       0.035       1.061
Master's degree                  1.6139      1.035      1.560      0.119      -0.414       3.642
Ph.D. or professional degree   -14.9308   8703.323     -0.002      0.999   -1.71e+04     1.7e+04
0 years                        -15.7530   2592.677     -0.006      0.995   -5097.306    5065.800
1-2 years                       -0.0189      0.342     -0.055      0.956      -0.690       0.652
11-20 years                    -15.2774   7851.165     -0.002      0.998   -1.54e+04    1.54e+04
3-5 years                        1.0955      0.431      2.544      0.011       0.252       1.939
6-10 years                      -6.4079     30.667     -0.209      0.834     -66.514      53.698
================================================================================================
Personal Care and Service Occupations 2023

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
 80%|████████  | 72/90 [00:57<00:12,  1.49it/s]

df length: 25603
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.115145
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:                25603
Model:                          Logit   Df Residuals:                    25591
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.03037
Time:                        23:57:05   Log-Likelihood:                -2948.1
converged:                      False   LL-Null:                       -3040.4
Covariance Type:            nonrobust   LLR p-value:                 1.125e-33
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.9666      0.059    -66.684      0.000      -4.083      -3.850
AI ROLE                        -10.6267    189.745     -0.056      0.955    -382.520     361.267
Associate degree                 1.1169      0.221      5.046      0.000       0.683       1.551
Bachelor's degree                1.6396      0.124     13.219      0.000       1.397       1.883
High school or GED               0.5202      0.093      5.604      0.000       0.338       0.702
Master's degree                  1.0526      0.517      2.036      0.042       0.040       2.066
Ph.D. or professional degree    -4.8620     24.179     -0.201      0.841     -52.252      42.528
0 years                          0.8491      0.172      4.938      0.000       0.512       1.186
1-2 years                       -0.2471      0.111     -2.234      0.025      -0.464      -0.030
11-20 years                     -0.6779      1.016     -0.667      0.505      -2.669       1.313
3-5 years                       -0.1849      0.171     -1.079      0.281      -0.521       0.151
6-10 years                      -0.9014      0.719     -1.253      0.210      -2.311       0.508
================================================================================================
Production Occupations 2019

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
 81%|████████  | 73/90 [00:58<00:11,  1.45it/s]

df length: 52795
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.036062
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:                52795
Model:                          Logit   Df Residuals:                    52783
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01479
Time:                        23:57:05   Log-Likelihood:                -1903.9
converged:                      False   LL-Null:                       -1932.5
Covariance Type:            nonrobust   LLR p-value:                 3.094e-08
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -5.6056      0.105    -53.160      0.000      -5.812      -5.399
AI ROLE                        -12.9728    680.087     -0.019      0.985   -1345.918    1319.972
Associate degree                 0.8108      0.303      2.674      0.007       0.217       1.405
Bachelor's degree                1.0652      0.192      5.552      0.000       0.689       1.441
High school or GED               0.7060      0.133      5.324      0.000       0.446       0.966
Master's degree                  0.3942      0.717      0.550      0.582      -1.010       1.799
Ph.D. or professional degree     1.6584      1.015      1.633      0.102      -0.332       3.649
0 years                         -0.0107      0.363     -0.029      0.976      -0.723       0.701
1-2 years                        0.1740      0.143      1.220      0.223      -0.106       0.454
11-20 years                      0.1041      1.013      0.103      0.918      -1.882       2.090
3-5 years                        0.0467      0.168      0.278      0.781      -0.282       0.376
6-10 years                      -0.7210      0.463     -1.557      0.120      -1.629       0.187
================================================================================================
Production Occupations 2021

 82%|████████▏ | 74/90 [00:59<00:11,  1.43it/s]

df length: 77544
Optimization terminated successfully.
         Current function value: 0.093751
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:                77544
Model:                          Logit   Df Residuals:                    77532
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02065
Time:                        23:57:06   Log-Likelihood:                -7269.8
converged:                       True   LL-Null:                       -7423.1
Covariance Type:            nonrobust   LLR p-value:                 3.716e-59
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.4404      0.050    -89.577      0.000      -4.538      -4.343
AI ROLE                          0.4570      0.345      1.326      0.185      -0.218       1.133
Associate degree                 0.5898      0.161      3.656      0.000       0.274       0.906
Bachelor's degree                1.1940      0.091     13.170      0.000       1.016       1.372
High school or GED               0.6665      0.061     10.849      0.000       0.546       0.787
Master's degree                  0.5494      0.323      1.699      0.089      -0.084       1.183
Ph.D. or professional degree     0.9336      0.722      1.294      0.196      -0.481       2.348
0 years                         -0.3825      0.150     -2.554      0.011      -0.676      -0.089
1-2 years                        0.2105      0.066      3.176      0.001       0.081       0.340
11-20 years                     -0.7434      0.715     -1.039      0.299      -2.145       0.658
3-5 years                        0.2418      0.078      3.081      0.002       0.088       0.396
6-10 years                      -0.1989      0.185     -1.075      0.283      -0.562       0.164
================================================================================================
Production Occupations 2022

 83%|████████▎ | 75/90 [01:00<00:10,  1.40it/s]

df length: 80132
Optimization terminated successfully.
         Current function value: 0.129061
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:                80132
Model:                          Logit   Df Residuals:                    80120
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02646
Time:                        23:57:07   Log-Likelihood:                -10342.
converged:                       True   LL-Null:                       -10623.
Covariance Type:            nonrobust   LLR p-value:                1.751e-113
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.0879      0.040   -101.933      0.000      -4.167      -4.009
AI ROLE                          0.1303      0.277      0.470      0.639      -0.413       0.674
Associate degree                 0.7182      0.116      6.218      0.000       0.492       0.945
Bachelor's degree                1.1096      0.072     15.458      0.000       0.969       1.250
High school or GED               0.6687      0.050     13.377      0.000       0.571       0.767
Master's degree                  0.7599      0.226      3.359      0.001       0.317       1.203
Ph.D. or professional degree     1.1720      0.463      2.529      0.011       0.264       2.080
0 years                         -0.1982      0.117     -1.692      0.091      -0.428       0.031
1-2 years                        0.3651      0.053      6.838      0.000       0.260       0.470
11-20 years                      0.8475      0.253      3.352      0.001       0.352       1.343
3-5 years                        0.3112      0.062      5.007      0.000       0.189       0.433
6-10 years                       0.4201      0.110      3.828      0.000       0.205       0.635
================================================================================================
Production Occupations 2020
df length: 59540
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.053647
         Iterations: 35

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
 84%|████████▍ | 76/90 [01:00<00:10,  1.36it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:                59540
Model:                          Logit   Df Residuals:                    59528
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01983
Time:                        23:57:08   Log-Likelihood:                -3194.1
converged:                      False   LL-Null:                       -3258.7
Covariance Type:            nonrobust   LLR p-value:                 2.485e-22
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -5.0692      0.077    -65.636      0.000      -5.221      -4.918
AI ROLE                        -18.1450   6097.057     -0.003      0.998    -1.2e+04    1.19e+04
Associate degree                 0.6783      0.238      2.852      0.004       0.212       1.144
Bachelor's degree                1.2324      0.140      8.775      0.000       0.957       1.508
High school or GED               0.6121      0.098      6.241      0.000       0.420       0.804
Master's degree                  1.0242      0.419      2.443      0.015       0.203       1.846
Ph.D. or professional degree     1.2015      1.015      1.184      0.237      -0.788       3.191
0 years                         -0.8023      0.252     -3.186      0.001      -1.296      -0.309
1-2 years                        0.0901      0.110      0.818      0.413      -0.126       0.306
11-20 years                     -0.5521      1.009     -0.547      0.584      -2.531       1.426
3-5 years                        0.1775      0.125      1.422      0.155      -0.067       0.422
6-10 years                       0.1589      0.242      0.656      0.512      -0.316       0.634
================================================================================================
Production Occupations 2018

 86%|████████▌ | 77/90 [01:01<00:09,  1.40it/s]

df length: 53697
Optimization terminated successfully.
         Current function value: 0.012006
         Iterations 11
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:                53697
Model:                          Logit   Df Residuals:                    53685
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.06649
Time:                        23:57:08   Log-Likelihood:                -644.69
converged:                       True   LL-Null:                       -690.61
Covariance Type:            nonrobust   LLR p-value:                 7.271e-15
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -7.2508      0.229    -31.597      0.000      -7.701      -6.801
AI ROLE                          1.4933      0.759      1.968      0.049       0.006       2.981
Associate degree                -0.0126      1.032     -0.012      0.990      -2.036       2.011
Bachelor's degree                2.3778      0.312      7.627      0.000       1.767       2.989
High school or GED               0.9412      0.288      3.271      0.001       0.377       1.505
Master's degree                  2.1739      0.752      2.891      0.004       0.700       3.648
Ph.D. or professional degree     3.9598      0.792      4.997      0.000       2.407       5.513
0 years                          0.9565      0.439      2.179      0.029       0.096       1.817
1-2 years                       -0.2226      0.300     -0.741      0.459      -0.811       0.366
11-20 years                      1.3427      0.758      1.772      0.076      -0.142       2.828
3-5 years                       -0.1726      0.296     -0.583      0.560      -0.752       0.407
6-10 years                      -0.1429      0.496     -0.288      0.773      -1.114       0.828
================================================================================================
Production Occupations 2023

 87%|████████▋ | 78/90 [01:02<00:08,  1.41it/s]

df length: 63904
Optimization terminated successfully.
         Current function value: 0.182339
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:                63904
Model:                          Logit   Df Residuals:                    63892
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02720
Time:                        23:57:09   Log-Likelihood:                -11652.
converged:                       True   LL-Null:                       -11978.
Covariance Type:            nonrobust   LLR p-value:                1.227e-132
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.4999      0.035   -100.645      0.000      -3.568      -3.432
AI ROLE                         -0.1812      0.313     -0.579      0.563      -0.795       0.432
Associate degree                 1.1133      0.091     12.263      0.000       0.935       1.291
Bachelor's degree                1.3088      0.061     21.288      0.000       1.188       1.429
High school or GED               0.5080      0.045     11.353      0.000       0.420       0.596
Master's degree                  0.3350      0.250      1.339      0.180      -0.155       0.825
Ph.D. or professional degree     0.0197      0.720      0.027      0.978      -1.391       1.431
0 years                         -0.1484      0.105     -1.417      0.156      -0.353       0.057
1-2 years                        0.1915      0.049      3.947      0.000       0.096       0.287
11-20 years                      0.4518      0.245      1.846      0.065      -0.028       0.931
3-5 years                        0.1213      0.056      2.184      0.029       0.012       0.230
6-10 years                       0.1438      0.101      1.422      0.155      -0.054       0.342
================================================================================================
Sales and Related Occupations 2019
df length: 185705

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
 88%|████████▊ | 79/90 [01:03<00:09,  1.11it/s]

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.064331
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:               185705
Model:                          Logit   Df Residuals:                   185693
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01698
Time:                        23:57:10   Log-Likelihood:                -11947.
converged:                      False   LL-Null:                       -12153.
Covariance Type:            nonrobust   LLR p-value:                 1.242e-81
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.6285      0.036   -129.013      0.000      -4.699      -4.558
AI ROLE                         -0.0179      0.358     -0.050      0.960      -0.720       0.684
Associate degree                 0.5475      0.130      4.202      0.000       0.292       0.803
Bachelor's degree                0.7391      0.063     11.764      0.000       0.616       0.862
High school or GED               0.6978      0.050     13.874      0.000       0.599       0.796
Master's degree                 -0.6606      0.503     -1.314      0.189      -1.646       0.324
Ph.D. or professional degree    -9.6977    144.447     -0.067      0.946    -292.809     273.414
0 years                         -1.8458      0.225     -8.190      0.000      -2.288      -1.404
1-2 years                       -0.4842      0.058     -8.299      0.000      -0.599      -0.370
11-20 years                     -0.8678      0.582     -1.492      0.136      -2.008       0.272
3-5 years                       -0.1161      0.070     -1.654      0.098      -0.254       0.022
6-10 years                      -0.5011      0.167     -2.999      0.003      -0.829      -0.174
================================================================================================
Sales and Related Occupations 2021
df length: 207667

 89%|████████▉ | 80/90 [01:04<00:09,  1.04it/s]

Optimization terminated successfully.
         Current function value: 0.156075
         Iterations 9
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:               207667
Model:                          Logit   Df Residuals:                   207655
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02406
Time:                        23:57:11   Log-Likelihood:                -32412.
converged:                       True   LL-Null:                       -33211.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.7386      0.022   -172.006      0.000      -3.781      -3.696
AI ROLE                          0.3485      0.158      2.202      0.028       0.038       0.659
Associate degree                 0.9266      0.066     13.963      0.000       0.797       1.057
Bachelor's degree                0.5957      0.039     15.268      0.000       0.519       0.672
High school or GED               0.8794      0.028     31.943      0.000       0.825       0.933
Master's degree                 -0.8191      0.270     -3.039      0.002      -1.347      -0.291
Ph.D. or professional degree    -0.2051      0.715     -0.287      0.774      -1.606       1.196
0 years                         -1.1471      0.103    -11.100      0.000      -1.350      -0.945
1-2 years                        0.1241      0.028      4.470      0.000       0.070       0.179
11-20 years                     -0.5388      0.293     -1.839      0.066      -1.113       0.035
3-5 years                        0.0264      0.040      0.653      0.514      -0.053       0.106
6-10 years                       0.1113      0.085      1.307      0.191      -0.056       0.278
================================================================================================
Sales and Related Occupations 2022
df length: 216216

 90%|█████████ | 81/90 [01:05<00:09,  1.01s/it]

Optimization terminated successfully.
         Current function value: 0.192143
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:               216216
Model:                          Logit   Df Residuals:                   216204
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02182
Time:                        23:57:12   Log-Likelihood:                -41544.
converged:                       True   LL-Null:                       -42471.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.3936      0.018   -193.883      0.000      -3.428      -3.359
AI ROLE                          0.7612      0.105      7.235      0.000       0.555       0.967
Associate degree                 0.7271      0.053     13.694      0.000       0.623       0.831
Bachelor's degree                0.5643      0.031     18.044      0.000       0.503       0.626
High school or GED               0.5082      0.024     21.282      0.000       0.461       0.555
Master's degree                 -0.3687      0.186     -1.983      0.047      -0.733      -0.004
Ph.D. or professional degree     0.2654      0.390      0.680      0.497      -0.500       1.031
0 years                         -0.9231      0.085    -10.869      0.000      -1.090      -0.757
1-2 years                        0.4126      0.024     17.101      0.000       0.365       0.460
11-20 years                     -0.3866      0.273     -1.414      0.157      -0.922       0.149
3-5 years                        0.2964      0.033      9.014      0.000       0.232       0.361
6-10 years                       0.5477      0.061      9.002      0.000       0.428       0.667
================================================================================================
Sales and Related Occupations 2020
df length: 180255
Optimization terminated successfully.
         Current function value: 0.082859
         Iterations 10

 91%|█████████ | 82/90 [01:06<00:08,  1.01s/it]

                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:               180255
Model:                          Logit   Df Residuals:                   180243
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01240
Time:                        23:57:13   Log-Likelihood:                -14936.
converged:                       True   LL-Null:                       -15123.
Covariance Type:            nonrobust   LLR p-value:                 1.266e-73
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.3288      0.030   -145.380      0.000      -4.387      -4.270
AI ROLE                          0.6107      0.230      2.653      0.008       0.160       1.062
Associate degree                 0.7002      0.107      6.526      0.000       0.490       0.910
Bachelor's degree                0.5474      0.059      9.231      0.000       0.431       0.664
High school or GED               0.5221      0.043     12.247      0.000       0.439       0.606
Master's degree                 -0.4395      0.381     -1.154      0.248      -1.186       0.307
Ph.D. or professional degree    -0.1162      1.006     -0.116      0.908      -2.089       1.856
0 years                         -1.4233      0.160     -8.878      0.000      -1.738      -1.109
1-2 years                        0.0883      0.046      1.933      0.053      -0.001       0.178
11-20 years                     -2.2131      1.002     -2.208      0.027      -4.177      -0.249
3-5 years                       -0.1169      0.068     -1.720      0.085      -0.250       0.016
6-10 years                      -0.2641      0.154     -1.718      0.086      -0.565       0.037
================================================================================================
Sales and Related Occupations 2018
df length: 170255
Optimization terminated successfully.
         Current function value: 0.046647
         Iterations 11

 92%|█████████▏| 83/90 [01:07<00:07,  1.01s/it]

                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:               170255
Model:                          Logit   Df Residuals:                   170243
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02079
Time:                        23:57:14   Log-Likelihood:                -7942.0
converged:                       True   LL-Null:                       -8110.6
Covariance Type:            nonrobust   LLR p-value:                 1.194e-65
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.9952      0.045   -111.195      0.000      -5.083      -4.907
AI ROLE                         -0.2316      0.581     -0.398      0.690      -1.371       0.908
Associate degree                -0.0120      0.207     -0.058      0.954      -0.418       0.394
Bachelor's degree                0.4907      0.086      5.709      0.000       0.322       0.659
High school or GED               0.8785      0.062     14.274      0.000       0.758       0.999
Master's degree                 -0.5674      0.710     -0.799      0.424      -1.959       0.824
Ph.D. or professional degree     1.3704      0.717      1.911      0.056      -0.035       2.776
0 years                         -2.4081      0.449     -5.367      0.000      -3.287      -1.529
1-2 years                       -0.8140      0.081    -10.000      0.000      -0.974      -0.654
11-20 years                     -0.6162      0.712     -0.866      0.387      -2.011       0.779
3-5 years                       -0.1843      0.092     -2.001      0.045      -0.365      -0.004
6-10 years                      -0.9097      0.258     -3.532      0.000      -1.415      -0.405
================================================================================================
Sales and Related Occupations 2023
df length: 183257
Optimization terminated successfully.
         Current function value: 0.269294
         Iterations 8

 93%|█████████▎| 84/90 [01:08<00:06,  1.01s/it]

                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:               183257
Model:                          Logit   Df Residuals:                   183245
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.03090
Time:                        23:57:15   Log-Likelihood:                -49350.
converged:                       True   LL-Null:                       -50924.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.7904      0.015   -191.706      0.000      -2.819      -2.762
AI ROLE                          0.5687      0.110      5.152      0.000       0.352       0.785
Associate degree                 1.4461      0.038     37.751      0.000       1.371       1.521
Bachelor's degree                0.9490      0.026     36.165      0.000       0.898       1.000
High school or GED               0.3605      0.021     16.945      0.000       0.319       0.402
Master's degree                 -0.2799      0.176     -1.587      0.113      -0.626       0.066
Ph.D. or professional degree    -0.8264      0.587     -1.408      0.159      -1.976       0.324
0 years                         -1.0446      0.068    -15.330      0.000      -1.178      -0.911
1-2 years                        0.0697      0.022      3.144      0.002       0.026       0.113
11-20 years                      0.3651      0.144      2.530      0.011       0.082       0.648
3-5 years                        0.0933      0.028      3.293      0.001       0.038       0.149
6-10 years                       0.2872      0.055      5.260      0.000       0.180       0.394
================================================================================================
Transportation and Material Moving Occupations 2019
df length: 92120

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
 94%|█████████▍| 85/90 [01:09<00:04,  1.03it/s]

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.035348
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:                92120
Model:                          Logit   Df Residuals:                    92108
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.006514
Time:                        23:57:16   Log-Likelihood:                -3256.3
converged:                      False   LL-Null:                       -3277.6
Covariance Type:            nonrobust   LLR p-value:                 1.223e-05
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -5.0934      0.056    -90.376      0.000      -5.204      -4.983
AI ROLE                        -15.8073   6008.575     -0.003      0.998   -1.18e+04    1.18e+04
Associate degree                -0.4232      0.713     -0.593      0.553      -1.821       0.974
Bachelor's degree                0.3843      0.333      1.155      0.248      -0.268       1.037
High school or GED               0.1971      0.094      2.097      0.036       0.013       0.381
Master's degree                  0.3721      1.006      0.370      0.711      -1.599       2.344
Ph.D. or professional degree   -17.8834   1.73e+04     -0.001      0.999   -3.38e+04    3.38e+04
0 years                         -1.0328      0.320     -3.225      0.001      -1.660      -0.405
1-2 years                       -0.6506      0.143     -4.540      0.000      -0.931      -0.370
11-20 years                     -7.3758     62.385     -0.118      0.906    -129.648     114.896
3-5 years                        0.0762      0.196      0.388      0.698      -0.309       0.461
6-10 years                      -0.0552      0.592     -0.093      0.926      -1.216       1.106
================================================================================================
Transportation and Material Moving Occupations 2021
df length: 168157

 96%|█████████▌| 86/90 [01:10<00:03,  1.01it/s]

Optimization terminated successfully.
         Current function value: 0.162683
         Iterations 17
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:               168157
Model:                          Logit   Df Residuals:                   168145
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02548
Time:                        23:57:17   Log-Likelihood:                -27356.
converged:                       True   LL-Null:                       -28071.
Covariance Type:            nonrobust   LLR p-value:                3.471e-300
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.1057      0.017   -186.496      0.000      -3.138      -3.073
AI ROLE                         -0.2230      0.429     -0.520      0.603      -1.064       0.618
Associate degree                 1.9464      0.108     17.940      0.000       1.734       2.159
Bachelor's degree                1.2812      0.096     13.322      0.000       1.093       1.470
High school or GED               0.3113      0.026     11.798      0.000       0.260       0.363
Master's degree                 -1.1458      0.582     -1.970      0.049      -2.286      -0.006
Ph.D. or professional degree     0.4200      1.028      0.408      0.683      -1.595       2.435
0 years                         -1.0871      0.080    -13.517      0.000      -1.245      -0.929
1-2 years                       -1.0766      0.045    -23.826      0.000      -1.165      -0.988
11-20 years                   -684.3342  1.44e+148 -4.76e-146      1.000  -2.82e+148   2.82e+148
3-5 years                       -1.3998      0.104    -13.476      0.000      -1.603      -1.196
6-10 years                      -1.6883      0.341     -4.948      0.000      -2.357      -1.020
================================================================================================
Transportation and Material Moving Occupations 2022
df length: 136730

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
 97%|█████████▋| 87/90 [01:11<00:03,  1.02s/it]

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.228750
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:               136730
Model:                          Logit   Df Residuals:                   136718
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.03012
Time:                        23:57:19   Log-Likelihood:                -31277.
converged:                      False   LL-Null:                       -32248.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.4045      0.013   -182.109      0.000      -2.430      -2.379
AI ROLE                          0.4275      0.305      1.402      0.161      -0.170       1.025
Associate degree                 1.4116      0.091     15.455      0.000       1.233       1.591
Bachelor's degree                0.8872      0.080     11.064      0.000       0.730       1.044
High school or GED              -0.4364      0.029    -14.945      0.000      -0.494      -0.379
Master's degree                 -1.5712      0.505     -3.113      0.002      -2.560      -0.582
Ph.D. or professional degree    -7.5481     29.350     -0.257      0.797     -65.072      49.976
0 years                         -1.3620      0.080    -17.043      0.000      -1.519      -1.205
1-2 years                       -0.8801      0.038    -23.386      0.000      -0.954      -0.806
11-20 years                     -1.9051      0.717     -2.657      0.008      -3.310      -0.500
3-5 years                       -1.2997      0.083    -15.642      0.000      -1.463      -1.137
6-10 years                      -1.2904      0.237     -5.438      0.000      -1.755      -0.825
================================================================================================
Transportation and Material Moving Occupations 2020
df length: 141154

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
 98%|█████████▊| 88/90 [01:12<00:02,  1.05s/it]

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.069623
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:               141154
Model:                          Logit   Df Residuals:                   141142
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.03821
Time:                        23:57:20   Log-Likelihood:                -9827.6
converged:                      False   LL-Null:                       -10218.
Covariance Type:            nonrobust   LLR p-value:                2.449e-160
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.9275      0.028   -142.149      0.000      -3.982      -3.873
AI ROLE                          0.5441      1.016      0.535      0.592      -1.448       2.536
Associate degree                -0.1319      0.413     -0.319      0.749      -0.942       0.678
Bachelor's degree               -0.3151      0.310     -1.016      0.310      -0.923       0.293
High school or GED              -0.0488      0.053     -0.923      0.356      -0.153       0.055
Master's degree                -24.1184   1.06e+05     -0.000      1.000   -2.07e+05    2.07e+05
Ph.D. or professional degree   -14.4395   1998.089     -0.007      0.994   -3930.623    3901.744
0 years                         -3.1784      0.237    -13.385      0.000      -3.644      -2.713
1-2 years                       -1.0570      0.085    -12.483      0.000      -1.223      -0.891
11-20 years                     -8.0268     38.141     -0.210      0.833     -82.781      66.728
3-5 years                       -0.8173      0.166     -4.929      0.000      -1.142      -0.492
6-10 years                      -0.2537      0.387     -0.655      0.512      -1.013       0.505
================================================================================================
Transportation and Material Moving Occupations 2018
df length: 111268

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
 99%|█████████▉| 89/90 [01:13<00:01,  1.03s/it]

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.013360
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:               111268
Model:                          Logit   Df Residuals:                   111256
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01434
Time:                        23:57:21   Log-Likelihood:                -1486.6
converged:                      False   LL-Null:                       -1508.2
Covariance Type:            nonrobust   LLR p-value:                 9.802e-06
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -6.1040      0.081    -75.257      0.000      -6.263      -5.945
AI ROLE                          2.3169      1.037      2.235      0.025       0.285       4.349
Associate degree                 0.3819      1.014      0.377      0.706      -1.605       2.369
Bachelor's degree                1.1733      0.446      2.631      0.009       0.299       2.047
High school or GED              -0.1011      0.182     -0.556      0.578      -0.457       0.255
Master's degree                  1.5609      1.008      1.548      0.122      -0.415       3.537
Ph.D. or professional degree   -13.6423   2642.503     -0.005      0.996   -5192.854    5165.569
0 years                         -1.2473      0.582     -2.142      0.032      -2.389      -0.106
1-2 years                       -1.2749      0.300     -4.244      0.000      -1.864      -0.686
11-20 years                    -28.2631   2.52e+06  -1.12e-05      1.000   -4.94e+06    4.94e+06
3-5 years                       -0.6489      0.431     -1.507      0.132      -1.493       0.195
6-10 years                      -0.1638      0.739     -0.222      0.825      -1.612       1.284
================================================================================================
Transportation and Material Moving Occupations 2023
df length: 110719
Optimization terminated successfully.
         Current function value: 0.226010
         Iterations 8

100%|██████████| 90/90 [01:14<00:00,  1.20it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:         PARENTAL_LEAVE   No. Observations:               110719
Model:                          Logit   Df Residuals:                   110707
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.06144
Time:                        23:57:21   Log-Likelihood:                -25024.
converged:                       True   LL-Null:                       -26662.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.6677      0.017   -160.842      0.000      -2.700      -2.635
AI ROLE                         -0.8265      0.529     -1.562      0.118      -1.864       0.211
Associate degree                 3.0651      0.062     49.797      0.000       2.945       3.186
Bachelor's degree                1.8980      0.060     31.694      0.000       1.781       2.015
High school or GED               0.1786      0.029      6.179      0.000       0.122       0.235
Master's degree                 -0.5341      0.456     -1.171      0.241      -1.428       0.360
Ph.D. or professional degree    -0.7128      1.016     -0.702      0.483      -2.704       1.278
0 years                         -0.9769      0.070    -14.028      0.000      -1.113      -0.840
1-2 years                       -0.6555      0.037    -17.771      0.000      -0.728      -0.583
11-20 years                     -1.5147      0.602     -2.516      0.012      -2.694      -0.335
3-5 years                       -0.9193      0.072    -12.750      0.000      -1.061      -0.778
6-10 years                      -1.8715      0.237     -7.909      0.000      -2.335      -1.408
================================================================================================
CULTURE

  0%|          | 0/90 [00:00<?, ?it/s]

Architecture and Engineering Occupations 2019

  1%|          | 1/90 [00:00<00:57,  1.55it/s]

df length: 42432
Optimization terminated successfully.
         Current function value: 0.212772
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:                42432
Model:                          Logit   Df Residuals:                    42420
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01007
Time:                        23:57:22   Log-Likelihood:                -9028.4
converged:                       True   LL-Null:                       -9120.2
Covariance Type:            nonrobust   LLR p-value:                 1.739e-33
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.1703      0.050    -63.632      0.000      -3.268      -3.073
AI ROLE                          0.5687      0.114      4.969      0.000       0.344       0.793
Associate degree                 0.3022      0.097      3.118      0.002       0.112       0.492
Bachelor's degree                0.4547      0.058      7.889      0.000       0.342       0.568
High school or GED               0.2360      0.080      2.935      0.003       0.078       0.394
Master's degree                  0.8684      0.121      7.153      0.000       0.630       1.106
Ph.D. or professional degree     1.3883      0.168      8.287      0.000       1.060       1.717
0 years                         -0.1557      0.142     -1.099      0.272      -0.434       0.122
1-2 years                        0.0049      0.068      0.073      0.942      -0.129       0.139
11-20 years                      0.1201      0.138      0.873      0.382      -0.149       0.390
3-5 years                       -0.0963      0.056     -1.721      0.085      -0.206       0.013
6-10 years                       0.1299      0.065      2.003      0.045       0.003       0.257
================================================================================================
Architecture and Engineering Occupations 2021

  2%|▏         | 2/90 [00:01<00:56,  1.57it/s]

df length: 42098
Optimization terminated successfully.
         Current function value: 0.324531
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:                42098
Model:                          Logit   Df Residuals:                    42086
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.03037
Time:                        23:57:23   Log-Likelihood:                -13662.
converged:                       True   LL-Null:                       -14090.
Covariance Type:            nonrobust   LLR p-value:                2.045e-176
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.8757      0.043    -66.451      0.000      -2.961      -2.791
AI ROLE                          0.8819      0.079     11.197      0.000       0.728       1.036
Associate degree                 0.5254      0.074      7.083      0.000       0.380       0.671
Bachelor's degree                0.9005      0.048     18.659      0.000       0.806       0.995
High school or GED               0.2571      0.065      3.970      0.000       0.130       0.384
Master's degree                  1.0819      0.103     10.527      0.000       0.880       1.283
Ph.D. or professional degree     1.6520      0.143     11.582      0.000       1.372       1.932
0 years                          0.1058      0.100      1.054      0.292      -0.091       0.303
1-2 years                       -0.0095      0.053     -0.178      0.859      -0.114       0.095
11-20 years                      0.4318      0.092      4.697      0.000       0.252       0.612
3-5 years                        0.1370      0.042      3.229      0.001       0.054       0.220
6-10 years                       0.1669      0.051      3.251      0.001       0.066       0.268
================================================================================================
Architecture and Engineering Occupations 2022

  3%|▎         | 3/90 [00:01<00:56,  1.54it/s]

df length: 57103
Optimization terminated successfully.
         Current function value: 0.418020
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:                57103
Model:                          Logit   Df Residuals:                    57091
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.04222
Time:                        23:57:23   Log-Likelihood:                -23870.
converged:                       True   LL-Null:                       -24922.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.5875      0.032    -80.816      0.000      -2.650      -2.525
AI ROLE                          0.9059      0.059     15.405      0.000       0.791       1.021
Associate degree                 0.6828      0.053     12.788      0.000       0.578       0.787
Bachelor's degree                0.9732      0.035     27.445      0.000       0.904       1.043
High school or GED               0.3678      0.049      7.517      0.000       0.272       0.464
Master's degree                  0.9637      0.081     11.970      0.000       0.806       1.121
Ph.D. or professional degree     1.5513      0.120     12.882      0.000       1.315       1.787
0 years                         -0.2017      0.085     -2.371      0.018      -0.368      -0.035
1-2 years                        0.1433      0.039      3.674      0.000       0.067       0.220
11-20 years                      0.7910      0.061     13.053      0.000       0.672       0.910
3-5 years                        0.2700      0.032      8.523      0.000       0.208       0.332
6-10 years                       0.4155      0.037     11.253      0.000       0.343       0.488
================================================================================================
Architecture and Engineering Occupations 2020

  4%|▍         | 4/90 [00:02<00:54,  1.57it/s]

df length: 33522
Optimization terminated successfully.
         Current function value: 0.240290
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:                33522
Model:                          Logit   Df Residuals:                    33510
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02152
Time:                        23:57:24   Log-Likelihood:                -8055.0
converged:                       True   LL-Null:                       -8232.2
Covariance Type:            nonrobust   LLR p-value:                 2.965e-69
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.0897      0.053    -58.467      0.000      -3.193      -2.986
AI ROLE                          0.9932      0.105      9.421      0.000       0.787       1.200
Associate degree                 0.5481      0.097      5.645      0.000       0.358       0.738
Bachelor's degree                0.6547      0.061     10.688      0.000       0.535       0.775
High school or GED               0.2456      0.084      2.921      0.003       0.081       0.410
Master's degree                  1.0382      0.122      8.477      0.000       0.798       1.278
Ph.D. or professional degree     1.6630      0.164     10.127      0.000       1.341       1.985
0 years                         -0.3657      0.170     -2.154      0.031      -0.698      -0.033
1-2 years                       -0.0859      0.072     -1.198      0.231      -0.226       0.055
11-20 years                      0.3647      0.119      3.060      0.002       0.131       0.598
3-5 years                       -0.1281      0.058     -2.218      0.027      -0.241      -0.015
6-10 years                       0.0312      0.069      0.454      0.650      -0.103       0.166
================================================================================================
Architecture and Engineering Occupations 2018

  6%|▌         | 5/90 [00:03<00:53,  1.59it/s]

df length: 40569
Optimization terminated successfully.
         Current function value: 0.190743
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:                40569
Model:                          Logit   Df Residuals:                    40557
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.006015
Time:                        23:57:25   Log-Likelihood:                -7738.3
converged:                       True   LL-Null:                       -7785.1
Covariance Type:            nonrobust   LLR p-value:                 3.206e-15
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.2736      0.052    -63.346      0.000      -3.375      -3.172
AI ROLE                          0.3451      0.154      2.234      0.025       0.042       0.648
Associate degree                 0.4187      0.096      4.382      0.000       0.231       0.606
Bachelor's degree                0.3990      0.062      6.469      0.000       0.278       0.520
High school or GED               0.0315      0.093      0.340      0.734      -0.150       0.213
Master's degree                  0.3208      0.159      2.015      0.044       0.009       0.633
Ph.D. or professional degree     1.1697      0.207      5.652      0.000       0.764       1.575
0 years                         -0.2218      0.169     -1.310      0.190      -0.554       0.110
1-2 years                       -0.0150      0.075     -0.199      0.843      -0.163       0.133
11-20 years                      0.1525      0.161      0.950      0.342      -0.162       0.467
3-5 years                        0.0470      0.060      0.783      0.433      -0.071       0.165
6-10 years                       0.0087      0.077      0.113      0.910      -0.142       0.159
================================================================================================
Architecture and Engineering Occupations 2023

  7%|▋         | 6/90 [00:03<00:53,  1.58it/s]

df length: 46241
Optimization terminated successfully.
         Current function value: 0.448615
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:                46241
Model:                          Logit   Df Residuals:                    46229
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01853
Time:                        23:57:25   Log-Likelihood:                -20744.
converged:                       True   LL-Null:                       -21136.
Covariance Type:            nonrobust   LLR p-value:                7.170e-161
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.1964      0.032    -68.324      0.000      -2.259      -2.133
AI ROLE                          0.6202      0.069      9.026      0.000       0.486       0.755
Associate degree                 0.6284      0.053     11.790      0.000       0.524       0.733
Bachelor's degree                0.6155      0.036     17.228      0.000       0.546       0.686
High school or GED               0.2272      0.049      4.621      0.000       0.131       0.324
Master's degree                  0.7113      0.091      7.856      0.000       0.534       0.889
Ph.D. or professional degree     1.0456      0.131      7.972      0.000       0.789       1.303
0 years                          0.0870      0.077      1.130      0.259      -0.064       0.238
1-2 years                        0.1524      0.041      3.712      0.000       0.072       0.233
11-20 years                      0.3421      0.069      4.951      0.000       0.207       0.477
3-5 years                        0.1858      0.033      5.547      0.000       0.120       0.251
6-10 years                       0.3521      0.039      8.964      0.000       0.275       0.429
================================================================================================
Arts, Design, Entertainment, Sports, and Media Occupations 2019

  8%|▊         | 7/90 [00:04<00:52,  1.58it/s]

df length: 40594
Optimization terminated successfully.
         Current function value: 0.191182
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:                40594
Model:                          Logit   Df Residuals:                    40582
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02235
Time:                        23:57:26   Log-Likelihood:                -7760.9
converged:                       True   LL-Null:                       -7938.3
Covariance Type:            nonrobust   LLR p-value:                 2.329e-69
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.2929      0.040    -82.960      0.000      -3.371      -3.215
AI ROLE                          0.2599      0.201      1.290      0.197      -0.135       0.655
Associate degree                -0.1188      0.156     -0.761      0.447      -0.425       0.187
Bachelor's degree                0.5026      0.057      8.894      0.000       0.392       0.613
High school or GED              -0.1457      0.075     -1.945      0.052      -0.292       0.001
Master's degree                  0.6365      0.165      3.851      0.000       0.313       0.960
Ph.D. or professional degree     0.8398      0.295      2.846      0.004       0.261       1.418
0 years                         -0.8756      0.256     -3.426      0.001      -1.376      -0.375
1-2 years                        0.2975      0.065      4.594      0.000       0.171       0.424
11-20 years                      0.7082      0.201      3.515      0.000       0.313       1.103
3-5 years                        0.3478      0.064      5.459      0.000       0.223       0.473
6-10 years                       0.6935      0.090      7.727      0.000       0.518       0.869
================================================================================================
Arts, Design, Entertainment, Sports, and Media Occupations 2021

  9%|▉         | 8/90 [00:05<00:51,  1.58it/s]

df length: 49779
Optimization terminated successfully.
         Current function value: 0.266759
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:                49779
Model:                          Logit   Df Residuals:                    49767
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.04971
Time:                        23:57:26   Log-Likelihood:                -13279.
converged:                       True   LL-Null:                       -13974.
Covariance Type:            nonrobust   LLR p-value:                2.669e-291
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.8881      0.029    -98.705      0.000      -2.945      -2.831
AI ROLE                          0.7370      0.126      5.854      0.000       0.490       0.984
Associate degree                 0.1197      0.102      1.178      0.239      -0.080       0.319
Bachelor's degree                0.5510      0.042     13.154      0.000       0.469       0.633
High school or GED              -0.1611      0.051     -3.142      0.002      -0.262      -0.061
Master's degree                  0.7877      0.137      5.740      0.000       0.519       1.057
Ph.D. or professional degree     0.3611      0.288      1.253      0.210      -0.204       0.926
0 years                         -0.7708      0.165     -4.675      0.000      -1.094      -0.448
1-2 years                        0.3798      0.048      7.960      0.000       0.286       0.473
11-20 years                      1.6570      0.147     11.238      0.000       1.368       1.946
3-5 years                        0.7336      0.046     15.871      0.000       0.643       0.824
6-10 years                       1.1156      0.064     17.409      0.000       0.990       1.241
================================================================================================
Arts, Design, Entertainment, Sports, and Media Occupations 2022

 10%|█         | 9/90 [00:05<00:51,  1.56it/s]

df length: 54182
Optimization terminated successfully.
         Current function value: 0.332120
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:                54182
Model:                          Logit   Df Residuals:                    54170
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.07008
Time:                        23:57:27   Log-Likelihood:                -17995.
converged:                       True   LL-Null:                       -19351.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.7885      0.025   -109.728      0.000      -2.838      -2.739
AI ROLE                          0.5069      0.106      4.763      0.000       0.298       0.715
Associate degree                 0.3777      0.079      4.804      0.000       0.224       0.532
Bachelor's degree                0.8831      0.036     24.784      0.000       0.813       0.953
High school or GED               0.4109      0.042      9.700      0.000       0.328       0.494
Master's degree                  1.2095      0.113     10.685      0.000       0.988       1.431
Ph.D. or professional degree     0.8485      0.218      3.884      0.000       0.420       1.277
0 years                         -0.4780      0.116     -4.137      0.000      -0.705      -0.252
1-2 years                        0.5912      0.040     14.960      0.000       0.514       0.669
11-20 years                      2.0041      0.120     16.763      0.000       1.770       2.238
3-5 years                        0.7742      0.038     20.194      0.000       0.699       0.849
6-10 years                       0.9581      0.055     17.366      0.000       0.850       1.066
================================================================================================
Arts, Design, Entertainment, Sports, and Media Occupations 2020

 11%|█         | 10/90 [00:06<00:50,  1.58it/s]

df length: 39617
Optimization terminated successfully.
         Current function value: 0.156236
         Iterations 9
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:                39617
Model:                          Logit   Df Residuals:                    39605
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.06042
Time:                        23:57:28   Log-Likelihood:                -6189.6
converged:                       True   LL-Null:                       -6587.6
Covariance Type:            nonrobust   LLR p-value:                1.381e-163
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.5824      0.046    -78.122      0.000      -3.672      -3.492
AI ROLE                          0.9980      0.184      5.424      0.000       0.637       1.359
Associate degree                 0.3547      0.154      2.304      0.021       0.053       0.656
Bachelor's degree                0.6226      0.065      9.561      0.000       0.495       0.750
High school or GED              -0.6289      0.090     -7.022      0.000      -0.804      -0.453
Master's degree                  0.9432      0.177      5.319      0.000       0.596       1.291
Ph.D. or professional degree     0.7127      0.341      2.093      0.036       0.045       1.380
0 years                         -0.7462      0.249     -2.996      0.003      -1.234      -0.258
1-2 years                        0.4264      0.076      5.606      0.000       0.277       0.576
11-20 years                      1.4220      0.218      6.525      0.000       0.995       1.849
3-5 years                        0.6425      0.073      8.787      0.000       0.499       0.786
6-10 years                       1.0972      0.096     11.484      0.000       0.910       1.284
================================================================================================
Arts, Design, Entertainment, Sports, and Media Occupations 2018

 12%|█▏        | 11/90 [00:06<00:49,  1.60it/s]

df length: 37105
Optimization terminated successfully.
         Current function value: 0.166930
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:                37105
Model:                          Logit   Df Residuals:                    37093
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01744
Time:                        23:57:28   Log-Likelihood:                -6193.9
converged:                       True   LL-Null:                       -6303.8
Covariance Type:            nonrobust   LLR p-value:                 5.620e-41
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.5272      0.046    -76.983      0.000      -3.617      -3.437
AI ROLE                          0.3373      0.267      1.264      0.206      -0.186       0.861
Associate degree                 0.2456      0.164      1.498      0.134      -0.076       0.567
Bachelor's degree                0.7226      0.066     10.959      0.000       0.593       0.852
High school or GED               0.2371      0.082      2.883      0.004       0.076       0.398
Master's degree                  0.7950      0.199      3.993      0.000       0.405       1.185
Ph.D. or professional degree     0.6826      0.368      1.856      0.063      -0.038       1.403
0 years                         -0.6152      0.295     -2.084      0.037      -1.194      -0.037
1-2 years                        0.0122      0.075      0.162      0.872      -0.136       0.160
11-20 years                      0.0798      0.287      0.278      0.781      -0.484       0.643
3-5 years                        0.1424      0.074      1.929      0.054      -0.002       0.287
6-10 years                       0.3812      0.104      3.681      0.000       0.178       0.584
================================================================================================
Arts, Design, Entertainment, Sports, and Media Occupations 2023

 13%|█▎        | 12/90 [00:07<00:48,  1.62it/s]

df length: 40306
Optimization terminated successfully.
         Current function value: 0.333398
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:                40306
Model:                          Logit   Df Residuals:                    40294
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.05722
Time:                        23:57:29   Log-Likelihood:                -13438.
converged:                       True   LL-Null:                       -14253.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.6985      0.028    -96.838      0.000      -2.753      -2.644
AI ROLE                          0.1484      0.120      1.239      0.215      -0.086       0.383
Associate degree                 0.4051      0.091      4.450      0.000       0.227       0.584
Bachelor's degree                0.9017      0.041     21.781      0.000       0.821       0.983
High school or GED               0.4675      0.048      9.730      0.000       0.373       0.562
Master's degree                  1.1184      0.136      8.194      0.000       0.851       1.386
Ph.D. or professional degree     1.2819      0.208      6.167      0.000       0.874       1.689
0 years                         -0.6058      0.135     -4.500      0.000      -0.870      -0.342
1-2 years                        0.5253      0.045     11.566      0.000       0.436       0.614
11-20 years                      0.9861      0.154      6.419      0.000       0.685       1.287
3-5 years                        0.5845      0.046     12.826      0.000       0.495       0.674
6-10 years                       0.9167      0.063     14.497      0.000       0.793       1.041
================================================================================================
Business and Financial Operations Occupations 2019
df length: 141921
Optimization terminated successfully.
         Current function value: 0.236435
         Iterations 7

 14%|█▍        | 13/90 [00:08<00:55,  1.40it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:               141921
Model:                          Logit   Df Residuals:                   141909
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.007150
Time:                        23:57:30   Log-Likelihood:                -33555.
converged:                       True   LL-Null:                       -33797.
Covariance Type:            nonrobust   LLR p-value:                 1.170e-96
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.0450      0.024   -125.499      0.000      -3.093      -2.997
AI ROLE                          0.4877      0.070      7.002      0.000       0.351       0.624
Associate degree                 0.1166      0.065      1.791      0.073      -0.011       0.244
Bachelor's degree                0.4386      0.028     15.533      0.000       0.383       0.494
High school or GED               0.3619      0.040      9.123      0.000       0.284       0.440
Master's degree                  0.5107      0.080      6.362      0.000       0.353       0.668
Ph.D. or professional degree     0.0285      0.225      0.126      0.899      -0.413       0.470
0 years                         -0.1411      0.092     -1.541      0.123      -0.321       0.038
1-2 years                       -0.0047      0.032     -0.148      0.882      -0.067       0.058
11-20 years                      0.2655      0.098      2.701      0.007       0.073       0.458
3-5 years                        0.1288      0.028      4.576      0.000       0.074       0.184
6-10 years                       0.1543      0.039      3.969      0.000       0.078       0.230
================================================================================================
Business and Financial Operations Occupations 2021
df length: 158377
Optimization terminated successfully.
         Current function value: 0.369083
         Iterations 6

 16%|█▌        | 14/90 [00:09<01:00,  1.26it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:               158377
Model:                          Logit   Df Residuals:                   158365
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01453
Time:                        23:57:31   Log-Likelihood:                -58454.
converged:                       True   LL-Null:                       -59316.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.3310      0.017   -134.444      0.000      -2.365      -2.297
AI ROLE                          0.5924      0.044     13.526      0.000       0.507       0.678
Associate degree                -0.1300      0.045     -2.920      0.004      -0.217      -0.043
Bachelor's degree                0.2311      0.019     11.872      0.000       0.193       0.269
High school or GED               0.0765      0.027      2.841      0.005       0.024       0.129
Master's degree                  0.7709      0.055     13.981      0.000       0.663       0.879
Ph.D. or professional degree     0.8873      0.103      8.578      0.000       0.685       1.090
0 years                          0.0395      0.064      0.612      0.540      -0.087       0.166
1-2 years                        0.1802      0.022      8.049      0.000       0.136       0.224
11-20 years                      0.9279      0.063     14.629      0.000       0.804       1.052
3-5 years                        0.2828      0.020     13.955      0.000       0.243       0.322
6-10 years                       0.6740      0.026     25.746      0.000       0.623       0.725
================================================================================================
Business and Financial Operations Occupations 2022
df length: 182061
Optimization terminated successfully.
         Current function value: 0.451054
         Iterations 6

 17%|█▋        | 15/90 [00:10<01:05,  1.15it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:               182061
Model:                          Logit   Df Residuals:                   182049
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01984
Time:                        23:57:32   Log-Likelihood:                -82119.
converged:                       True   LL-Null:                       -83782.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.1134      0.015   -144.590      0.000      -2.142      -2.085
AI ROLE                          0.4225      0.037     11.283      0.000       0.349       0.496
Associate degree                 0.0223      0.036      0.612      0.541      -0.049       0.094
Bachelor's degree                0.4948      0.017     29.473      0.000       0.462       0.528
High school or GED               0.4325      0.022     19.258      0.000       0.388       0.476
Master's degree                  0.6844      0.050     13.639      0.000       0.586       0.783
Ph.D. or professional degree     1.5782      0.077     20.504      0.000       1.427       1.729
0 years                         -0.3542      0.057     -6.212      0.000      -0.466      -0.242
1-2 years                        0.1064      0.019      5.700      0.000       0.070       0.143
11-20 years                      0.7916      0.051     15.446      0.000       0.691       0.892
3-5 years                        0.3241      0.017     19.522      0.000       0.292       0.357
6-10 years                       0.4957      0.022     22.508      0.000       0.453       0.539
================================================================================================
Business and Financial Operations Occupations 2020
df length: 125072
Optimization terminated successfully.
         Current function value: 0.236598
         Iterations 7

 18%|█▊        | 16/90 [00:11<01:05,  1.14it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:               125072
Model:                          Logit   Df Residuals:                   125060
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01067
Time:                        23:57:33   Log-Likelihood:                -29592.
converged:                       True   LL-Null:                       -29911.
Covariance Type:            nonrobust   LLR p-value:                8.825e-130
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.0640      0.026   -119.364      0.000      -3.114      -3.014
AI ROLE                          0.4350      0.072      6.034      0.000       0.294       0.576
Associate degree                 0.1146      0.071      1.610      0.107      -0.025       0.254
Bachelor's degree                0.5521      0.030     18.620      0.000       0.494       0.610
High school or GED               0.3056      0.043      7.099      0.000       0.221       0.390
Master's degree                  0.7646      0.083      9.233      0.000       0.602       0.927
Ph.D. or professional degree     0.7160      0.179      3.995      0.000       0.365       1.067
0 years                         -0.4869      0.099     -4.940      0.000      -0.680      -0.294
1-2 years                        0.0294      0.033      0.880      0.379      -0.036       0.095
11-20 years                      0.1044      0.109      0.959      0.338      -0.109       0.318
3-5 years                        0.0057      0.030      0.190      0.849      -0.053       0.065
6-10 years                       0.2267      0.040      5.670      0.000       0.148       0.305
================================================================================================
Business and Financial Operations Occupations 2018
df length: 139740
Optimization terminated successfully.
         Current function value: 0.217848
         Iterations 7

 19%|█▉        | 17/90 [00:12<01:05,  1.12it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:               139740
Model:                          Logit   Df Residuals:                   139728
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01011
Time:                        23:57:34   Log-Likelihood:                -30442.
converged:                       True   LL-Null:                       -30753.
Covariance Type:            nonrobust   LLR p-value:                3.473e-126
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.2672      0.027   -121.297      0.000      -3.320      -3.214
AI ROLE                          0.5875      0.070      8.366      0.000       0.450       0.725
Associate degree                 0.2223      0.069      3.203      0.001       0.086       0.358
Bachelor's degree                0.5310      0.031     17.180      0.000       0.470       0.592
High school or GED               0.2797      0.046      6.123      0.000       0.190       0.369
Master's degree                  0.6780      0.082      8.236      0.000       0.517       0.839
Ph.D. or professional degree     0.6735      0.187      3.600      0.000       0.307       1.040
0 years                          0.2480      0.093      2.656      0.008       0.065       0.431
1-2 years                        0.1069      0.034      3.119      0.002       0.040       0.174
11-20 years                      0.0778      0.112      0.697      0.486      -0.141       0.296
3-5 years                        0.1365      0.030      4.503      0.000       0.077       0.196
6-10 years                       0.2456      0.040      6.148      0.000       0.167       0.324
================================================================================================
Business and Financial Operations Occupations 2023
df length: 124651
Optimization terminated successfully.
         Current function value: 0.443932
         Iterations 6

 20%|██        | 18/90 [00:13<01:03,  1.13it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:               124651
Model:                          Logit   Df Residuals:                   124639
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02039
Time:                        23:57:35   Log-Likelihood:                -55337.
converged:                       True   LL-Null:                       -56488.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.1913      0.018   -121.039      0.000      -2.227      -2.156
AI ROLE                          0.6120      0.046     13.272      0.000       0.522       0.702
Associate degree                 0.4830      0.040     11.960      0.000       0.404       0.562
Bachelor's degree                0.6671      0.021     31.744      0.000       0.626       0.708
High school or GED               0.5198      0.027     18.908      0.000       0.466       0.574
Master's degree                  0.8969      0.059     15.311      0.000       0.782       1.012
Ph.D. or professional degree     1.3519      0.093     14.542      0.000       1.170       1.534
0 years                         -0.3351      0.067     -5.026      0.000      -0.466      -0.204
1-2 years                        0.0642      0.023      2.825      0.005       0.020       0.109
11-20 years                      0.6311      0.058     10.853      0.000       0.517       0.745
3-5 years                        0.1485      0.020      7.262      0.000       0.108       0.189
6-10 years                       0.3154      0.026     11.927      0.000       0.264       0.367
================================================================================================
Community and Social Service Occupations 2019

 21%|██        | 19/90 [00:13<00:56,  1.25it/s]

df length: 30528
Optimization terminated successfully.
         Current function value: 0.198034
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:                30528
Model:                          Logit   Df Residuals:                    30516
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01511
Time:                        23:57:35   Log-Likelihood:                -6045.6
converged:                       True   LL-Null:                       -6138.4
Covariance Type:            nonrobust   LLR p-value:                 7.289e-34
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.4548      0.067    -51.651      0.000      -3.586      -3.324
AI ROLE                          1.0836      0.350      3.094      0.002       0.397       1.770
Associate degree                 0.5982      0.119      5.013      0.000       0.364       0.832
Bachelor's degree                0.5779      0.082      7.052      0.000       0.417       0.739
High school or GED               0.1335      0.092      1.445      0.148      -0.048       0.315
Master's degree                  0.5978      0.087      6.863      0.000       0.427       0.769
Ph.D. or professional degree     1.0649      0.241      4.415      0.000       0.592       1.538
0 years                         -0.2222      0.226     -0.981      0.326      -0.666       0.222
1-2 years                        0.1820      0.063      2.897      0.004       0.059       0.305
11-20 years                     -0.1090      0.727     -0.150      0.881      -1.534       1.316
3-5 years                        0.3966      0.072      5.471      0.000       0.255       0.539
6-10 years                       0.5408      0.170      3.174      0.002       0.207       0.875
================================================================================================
Community and Social Service Occupations 2021

 22%|██▏       | 20/90 [00:14<00:51,  1.36it/s]

df length: 39363
Optimization terminated successfully.
         Current function value: 0.338857
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:                39363
Model:                          Logit   Df Residuals:                    39351
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01161
Time:                        23:57:36   Log-Likelihood:                -13338.
converged:                       True   LL-Null:                       -13495.
Covariance Type:            nonrobust   LLR p-value:                 1.262e-60
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.4142      0.038    -62.843      0.000      -2.489      -2.339
AI ROLE                          0.6531      0.304      2.146      0.032       0.057       1.249
Associate degree                 0.1932      0.080      2.415      0.016       0.036       0.350
Bachelor's degree                0.4242      0.050      8.430      0.000       0.326       0.523
High school or GED               0.2770      0.051      5.425      0.000       0.177       0.377
Master's degree                  0.3956      0.054      7.377      0.000       0.290       0.501
Ph.D. or professional degree     1.7714      0.104     17.022      0.000       1.567       1.975
0 years                          0.3078      0.101      3.049      0.002       0.110       0.506
1-2 years                       -0.0777      0.039     -1.975      0.048      -0.155      -0.001
11-20 years                     -0.0357      0.473     -0.075      0.940      -0.963       0.891
3-5 years                        0.0461      0.049      0.944      0.345      -0.050       0.142
6-10 years                       0.2921      0.130      2.253      0.024       0.038       0.546
================================================================================================
Community and Social Service Occupations 2022

 23%|██▎       | 21/90 [00:15<00:48,  1.43it/s]

df length: 46564
Optimization terminated successfully.
         Current function value: 0.414624
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:                46564
Model:                          Logit   Df Residuals:                    46552
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01455
Time:                        23:57:36   Log-Likelihood:                -19307.
converged:                       True   LL-Null:                       -19592.
Covariance Type:            nonrobust   LLR p-value:                3.666e-115
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.0049      0.029    -69.480      0.000      -2.061      -1.948
AI ROLE                          0.9170      0.201      4.572      0.000       0.524       1.310
Associate degree                 0.1276      0.060      2.130      0.033       0.010       0.245
Bachelor's degree                0.3219      0.038      8.444      0.000       0.247       0.397
High school or GED              -0.0634      0.042     -1.525      0.127      -0.145       0.018
Master's degree                  0.0173      0.043      0.400      0.689      -0.068       0.102
Ph.D. or professional degree     1.2150      0.082     14.769      0.000       1.054       1.376
0 years                          0.3945      0.072      5.445      0.000       0.252       0.536
1-2 years                        0.1274      0.032      3.986      0.000       0.065       0.190
11-20 years                      0.8822      0.261      3.379      0.001       0.371       1.394
3-5 years                        0.4734      0.038     12.409      0.000       0.399       0.548
6-10 years                       0.4734      0.100      4.745      0.000       0.278       0.669
================================================================================================
Community and Social Service Occupations 2020

 24%|██▍       | 22/90 [00:15<00:44,  1.51it/s]

df length: 30962
Optimization terminated successfully.
         Current function value: 0.227116
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:                30962
Model:                          Logit   Df Residuals:                    30950
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.009510
Time:                        23:57:37   Log-Likelihood:                -7032.0
converged:                       True   LL-Null:                       -7099.5
Covariance Type:            nonrobust   LLR p-value:                 1.659e-23
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.0615      0.056    -54.742      0.000      -3.171      -2.952
AI ROLE                          0.7071      0.441      1.604      0.109      -0.157       1.571
Associate degree                 0.4088      0.108      3.786      0.000       0.197       0.620
Bachelor's degree                0.3490      0.073      4.789      0.000       0.206       0.492
High school or GED               0.0166      0.080      0.208      0.835      -0.139       0.172
Master's degree                  0.4888      0.075      6.482      0.000       0.341       0.637
Ph.D. or professional degree     1.0374      0.184      5.640      0.000       0.677       1.398
0 years                         -0.5055      0.231     -2.192      0.028      -0.957      -0.054
1-2 years                        0.1224      0.056      2.173      0.030       0.012       0.233
11-20 years                      0.2876      0.603      0.477      0.634      -0.895       1.470
3-5 years                        0.2276      0.069      3.278      0.001       0.092       0.364
6-10 years                       0.3355      0.182      1.840      0.066      -0.022       0.693
================================================================================================
Community and Social Service Occupations 2018

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
 26%|██▌       | 23/90 [00:16<00:43,  1.56it/s]

df length: 25206
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.168773
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:                25206
Model:                          Logit   Df Residuals:                    25194
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01116
Time:                        23:57:38   Log-Likelihood:                -4254.1
converged:                      False   LL-Null:                       -4302.1
Covariance Type:            nonrobust   LLR p-value:                 1.078e-15
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.5881      0.077    -46.730      0.000      -3.739      -3.438
AI ROLE                          0.3593      0.600      0.599      0.549      -0.817       1.536
Associate degree                 0.4098      0.145      2.823      0.005       0.125       0.694
Bachelor's degree                0.5233      0.096      5.426      0.000       0.334       0.712
High school or GED               0.0736      0.113      0.652      0.514      -0.148       0.295
Master's degree                  0.4350      0.104      4.178      0.000       0.231       0.639
Ph.D. or professional degree    -0.0435      0.462     -0.094      0.925      -0.950       0.863
0 years                         -0.2694      0.310     -0.869      0.385      -0.877       0.339
1-2 years                        0.1793      0.077      2.330      0.020       0.028       0.330
11-20 years                    -20.5790   2.08e+04     -0.001      0.999   -4.08e+04    4.07e+04
3-5 years                        0.3650      0.089      4.112      0.000       0.191       0.539
6-10 years                       0.5602      0.216      2.593      0.010       0.137       0.984
================================================================================================
Community and Social Service Occupations 2023

 27%|██▋       | 24/90 [00:16<00:41,  1.59it/s]

df length: 43218
Optimization terminated successfully.
         Current function value: 0.436515
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:                43218
Model:                          Logit   Df Residuals:                    43206
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.006491
Time:                        23:57:38   Log-Likelihood:                -18865.
converged:                       True   LL-Null:                       -18989.
Covariance Type:            nonrobust   LLR p-value:                 1.495e-46
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.7891      0.029    -61.924      0.000      -1.846      -1.732
AI ROLE                          1.2231      0.220      5.551      0.000       0.791       1.655
Associate degree                 0.2278      0.060      3.801      0.000       0.110       0.345
Bachelor's degree                0.2174      0.039      5.520      0.000       0.140       0.295
High school or GED              -0.1181      0.043     -2.766      0.006      -0.202      -0.034
Master's degree                  0.2028      0.041      4.929      0.000       0.122       0.283
Ph.D. or professional degree     0.3627      0.077      4.733      0.000       0.213       0.513
0 years                         -0.2506      0.100     -2.499      0.012      -0.447      -0.054
1-2 years                       -0.0541      0.032     -1.696      0.090      -0.117       0.008
11-20 years                      0.2492      0.288      0.865      0.387      -0.315       0.814
3-5 years                        0.2468      0.039      6.259      0.000       0.170       0.324
6-10 years                       0.3777      0.103      3.680      0.000       0.177       0.579
================================================================================================
Computer and Mathematical Occupations 2019
df length: 187188
Optimization terminated successfully.
         Current function value: 0.228431
         Iterations 8

 28%|██▊       | 25/90 [00:17<00:48,  1.35it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:               187188
Model:                          Logit   Df Residuals:                   187176
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02316
Time:                        23:57:39   Log-Likelihood:                -42760.
converged:                       True   LL-Null:                       -43773.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.3603      0.022   -155.320      0.000      -3.403      -3.318
AI ROLE                          0.3608      0.032     11.347      0.000       0.299       0.423
Associate degree                 0.1883      0.061      3.111      0.002       0.070       0.307
Bachelor's degree                0.6802      0.023     29.307      0.000       0.635       0.726
High school or GED               0.4861      0.048     10.178      0.000       0.392       0.580
Master's degree                  0.6940      0.061     11.448      0.000       0.575       0.813
Ph.D. or professional degree     0.6342      0.138      4.595      0.000       0.364       0.905
0 years                         -0.6713      0.101     -6.661      0.000      -0.869      -0.474
1-2 years                        0.1552      0.035      4.458      0.000       0.087       0.223
11-20 years                      0.6328      0.060     10.564      0.000       0.515       0.750
3-5 years                        0.3788      0.025     14.933      0.000       0.329       0.429
6-10 years                       0.2788      0.029      9.455      0.000       0.221       0.337
================================================================================================
Computer and Mathematical Occupations 2021
df length: 175692
Optimization terminated successfully.
         Current function value: 0.367398
         Iterations 7

 29%|██▉       | 26/90 [00:18<00:52,  1.23it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:               175692
Model:                          Logit   Df Residuals:                   175680
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02288
Time:                        23:57:40   Log-Likelihood:                -64549.
converged:                       True   LL-Null:                       -66060.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.5108      0.016   -152.307      0.000      -2.543      -2.479
AI ROLE                          0.5439      0.022     25.114      0.000       0.501       0.586
Associate degree                 0.3220      0.040      8.134      0.000       0.244       0.400
Bachelor's degree                0.5051      0.018     28.344      0.000       0.470       0.540
High school or GED               0.2646      0.035      7.532      0.000       0.196       0.333
Master's degree                  0.5173      0.045     11.557      0.000       0.430       0.605
Ph.D. or professional degree     0.4923      0.102      4.812      0.000       0.292       0.693
0 years                         -0.8348      0.083    -10.049      0.000      -0.998      -0.672
1-2 years                        0.1003      0.026      3.820      0.000       0.049       0.152
11-20 years                      0.8068      0.041     19.471      0.000       0.726       0.888
3-5 years                        0.2479      0.020     12.665      0.000       0.210       0.286
6-10 years                       0.3574      0.022     16.304      0.000       0.314       0.400
================================================================================================
Computer and Mathematical Occupations 2022
df length: 203321
Optimization terminated successfully.
         Current function value: 0.462576
         Iterations 6

 30%|███       | 27/90 [00:19<00:55,  1.15it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:               203321
Model:                          Logit   Df Residuals:                   203309
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02945
Time:                        23:57:41   Log-Likelihood:                -94051.
converged:                       True   LL-Null:                       -96905.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.2060      0.014   -161.882      0.000      -2.233      -2.179
AI ROLE                          0.4639      0.018     26.224      0.000       0.429       0.499
Associate degree                 0.4535      0.031     14.455      0.000       0.392       0.515
Bachelor's degree                0.6344      0.015     43.210      0.000       0.606       0.663
High school or GED               0.6288      0.025     24.678      0.000       0.579       0.679
Master's degree                  0.5044      0.037     13.468      0.000       0.431       0.578
Ph.D. or professional degree     0.9727      0.077     12.600      0.000       0.821       1.124
0 years                         -0.3973      0.064     -6.255      0.000      -0.522      -0.273
1-2 years                        0.1511      0.021      7.283      0.000       0.110       0.192
11-20 years                      0.9829      0.033     30.174      0.000       0.919       1.047
3-5 years                        0.3120      0.016     19.668      0.000       0.281       0.343
6-10 years                       0.3805      0.018     21.457      0.000       0.346       0.415
================================================================================================
Computer and Mathematical Occupations 2020
df length: 157708
Optimization terminated successfully.
         Current function value: 0.239048
         Iterations 7

 31%|███       | 28/90 [00:20<00:54,  1.13it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:               157708
Model:                          Logit   Df Residuals:                   157696
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.03227
Time:                        23:57:42   Log-Likelihood:                -37700.
converged:                       True   LL-Null:                       -38957.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.3596      0.023   -144.186      0.000      -3.405      -3.314
AI ROLE                          0.6407      0.030     21.398      0.000       0.582       0.699
Associate degree                 0.5420      0.060      8.992      0.000       0.424       0.660
Bachelor's degree                0.8918      0.025     35.004      0.000       0.842       0.942
High school or GED               0.7352      0.049     15.125      0.000       0.640       0.831
Master's degree                  0.9646      0.057     16.779      0.000       0.852       1.077
Ph.D. or professional degree     0.9705      0.129      7.527      0.000       0.718       1.223
0 years                         -0.6144      0.111     -5.523      0.000      -0.832      -0.396
1-2 years                        0.0122      0.037      0.332      0.740      -0.060       0.085
11-20 years                      0.2986      0.064      4.687      0.000       0.174       0.423
3-5 years                        0.1909      0.027      7.155      0.000       0.139       0.243
6-10 years                       0.1368      0.030      4.497      0.000       0.077       0.196
================================================================================================
Computer and Mathematical Occupations 2018
df length: 178714
Optimization terminated successfully.
         Current function value: 0.226989
         Iterations 7

 32%|███▏      | 29/90 [00:21<00:55,  1.10it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:               178714
Model:                          Logit   Df Residuals:                   178702
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01430
Time:                        23:57:43   Log-Likelihood:                -40566.
converged:                       True   LL-Null:                       -41155.
Covariance Type:            nonrobust   LLR p-value:                1.184e-245
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.2153      0.021   -152.466      0.000      -3.257      -3.174
AI ROLE                          0.3469      0.035      9.909      0.000       0.278       0.416
Associate degree                -0.1111      0.065     -1.698      0.090      -0.239       0.017
Bachelor's degree                0.4317      0.023     18.597      0.000       0.386       0.477
High school or GED              -0.0917      0.056     -1.631      0.103      -0.202       0.018
Master's degree                  0.4411      0.063      7.022      0.000       0.318       0.564
Ph.D. or professional degree     0.3926      0.147      2.679      0.007       0.105       0.680
0 years                         -0.0954      0.116     -0.823      0.411      -0.323       0.132
1-2 years                        0.2289      0.036      6.442      0.000       0.159       0.299
11-20 years                      0.4350      0.069      6.292      0.000       0.299       0.571
3-5 years                        0.4132      0.026     15.934      0.000       0.362       0.464
6-10 years                       0.2541      0.031      8.261      0.000       0.194       0.314
================================================================================================
Computer and Mathematical Occupations 2023
df length: 127390
Optimization terminated successfully.
         Current function value: 0.455408
         Iterations 6

 33%|███▎      | 30/90 [00:22<00:52,  1.14it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:               127390
Model:                          Logit   Df Residuals:                   127378
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02664
Time:                        23:57:44   Log-Likelihood:                -58014.
converged:                       True   LL-Null:                       -59602.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.2814      0.018   -126.361      0.000      -2.317      -2.246
AI ROLE                          0.4825      0.023     20.951      0.000       0.437       0.528
Associate degree                 0.6559      0.037     17.902      0.000       0.584       0.728
Bachelor's degree                0.6783      0.019     35.335      0.000       0.641       0.716
High school or GED               0.6241      0.032     19.732      0.000       0.562       0.686
Master's degree                  0.6345      0.048     13.088      0.000       0.539       0.729
Ph.D. or professional degree     0.9228      0.098      9.399      0.000       0.730       1.115
0 years                         -0.0823      0.077     -1.068      0.286      -0.233       0.069
1-2 years                        0.1857      0.027      6.919      0.000       0.133       0.238
11-20 years                      0.5076      0.042     12.207      0.000       0.426       0.589
3-5 years                        0.3257      0.021     15.841      0.000       0.285       0.366
6-10 years                       0.3254      0.023     14.438      0.000       0.281       0.370
================================================================================================
Educational Instruction and Library Occupations 2019

 34%|███▍      | 31/90 [00:23<00:47,  1.24it/s]

df length: 45660
Optimization terminated successfully.
         Current function value: 0.226777
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:                45660
Model:                          Logit   Df Residuals:                    45648
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.08104
Time:                        23:57:44   Log-Likelihood:                -10355.
converged:                       True   LL-Null:                       -11268.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.8164      0.053    -71.390      0.000      -3.921      -3.712
AI ROLE                          0.7336      0.177      4.154      0.000       0.387       1.080
Associate degree                 1.1052      0.087     12.729      0.000       0.935       1.275
Bachelor's degree                1.0862      0.064     17.049      0.000       0.961       1.211
High school or GED               1.1364      0.071     16.113      0.000       0.998       1.275
Master's degree                  2.0406      0.070     28.966      0.000       1.903       2.179
Ph.D. or professional degree     2.7640      0.077     35.780      0.000       2.613       2.915
0 years                          0.7485      0.121      6.190      0.000       0.512       0.985
1-2 years                        0.1240      0.053      2.332      0.020       0.020       0.228
11-20 years                     -0.7111      0.604     -1.178      0.239      -1.895       0.473
3-5 years                        0.3712      0.060      6.179      0.000       0.253       0.489
6-10 years                       0.7985      0.121      6.612      0.000       0.562       1.035
================================================================================================
Educational Instruction and Library Occupations 2021

 36%|███▌      | 32/90 [00:23<00:43,  1.33it/s]

df length: 54703
Optimization terminated successfully.
         Current function value: 0.269767
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:                54703
Model:                          Logit   Df Residuals:                    54691
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.09102
Time:                        23:57:45   Log-Likelihood:                -14757.
converged:                       True   LL-Null:                       -16235.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.4065      0.040    -84.285      0.000      -3.486      -3.327
AI ROLE                          1.2912      0.138      9.385      0.000       1.022       1.561
Associate degree                 0.8280      0.068     12.142      0.000       0.694       0.962
Bachelor's degree                1.1918      0.049     24.558      0.000       1.097       1.287
High school or GED               0.4605      0.057      8.148      0.000       0.350       0.571
Master's degree                  1.9995      0.058     34.714      0.000       1.887       2.112
Ph.D. or professional degree     2.7734      0.069     40.364      0.000       2.639       2.908
0 years                          0.9167      0.084     10.899      0.000       0.752       1.082
1-2 years                        0.3775      0.043      8.716      0.000       0.293       0.462
11-20 years                      0.3545      0.307      1.155      0.248      -0.247       0.956
3-5 years                        0.4715      0.048      9.759      0.000       0.377       0.566
6-10 years                       0.5237      0.112      4.681      0.000       0.304       0.743
================================================================================================
Educational Instruction and Library Occupations 2022

 37%|███▋      | 33/90 [00:24<00:40,  1.40it/s]

df length: 62895
Optimization terminated successfully.
         Current function value: 0.335737
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:                62895
Model:                          Logit   Df Residuals:                    62883
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.08928
Time:                        23:57:46   Log-Likelihood:                -21116.
converged:                       True   LL-Null:                       -23186.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.0171      0.033    -90.865      0.000      -3.082      -2.952
AI ROLE                          0.8199      0.112      7.335      0.000       0.601       1.039
Associate degree                 1.0948      0.054     20.256      0.000       0.989       1.201
Bachelor's degree                1.1326      0.040     28.647      0.000       1.055       1.210
High school or GED               0.5108      0.047     10.902      0.000       0.419       0.603
Master's degree                  1.9214      0.046     41.392      0.000       1.830       2.012
Ph.D. or professional degree     2.7524      0.056     49.297      0.000       2.643       2.862
0 years                         -0.0471      0.058     -0.811      0.417      -0.161       0.067
1-2 years                        0.1034      0.036      2.881      0.004       0.033       0.174
11-20 years                     -0.3352      0.308     -1.087      0.277      -0.940       0.269
3-5 years                        0.4783      0.039     12.168      0.000       0.401       0.555
6-10 years                       0.7447      0.084      8.865      0.000       0.580       0.909
================================================================================================
Educational Instruction and Library Occupations 2020

 38%|███▊      | 34/90 [00:24<00:38,  1.46it/s]

df length: 42631
Optimization terminated successfully.
         Current function value: 0.233209
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:                42631
Model:                          Logit   Df Residuals:                    42619
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.08139
Time:                        23:57:46   Log-Likelihood:                -9941.9
converged:                       True   LL-Null:                       -10823.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.6484      0.050    -72.839      0.000      -3.747      -3.550
AI ROLE                          1.1582      0.178      6.518      0.000       0.810       1.506
Associate degree                 0.8976      0.083     10.794      0.000       0.735       1.061
Bachelor's degree                1.1246      0.060     18.663      0.000       1.006       1.243
High school or GED               0.5381      0.074      7.268      0.000       0.393       0.683
Master's degree                  1.8368      0.071     25.995      0.000       1.698       1.975
Ph.D. or professional degree     2.6677      0.078     33.991      0.000       2.514       2.822
0 years                          1.1214      0.112     10.006      0.000       0.902       1.341
1-2 years                        0.3729      0.053      7.054      0.000       0.269       0.476
11-20 years                     -0.5588      0.603     -0.926      0.354      -1.742       0.624
3-5 years                        0.3708      0.061      6.049      0.000       0.251       0.491
6-10 years                       0.6138      0.132      4.644      0.000       0.355       0.873
================================================================================================
Educational Instruction and Library Occupations 2018

 39%|███▉      | 35/90 [00:25<00:36,  1.52it/s]

df length: 41745
Optimization terminated successfully.
         Current function value: 0.208137
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:                41745
Model:                          Logit   Df Residuals:                    41733
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.07551
Time:                        23:57:47   Log-Likelihood:                -8688.7
converged:                       True   LL-Null:                       -9398.4
Covariance Type:            nonrobust   LLR p-value:                7.925e-298
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.9266      0.057    -68.706      0.000      -4.039      -3.815
AI ROLE                          0.5648      0.220      2.570      0.010       0.134       0.996
Associate degree                 1.2036      0.101     11.937      0.000       1.006       1.401
Bachelor's degree                1.1929      0.070     17.088      0.000       1.056       1.330
High school or GED               1.4095      0.075     18.750      0.000       1.262       1.557
Master's degree                  2.0016      0.077     26.096      0.000       1.851       2.152
Ph.D. or professional degree     2.6838      0.084     31.950      0.000       2.519       2.848
0 years                         -1.1231      0.307     -3.660      0.000      -1.724      -0.522
1-2 years                       -0.0499      0.062     -0.810      0.418      -0.171       0.071
11-20 years                      0.4868      0.486      1.002      0.317      -0.466       1.439
3-5 years                        0.1790      0.067      2.668      0.008       0.048       0.310
6-10 years                       0.4471      0.140      3.199      0.001       0.173       0.721
================================================================================================
Educational Instruction and Library Occupations 2023
df length: 56729

 40%|████      | 36/90 [00:26<00:37,  1.43it/s]

Optimization terminated successfully.
         Current function value: 0.349684
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:                56729
Model:                          Logit   Df Residuals:                    56717
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.08746
Time:                        23:57:48   Log-Likelihood:                -19837.
converged:                       True   LL-Null:                       -21738.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.0078      0.033    -90.093      0.000      -3.073      -2.942
AI ROLE                          0.8340      0.106      7.880      0.000       0.627       1.041
Associate degree                 1.0671      0.056     19.058      0.000       0.957       1.177
Bachelor's degree                1.1603      0.040     28.846      0.000       1.081       1.239
High school or GED               0.6774      0.047     14.467      0.000       0.586       0.769
Master's degree                  1.9315      0.047     40.807      0.000       1.839       2.024
Ph.D. or professional degree     2.6543      0.056     46.980      0.000       2.544       2.765
0 years                          0.8004      0.059     13.630      0.000       0.685       0.916
1-2 years                        0.1342      0.038      3.572      0.000       0.061       0.208
11-20 years                     -0.4012      0.270     -1.489      0.137      -0.929       0.127
3-5 years                        0.3798      0.042      9.140      0.000       0.298       0.461
6-10 years                       0.9323      0.082     11.359      0.000       0.771       1.093
================================================================================================
Healthcare Practitioners and Technical Occupations 2019
df length: 177733
Optimization terminated successfully.
         Current function value: 0.209677
         Iterations 8

 41%|████      | 37/90 [00:27<00:41,  1.29it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:               177733
Model:                          Logit   Df Residuals:                   177721
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.03065
Time:                        23:57:49   Log-Likelihood:                -37267.
converged:                       True   LL-Null:                       -38445.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.2718      0.018   -177.701      0.000      -3.308      -3.236
AI ROLE                          0.2051      0.272      0.753      0.451      -0.329       0.739
Associate degree                 0.1540      0.036      4.281      0.000       0.083       0.224
Bachelor's degree                0.9702      0.028     34.535      0.000       0.915       1.025
High school or GED               1.0506      0.028     38.165      0.000       0.997       1.105
Master's degree                  0.2699      0.060      4.514      0.000       0.153       0.387
Ph.D. or professional degree    -0.2497      0.094     -2.650      0.008      -0.434      -0.065
0 years                         -0.5241      0.088     -5.926      0.000      -0.698      -0.351
1-2 years                        0.2424      0.023     10.743      0.000       0.198       0.287
11-20 years                     -1.1110      0.585     -1.901      0.057      -2.257       0.035
3-5 years                       -0.0316      0.039     -0.818      0.413      -0.107       0.044
6-10 years                       0.3542      0.112      3.160      0.002       0.135       0.574
================================================================================================
Healthcare Practitioners and Technical Occupations 2021
df length: 235145
Optimization terminated successfully.
         Current function value: 0.297912
         Iterations 7

 42%|████▏     | 38/90 [00:28<00:45,  1.14it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:               235145
Model:                          Logit   Df Residuals:                   235133
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02236
Time:                        23:57:50   Log-Likelihood:                -70053.
converged:                       True   LL-Null:                       -71655.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.5821      0.013   -203.976      0.000      -2.607      -2.557
AI ROLE                          0.1251      0.186      0.674      0.500      -0.239       0.489
Associate degree                 0.0474      0.023      2.046      0.041       0.002       0.093
Bachelor's degree                1.0022      0.020     50.564      0.000       0.963       1.041
High school or GED               0.6690      0.020     33.094      0.000       0.629       0.709
Master's degree                  0.3704      0.037      9.972      0.000       0.298       0.443
Ph.D. or professional degree     0.1277      0.052      2.473      0.013       0.026       0.229
0 years                         -0.6617      0.064    -10.302      0.000      -0.788      -0.536
1-2 years                       -0.0056      0.016     -0.356      0.722      -0.036       0.025
11-20 years                      0.8548      0.180      4.760      0.000       0.503       1.207
3-5 years                       -0.1600      0.028     -5.732      0.000      -0.215      -0.105
6-10 years                       0.2534      0.084      3.016      0.003       0.089       0.418
================================================================================================
Healthcare Practitioners and Technical Occupations 2022
df length: 293272
Optimization terminated successfully.
         Current function value: 0.332281
         Iterations 6

 43%|████▎     | 39/90 [00:29<00:49,  1.03it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:               293272
Model:                          Logit   Df Residuals:                   293260
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02606
Time:                        23:57:51   Log-Likelihood:                -97449.
converged:                       True   LL-Null:                   -1.0006e+05
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.5676      0.011   -238.188      0.000      -2.589      -2.547
AI ROLE                          0.8462      0.146      5.802      0.000       0.560       1.132
Associate degree                 0.2502      0.018     14.060      0.000       0.215       0.285
Bachelor's degree                1.0067      0.017     60.556      0.000       0.974       1.039
High school or GED               0.5908      0.018     32.694      0.000       0.555       0.626
Master's degree                  0.4433      0.033     13.519      0.000       0.379       0.508
Ph.D. or professional degree     0.3867      0.040      9.693      0.000       0.308       0.465
0 years                          0.4566      0.035     13.063      0.000       0.388       0.525
1-2 years                        0.2649      0.013     20.106      0.000       0.239       0.291
11-20 years                      0.7658      0.175      4.386      0.000       0.424       1.108
3-5 years                        0.2741      0.022     12.372      0.000       0.231       0.317
6-10 years                       0.7659      0.061     12.475      0.000       0.646       0.886
================================================================================================
Healthcare Practitioners and Technical Occupations 2020
df length: 208848
Optimization terminated successfully.
         Current function value: 0.211122
         Iterations 7

 44%|████▍     | 40/90 [00:30<00:49,  1.01it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:               208848
Model:                          Logit   Df Residuals:                   208836
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.03510
Time:                        23:57:52   Log-Likelihood:                -44092.
converged:                       True   LL-Null:                       -45696.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.2824      0.017   -191.511      0.000      -3.316      -3.249
AI ROLE                          0.0925      0.258      0.359      0.720      -0.412       0.597
Associate degree                 0.3216      0.032     10.204      0.000       0.260       0.383
Bachelor's degree                1.2916      0.026     50.606      0.000       1.242       1.342
High school or GED               0.9414      0.027     35.231      0.000       0.889       0.994
Master's degree                  0.5120      0.053      9.653      0.000       0.408       0.616
Ph.D. or professional degree    -0.0314      0.075     -0.417      0.677      -0.179       0.116
0 years                         -0.6918      0.088     -7.828      0.000      -0.865      -0.519
1-2 years                        0.1908      0.020      9.331      0.000       0.151       0.231
11-20 years                      0.1299      0.278      0.467      0.640      -0.415       0.675
3-5 years                        0.0442      0.036      1.234      0.217      -0.026       0.114
6-10 years                       0.2091      0.110      1.902      0.057      -0.006       0.425
================================================================================================
Healthcare Practitioners and Technical Occupations 2018
df length: 178552
Optimization terminated successfully.
         Current function value: 0.115296
         Iterations 8

 46%|████▌     | 41/90 [00:31<00:48,  1.02it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:               178552
Model:                          Logit   Df Residuals:                   178540
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02525
Time:                        23:57:53   Log-Likelihood:                -20586.
converged:                       True   LL-Null:                       -21120.
Covariance Type:            nonrobust   LLR p-value:                9.375e-222
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.0391      0.027   -149.616      0.000      -4.092      -3.986
AI ROLE                          0.4662      0.313      1.491      0.136      -0.147       1.079
Associate degree                 0.4130      0.050      8.312      0.000       0.316       0.510
Bachelor's degree                1.1980      0.040     30.127      0.000       1.120       1.276
High school or GED               0.8036      0.044     18.062      0.000       0.716       0.891
Master's degree                  0.8546      0.073     11.709      0.000       0.712       0.998
Ph.D. or professional degree    -0.0657      0.117     -0.562      0.574      -0.295       0.163
0 years                         -0.6918      0.134     -5.145      0.000      -0.955      -0.428
1-2 years                       -0.0624      0.034     -1.850      0.064      -0.129       0.004
11-20 years                     -0.2581      0.719     -0.359      0.720      -1.668       1.152
3-5 years                       -0.1472      0.053     -2.758      0.006      -0.252      -0.043
6-10 years                       0.5335      0.133      4.002      0.000       0.272       0.795
================================================================================================
Healthcare Practitioners and Technical Occupations 2023
df length: 286144
Optimization terminated successfully.
         Current function value: 0.359478
         Iterations 6

 47%|████▋     | 42/90 [00:32<00:50,  1.05s/it]

                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:               286144
Model:                          Logit   Df Residuals:                   286132
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02266
Time:                        23:57:54   Log-Likelihood:            -1.0286e+05
converged:                       True   LL-Null:                   -1.0525e+05
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.4079      0.010   -237.848      0.000      -2.428      -2.388
AI ROLE                          0.5796      0.160      3.629      0.000       0.267       0.893
Associate degree                 0.4549      0.017     27.441      0.000       0.422       0.487
Bachelor's degree                0.9100      0.017     54.536      0.000       0.877       0.943
High school or GED               0.6867      0.017     39.362      0.000       0.652       0.721
Master's degree                  0.7796      0.029     26.867      0.000       0.723       0.836
Ph.D. or professional degree     0.2962      0.039      7.525      0.000       0.219       0.373
0 years                         -0.0184      0.036     -0.516      0.606      -0.088       0.052
1-2 years                        0.1718      0.013     13.526      0.000       0.147       0.197
11-20 years                      0.5448      0.146      3.743      0.000       0.259       0.830
3-5 years                        0.1570      0.022      7.157      0.000       0.114       0.200
6-10 years                       0.8660      0.055     15.699      0.000       0.758       0.974
================================================================================================
Legal Occupations 2019

 48%|████▊     | 43/90 [00:33<00:42,  1.12it/s]

df length: 10618
Optimization terminated successfully.
         Current function value: 0.182373
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:                10618
Model:                          Logit   Df Residuals:                    10606
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.03798
Time:                        23:57:55   Log-Likelihood:                -1936.4
converged:                       True   LL-Null:                       -2012.9
Covariance Type:            nonrobust   LLR p-value:                 3.828e-27
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.7642      0.098    -38.429      0.000      -3.956      -3.572
AI ROLE                          0.0842      0.523      0.161      0.872      -0.941       1.110
Associate degree                 0.6120      0.209      2.923      0.003       0.202       1.022
Bachelor's degree                0.7824      0.125      6.271      0.000       0.538       1.027
High school or GED               0.5847      0.162      3.614      0.000       0.268       0.902
Master's degree                  0.8825      0.326      2.711      0.007       0.245       1.521
Ph.D. or professional degree     0.9264      0.128      7.249      0.000       0.676       1.177
0 years                          1.1402      0.297      3.835      0.000       0.557       1.723
1-2 years                        0.2645      0.135      1.953      0.051      -0.001       0.530
11-20 years                      1.4825      0.459      3.231      0.001       0.583       2.382
3-5 years                        0.5623      0.117      4.802      0.000       0.333       0.792
6-10 years                       0.9554      0.162      5.894      0.000       0.638       1.273
================================================================================================
Legal Occupations 2021

 49%|████▉     | 44/90 [00:33<00:35,  1.28it/s]

df length: 13410
Optimization terminated successfully.
         Current function value: 0.288909
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:                13410
Model:                          Logit   Df Residuals:                    13398
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.04943
Time:                        23:57:55   Log-Likelihood:                -3874.3
converged:                       True   LL-Null:                       -4075.7
Covariance Type:            nonrobust   LLR p-value:                 1.443e-79
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.0278      0.066    -45.613      0.000      -3.158      -2.898
AI ROLE                          0.6403      0.253      2.535      0.011       0.145       1.135
Associate degree                -0.0204      0.166     -0.123      0.902      -0.345       0.304
Bachelor's degree                0.6834      0.086      7.942      0.000       0.515       0.852
High school or GED               0.3255      0.098      3.322      0.001       0.133       0.517
Master's degree                  1.3116      0.232      5.657      0.000       0.857       1.766
Ph.D. or professional degree     0.8644      0.084     10.300      0.000       0.700       1.029
0 years                         -0.2000      0.316     -0.633      0.527      -0.820       0.419
1-2 years                        0.3232      0.091      3.568      0.000       0.146       0.501
11-20 years                      1.4886      0.254      5.849      0.000       0.990       1.987
3-5 years                        0.5683      0.078      7.243      0.000       0.415       0.722
6-10 years                       1.1094      0.104     10.662      0.000       0.905       1.313
================================================================================================
Legal Occupations 2022

 50%|█████     | 45/90 [00:34<00:31,  1.42it/s]

df length: 14411
Optimization terminated successfully.
         Current function value: 0.323495
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:                14411
Model:                          Logit   Df Residuals:                    14399
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.04745
Time:                        23:57:56   Log-Likelihood:                -4661.9
converged:                       True   LL-Null:                       -4894.1
Covariance Type:            nonrobust   LLR p-value:                 1.190e-92
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.7253      0.056    -48.415      0.000      -2.836      -2.615
AI ROLE                          1.0022      0.226      4.431      0.000       0.559       1.445
Associate degree                -0.0055      0.149     -0.037      0.971      -0.298       0.287
Bachelor's degree                0.6709      0.076      8.858      0.000       0.522       0.819
High school or GED               0.2171      0.098      2.226      0.026       0.026       0.408
Master's degree                  1.0500      0.188      5.573      0.000       0.681       1.419
Ph.D. or professional degree     0.8048      0.075     10.779      0.000       0.658       0.951
0 years                          0.0637      0.230      0.277      0.782      -0.387       0.514
1-2 years                        0.0175      0.084      0.209      0.835      -0.147       0.182
11-20 years                      0.6992      0.247      2.833      0.005       0.216       1.183
3-5 years                        0.4806      0.069      6.934      0.000       0.345       0.616
6-10 years                       1.0269      0.093     11.056      0.000       0.845       1.209
================================================================================================
Legal Occupations 2020

 51%|█████     | 46/90 [00:34<00:28,  1.55it/s]

df length: 10122
Optimization terminated successfully.
         Current function value: 0.196747
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:                10122
Model:                          Logit   Df Residuals:                    10110
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.04615
Time:                        23:57:56   Log-Likelihood:                -1991.5
converged:                       True   LL-Null:                       -2087.8
Covariance Type:            nonrobust   LLR p-value:                 2.398e-35
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.4708      0.090    -38.368      0.000      -3.648      -3.293
AI ROLE                          0.7080      0.450      1.572      0.116      -0.175       1.591
Associate degree                 0.0363      0.251      0.145      0.885      -0.456       0.529
Bachelor's degree                0.7850      0.126      6.216      0.000       0.538       1.033
High school or GED               0.7905      0.145      5.461      0.000       0.507       1.074
Master's degree                  0.8390      0.319      2.631      0.009       0.214       1.464
Ph.D. or professional degree     0.9275      0.125      7.405      0.000       0.682       1.173
0 years                         -0.0499      0.466     -0.107      0.915      -0.963       0.864
1-2 years                       -0.0345      0.135     -0.256      0.798      -0.299       0.230
11-20 years                      1.9299      0.293      6.590      0.000       1.356       2.504
3-5 years                        0.2178      0.114      1.912      0.056      -0.005       0.441
6-10 years                       0.9522      0.149      6.403      0.000       0.661       1.244
================================================================================================
Legal Occupations 2018

 52%|█████▏    | 47/90 [00:35<00:25,  1.67it/s]

df length: 9145
Optimization terminated successfully.
         Current function value: 0.171375
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:                 9145
Model:                          Logit   Df Residuals:                     9133
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.03702
Time:                        23:57:57   Log-Likelihood:                -1567.2
converged:                       True   LL-Null:                       -1627.5
Covariance Type:            nonrobust   LLR p-value:                 1.447e-20
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.8876      0.115    -33.944      0.000      -4.112      -3.663
AI ROLE                         -0.4336      0.731     -0.593      0.553      -1.866       0.998
Associate degree                 0.4114      0.263      1.563      0.118      -0.105       0.927
Bachelor's degree                0.5951      0.139      4.275      0.000       0.322       0.868
High school or GED               0.7983      0.170      4.707      0.000       0.466       1.131
Master's degree                  1.0907      0.334      3.268      0.001       0.437       1.745
Ph.D. or professional degree     0.6590      0.149      4.434      0.000       0.368       0.950
0 years                          1.3113      0.369      3.555      0.000       0.588       2.034
1-2 years                        0.3151      0.158      1.998      0.046       0.006       0.624
11-20 years                      1.5492      0.459      3.375      0.001       0.649       2.449
3-5 years                        0.6618      0.135      4.920      0.000       0.398       0.925
6-10 years                       1.1554      0.174      6.645      0.000       0.815       1.496
================================================================================================
Legal Occupations 2023

 53%|█████▎    | 48/90 [00:35<00:23,  1.77it/s]

df length: 11385
Optimization terminated successfully.
         Current function value: 0.360722
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:                11385
Model:                          Logit   Df Residuals:                    11373
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02561
Time:                        23:57:57   Log-Likelihood:                -4106.8
converged:                       True   LL-Null:                       -4214.8
Covariance Type:            nonrobust   LLR p-value:                 3.738e-40
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.3983      0.057    -42.094      0.000      -2.510      -2.287
AI ROLE                          0.9558      0.236      4.048      0.000       0.493       1.419
Associate degree                 0.0196      0.144      0.136      0.892      -0.262       0.302
Bachelor's degree                0.5809      0.083      7.031      0.000       0.419       0.743
High school or GED               0.2639      0.101      2.606      0.009       0.065       0.462
Master's degree                  0.6821      0.229      2.982      0.003       0.234       1.130
Ph.D. or professional degree     0.4844      0.078      6.249      0.000       0.332       0.636
0 years                         -0.3477      0.266     -1.308      0.191      -0.869       0.173
1-2 years                        0.0634      0.083      0.762      0.446      -0.100       0.226
11-20 years                      0.8169      0.285      2.870      0.004       0.259       1.375
3-5 years                        0.2845      0.073      3.900      0.000       0.142       0.427
6-10 years                       0.8510      0.101      8.421      0.000       0.653       1.049
================================================================================================
Life, Physical, and Social Science Occupations 2019

 54%|█████▍    | 49/90 [00:36<00:23,  1.77it/s]

df length: 19301
Optimization terminated successfully.
         Current function value: 0.212530
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:                19301
Model:                          Logit   Df Residuals:                    19289
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02456
Time:                        23:57:58   Log-Likelihood:                -4102.0
converged:                       True   LL-Null:                       -4205.3
Covariance Type:            nonrobust   LLR p-value:                 3.192e-38
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.5160      0.084    -41.753      0.000      -3.681      -3.351
AI ROLE                          0.4993      0.177      2.822      0.005       0.153       0.846
Associate degree                 0.7729      0.165      4.677      0.000       0.449       1.097
Bachelor's degree                0.7685      0.101      7.614      0.000       0.571       0.966
High school or GED               0.5029      0.124      4.058      0.000       0.260       0.746
Master's degree                  1.0155      0.128      7.930      0.000       0.765       1.266
Ph.D. or professional degree     1.4129      0.116     12.207      0.000       1.186       1.640
0 years                         -0.2148      0.217     -0.990      0.322      -0.640       0.210
1-2 years                       -0.0866      0.087     -0.999      0.318      -0.257       0.083
11-20 years                      0.2372      0.285      0.833      0.405      -0.321       0.796
3-5 years                        0.0698      0.084      0.833      0.405      -0.094       0.234
6-10 years                       0.2625      0.115      2.290      0.022       0.038       0.487
================================================================================================
Life, Physical, and Social Science Occupations 2021

 56%|█████▌    | 50/90 [00:37<00:23,  1.72it/s]

df length: 25175
Optimization terminated successfully.
         Current function value: 0.328705
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:                25175
Model:                          Logit   Df Residuals:                    25163
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.03504
Time:                        23:57:58   Log-Likelihood:                -8275.2
converged:                       True   LL-Null:                       -8575.6
Covariance Type:            nonrobust   LLR p-value:                8.659e-122
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.6824      0.051    -52.937      0.000      -2.782      -2.583
AI ROLE                          0.4319      0.114      3.794      0.000       0.209       0.655
Associate degree                 0.2518      0.118      2.136      0.033       0.021       0.483
Bachelor's degree                0.6778      0.064     10.658      0.000       0.553       0.802
High school or GED               0.2359      0.081      2.898      0.004       0.076       0.396
Master's degree                  0.8102      0.083      9.740      0.000       0.647       0.973
Ph.D. or professional degree     1.4423      0.073     19.856      0.000       1.300       1.585
0 years                         -0.4310      0.146     -2.944      0.003      -0.718      -0.144
1-2 years                       -0.2034      0.059     -3.470      0.001      -0.318      -0.088
11-20 years                      0.3344      0.171      1.960      0.050    8.26e-05       0.669
3-5 years                        0.0203      0.056      0.361      0.718      -0.090       0.131
6-10 years                       0.4247      0.074      5.720      0.000       0.279       0.570
================================================================================================
Life, Physical, and Social Science Occupations 2022

 57%|█████▋    | 51/90 [00:37<00:23,  1.69it/s]

df length: 30329
Optimization terminated successfully.
         Current function value: 0.389014
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:                30329
Model:                          Logit   Df Residuals:                    30317
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.04598
Time:                        23:57:59   Log-Likelihood:                -11798.
converged:                       True   LL-Null:                       -12367.
Covariance Type:            nonrobust   LLR p-value:                5.327e-237
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.7207      0.047    -57.487      0.000      -2.813      -2.628
AI ROLE                          0.5483      0.087      6.321      0.000       0.378       0.718
Associate degree                 0.6979      0.089      7.809      0.000       0.523       0.873
Bachelor's degree                0.9930      0.055     17.954      0.000       0.885       1.101
High school or GED               0.5613      0.069      8.186      0.000       0.427       0.696
Master's degree                  0.8242      0.076     10.864      0.000       0.675       0.973
Ph.D. or professional degree     1.5910      0.065     24.600      0.000       1.464       1.718
0 years                         -0.3879      0.115     -3.379      0.001      -0.613      -0.163
1-2 years                       -0.0559      0.048     -1.160      0.246      -0.150       0.039
11-20 years                      0.7181      0.128      5.604      0.000       0.467       0.969
3-5 years                        0.2973      0.045      6.640      0.000       0.210       0.385
6-10 years                       0.5764      0.060      9.551      0.000       0.458       0.695
================================================================================================
Life, Physical, and Social Science Occupations 2020

 58%|█████▊    | 52/90 [00:38<00:22,  1.68it/s]

df length: 20260
Optimization terminated successfully.
         Current function value: 0.237801
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:                20260
Model:                          Logit   Df Residuals:                    20248
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02773
Time:                        23:58:00   Log-Likelihood:                -4817.8
converged:                       True   LL-Null:                       -4955.2
Covariance Type:            nonrobust   LLR p-value:                 1.757e-52
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.2450      0.070    -46.319      0.000      -3.382      -3.108
AI ROLE                          0.3929      0.164      2.393      0.017       0.071       0.715
Associate degree                 0.4722      0.158      2.996      0.003       0.163       0.781
Bachelor's degree                0.7859      0.088      8.956      0.000       0.614       0.958
High school or GED               0.4174      0.111      3.775      0.000       0.201       0.634
Master's degree                  0.7271      0.118      6.178      0.000       0.496       0.958
Ph.D. or professional degree     1.3844      0.098     14.133      0.000       1.192       1.576
0 years                         -0.3313      0.216     -1.536      0.124      -0.754       0.091
1-2 years                       -0.2488      0.081     -3.057      0.002      -0.408      -0.089
11-20 years                      0.4403      0.229      1.923      0.054      -0.008       0.889
3-5 years                        0.0451      0.076      0.596      0.551      -0.103       0.194
6-10 years                       0.2204      0.106      2.088      0.037       0.014       0.427
================================================================================================
Life, Physical, and Social Science Occupations 2018

 59%|█████▉    | 53/90 [00:38<00:21,  1.70it/s]

df length: 19078
Optimization terminated successfully.
         Current function value: 0.182067
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:                19078
Model:                          Logit   Df Residuals:                    19066
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02611
Time:                        23:58:00   Log-Likelihood:                -3473.5
converged:                       True   LL-Null:                       -3566.6
Covariance Type:            nonrobust   LLR p-value:                 5.289e-34
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.7780      0.093    -40.688      0.000      -3.960      -3.596
AI ROLE                          0.4537      0.220      2.059      0.040       0.022       0.886
Associate degree                 0.8626      0.184      4.680      0.000       0.501       1.224
Bachelor's degree                0.9229      0.112      8.254      0.000       0.704       1.142
High school or GED               0.5000      0.145      3.451      0.001       0.216       0.784
Master's degree                  1.0175      0.145      7.021      0.000       0.733       1.302
Ph.D. or professional degree     1.4488      0.128     11.358      0.000       1.199       1.699
0 years                         -0.0414      0.233     -0.178      0.859      -0.498       0.415
1-2 years                       -0.1842      0.100     -1.849      0.064      -0.380       0.011
11-20 years                      0.4595      0.263      1.750      0.080      -0.055       0.974
3-5 years                        0.0715      0.091      0.785      0.432      -0.107       0.250
6-10 years                       0.1004      0.131      0.769      0.442      -0.155       0.356
================================================================================================
Life, Physical, and Social Science Occupations 2023

 60%|██████    | 54/90 [00:39<00:21,  1.71it/s]

df length: 26051
Optimization terminated successfully.
         Current function value: 0.429564
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:                26051
Model:                          Logit   Df Residuals:                    26039
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.05334
Time:                        23:58:01   Log-Likelihood:                -11191.
converged:                       True   LL-Null:                       -11821.
Covariance Type:            nonrobust   LLR p-value:                1.059e-263
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.3879      0.045    -52.702      0.000      -2.477      -2.299
AI ROLE                          0.1421      0.110      1.293      0.196      -0.073       0.358
Associate degree                 0.5869      0.092      6.356      0.000       0.406       0.768
Bachelor's degree                0.8515      0.055     15.553      0.000       0.744       0.959
High school or GED               0.4596      0.068      6.795      0.000       0.327       0.592
Master's degree                  0.8830      0.072     12.205      0.000       0.741       1.025
Ph.D. or professional degree     1.8408      0.060     30.917      0.000       1.724       1.957
0 years                         -0.3628      0.108     -3.358      0.001      -0.575      -0.151
1-2 years                       -0.1760      0.048     -3.677      0.000      -0.270      -0.082
11-20 years                      0.6749      0.145      4.658      0.000       0.391       0.959
3-5 years                        0.1107      0.047      2.364      0.018       0.019       0.203
6-10 years                       0.4762      0.063      7.530      0.000       0.352       0.600
================================================================================================
Management Occupations 2019
df length: 174325
Optimization terminated successfully.
         Current function value: 0.264492
         Iterations 7

 61%|██████    | 55/90 [00:40<00:24,  1.43it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:               174325
Model:                          Logit   Df Residuals:                   174313
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01684
Time:                        23:58:02   Log-Likelihood:                -46108.
converged:                       True   LL-Null:                       -46897.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.0444      0.020   -148.651      0.000      -3.085      -3.004
AI ROLE                          0.5809      0.059      9.891      0.000       0.466       0.696
Associate degree                 0.4641      0.048      9.569      0.000       0.369       0.559
Bachelor's degree                0.5828      0.025     23.450      0.000       0.534       0.632
High school or GED               0.6250      0.030     20.753      0.000       0.566       0.684
Master's degree                  0.6408      0.049     12.984      0.000       0.544       0.738
Ph.D. or professional degree     0.9293      0.084     11.049      0.000       0.764       1.094
0 years                         -0.1932      0.119     -1.628      0.103      -0.426       0.039
1-2 years                       -0.0751      0.030     -2.514      0.012      -0.134      -0.017
11-20 years                      0.5202      0.058      8.947      0.000       0.406       0.634
3-5 years                        0.1926      0.024      7.978      0.000       0.145       0.240
6-10 years                       0.3639      0.028     12.809      0.000       0.308       0.420
================================================================================================
Management Occupations 2021
df length: 220041
Optimization terminated successfully.
         Current function value: 0.370606
         Iterations 6

 62%|██████▏   | 56/90 [00:41<00:27,  1.23it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:               220041
Model:                          Logit   Df Residuals:                   220029
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02312
Time:                        23:58:03   Log-Likelihood:                -81548.
converged:                       True   LL-Null:                       -83479.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.3478      0.014   -168.819      0.000      -2.375      -2.321
AI ROLE                          0.8255      0.037     22.057      0.000       0.752       0.899
Associate degree                -0.2109      0.040     -5.217      0.000      -0.290      -0.132
Bachelor's degree                0.4326      0.017     25.411      0.000       0.399       0.466
High school or GED               0.0347      0.021      1.620      0.105      -0.007       0.077
Master's degree                  0.7083      0.034     21.006      0.000       0.642       0.774
Ph.D. or professional degree     0.3996      0.066      6.022      0.000       0.270       0.530
0 years                          0.3701      0.059      6.255      0.000       0.254       0.486
1-2 years                        0.0169      0.021      0.790      0.429      -0.025       0.059
11-20 years                      0.5811      0.042     13.910      0.000       0.499       0.663
3-5 years                        0.2194      0.017     12.536      0.000       0.185       0.254
6-10 years                       0.5302      0.020     26.427      0.000       0.491       0.570
================================================================================================
Management Occupations 2022
df length: 258812
Optimization terminated successfully.
         Current function value: 0.434827
         Iterations 7

 63%|██████▎   | 57/90 [00:42<00:30,  1.07it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:               258812
Model:                          Logit   Df Residuals:                   258800
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.03242
Time:                        23:58:04   Log-Likelihood:            -1.1254e+05
converged:                       True   LL-Null:                   -1.1631e+05
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.1878      0.012   -186.198      0.000      -2.211      -2.165
AI ROLE                          0.7398      0.032     22.960      0.000       0.677       0.803
Associate degree                 0.0143      0.032      0.452      0.652      -0.048       0.076
Bachelor's degree                0.6080      0.014     42.729      0.000       0.580       0.636
High school or GED               0.2248      0.018     12.471      0.000       0.189       0.260
Master's degree                  0.6827      0.029     23.267      0.000       0.625       0.740
Ph.D. or professional degree     0.7639      0.054     14.263      0.000       0.659       0.869
0 years                         -0.6536      0.073     -8.925      0.000      -0.797      -0.510
1-2 years                        0.0821      0.017      4.715      0.000       0.048       0.116
11-20 years                      0.7413      0.035     21.350      0.000       0.673       0.809
3-5 years                        0.2878      0.015     19.800      0.000       0.259       0.316
6-10 years                       0.6073      0.017     36.228      0.000       0.574       0.640
================================================================================================
Management Occupations 2020
df length: 162514
Optimization terminated successfully.
         Current function value: 0.274867
         Iterations 7

 64%|██████▍   | 58/90 [00:43<00:30,  1.06it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:               162514
Model:                          Logit   Df Residuals:                   162502
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02157
Time:                        23:58:05   Log-Likelihood:                -44670.
converged:                       True   LL-Null:                       -45654.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.9132      0.020   -144.069      0.000      -2.953      -2.874
AI ROLE                          0.9595      0.051     18.682      0.000       0.859       1.060
Associate degree                 0.2065      0.055      3.758      0.000       0.099       0.314
Bachelor's degree                0.6077      0.025     24.370      0.000       0.559       0.657
High school or GED               0.4915      0.030     16.490      0.000       0.433       0.550
Master's degree                  0.8052      0.047     17.188      0.000       0.713       0.897
Ph.D. or professional degree     0.8928      0.074     12.094      0.000       0.748       1.038
0 years                         -0.6871      0.117     -5.894      0.000      -0.916      -0.459
1-2 years                       -0.2329      0.031     -7.490      0.000      -0.294      -0.172
11-20 years                      0.4947      0.056      8.847      0.000       0.385       0.604
3-5 years                        0.1221      0.024      5.054      0.000       0.075       0.169
6-10 years                       0.2874      0.029     10.079      0.000       0.232       0.343
================================================================================================
Management Occupations 2018
df length: 169177
Optimization terminated successfully.
         Current function value: 0.224855
         Iterations 7

 66%|██████▌   | 59/90 [00:44<00:29,  1.05it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:               169177
Model:                          Logit   Df Residuals:                   169165
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01748
Time:                        23:58:06   Log-Likelihood:                -38040.
converged:                       True   LL-Null:                       -38717.
Covariance Type:            nonrobust   LLR p-value:                1.117e-283
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.3673      0.024   -140.551      0.000      -3.414      -3.320
AI ROLE                          0.3277      0.076      4.336      0.000       0.180       0.476
Associate degree                 0.6417      0.053     12.120      0.000       0.538       0.745
Bachelor's degree                0.6333      0.029     22.075      0.000       0.577       0.689
High school or GED               0.5866      0.036     16.493      0.000       0.517       0.656
Master's degree                  0.8172      0.053     15.278      0.000       0.712       0.922
Ph.D. or professional degree     1.2389      0.086     14.364      0.000       1.070       1.408
0 years                          0.1323      0.118      1.123      0.261      -0.098       0.363
1-2 years                        0.0577      0.034      1.703      0.088      -0.009       0.124
11-20 years                      0.5549      0.067      8.305      0.000       0.424       0.686
3-5 years                        0.2540      0.028      9.212      0.000       0.200       0.308
6-10 years                       0.3507      0.032     10.933      0.000       0.288       0.414
================================================================================================
Management Occupations 2023
df length: 201898
Optimization terminated successfully.
         Current function value: 0.438180
         Iterations 6

 67%|██████▋   | 60/90 [00:45<00:29,  1.03it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:               201898
Model:                          Logit   Df Residuals:                   201886
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02860
Time:                        23:58:07   Log-Likelihood:                -88468.
converged:                       True   LL-Null:                       -91072.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.1693      0.013   -163.811      0.000      -2.195      -2.143
AI ROLE                          0.6687      0.040     16.771      0.000       0.591       0.747
Associate degree                 0.3355      0.032     10.407      0.000       0.272       0.399
Bachelor's degree                0.6617      0.016     40.531      0.000       0.630       0.694
High school or GED               0.3057      0.020     15.433      0.000       0.267       0.345
Master's degree                  0.8409      0.032     26.417      0.000       0.779       0.903
Ph.D. or professional degree     0.9487      0.057     16.656      0.000       0.837       1.060
0 years                         -0.6162      0.077     -7.972      0.000      -0.768      -0.465
1-2 years                        0.0483      0.019      2.540      0.011       0.011       0.086
11-20 years                      0.6828      0.038     17.853      0.000       0.608       0.758
3-5 years                        0.2108      0.016     12.863      0.000       0.179       0.243
6-10 years                       0.4644      0.019     23.900      0.000       0.426       0.503
================================================================================================
Office and Administrative Support Occupations 2019
df length: 185082
Optimization terminated successfully.
         Current function value: 0.186786
         Iterations 7

 68%|██████▊   | 61/90 [00:46<00:28,  1.01it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:               185082
Model:                          Logit   Df Residuals:                   185070
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.005631
Time:                        23:58:08   Log-Likelihood:                -34571.
converged:                       True   LL-Null:                       -34767.
Covariance Type:            nonrobust   LLR p-value:                 3.792e-77
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.2153      0.019   -167.484      0.000      -3.253      -3.178
AI ROLE                          0.1860      0.179      1.037      0.300      -0.165       0.537
Associate degree                -0.0139      0.052     -0.266      0.791      -0.116       0.088
Bachelor's degree                0.3104      0.034      9.175      0.000       0.244       0.377
High school or GED               0.0828      0.026      3.186      0.001       0.032       0.134
Master's degree                  0.6010      0.133      4.506      0.000       0.340       0.862
Ph.D. or professional degree     1.1006      0.214      5.146      0.000       0.681       1.520
0 years                          0.2027      0.062      3.275      0.001       0.081       0.324
1-2 years                        0.1451      0.027      5.372      0.000       0.092       0.198
11-20 years                      0.4425      0.213      2.075      0.038       0.025       0.860
3-5 years                        0.3375      0.034     10.041      0.000       0.272       0.403
6-10 years                       0.6112      0.067      9.127      0.000       0.480       0.742
================================================================================================
Office and Administrative Support Occupations 2021
df length: 223691
Optimization terminated successfully.
         Current function value: 0.252880
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:               223691
Model:                          Logit   Df Residuals:                   223679
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02213
Time:                        23:58:09   Log-Likelihood:                -56567.
converged:                       True   LL-Null:                       -57847.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.7668      0.015   -184.683      0.000      -2.796      -2.737
AI ROLE                          0.5458      0.101      5.431      0.000       0.349       0.743
Associate degree                -0.1515      0.039     -3.866      0.000      -0.228      -0.075
Bachelor's degree                0.4184      0.025     16.451      0.000       0.369       0.468
High school or GED              -0.2403      0.020    -12.291      0.000      -0.279      -0.202
Master's degree                  0.5337      0.100      5.329      0.000       0.337       0.730
Ph.D. or professional degree     1.4661      0.156      9.393      0.000       1.160       1.772
0 years                         -0.2851      0.053     -5.392      0.000      -0.389      -0.181
1-2 years                        0.5122      0.020     26.081      0.000       0.474       0.551
11-20 years                      1.3438      0.123     10.922      0.000       1.103       1.585
3-5 years                        0.5789      0.025     22.950      0.000       0.529       0.628
6-10 years                       0.8851      0.050     17.873      0.000       0.788       0.982
================================================================================================

 69%|██████▉   | 62/90 [00:47<00:29,  1.04s/it]

Office and Administrative Support Occupations 2022
df length: 238205
Optimization terminated successfully.
         Current function value: 0.323050
         Iterations 6

 70%|███████   | 63/90 [00:49<00:29,  1.08s/it]

                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:               238205
Model:                          Logit   Df Residuals:                   238193
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01838
Time:                        23:58:10   Log-Likelihood:                -76952.
converged:                       True   LL-Null:                       -78393.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.4619      0.012   -200.001      0.000      -2.486      -2.438
AI ROLE                          0.4095      0.086      4.789      0.000       0.242       0.577
Associate degree                 0.0373      0.032      1.163      0.245      -0.026       0.100
Bachelor's degree                0.5472      0.021     25.905      0.000       0.506       0.589
High school or GED               0.0036      0.016      0.218      0.827      -0.028       0.035
Master's degree                  0.6344      0.081      7.813      0.000       0.475       0.794
Ph.D. or professional degree     1.5503      0.114     13.598      0.000       1.327       1.774
0 years                          0.3029      0.035      8.681      0.000       0.235       0.371
1-2 years                        0.2510      0.017     14.860      0.000       0.218       0.284
11-20 years                      1.0641      0.109      9.757      0.000       0.850       1.278
3-5 years                        0.5438      0.020     26.764      0.000       0.504       0.584
6-10 years                       0.7844      0.039     19.965      0.000       0.707       0.861
================================================================================================
Office and Administrative Support Occupations 2020
df length: 175927
Optimization terminated successfully.
         Current function value: 0.172630
         Iterations 8

 71%|███████   | 64/90 [00:50<00:27,  1.07s/it]

                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:               175927
Model:                          Logit   Df Residuals:                   175915
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01681
Time:                        23:58:11   Log-Likelihood:                -30370.
converged:                       True   LL-Null:                       -30889.
Covariance Type:            nonrobust   LLR p-value:                1.022e-215
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.4037      0.021   -158.550      0.000      -3.446      -3.362
AI ROLE                          0.6935      0.160      4.344      0.000       0.381       1.006
Associate degree                 0.2542      0.056      4.560      0.000       0.145       0.364
Bachelor's degree                0.6750      0.036     18.500      0.000       0.603       0.746
High school or GED               0.1446      0.028      5.134      0.000       0.089       0.200
Master's degree                  1.0830      0.127      8.555      0.000       0.835       1.331
Ph.D. or professional degree     0.8925      0.248      3.599      0.000       0.406       1.379
0 years                         -0.5627      0.075     -7.458      0.000      -0.711      -0.415
1-2 years                        0.2055      0.029      7.051      0.000       0.148       0.263
11-20 years                      0.9701      0.154      6.285      0.000       0.668       1.273
3-5 years                        0.4176      0.036     11.762      0.000       0.348       0.487
6-10 years                       0.6147      0.073      8.433      0.000       0.472       0.757
================================================================================================
Office and Administrative Support Occupations 2018
df length: 173712
Optimization terminated successfully.
         Current function value: 0.175361
         Iterations 7

 72%|███████▏  | 65/90 [00:51<00:26,  1.05s/it]

                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:               173712
Model:                          Logit   Df Residuals:                   173700
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.005816
Time:                        23:58:12   Log-Likelihood:                -30462.
converged:                       True   LL-Null:                       -30641.
Covariance Type:            nonrobust   LLR p-value:                 1.050e-69
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.2899      0.020   -162.589      0.000      -3.330      -3.250
AI ROLE                          0.6729      0.175      3.853      0.000       0.331       1.015
Associate degree                -0.0323      0.058     -0.558      0.577      -0.146       0.081
Bachelor's degree                0.4044      0.037     10.916      0.000       0.332       0.477
High school or GED               0.2465      0.028      8.808      0.000       0.192       0.301
Master's degree                  0.9085      0.138      6.565      0.000       0.637       1.180
Ph.D. or professional degree     0.7689      0.254      3.024      0.002       0.270       1.267
0 years                          0.4086      0.063      6.510      0.000       0.286       0.532
1-2 years                       -0.0826      0.030     -2.738      0.006      -0.142      -0.023
11-20 years                     -0.2126      0.275     -0.774      0.439      -0.751       0.326
3-5 years                        0.1423      0.037      3.878      0.000       0.070       0.214
6-10 years                       0.4079      0.075      5.475      0.000       0.262       0.554
================================================================================================
Office and Administrative Support Occupations 2023
df length: 177048
Optimization terminated successfully.
         Current function value: 0.354676
         Iterations 6

 73%|███████▎  | 66/90 [00:52<00:24,  1.03s/it]

                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:               177048
Model:                          Logit   Df Residuals:                   177036
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01150
Time:                        23:58:13   Log-Likelihood:                -62795.
converged:                       True   LL-Null:                       -63525.
Covariance Type:            nonrobust   LLR p-value:                6.862e-307
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.2286      0.013   -170.007      0.000      -2.254      -2.203
AI ROLE                          0.4993      0.095      5.253      0.000       0.313       0.686
Associate degree                 0.1696      0.035      4.903      0.000       0.102       0.237
Bachelor's degree                0.5155      0.024     21.512      0.000       0.469       0.563
High school or GED               0.0477      0.018      2.721      0.007       0.013       0.082
Master's degree                  0.5401      0.087      6.220      0.000       0.370       0.710
Ph.D. or professional degree     1.3106      0.129     10.142      0.000       1.057       1.564
0 years                         -0.1713      0.041     -4.184      0.000      -0.252      -0.091
1-2 years                        0.1230      0.018      6.744      0.000       0.087       0.159
11-20 years                      0.6193      0.120      5.170      0.000       0.385       0.854
3-5 years                        0.3202      0.023     14.084      0.000       0.276       0.365
6-10 years                       0.6057      0.045     13.363      0.000       0.517       0.694
================================================================================================
Personal Care and Service Occupations 2019

 74%|███████▍  | 67/90 [00:52<00:20,  1.11it/s]

df length: 25875
Optimization terminated successfully.
         Current function value: 0.163952
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:                25875
Model:                          Logit   Df Residuals:                    25863
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01145
Time:                        23:58:14   Log-Likelihood:                -4242.2
converged:                       True   LL-Null:                       -4291.4
Covariance Type:            nonrobust   LLR p-value:                 3.931e-16
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.0910      0.038    -81.963      0.000      -3.165      -3.017
AI ROLE                          0.8561      0.797      1.074      0.283      -0.706       2.418
Associate degree                 0.2107      0.207      1.021      0.307      -0.194       0.615
Bachelor's degree                0.1077      0.144      0.746      0.456      -0.175       0.391
High school or GED              -0.7014      0.097     -7.194      0.000      -0.892      -0.510
Master's degree                  1.2039      0.366      3.288      0.001       0.486       1.922
Ph.D. or professional degree     1.8574      0.834      2.228      0.026       0.223       3.491
0 years                          0.2786      0.239      1.165      0.244      -0.190       0.747
1-2 years                       -0.0971      0.109     -0.895      0.371      -0.310       0.116
11-20 years                      1.5127      0.634      2.387      0.017       0.271       2.755
3-5 years                        0.2877      0.160      1.794      0.073      -0.027       0.602
6-10 years                      -0.1274      0.519     -0.246      0.806      -1.144       0.890
================================================================================================
Personal Care and Service Occupations 2021

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
 76%|███████▌  | 68/90 [00:53<00:17,  1.22it/s]

df length: 28728
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.196173
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:                28728
Model:                          Logit   Df Residuals:                    28716
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02514
Time:                        23:58:15   Log-Likelihood:                -5635.7
converged:                      False   LL-Null:                       -5781.0
Covariance Type:            nonrobust   LLR p-value:                 7.938e-56
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.2379      0.040    -81.830      0.000      -3.315      -3.160
AI ROLE                        -20.4961   2.44e+04     -0.001      0.999   -4.78e+04    4.78e+04
Associate degree                -0.1258      0.204     -0.618      0.537      -0.525       0.273
Bachelor's degree                0.6615      0.101      6.534      0.000       0.463       0.860
High school or GED               0.1864      0.061      3.043      0.002       0.066       0.306
Master's degree                  1.2263      0.274      4.481      0.000       0.690       1.763
Ph.D. or professional degree   -16.8525   5633.907     -0.003      0.998   -1.11e+04     1.1e+04
0 years                          0.0415      0.197      0.211      0.833      -0.344       0.427
1-2 years                        0.5614      0.066      8.456      0.000       0.431       0.692
11-20 years                      0.6751      0.739      0.913      0.361      -0.774       2.124
3-5 years                        1.0911      0.097     11.280      0.000       0.902       1.281
6-10 years                       0.9201      0.327      2.814      0.005       0.279       1.561
================================================================================================
Personal Care and Service Occupations 2022

 77%|███████▋  | 69/90 [00:53<00:15,  1.34it/s]

df length: 32448
Optimization terminated successfully.
         Current function value: 0.224626
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:                32448
Model:                          Logit   Df Residuals:                    32436
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.03749
Time:                        23:58:15   Log-Likelihood:                -7288.7
converged:                       True   LL-Null:                       -7572.5
Covariance Type:            nonrobust   LLR p-value:                1.113e-114
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.1678      0.035    -90.563      0.000      -3.236      -3.099
AI ROLE                          0.5532      0.494      1.119      0.263      -0.416       1.522
Associate degree                 0.2697      0.154      1.751      0.080      -0.032       0.572
Bachelor's degree                1.1178      0.081     13.754      0.000       0.958       1.277
High school or GED               0.4700      0.053      8.805      0.000       0.365       0.575
Master's degree                  1.7457      0.271      6.432      0.000       1.214       2.278
Ph.D. or professional degree     0.0646      1.035      0.062      0.950      -1.964       2.093
0 years                          0.3642      0.143      2.543      0.011       0.084       0.645
1-2 years                        0.6511      0.057     11.474      0.000       0.540       0.762
11-20 years                     -0.8295      1.017     -0.816      0.415      -2.822       1.163
3-5 years                        0.7187      0.086      8.341      0.000       0.550       0.888
6-10 years                       0.8669      0.237      3.663      0.000       0.403       1.331
================================================================================================
Personal Care and Service Occupations 2020

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
 78%|███████▊  | 70/90 [00:54<00:14,  1.42it/s]

df length: 24654
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.149545
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:                24654
Model:                          Logit   Df Residuals:                    24642
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.03151
Time:                        23:58:16   Log-Likelihood:                -3686.9
converged:                      False   LL-Null:                       -3806.8
Covariance Type:            nonrobust   LLR p-value:                 3.667e-45
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.4278      0.045    -76.031      0.000      -3.516      -3.339
AI ROLE                          2.5429      0.597      4.256      0.000       1.372       3.714
Associate degree                -0.1352      0.273     -0.495      0.621      -0.671       0.400
Bachelor's degree                0.4427      0.142      3.111      0.002       0.164       0.722
High school or GED               0.0538      0.083      0.645      0.519      -0.110       0.217
Master's degree                  1.6119      0.384      4.201      0.000       0.860       2.364
Ph.D. or professional degree   -14.1176   1851.086     -0.008      0.994   -3642.179    3613.944
0 years                         -0.2424      0.324     -0.748      0.454      -0.877       0.392
1-2 years                       -0.2814      0.118     -2.379      0.017      -0.513      -0.050
11-20 years                      0.4936      1.031      0.479      0.632      -1.527       2.514
3-5 years                        1.5051      0.108     13.965      0.000       1.294       1.716
6-10 years                       0.1394      0.470      0.297      0.767      -0.782       1.061
================================================================================================
Personal Care and Service Occupations 2018

 79%|███████▉  | 71/90 [00:55<00:12,  1.50it/s]

df length: 25428
Optimization terminated successfully.
         Current function value: 0.146694
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:                25428
Model:                          Logit   Df Residuals:                    25416
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01178
Time:                        23:58:16   Log-Likelihood:                -3730.1
converged:                       True   LL-Null:                       -3774.6
Covariance Type:            nonrobust   LLR p-value:                 2.741e-14
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.2260      0.039    -81.838      0.000      -3.303      -3.149
AI ROLE                          0.8816      1.051      0.839      0.401      -1.178       2.941
Associate degree                 0.0439      0.265      0.165      0.869      -0.476       0.564
Bachelor's degree                0.2759      0.165      1.672      0.095      -0.048       0.599
High school or GED              -0.6833      0.114     -6.019      0.000      -0.906      -0.461
Master's degree                  1.1087      0.411      2.697      0.007       0.303       1.914
Ph.D. or professional degree     0.9066      1.052      0.862      0.389      -1.155       2.969
0 years                         -0.3917      0.416     -0.942      0.346      -1.207       0.423
1-2 years                       -0.3121      0.133     -2.348      0.019      -0.573      -0.052
11-20 years                      0.9209      0.765      1.204      0.229      -0.578       2.420
3-5 years                        0.3223      0.185      1.746      0.081      -0.039       0.684
6-10 years                      -1.0645      0.723     -1.473      0.141      -2.481       0.352
================================================================================================
Personal Care and Service Occupations 2023

 80%|████████  | 72/90 [00:55<00:11,  1.57it/s]

df length: 25603
Optimization terminated successfully.
         Current function value: 0.255862
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:                25603
Model:                          Logit   Df Residuals:                    25591
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02682
Time:                        23:58:17   Log-Likelihood:                -6550.8
converged:                       True   LL-Null:                       -6731.4
Covariance Type:            nonrobust   LLR p-value:                 1.073e-70
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.8523      0.035    -81.346      0.000      -2.921      -2.784
AI ROLE                         -1.2638      1.026     -1.232      0.218      -3.275       0.747
Associate degree                 0.5464      0.148      3.697      0.000       0.257       0.836
Bachelor's degree                1.1047      0.083     13.286      0.000       0.942       1.268
High school or GED               0.2840      0.056      5.050      0.000       0.174       0.394
Master's degree                  1.4045      0.265      5.301      0.000       0.885       1.924
Ph.D. or professional degree     1.8072      0.609      2.965      0.003       0.613       3.002
0 years                         -0.1599      0.170     -0.938      0.348      -0.494       0.174
1-2 years                        0.4456      0.060      7.456      0.000       0.328       0.563
11-20 years                     -1.5372      1.011     -1.520      0.129      -3.520       0.445
3-5 years                        0.4506      0.094      4.769      0.000       0.265       0.636
6-10 years                       1.0342      0.236      4.374      0.000       0.571       1.498
================================================================================================
Production Occupations 2019

 81%|████████  | 73/90 [00:56<00:10,  1.56it/s]

df length: 52795
Optimization terminated successfully.
         Current function value: 0.146819
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:                52795
Model:                          Logit   Df Residuals:                    52783
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01557
Time:                        23:58:18   Log-Likelihood:                -7751.3
converged:                       True   LL-Null:                       -7873.9
Covariance Type:            nonrobust   LLR p-value:                 2.827e-46
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.7025      0.042    -88.771      0.000      -3.784      -3.621
AI ROLE                          0.6824      0.322      2.120      0.034       0.052       1.313
Associate degree                 0.4512      0.134      3.366      0.001       0.188       0.714
Bachelor's degree                0.8780      0.079     11.167      0.000       0.724       1.032
High school or GED               0.3882      0.056      6.994      0.000       0.279       0.497
Master's degree                 -0.0134      0.324     -0.041      0.967      -0.649       0.622
Ph.D. or professional degree     1.2466      0.473      2.636      0.008       0.320       2.174
0 years                         -0.4940      0.197     -2.503      0.012      -0.881      -0.107
1-2 years                        0.1998      0.063      3.180      0.001       0.077       0.323
11-20 years                      0.8304      0.324      2.561      0.010       0.195       1.466
3-5 years                        0.2225      0.070      3.180      0.001       0.085       0.360
6-10 years                       0.3662      0.128      2.860      0.004       0.115       0.617
================================================================================================
Production Occupations 2021

 82%|████████▏ | 74/90 [00:56<00:10,  1.50it/s]

df length: 77544
Optimization terminated successfully.
         Current function value: 0.211534
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:                77544
Model:                          Logit   Df Residuals:                    77532
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01993
Time:                        23:58:18   Log-Likelihood:                -16403.
converged:                       True   LL-Null:                       -16737.
Covariance Type:            nonrobust   LLR p-value:                5.874e-136
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.0615      0.026   -117.397      0.000      -3.113      -3.010
AI ROLE                          0.9075      0.178      5.098      0.000       0.559       1.256
Associate degree                 0.4596      0.089      5.192      0.000       0.286       0.633
Bachelor's degree                0.8891      0.053     16.858      0.000       0.786       0.992
High school or GED               0.0654      0.036      1.815      0.070      -0.005       0.136
Master's degree                  0.2221      0.191      1.163      0.245      -0.152       0.596
Ph.D. or professional degree     1.4353      0.327      4.392      0.000       0.795       2.076
0 years                         -0.2643      0.086     -3.062      0.002      -0.433      -0.095
1-2 years                        0.1990      0.042      4.744      0.000       0.117       0.281
11-20 years                      0.8936      0.225      3.975      0.000       0.453       1.334
3-5 years                        0.3422      0.048      7.161      0.000       0.249       0.436
6-10 years                       0.5563      0.087      6.393      0.000       0.386       0.727
================================================================================================
Production Occupations 2022

 83%|████████▎ | 75/90 [00:57<00:10,  1.45it/s]

df length: 80132
Optimization terminated successfully.
         Current function value: 0.261448
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:                80132
Model:                          Logit   Df Residuals:                    80120
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.03504
Time:                        23:58:19   Log-Likelihood:                -20950.
converged:                       True   LL-Null:                       -21711.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.9145      0.024   -123.672      0.000      -2.961      -2.868
AI ROLE                          0.4657      0.160      2.904      0.004       0.151       0.780
Associate degree                 0.7110      0.072      9.835      0.000       0.569       0.853
Bachelor's degree                1.2500      0.044     28.380      0.000       1.164       1.336
High school or GED               0.4032      0.032     12.792      0.000       0.341       0.465
Master's degree                  0.3638      0.159      2.281      0.023       0.051       0.676
Ph.D. or professional degree     1.9429      0.241      8.069      0.000       1.471       2.415
0 years                         -0.4763      0.081     -5.898      0.000      -0.635      -0.318
1-2 years                        0.1900      0.035      5.357      0.000       0.121       0.260
11-20 years                      1.2511      0.156      8.033      0.000       0.946       1.556
3-5 years                        0.2508      0.040      6.293      0.000       0.173       0.329
6-10 years                       0.5127      0.068      7.561      0.000       0.380       0.646
================================================================================================
Production Occupations 2020

 84%|████████▍ | 76/90 [00:58<00:09,  1.46it/s]

df length: 59540
Optimization terminated successfully.
         Current function value: 0.143187
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:                59540
Model:                          Logit   Df Residuals:                    59528
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01656
Time:                        23:58:20   Log-Likelihood:                -8525.4
converged:                       True   LL-Null:                       -8668.9
Covariance Type:            nonrobust   LLR p-value:                 4.696e-55
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.5762      0.038    -94.579      0.000      -3.650      -3.502
AI ROLE                          0.1990      0.370      0.538      0.591      -0.526       0.924
Associate degree                 0.4382      0.130      3.373      0.001       0.184       0.693
Bachelor's degree                0.8950      0.078     11.546      0.000       0.743       1.047
High school or GED               0.1788      0.052      3.414      0.001       0.076       0.281
Master's degree                  0.5360      0.252      2.125      0.034       0.042       1.031
Ph.D. or professional degree     1.5460      0.442      3.501      0.000       0.681       2.411
0 years                         -0.9082      0.146     -6.241      0.000      -1.193      -0.623
1-2 years                        0.1667      0.060      2.759      0.006       0.048       0.285
11-20 years                      0.8545      0.310      2.752      0.006       0.246       1.463
3-5 years                        0.0385      0.073      0.524      0.600      -0.105       0.183
6-10 years                       0.5324      0.120      4.441      0.000       0.297       0.767
================================================================================================
Production Occupations 2018

 86%|████████▌ | 77/90 [00:59<00:08,  1.46it/s]

df length: 53697
Optimization terminated successfully.
         Current function value: 0.126802
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:                53697
Model:                          Logit   Df Residuals:                    53685
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02255
Time:                        23:58:20   Log-Likelihood:                -6808.9
converged:                       True   LL-Null:                       -6966.0
Covariance Type:            nonrobust   LLR p-value:                 8.737e-61
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.9837      0.046    -86.872      0.000      -4.074      -3.894
AI ROLE                          0.4943      0.397      1.246      0.213      -0.283       1.272
Associate degree                 0.4745      0.147      3.239      0.001       0.187       0.762
Bachelor's degree                1.0696      0.082     13.099      0.000       0.910       1.230
High school or GED               0.4374      0.062      7.051      0.000       0.316       0.559
Master's degree                  0.6542      0.299      2.192      0.028       0.069       1.239
Ph.D. or professional degree     1.5602      0.479      3.257      0.001       0.621       2.499
0 years                         -0.3179      0.202     -1.575      0.115      -0.713       0.078
1-2 years                        0.3303      0.068      4.860      0.000       0.197       0.464
11-20 years                      0.4929      0.428      1.150      0.250      -0.347       1.333
3-5 years                        0.2468      0.075      3.271      0.001       0.099       0.395
6-10 years                       0.4144      0.132      3.142      0.002       0.156       0.673
================================================================================================
Production Occupations 2023

 87%|████████▋ | 78/90 [00:59<00:08,  1.46it/s]

df length: 63904
Optimization terminated successfully.
         Current function value: 0.297538
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:                63904
Model:                          Logit   Df Residuals:                    63892
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02521
Time:                        23:58:21   Log-Likelihood:                -19014.
converged:                       True   LL-Null:                       -19506.
Covariance Type:            nonrobust   LLR p-value:                7.613e-204
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.6882      0.024   -110.955      0.000      -2.736      -2.641
AI ROLE                          0.6700      0.173      3.874      0.000       0.331       1.009
Associate degree                 0.8314      0.073     11.427      0.000       0.689       0.974
Bachelor's degree                1.1629      0.047     24.941      0.000       1.072       1.254
High school or GED               0.4464      0.032     13.984      0.000       0.384       0.509
Master's degree                  0.1786      0.186      0.961      0.337      -0.186       0.543
Ph.D. or professional degree     1.6060      0.282      5.704      0.000       1.054       2.158
0 years                         -0.2916      0.079     -3.699      0.000      -0.446      -0.137
1-2 years                        0.1212      0.036      3.366      0.001       0.051       0.192
11-20 years                      0.1971      0.209      0.941      0.346      -0.213       0.607
3-5 years                        0.0764      0.041      1.848      0.065      -0.005       0.157
6-10 years                       0.4335      0.071      6.130      0.000       0.295       0.572
================================================================================================
Sales and Related Occupations 2019
df length: 185705
Optimization terminated successfully.
         Current function value: 0.240658
         Iterations 7

 88%|████████▊ | 79/90 [01:00<00:08,  1.29it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:               185705
Model:                          Logit   Df Residuals:                   185693
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01023
Time:                        23:58:22   Log-Likelihood:                -44691.
converged:                       True   LL-Null:                       -45153.
Covariance Type:            nonrobust   LLR p-value:                4.983e-191
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.8335      0.015   -187.737      0.000      -2.863      -2.804
AI ROLE                          0.3691      0.128      2.877      0.004       0.118       0.621
Associate degree                 0.3097      0.057      5.400      0.000       0.197       0.422
Bachelor's degree                0.4969      0.028     18.063      0.000       0.443       0.551
High school or GED               0.3323      0.023     14.757      0.000       0.288       0.376
Master's degree                 -0.5900      0.190     -3.108      0.002      -0.962      -0.218
Ph.D. or professional degree    -0.1143      0.461     -0.248      0.804      -1.018       0.789
0 years                         -0.6345      0.057    -11.157      0.000      -0.746      -0.523
1-2 years                       -0.0306      0.024     -1.264      0.206      -0.078       0.017
11-20 years                      0.6231      0.146      4.265      0.000       0.337       0.910
3-5 years                       -0.0947      0.033     -2.837      0.005      -0.160      -0.029
6-10 years                       0.6352      0.052     12.300      0.000       0.534       0.736
================================================================================================
Sales and Related Occupations 2021
df length: 207667
Optimization terminated successfully.
         Current function value: 0.335553
         Iterations 7

 89%|████████▉ | 80/90 [01:01<00:08,  1.16it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:               207667
Model:                          Logit   Df Residuals:                   207655
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.009076
Time:                        23:58:23   Log-Likelihood:                -69683.
converged:                       True   LL-Null:                       -70322.
Covariance Type:            nonrobust   LLR p-value:                5.121e-267
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.3053      0.011   -201.420      0.000      -2.328      -2.283
AI ROLE                          0.3468      0.092      3.768      0.000       0.166       0.527
Associate degree                 0.3337      0.043      7.814      0.000       0.250       0.417
Bachelor's degree                0.0838      0.023      3.642      0.000       0.039       0.129
High school or GED               0.0291      0.017      1.737      0.082      -0.004       0.062
Master's degree                  0.6544      0.073      8.976      0.000       0.511       0.797
Ph.D. or professional degree     0.4815      0.268      1.794      0.073      -0.045       1.008
0 years                         -0.2775      0.042     -6.567      0.000      -0.360      -0.195
1-2 years                        0.4340      0.018     24.697      0.000       0.400       0.468
11-20 years                      0.2016      0.130      1.553      0.121      -0.053       0.456
3-5 years                        0.2172      0.026      8.509      0.000       0.167       0.267
6-10 years                       0.8079      0.044     18.166      0.000       0.721       0.895
================================================================================================
Sales and Related Occupations 2022
df length: 216216
Optimization terminated successfully.
         Current function value: 0.386048
         Iterations 7

 90%|█████████ | 81/90 [01:02<00:08,  1.07it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:               216216
Model:                          Logit   Df Residuals:                   216204
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01714
Time:                        23:58:24   Log-Likelihood:                -83470.
converged:                       True   LL-Null:                       -84925.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.1246      0.010   -208.772      0.000      -2.145      -2.105
AI ROLE                          0.4866      0.079      6.176      0.000       0.332       0.641
Associate degree                 0.7004      0.034     20.660      0.000       0.634       0.767
Bachelor's degree                0.2787      0.020     13.820      0.000       0.239       0.318
High school or GED               0.0967      0.015      6.343      0.000       0.067       0.127
Master's degree                  0.8680      0.068     12.816      0.000       0.735       1.001
Ph.D. or professional degree     0.5216      0.216      2.414      0.016       0.098       0.945
0 years                         -0.5357      0.042    -12.656      0.000      -0.619      -0.453
1-2 years                        0.4435      0.016     27.971      0.000       0.412       0.475
11-20 years                      0.6780      0.119      5.700      0.000       0.445       0.911
3-5 years                        0.3128      0.022     14.435      0.000       0.270       0.355
6-10 years                       0.8490      0.039     21.783      0.000       0.773       0.925
================================================================================================
Sales and Related Occupations 2020
df length: 180255
Optimization terminated successfully.
         Current function value: 0.267837
         Iterations 8

 91%|█████████ | 82/90 [01:03<00:07,  1.04it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:               180255
Model:                          Logit   Df Residuals:                   180243
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01433
Time:                        23:58:25   Log-Likelihood:                -48279.
converged:                       True   LL-Null:                       -48981.
Covariance Type:            nonrobust   LLR p-value:                2.134e-294
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.2847      0.012   -190.682      0.000      -2.308      -2.261
AI ROLE                          0.6623      0.111      5.955      0.000       0.444       0.880
Associate degree                -0.0125      0.063     -0.200      0.841      -0.135       0.110
Bachelor's degree                0.0677      0.029      2.297      0.022       0.010       0.125
High school or GED              -0.2403      0.022    -11.060      0.000      -0.283      -0.198
Master's degree                 -1.3713      0.221     -6.192      0.000      -1.805      -0.937
Ph.D. or professional degree     0.0299      0.372      0.080      0.936      -0.698       0.758
0 years                         -1.6868      0.079    -21.219      0.000      -1.843      -1.531
1-2 years                       -0.3865      0.026    -15.154      0.000      -0.436      -0.337
11-20 years                      0.0034      0.164      0.021      0.984      -0.318       0.325
3-5 years                       -0.3344      0.036     -9.394      0.000      -0.404      -0.265
6-10 years                       0.2746      0.060      4.554      0.000       0.156       0.393
================================================================================================
Sales and Related Occupations 2018
df length: 170255
Optimization terminated successfully.
         Current function value: 0.197257
         Iterations 8

 92%|█████████▏| 83/90 [01:04<00:06,  1.04it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:               170255
Model:                          Logit   Df Residuals:                   170243
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.02173
Time:                        23:58:26   Log-Likelihood:                -33584.
converged:                       True   LL-Null:                       -34330.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.3987      0.020   -171.955      0.000      -3.437      -3.360
AI ROLE                          0.1198      0.173      0.692      0.489      -0.220       0.459
Associate degree                 0.3708      0.062      6.017      0.000       0.250       0.492
Bachelor's degree                0.5862      0.033     17.843      0.000       0.522       0.651
High school or GED               0.5370      0.027     19.623      0.000       0.483       0.591
Master's degree                 -0.5006      0.255     -1.964      0.050      -1.000      -0.001
Ph.D. or professional degree    -1.2145      1.006     -1.207      0.227      -3.187       0.758
0 years                         -0.3093      0.081     -3.814      0.000      -0.468      -0.150
1-2 years                        0.4201      0.027     15.438      0.000       0.367       0.473
11-20 years                      1.0453      0.159      6.578      0.000       0.734       1.357
3-5 years                        0.2466      0.038      6.567      0.000       0.173       0.320
6-10 years                       0.9434      0.055     17.012      0.000       0.835       1.052
================================================================================================
Sales and Related Occupations 2023
df length: 183257
Optimization terminated successfully.
         Current function value: 0.426589
         Iterations 6

 93%|█████████▎| 84/90 [01:05<00:05,  1.04it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:               183257
Model:                          Logit   Df Residuals:                   183245
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.008441
Time:                        23:58:27   Log-Likelihood:                -78175.
converged:                       True   LL-Null:                       -78841.
Covariance Type:            nonrobust   LLR p-value:                8.916e-279
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -1.8667      0.010   -186.118      0.000      -1.886      -1.847
AI ROLE                          0.5467      0.092      5.960      0.000       0.367       0.727
Associate degree                 0.3063      0.038      8.031      0.000       0.232       0.381
Bachelor's degree                0.3381      0.021     15.832      0.000       0.296       0.380
High school or GED               0.2131      0.015     14.067      0.000       0.183       0.243
Master's degree                  0.5055      0.090      5.640      0.000       0.330       0.681
Ph.D. or professional degree     0.3682      0.246      1.496      0.135      -0.114       0.850
0 years                         -0.6017      0.039    -15.239      0.000      -0.679      -0.524
1-2 years                        0.1375      0.017      8.258      0.000       0.105       0.170
11-20 years                      0.3846      0.122      3.148      0.002       0.145       0.624
3-5 years                        0.1494      0.022      6.669      0.000       0.106       0.193
6-10 years                       0.5307      0.044     12.050      0.000       0.444       0.617
================================================================================================
Transportation and Material Moving Occupations 2019
df length: 92120

/data/sant6443/thesis/code/venv_thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
 94%|█████████▍| 85/90 [01:06<00:04,  1.06it/s]

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.105462
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:                92120
Model:                          Logit   Df Residuals:                    92108
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01938
Time:                        23:58:28   Log-Likelihood:                -9715.2
converged:                      False   LL-Null:                       -9907.1
Covariance Type:            nonrobust   LLR p-value:                 1.576e-75
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.1259      0.034   -122.168      0.000      -4.192      -4.060
AI ROLE                          0.1977      1.021      0.194      0.847      -1.804       2.199
Associate degree                 0.8897      0.217      4.103      0.000       0.465       1.315
Bachelor's degree                0.9555      0.150      6.368      0.000       0.661       1.250
High school or GED               0.8043      0.046     17.498      0.000       0.714       0.894
Master's degree                  0.4227      0.586      0.722      0.470      -0.725       1.571
Ph.D. or professional degree   -13.0132    882.571     -0.015      0.988   -1742.821    1716.795
0 years                          0.6802      0.081      8.360      0.000       0.521       0.840
1-2 years                       -0.1311      0.061     -2.137      0.033      -0.251      -0.011
11-20 years                      0.2293      0.726      0.316      0.752      -1.194       1.652
3-5 years                       -0.0026      0.105     -0.025      0.980      -0.209       0.204
6-10 years                       0.2439      0.263      0.926      0.354      -0.272       0.760
================================================================================================
Transportation and Material Moving Occupations 2021
df length: 168157
Optimization terminated successfully.
         Current function value: 0.205520
         Iterations 8

 96%|█████████▌| 86/90 [01:07<00:03,  1.05it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:               168157
Model:                          Logit   Df Residuals:                   168145
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01096
Time:                        23:58:29   Log-Likelihood:                -34560.
converged:                       True   LL-Null:                       -34943.
Covariance Type:            nonrobust   LLR p-value:                3.580e-157
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.8672      0.015   -194.446      0.000      -2.896      -2.838
AI ROLE                          1.8459      0.208      8.894      0.000       1.439       2.253
Associate degree                 0.1492      0.170      0.876      0.381      -0.185       0.483
Bachelor's degree                0.8252      0.088      9.411      0.000       0.653       0.997
High school or GED               0.3033      0.023     13.318      0.000       0.259       0.348
Master's degree                 -0.9490      0.453     -2.094      0.036      -1.837      -0.061
Ph.D. or professional degree     1.0857      0.634      1.711      0.087      -0.158       2.329
0 years                         -0.5015      0.055     -9.054      0.000      -0.610      -0.393
1-2 years                       -0.6556      0.034    -19.064      0.000      -0.723      -0.588
11-20 years                      0.2679      0.342      0.784      0.433      -0.402       0.938
3-5 years                       -0.3150      0.061     -5.158      0.000      -0.435      -0.195
6-10 years                       0.0443      0.166      0.267      0.789      -0.281       0.370
================================================================================================
Transportation and Material Moving Occupations 2022
df length: 136730
Optimization terminated successfully.
         Current function value: 0.302797
         Iterations 7

 97%|█████████▋| 87/90 [01:08<00:02,  1.08it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:               136730
Model:                          Logit   Df Residuals:                   136718
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01601
Time:                        23:58:30   Log-Likelihood:                -41401.
converged:                       True   LL-Null:                       -42075.
Covariance Type:            nonrobust   LLR p-value:                2.846e-282
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.0497      0.011   -180.157      0.000      -2.072      -2.027
AI ROLE                          1.3520      0.209      6.474      0.000       0.943       1.761
Associate degree                -0.3611      0.140     -2.570      0.010      -0.636      -0.086
Bachelor's degree                0.2303      0.080      2.879      0.004       0.074       0.387
High school or GED              -0.2792      0.023    -12.104      0.000      -0.324      -0.234
Master's degree                 -0.7247      0.276     -2.622      0.009      -1.267      -0.183
Ph.D. or professional degree     0.5118      0.506      1.011      0.312      -0.480       1.504
0 years                         -0.8531      0.054    -15.924      0.000      -0.958      -0.748
1-2 years                       -0.7306      0.030    -24.346      0.000      -0.789      -0.672
11-20 years                     -0.6537      0.392     -1.669      0.095      -1.421       0.114
3-5 years                       -0.5460      0.054    -10.193      0.000      -0.651      -0.441
6-10 years                      -0.2271      0.145     -1.566      0.117      -0.511       0.057
================================================================================================
Transportation and Material Moving Occupations 2020
df length: 141154
Optimization terminated successfully.
         Current function value: 0.097763
         Iterations 9

 98%|█████████▊| 88/90 [01:09<00:01,  1.09it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:               141154
Model:                          Logit   Df Residuals:                   141142
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.01140
Time:                        23:58:31   Log-Likelihood:                -13800.
converged:                       True   LL-Null:                       -13959.
Covariance Type:            nonrobust   LLR p-value:                 1.302e-61
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -3.9566      0.027   -147.694      0.000      -4.009      -3.904
AI ROLE                          0.5486      0.735      0.746      0.456      -0.892       1.990
Associate degree                 0.9006      0.172      5.246      0.000       0.564       1.237
Bachelor's degree                0.9192      0.137      6.698      0.000       0.650       1.188
High school or GED               0.4175      0.040     10.390      0.000       0.339       0.496
Master's degree                  0.5301      0.456      1.164      0.245      -0.363       1.423
Ph.D. or professional degree     1.0393      0.729      1.426      0.154      -0.389       2.468
0 years                         -0.8076      0.070    -11.592      0.000      -0.944      -0.671
1-2 years                       -0.0192      0.050     -0.381      0.703      -0.118       0.080
11-20 years                      1.0469      0.373      2.809      0.005       0.317       1.777
3-5 years                        0.2329      0.090      2.582      0.010       0.056       0.410
6-10 years                       0.2649      0.242      1.094      0.274      -0.210       0.739
================================================================================================
Transportation and Material Moving Occupations 2018
df length: 111268
Optimization terminated successfully.
         Current function value: 0.066983
         Iterations 9

 99%|█████████▉| 89/90 [01:10<00:00,  1.13it/s]

                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:               111268
Model:                          Logit   Df Residuals:                   111256
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                 0.03633
Time:                        23:58:32   Log-Likelihood:                -7453.1
converged:                       True   LL-Null:                       -7734.1
Covariance Type:            nonrobust   LLR p-value:                1.857e-113
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -4.8568      0.041   -118.830      0.000      -4.937      -4.777
AI ROLE                          0.8258      0.738      1.119      0.263      -0.621       2.272
Associate degree                 1.4715      0.230      6.412      0.000       1.022       1.921
Bachelor's degree                1.5619      0.151     10.353      0.000       1.266       1.858
High school or GED               1.0807      0.056     19.405      0.000       0.972       1.190
Master's degree                  1.1082      0.587      1.889      0.059      -0.042       2.258
Ph.D. or professional degree     0.8554      1.012      0.846      0.398      -1.127       2.838
0 years                          0.9268      0.094      9.812      0.000       0.742       1.112
1-2 years                        0.2246      0.067      3.365      0.001       0.094       0.355
11-20 years                      0.5875      0.733      0.801      0.423      -0.850       2.025
3-5 years                        0.2348      0.119      1.979      0.048       0.002       0.467
6-10 years                       0.3124      0.270      1.156      0.248      -0.217       0.842
================================================================================================
Transportation and Material Moving Occupations 2023

100%|██████████| 90/90 [01:11<00:00,  1.27it/s]

df length: 110719
Optimization terminated successfully.
         Current function value: 0.291323
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                CULTURE   No. Observations:               110719
Model:                          Logit   Df Residuals:                   110707
Method:                           MLE   Df Model:                           11
Date:                Tue, 15 Oct 2024   Pseudo R-squ.:                0.007299
Time:                        23:58:32   Log-Likelihood:                -32255.
converged:                       True   LL-Null:                       -32492.
Covariance Type:            nonrobust   LLR p-value:                 9.485e-95
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           -2.2622      0.014   -162.257      0.000      -2.290      -2.235
AI ROLE                          1.0395      0.268      3.875      0.000       0.514       1.565
Associate degree                -0.3276      0.119     -2.759      0.006      -0.560      -0.095
Bachelor's degree                0.3489      0.076      4.589      0.000       0.200       0.498
High school or GED               0.0879      0.024      3.632      0.000       0.040       0.135
Master's degree                 -0.4080      0.345     -1.183      0.237      -1.084       0.268
Ph.D. or professional degree     0.5532      0.484      1.143      0.253      -0.395       1.502
0 years                         -0.8270      0.057    -14.504      0.000      -0.939      -0.715
1-2 years                       -0.4272      0.030    -14.218      0.000      -0.486      -0.368
11-20 years                     -0.2873      0.395     -0.728      0.467      -1.061       0.486
3-5 years                       -0.2200      0.055     -3.975      0.000      -0.328      -0.112
6-10 years                      -0.1425      0.142     -1.001      0.317      -0.421       0.136
================================================================================================

In [40]:
import sys

# Estimate the size of the models dictionary in bytes
size_in_bytes = sys.getsizeof(models_dict)
size_in_megabytes = size_in_bytes / (1024 ** 2)  # Convert to MB
print(f"Size of models_dict: {size_in_megabytes:.2f} MB")

Size of models_dict: 0.02 MB

In [41]:
models_dict

{('LEAVE',
  'Architecture and Engineering Occupations',
  np.int32(2019)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f1e80adb170>,
 ('LEAVE',
  'Architecture and Engineering Occupations',
  np.int32(2021)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102ceedbe0>,
 ('LEAVE',
  'Architecture and Engineering Occupations',
  np.int32(2022)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102ceeff20>,
 ('LEAVE',
  'Architecture and Engineering Occupations',
  np.int32(2020)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102ceec410>,
 ('LEAVE',
  'Architecture and Engineering Occupations',
  np.int32(2018)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f1d17290dd0>,
 ('LEAVE',
  'Architecture and Engineering Occupations',
  np.int32(2023)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d0cc740>,
 ('LEAVE',
  'Arts, Design, Entertainment, Sports, and Media Occupations',
  np.int32(2019)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d07f020>,
 ('LEAVE',
  'Arts, Design, Entertainment, Sports, and Media Occupations',
  np.int32(2021)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d0cdf70>,
 ('LEAVE',
  'Arts, Design, Entertainment, Sports, and Media Occupations',
  np.int32(2022)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d0b6870>,
 ('LEAVE',
  'Arts, Design, Entertainment, Sports, and Media Occupations',
  np.int32(2020)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d096150>,
 ('LEAVE',
  'Arts, Design, Entertainment, Sports, and Media Occupations',
  np.int32(2018)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d169ac0>,
 ('LEAVE',
  'Arts, Design, Entertainment, Sports, and Media Occupations',
  np.int32(2023)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102cee9ac0>,
 ('LEAVE',
  'Business and Financial Operations Occupations',
  np.int32(2019)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d0b5f10>,
 ('LEAVE',
  'Business and Financial Operations Occupations',
  np.int32(2021)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f1d17185310>,
 ('LEAVE',
  'Business and Financial Operations Occupations',
  np.int32(2022)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d0b6fc0>,
 ('LEAVE',
  'Business and Financial Operations Occupations',
  np.int32(2020)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d07a840>,
 ('LEAVE',
  'Business and Financial Operations Occupations',
  np.int32(2018)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d0aa780>,
 ('LEAVE',
  'Business and Financial Operations Occupations',
  np.int32(2023)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f1d171845f0>,
 ('LEAVE',
  'Community and Social Service Occupations',
  np.int32(2019)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f1d17b5cc50>,
 ('LEAVE',
  'Community and Social Service Occupations',
  np.int32(2021)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102ceec770>,
 ('LEAVE',
  'Community and Social Service Occupations',
  np.int32(2022)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d0ccce0>,
 ('LEAVE',
  'Community and Social Service Occupations',
  np.int32(2020)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d08e0f0>,
 ('LEAVE',
  'Community and Social Service Occupations',
  np.int32(2018)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d0cf3b0>,
 ('LEAVE',
  'Community and Social Service Occupations',
  np.int32(2023)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d0cfec0>,
 ('LEAVE',
  'Computer and Mathematical Occupations',
  np.int32(2019)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d0b6bd0>,
 ('LEAVE',
  'Computer and Mathematical Occupations',
  np.int32(2021)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102ceebef0>,
 ('LEAVE',
  'Computer and Mathematical Occupations',
  np.int32(2022)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d097da0>,
 ('LEAVE',
  'Computer and Mathematical Occupations',
  np.int32(2020)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d088da0>,
 ('LEAVE',
  'Computer and Mathematical Occupations',
  np.int32(2018)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102cee8da0>,
 ('LEAVE',
  'Computer and Mathematical Occupations',
  np.int32(2023)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d0781d0>,
 ('LEAVE',
  'Educational Instruction and Library Occupations',
  np.int32(2019)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d0c7020>,
 ('LEAVE',
  'Educational Instruction and Library Occupations',
  np.int32(2021)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d0bba40>,
 ('LEAVE',
  'Educational Instruction and Library Occupations',
  np.int32(2022)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f10250872f0>,
 ('LEAVE',
  'Educational Instruction and Library Occupations',
  np.int32(2020)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f1d17210bc0>,
 ('LEAVE',
  'Educational Instruction and Library Occupations',
  np.int32(2018)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d077560>,
 ('LEAVE',
  'Educational Instruction and Library Occupations',
  np.int32(2023)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d0a84a0>,
 ('LEAVE',
  'Healthcare Practitioners and Technical Occupations',
  np.int32(2019)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f1025087260>,
 ('LEAVE',
  'Healthcare Practitioners and Technical Occupations',
  np.int32(2021)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d0b8e90>,
 ('LEAVE',
  'Healthcare Practitioners and Technical Occupations',
  np.int32(2022)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f10702cbe60>,
 ('LEAVE',
  'Healthcare Practitioners and Technical Occupations',
  np.int32(2020)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d0c7b60>,
 ('LEAVE',
  'Healthcare Practitioners and Technical Occupations',
  np.int32(2018)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f1d17210b30>,
 ('LEAVE',
  'Healthcare Practitioners and Technical Occupations',
  np.int32(2023)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f1024fa2810>,
 ('LEAVE',
  'Legal Occupations',
  np.int32(2019)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d08fec0>,
 ('LEAVE',
  'Legal Occupations',
  np.int32(2021)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f1025086990>,
 ('LEAVE',
  'Legal Occupations',
  np.int32(2022)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d0ce330>,
 ('LEAVE',
  'Legal Occupations',
  np.int32(2020)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d08d400>,
 ('LEAVE',
  'Legal Occupations',
  np.int32(2018)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f1d17ea32c0>,
 ('LEAVE',
  'Legal Occupations',
  np.int32(2023)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d0cf740>,
 ('LEAVE',
  'Life, Physical, and Social Science Occupations',
  np.int32(2019)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102cee1c70>,
 ('LEAVE',
  'Life, Physical, and Social Science Occupations',
  np.int32(2021)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d08ef60>,
 ('LEAVE',
  'Life, Physical, and Social Science Occupations',
  np.int32(2022)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d07d700>,
 ('LEAVE',
  'Life, Physical, and Social Science Occupations',
  np.int32(2020)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d08c1a0>,
 ('LEAVE',
  'Life, Physical, and Social Science Occupations',
  np.int32(2018)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d0a7fe0>,
 ('LEAVE',
  'Life, Physical, and Social Science Occupations',
  np.int32(2023)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d0bf3e0>,
 ('LEAVE',
  'Management Occupations',
  np.int32(2019)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d168200>,
 ('LEAVE',
  'Management Occupations',
  np.int32(2021)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d07cfe0>,
 ('LEAVE',
  'Management Occupations',
  np.int32(2022)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d08ef30>,
 ('LEAVE',
  'Management Occupations',
  np.int32(2020)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d0cf7a0>,
 ('LEAVE',
  'Management Occupations',
  np.int32(2018)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d09a9c0>,
 ('LEAVE',
  'Management Occupations',
  np.int32(2023)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d099070>,
 ('LEAVE',
  'Office and Administrative Support Occupations',
  np.int32(2019)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d0898e0>,
 ('LEAVE',
  'Office and Administrative Support Occupations',
  np.int32(2021)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d0a6ea0>,
 ('LEAVE',
  'Office and Administrative Support Occupations',
  np.int32(2022)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102ceeac60>,
 ('LEAVE',
  'Office and Administrative Support Occupations',
  np.int32(2020)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d0ca540>,
 ('LEAVE',
  'Office and Administrative Support Occupations',
  np.int32(2018)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f1025087050>,
 ('LEAVE',
  'Office and Administrative Support Occupations',
  np.int32(2023)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102ceeae40>,
 ('LEAVE',
  'Personal Care and Service Occupations',
  np.int32(2019)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f1025179520>,
 ('LEAVE',
  'Personal Care and Service Occupations',
  np.int32(2021)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d0b9820>,
 ('LEAVE',
  'Personal Care and Service Occupations',
  np.int32(2022)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f1025085370>,
 ('LEAVE',
  'Personal Care and Service Occupations',
  np.int32(2020)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f1d17303740>,
 ('LEAVE',
  'Personal Care and Service Occupations',
  np.int32(2018)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d0b4fb0>,
 ('LEAVE',
  'Personal Care and Service Occupations',
  np.int32(2023)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f1025179fa0>,
 ('LEAVE',
  'Production Occupations',
  np.int32(2019)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f1024fa2150>,
 ('LEAVE',
  'Production Occupations',
  np.int32(2021)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f1d17181c40>,
 ('LEAVE',
  'Production Occupations',
  np.int32(2022)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d089ee0>,
 ('LEAVE',
  'Production Occupations',
  np.int32(2020)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102cee8740>,
 ('LEAVE',
  'Production Occupations',
  np.int32(2018)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d0c8320>,
 ('LEAVE',
  'Production Occupations',
  np.int32(2023)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d0cc5c0>,
 ('LEAVE',
  'Sales and Related Occupations',
  np.int32(2019)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d09f410>,
 ('LEAVE',
  'Sales and Related Occupations',
  np.int32(2021)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d0c2c90>,
 ('LEAVE',
  'Sales and Related Occupations',
  np.int32(2022)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d09f590>,
 ('LEAVE',
  'Sales and Related Occupations',
  np.int32(2020)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102cee24e0>,
 ('LEAVE',
  'Sales and Related Occupations',
  np.int32(2018)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102ceeb5c0>,
 ('LEAVE',
  'Sales and Related Occupations',
  np.int32(2023)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f1025178920>,
 ('LEAVE',
  'Transportation and Material Moving Occupations',
  np.int32(2019)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102cede4b0>,
 ('LEAVE',
  'Transportation and Material Moving Occupations',
  np.int32(2021)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102cedea80>,
 ('LEAVE',
  'Transportation and Material Moving Occupations',
  np.int32(2022)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d097a70>,
 ('LEAVE',
  'Transportation and Material Moving Occupations',
  np.int32(2020)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102cedd490>,
 ('LEAVE',
  'Transportation and Material Moving Occupations',
  np.int32(2018)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102cede030>,
 ('LEAVE',
  'Transportation and Material Moving Occupations',
  np.int32(2023)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102cedfb30>,
 ('HEALTH_WELLBEING',
  'Architecture and Engineering Occupations',
  np.int32(2019)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102cededb0>,
 ('HEALTH_WELLBEING',
  'Architecture and Engineering Occupations',
  np.int32(2021)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f10250820f0>,
 ('HEALTH_WELLBEING',
  'Architecture and Engineering Occupations',
  np.int32(2022)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d0bd850>,
 ('HEALTH_WELLBEING',
  'Architecture and Engineering Occupations',
  np.int32(2020)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d0965d0>,
 ('HEALTH_WELLBEING',
  'Architecture and Engineering Occupations',
  np.int32(2018)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102cee07d0>,
 ('HEALTH_WELLBEING',
  'Architecture and Engineering Occupations',
  np.int32(2023)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d0b91c0>,
 ('HEALTH_WELLBEING',
  'Arts, Design, Entertainment, Sports, and Media Occupations',
  np.int32(2019)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d0bea50>,
 ('HEALTH_WELLBEING',
  'Arts, Design, Entertainment, Sports, and Media Occupations',
  np.int32(2021)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d0c6c00>,
 ('HEALTH_WELLBEING',
  'Arts, Design, Entertainment, Sports, and Media Occupations',
  np.int32(2022)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f1025179b50>,
 ('HEALTH_WELLBEING',
  'Arts, Design, Entertainment, Sports, and Media Occupations',
  np.int32(2020)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102508a420>,
 ('HEALTH_WELLBEING',
  'Arts, Design, Entertainment, Sports, and Media Occupations',
  np.int32(2018)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102508aae0>,
 ('HEALTH_WELLBEING',
  'Arts, Design, Entertainment, Sports, and Media Occupations',
  np.int32(2023)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d0b13a0>,
 ('HEALTH_WELLBEING',
  'Business and Financial Operations Occupations',
  np.int32(2019)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102ceea120>,
 ('HEALTH_WELLBEING',
  'Business and Financial Operations Occupations',
  np.int32(2021)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d168770>,
 ('HEALTH_WELLBEING',
  'Business and Financial Operations Occupations',
  np.int32(2022)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d0b35f0>,
 ('HEALTH_WELLBEING',
  'Business and Financial Operations Occupations',
  np.int32(2020)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102ceea450>,
 ('HEALTH_WELLBEING',
  'Business and Financial Operations Occupations',
  np.int32(2018)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d0b42f0>,
 ('HEALTH_WELLBEING',
  'Business and Financial Operations Occupations',
  np.int32(2023)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d0b46e0>,
 ('HEALTH_WELLBEING',
  'Community and Social Service Occupations',
  np.int32(2019)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102517a4e0>,
 ('HEALTH_WELLBEING',
  'Community and Social Service Occupations',
  np.int32(2021)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102cee5b20>,
 ('HEALTH_WELLBEING',
  'Community and Social Service Occupations',
  np.int32(2022)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102cee7740>,
 ('HEALTH_WELLBEING',
  'Community and Social Service Occupations',
  np.int32(2020)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f1025086c30>,
 ('HEALTH_WELLBEING',
  'Community and Social Service Occupations',
  np.int32(2018)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f1025178620>,
 ('HEALTH_WELLBEING',
  'Community and Social Service Occupations',
  np.int32(2023)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d0b4440>,
 ('HEALTH_WELLBEING',
  'Computer and Mathematical Occupations',
  np.int32(2019)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d09b080>,
 ('HEALTH_WELLBEING',
  'Computer and Mathematical Occupations',
  np.int32(2021)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d08a0f0>,
 ('HEALTH_WELLBEING',
  'Computer and Mathematical Occupations',
  np.int32(2022)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d0bacf0>,
 ('HEALTH_WELLBEING',
  'Computer and Mathematical Occupations',
  np.int32(2020)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d07fa70>,
 ('HEALTH_WELLBEING',
  'Computer and Mathematical Occupations',
  np.int32(2018)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102ceecad0>,
 ('HEALTH_WELLBEING',
  'Computer and Mathematical Occupations',
  np.int32(2023)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f1024fa1820>,
 ('HEALTH_WELLBEING',
  'Educational Instruction and Library Occupations',
  np.int32(2019)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d0afec0>,
 ('HEALTH_WELLBEING',
  'Educational Instruction and Library Occupations',
  np.int32(2021)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f1025081730>,
 ('HEALTH_WELLBEING',
  'Educational Instruction and Library Occupations',
  np.int32(2022)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d0be600>,
 ('HEALTH_WELLBEING',
  'Educational Instruction and Library Occupations',
  np.int32(2020)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d0ad8b0>,
 ('HEALTH_WELLBEING',
  'Educational Instruction and Library Occupations',
  np.int32(2018)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f102d0ce990>,
 ('HEALTH_WELLBEING',
  'Educational Instruction and Library Occupations',
  np.int32(2023)): <statsmodels.discrete.discrete_model.BinaryResultsWrapper at 0x7f1025089d90>,
 ('HEALTH_WELLBEING',
  'Healthcare Practitioners and Technical Occupations',

In [42]:
# export models_dict to pickle
import pickle
with open('models_occ_year_dict.pickle', 'wb') as f:
    pickle.dump(models_dict, f)

In [4]:
import pickle

In [5]:
# import models_dict from pickle
with open('../exports/models_occ_year_dict.pickle', 'rb') as f:
    models_dict = pickle.load(f)

In [8]:
models_dict.keys()

dict_keys([('LEAVE', 'Architecture and Engineering Occupations', np.int32(2019)), ('LEAVE', 'Architecture and Engineering Occupations', np.int32(2021)), ('LEAVE', 'Architecture and Engineering Occupations', np.int32(2022)), ('LEAVE', 'Architecture and Engineering Occupations', np.int32(2020)), ('LEAVE', 'Architecture and Engineering Occupations', np.int32(2018)), ('LEAVE', 'Architecture and Engineering Occupations', np.int32(2023)), ('LEAVE', 'Arts, Design, Entertainment, Sports, and Media Occupations', np.int32(2019)), ('LEAVE', 'Arts, Design, Entertainment, Sports, and Media Occupations', np.int32(2021)), ('LEAVE', 'Arts, Design, Entertainment, Sports, and Media Occupations', np.int32(2022)), ('LEAVE', 'Arts, Design, Entertainment, Sports, and Media Occupations', np.int32(2020)), ('LEAVE', 'Arts, Design, Entertainment, Sports, and Media Occupations', np.int32(2018)), ('LEAVE', 'Arts, Design, Entertainment, Sports, and Media Occupations', np.int32(2023)), ('LEAVE', 'Business and Financial Operations Occupations', np.int32(2019)), ('LEAVE', 'Business and Financial Operations Occupations', np.int32(2021)), ('LEAVE', 'Business and Financial Operations Occupations', np.int32(2022)), ('LEAVE', 'Business and Financial Operations Occupations', np.int32(2020)), ('LEAVE', 'Business and Financial Operations Occupations', np.int32(2018)), ('LEAVE', 'Business and Financial Operations Occupations', np.int32(2023)), ('LEAVE', 'Community and Social Service Occupations', np.int32(2019)), ('LEAVE', 'Community and Social Service Occupations', np.int32(2021)), ('LEAVE', 'Community and Social Service Occupations', np.int32(2022)), ('LEAVE', 'Community and Social Service Occupations', np.int32(2020)), ('LEAVE', 'Community and Social Service Occupations', np.int32(2018)), ('LEAVE', 'Community and Social Service Occupations', np.int32(2023)), ('LEAVE', 'Computer and Mathematical Occupations', np.int32(2019)), ('LEAVE', 'Computer and Mathematical Occupations', np.int32(2021)), ('LEAVE', 'Computer and Mathematical Occupations', np.int32(2022)), ('LEAVE', 'Computer and Mathematical Occupations', np.int32(2020)), ('LEAVE', 'Computer and Mathematical Occupations', np.int32(2018)), ('LEAVE', 'Computer and Mathematical Occupations', np.int32(2023)), ('LEAVE', 'Educational Instruction and Library Occupations', np.int32(2019)), ('LEAVE', 'Educational Instruction and Library Occupations', np.int32(2021)), ('LEAVE', 'Educational Instruction and Library Occupations', np.int32(2022)), ('LEAVE', 'Educational Instruction and Library Occupations', np.int32(2020)), ('LEAVE', 'Educational Instruction and Library Occupations', np.int32(2018)), ('LEAVE', 'Educational Instruction and Library Occupations', np.int32(2023)), ('LEAVE', 'Healthcare Practitioners and Technical Occupations', np.int32(2019)), ('LEAVE', 'Healthcare Practitioners and Technical Occupations', np.int32(2021)), ('LEAVE', 'Healthcare Practitioners and Technical Occupations', np.int32(2022)), ('LEAVE', 'Healthcare Practitioners and Technical Occupations', np.int32(2020)), ('LEAVE', 'Healthcare Practitioners and Technical Occupations', np.int32(2018)), ('LEAVE', 'Healthcare Practitioners and Technical Occupations', np.int32(2023)), ('LEAVE', 'Legal Occupations', np.int32(2019)), ('LEAVE', 'Legal Occupations', np.int32(2021)), ('LEAVE', 'Legal Occupations', np.int32(2022)), ('LEAVE', 'Legal Occupations', np.int32(2020)), ('LEAVE', 'Legal Occupations', np.int32(2018)), ('LEAVE', 'Legal Occupations', np.int32(2023)), ('LEAVE', 'Life, Physical, and Social Science Occupations', np.int32(2019)), ('LEAVE', 'Life, Physical, and Social Science Occupations', np.int32(2021)), ('LEAVE', 'Life, Physical, and Social Science Occupations', np.int32(2022)), ('LEAVE', 'Life, Physical, and Social Science Occupations', np.int32(2020)), ('LEAVE', 'Life, Physical, and Social Science Occupations', np.int32(2018)), ('LEAVE', 'Life, Physical, and Social Science Occupations', np.int32(2023)), ('LEAVE', 'Management Occupations', np.int32(2019)), ('LEAVE', 'Management Occupations', np.int32(2021)), ('LEAVE', 'Management Occupations', np.int32(2022)), ('LEAVE', 'Management Occupations', np.int32(2020)), ('LEAVE', 'Management Occupations', np.int32(2018)), ('LEAVE', 'Management Occupations', np.int32(2023)), ('LEAVE', 'Office and Administrative Support Occupations', np.int32(2019)), ('LEAVE', 'Office and Administrative Support Occupations', np.int32(2021)), ('LEAVE', 'Office and Administrative Support Occupations', np.int32(2022)), ('LEAVE', 'Office and Administrative Support Occupations', np.int32(2020)), ('LEAVE', 'Office and Administrative Support Occupations', np.int32(2018)), ('LEAVE', 'Office and Administrative Support Occupations', np.int32(2023)), ('LEAVE', 'Personal Care and Service Occupations', np.int32(2019)), ('LEAVE', 'Personal Care and Service Occupations', np.int32(2021)), ('LEAVE', 'Personal Care and Service Occupations', np.int32(2022)), ('LEAVE', 'Personal Care and Service Occupations', np.int32(2020)), ('LEAVE', 'Personal Care and Service Occupations', np.int32(2018)), ('LEAVE', 'Personal Care and Service Occupations', np.int32(2023)), ('LEAVE', 'Production Occupations', np.int32(2019)), ('LEAVE', 'Production Occupations', np.int32(2021)), ('LEAVE', 'Production Occupations', np.int32(2022)), ('LEAVE', 'Production Occupations', np.int32(2020)), ('LEAVE', 'Production Occupations', np.int32(2018)), ('LEAVE', 'Production Occupations', np.int32(2023)), ('LEAVE', 'Sales and Related Occupations', np.int32(2019)), ('LEAVE', 'Sales and Related Occupations', np.int32(2021)), ('LEAVE', 'Sales and Related Occupations', np.int32(2022)), ('LEAVE', 'Sales and Related Occupations', np.int32(2020)), ('LEAVE', 'Sales and Related Occupations', np.int32(2018)), ('LEAVE', 'Sales and Related Occupations', np.int32(2023)), ('LEAVE', 'Transportation and Material Moving Occupations', np.int32(2019)), ('LEAVE', 'Transportation and Material Moving Occupations', np.int32(2021)), ('LEAVE', 'Transportation and Material Moving Occupations', np.int32(2022)), ('LEAVE', 'Transportation and Material Moving Occupations', np.int32(2020)), ('LEAVE', 'Transportation and Material Moving Occupations', np.int32(2018)), ('LEAVE', 'Transportation and Material Moving Occupations', np.int32(2023)), ('HEALTH_WELLBEING', 'Architecture and Engineering Occupations', np.int32(2019)), ('HEALTH_WELLBEING', 'Architecture and Engineering Occupations', np.int32(2021)), ('HEALTH_WELLBEING', 'Architecture and Engineering Occupations', np.int32(2022)), ('HEALTH_WELLBEING', 'Architecture and Engineering Occupations', np.int32(2020)), ('HEALTH_WELLBEING', 'Architecture and Engineering Occupations', np.int32(2018)), ('HEALTH_WELLBEING', 'Architecture and Engineering Occupations', np.int32(2023)), ('HEALTH_WELLBEING', 'Arts, Design, Entertainment, Sports, and Media Occupations', np.int32(2019)), ('HEALTH_WELLBEING', 'Arts, Design, Entertainment, Sports, and Media Occupations', np.int32(2021)), ('HEALTH_WELLBEING', 'Arts, Design, Entertainment, Sports, and Media Occupations', np.int32(2022)), ('HEALTH_WELLBEING', 'Arts, Design, Entertainment, Sports, and Media Occupations', np.int32(2020)), ('HEALTH_WELLBEING', 'Arts, Design, Entertainment, Sports, and Media Occupations', np.int32(2018)), ('HEALTH_WELLBEING', 'Arts, Design, Entertainment, Sports, and Media Occupations', np.int32(2023)), ('HEALTH_WELLBEING', 'Business and Financial Operations Occupations', np.int32(2019)), ('HEALTH_WELLBEING', 'Business and Financial Operations Occupations', np.int32(2021)), ('HEALTH_WELLBEING', 'Business and Financial Operations Occupations', np.int32(2022)), ('HEALTH_WELLBEING', 'Business and Financial Operations Occupations', np.int32(2020)), ('HEALTH_WELLBEING', 'Business and Financial Operations Occupations', np.int32(2018)), ('HEALTH_WELLBEING', 'Business and Financial Operations Occupations', np.int32(2023)), ('HEALTH_WELLBEING', 'Community and Social Service Occupations', np.int32(2019)), ('HEALTH_WELLBEING', 'Community and Social Service Occupations', np.int32(2021)), ('HEALTH_WELLBEING', 'Community and Social Service Occupations', np.int32(2022)), ('HEALTH_WELLBEING', 'Community and Social Service Occupations', np.int32(2020)), ('HEALTH_WELLBEING', 'Community and Social Service Occupations', np.int32(2018)), ('HEALTH_WELLBEING', 'Community and Social Service Occupations', np.int32(2023)), ('HEALTH_WELLBEING', 'Computer and Mathematical Occupations', np.int32(2019)), ('HEALTH_WELLBEING', 'Computer and Mathematical Occupations', np.int32(2021)), ('HEALTH_WELLBEING', 'Computer and Mathematical Occupations', np.int32(2022)), ('HEALTH_WELLBEING', 'Computer and Mathematical Occupations', np.int32(2020)), ('HEALTH_WELLBEING', 'Computer and Mathematical Occupations', np.int32(2018)), ('HEALTH_WELLBEING', 'Computer and Mathematical Occupations', np.int32(2023)), ('HEALTH_WELLBEING', 'Educational Instruction and Library Occupations', np.int32(2019)), ('HEALTH_WELLBEING', 'Educational Instruction and Library Occupations', np.int32(2021)), ('HEALTH_WELLBEING', 'Educational Instruction and Library Occupations', np.int32(2022)), ('HEALTH_WELLBEING', 'Educational Instruction and Library Occupations', np.int32(2020)), ('HEALTH_WELLBEING', 'Educational Instruction and Library Occupations', np.int32(2018)), ('HEALTH_WELLBEING', 'Educational Instruction and Library Occupations', np.int32(2023)), ('HEALTH_WELLBEING', 'Healthcare Practitioners and Technical Occupations', np.int32(2019)), ('HEALTH_WELLBEING', 'Healthcare Practitioners and Technical Occupations', np.int32(2021)), ('HEALTH_WELLBEING', 'Healthcare Practitioners and Technical Occupations', np.int32(2022)), ('HEALTH_WELLBEING', 'Healthcare Practitioners and Technical Occupations', np.int32(2020)), ('HEALTH_WELLBEING', 'Healthcare Practitioners and Technical Occupations', np.int32(2018)), ('HEALTH_WELLBEING', 'Healthcare Practitioners and Technical Occupations', np.int32(2023)), ('HEALTH_WELLBEING', 'Legal Occupations', np.int32(2019)), ('HEALTH_WELLBEING', 'Legal Occupations', np.int32(2021)), ('HEALTH_WELLBEING', 'Legal Occupations', np.int32(2022)), ('HEALTH_WELLBEING', 'Legal Occupations', np.int32(2020)), ('HEALTH_WELLBEING', 'Legal Occupations', np.int32(2018)), ('HEALTH_WELLBEING', 'Legal Occupations', np.int32(2023)), ('HEALTH_WELLBEING', 'Life, Physical, and Social Science Occupations', np.int32(2019)), ('HEALTH_WELLBEING', 'Life, Physical, and Social Science Occupations', np.int32(2021)), ('HEALTH_WELLBEING', 'Life, Physical, and Social Science Occupations', np.int32(2022)), ('HEALTH_WELLBEING', 'Life, Physical, and Social Science Occupations', np.int32(2020)), ('HEALTH_WELLBEING', 'Life, Physical, and Social Science Occupations', np.int32(2018)), ('HEALTH_WELLBEING', 'Life, Physical, and Social Science Occupations', np.int32(2023)), ('HEALTH_WELLBEING', 'Management Occupations', np.int32(2019)), ('HEALTH_WELLBEING', 'Management Occupations', np.int32(2021)), ('HEALTH_WELLBEING', 'Management Occupations', np.int32(2022)), ('HEALTH_WELLBEING', 'Management Occupations', np.int32(2020)), ('HEALTH_WELLBEING', 'Management Occupations', np.int32(2018)), ('HEALTH_WELLBEING', 'Management Occupations', np.int32(2023)), ('HEALTH_WELLBEING', 'Office and Administrative Support Occupations', np.int32(2019)), ('HEALTH_WELLBEING', 'Office and Administrative Support Occupations', np.int32(2021)), ('HEALTH_WELLBEING', 'Office and Administrative Support Occupations', np.int32(2022)), ('HEALTH_WELLBEING', 'Office and Administrative Support Occupations', np.int32(2020)), ('HEALTH_WELLBEING', 'Office and Administrative Support Occupations', np.int32(2018)), ('HEALTH_WELLBEING', 'Office and Administrative Support Occupations', np.int32(2023)), ('HEALTH_WELLBEING', 'Personal Care and Service Occupations', np.int32(2019)), ('HEALTH_WELLBEING', 'Personal Care and Service Occupations', np.int32(2021)), ('HEALTH_WELLBEING', 'Personal Care and Service Occupations', np.int32(2022)), ('HEALTH_WELLBEING', 'Personal Care and Service Occupations', np.int32(2020)), ('HEALTH_WELLBEING', 'Personal Care and Service Occupations', np.int32(2018)), ('HEALTH_WELLBEING', 'Personal Care and Service Occupations', np.int32(2023)), ('HEALTH_WELLBEING', 'Production Occupations', np.int32(2019)), ('HEALTH_WELLBEING', 'Production Occupations', np.int32(2021)), ('HEALTH_WELLBEING', 'Production Occupations', np.int32(2022)), ('HEALTH_WELLBEING', 'Production Occupations', np.int32(2020)), ('HEALTH_WELLBEING', 'Production Occupations', np.int32(2018)), ('HEALTH_WELLBEING', 'Production Occupations', np.int32(2023)), ('HEALTH_WELLBEING', 'Sales and Related Occupations', np.int32(2019)), ('HEALTH_WELLBEING', 'Sales and Related Occupations', np.int32(2021)), ('HEALTH_WELLBEING', 'Sales and Related Occupations', np.int32(2022)), ('HEALTH_WELLBEING', 'Sales and Related Occupations', np.int32(2020)), ('HEALTH_WELLBEING', 'Sales and Related Occupations', np.int32(2018)), ('HEALTH_WELLBEING', 'Sales and Related Occupations', np.int32(2023)), ('HEALTH_WELLBEING', 'Transportation and Material Moving Occupations', np.int32(2019)), ('HEALTH_WELLBEING', 'Transportation and Material Moving Occupations', np.int32(2021)), ('HEALTH_WELLBEING', 'Transportation and Material Moving Occupations', np.int32(2022)), ('HEALTH_WELLBEING', 'Transportation and Material Moving Occupations', np.int32(2020)), ('HEALTH_WELLBEING', 'Transportation and Material Moving Occupations', np.int32(2018)), ('HEALTH_WELLBEING', 'Transportation and Material Moving Occupations', np.int32(2023)), ('PARENTAL_LEAVE', 'Architecture and Engineering Occupations', np.int32(2019)), ('PARENTAL_LEAVE', 'Architecture and Engineering Occupations', np.int32(2021)), ('PARENTAL_LEAVE', 'Architecture and Engineering Occupations', np.int32(2022)), ('PARENTAL_LEAVE', 'Architecture and Engineering Occupations', np.int32(2020)), ('PARENTAL_LEAVE', 'Architecture and Engineering Occupations', np.int32(2018)), ('PARENTAL_LEAVE', 'Architecture and Engineering Occupations', np.int32(2023)), ('PARENTAL_LEAVE', 'Arts, Design, Entertainment, Sports, and Media Occupations', np.int32(2019)), ('PARENTAL_LEAVE', 'Arts, Design, Entertainment, Sports, and Media Occupations', np.int32(2021)), ('PARENTAL_LEAVE', 'Arts, Design, Entertainment, Sports, and Media Occupations', np.int32(2022)), ('PARENTAL_LEAVE', 'Arts, Design, Entertainment, Sports, and Media Occupations', np.int32(2020)), ('PARENTAL_LEAVE', 'Arts, Design, Entertainment, Sports, and Media Occupations', np.int32(2018)), ('PARENTAL_LEAVE', 'Arts, Design, Entertainment, Sports, and Media Occupations', np.int32(2023)), ('PARENTAL_LEAVE', 'Business and Financial Operations Occupations', np.int32(2019)), ('PARENTAL_LEAVE', 'Business and Financial Operations Occupations', np.int32(2021)), ('PARENTAL_LEAVE', 'Business and Financial Operations Occupations', np.int32(2022)), ('PARENTAL_LEAVE', 'Business and Financial Operations Occupations', np.int32(2020)), ('PARENTAL_LEAVE', 'Business and Financial Operations Occupations', np.int32(2018)), ('PARENTAL_LEAVE', 'Business and Financial Operations Occupations', np.int32(2023)), ('PARENTAL_LEAVE', 'Community and Social Service Occupations', np.int32(2019)), ('PARENTAL_LEAVE', 'Community and Social Service Occupations', np.int32(2021)), ('PARENTAL_LEAVE', 'Community and Social Service Occupations', np.int32(2022)), ('PARENTAL_LEAVE', 'Community and Social Service Occupations', np.int32(2020)), ('PARENTAL_LEAVE', 'Community and Social Service Occupations', np.int32(2018)), ('PARENTAL_LEAVE', 'Community and Social Service Occupations', np.int32(2023)), ('PARENTAL_LEAVE', 'Computer and Mathematical Occupations', np.int32(2019)), ('PARENTAL_LEAVE', 'Computer and Mathematical Occupations', np.int32(2021)), ('PARENTAL_LEAVE', 'Computer and Mathematical Occupations', np.int32(2022)), ('PARENTAL_LEAVE', 'Computer and Mathematical Occupations', np.int32(2020)), ('PARENTAL_LEAVE', 'Computer and Mathematical Occupations', np.int32(2018)), ('PARENTAL_LEAVE', 'Computer and Mathematical Occupations', np.int32(2023)), ('PARENTAL_LEAVE', 'Educational Instruction and Library Occupations', np.int32(2019)), ('PARENTAL_LEAVE', 'Educational Instruction and Library Occupations', np.int32(2021)), ('PARENTAL_LEAVE', 'Educational Instruction and Library Occupations', np.int32(2022)), ('PARENTAL_LEAVE', 'Educational Instruction and Library Occupations', np.int32(2020)), ('PARENTAL_LEAVE', 'Educational Instruction and Library Occupations', np.int32(2018)), ('PARENTAL_LEAVE', 'Educational Instruction and Library Occupations', np.int32(2023)), ('PARENTAL_LEAVE', 'Healthcare Practitioners and Technical Occupations', np.int32(2019)), ('PARENTAL_LEAVE', 'Healthcare Practitioners and Technical Occupations', np.int32(2021)), ('PARENTAL_LEAVE', 'Healthcare Practitioners and Technical Occupations', np.int32(2022)), ('PARENTAL_LEAVE', 'Healthcare Practitioners and Technical Occupations', np.int32(2020)), ('PARENTAL_LEAVE', 'Healthcare Practitioners and Technical Occupations', np.int32(2018)), ('PARENTAL_LEAVE', 'Healthcare Practitioners and Technical Occupations', np.int32(2023)), ('PARENTAL_LEAVE', 'Legal Occupations', np.int32(2019)), ('PARENTAL_LEAVE', 'Legal Occupations', np.int32(2021)), ('PARENTAL_LEAVE', 'Legal Occupations', np.int32(2022)), ('PARENTAL_LEAVE', 'Legal Occupations', np.int32(2020)), ('PARENTAL_LEAVE', 'Legal Occupations', np.int32(2018)), ('PARENTAL_LEAVE', 'Legal Occupations', np.int32(2023)), ('PARENTAL_LEAVE', 'Life, Physical, and Social Science Occupations', np.int32(2019)), ('PARENTAL_LEAVE', 'Life, Physical, and Social Science Occupations', np.int32(2021)), ('PARENTAL_LEAVE', 'Life, Physical, and Social Science Occupations', np.int32(2022)), ('PARENTAL_LEAVE', 'Life, Physical, and Social Science Occupations', np.int32(2020)), ('PARENTAL_LEAVE', 'Life, Physical, and Social Science Occupations', np.int32(2018)), ('PARENTAL_LEAVE', 'Life, Physical, and Social Science Occupations', np.int32(2023)), ('PARENTAL_LEAVE', 'Management Occupations', np.int32(2019)), ('PARENTAL_LEAVE', 'Management Occupations', np.int32(2021)), ('PARENTAL_LEAVE', 'Management Occupations', np.int32(2022)), ('PARENTAL_LEAVE', 'Management Occupations', np.int32(2020)), ('PARENTAL_LEAVE', 'Management Occupations', np.int32(2018)), ('PARENTAL_LEAVE', 'Management Occupations', np.int32(2023)), ('PARENTAL_LEAVE', 'Office and Administrative Support Occupations', np.int32(2019)), ('PARENTAL_LEAVE', 'Office and Administrative Support Occupations', np.int32(2021)), ('PARENTAL_LEAVE', 'Office and Administrative Support Occupations', np.int32(2022)), ('PARENTAL_LEAVE', 'Office and Administrative Support Occupations', np.int32(2020)), ('PARENTAL_LEAVE', 'Office and Administrative Support Occupations', np.int32(2018)), ('PARENTAL_LEAVE', 'Office and Administrative Support Occupations', np.int32(2023)), ('PARENTAL_LEAVE', 'Personal Care and Service Occupations', np.int32(2019)), ('PARENTAL_LEAVE', 'Personal Care and Service Occupations', np.int32(2021)), ('PARENTAL_LEAVE', 'Personal Care and Service Occupations', np.int32(2022)), ('PARENTAL_LEAVE', 'Personal Care and Service Occupations', np.int32(2020)), ('PARENTAL_LEAVE', 'Personal Care and Service Occupations', np.int32(2018)), ('PARENTAL_LEAVE', 'Personal Care and Service Occupations', np.int32(2023)), ('PARENTAL_LEAVE', 'Production Occupations', np.int32(2019)), ('PARENTAL_LEAVE', 'Production Occupations', np.int32(2021)), ('PARENTAL_LEAVE', 'Production Occupations', np.int32(2022)), ('PARENTAL_LEAVE', 'Production Occupations', np.int32(2020)), ('PARENTAL_LEAVE', 'Production Occupations', np.int32(2018)), ('PARENTAL_LEAVE', 'Production Occupations', np.int32(2023)), ('PARENTAL_LEAVE', 'Sales and Related Occupations', np.int32(2019)), ('PARENTAL_LEAVE', 'Sales and Related Occupations', np.int32(2021)), ('PARENTAL_LEAVE', 'Sales and Related Occupations', np.int32(2022)), ('PARENTAL_LEAVE', 'Sales and Related Occupations', np.int32(2020)), ('PARENTAL_LEAV

In [11]:
list(models_dict.keys())[0][0]

'LEAVE'

In [20]:
coefficients = []
errors = []
pvalues = []
benefits = []
occupations = []
years = []

keys_list = list(models_dict.keys())
for key, value in models_dict.items(): 
    model = value
    try:
        coef = model.params['AI ROLE']
        err = model.bse['AI ROLE']
        pvalue = model.pvalues['AI ROLE'].round(3)
    except:
        coef = None
        err = None
        pvalue = None
    benefit = key[0]
    occ = key[1]
    year = key[2]
    
    coefficients.append(coef)
    errors.append(err)
    pvalues.append(pvalue)
    benefits.append(benefit)
    occupations.append(occ)
    years.append(year)

# Creating DataFrame
results = {
    'Benefit': benefits,
    'Occupation': occupations,
    'Year': years,
    'AI Coefficient': coefficients,
    'Error': errors,
    'P-Value': pvalues,
}

results_df = pd.DataFrame(results)

In [21]:
results_df

,Benefit,Occupation,Year,AI Coefficient,Error,P-Value
0,LEAVE,Architecture and Engineering Occupations,2019,-0.301721,0.125739,0.016
1,LEAVE,Architecture and Engineering Occupations,2021,-0.624508,0.104244,0.000
2,LEAVE,Architecture and Engineering Occupations,2022,-0.412328,0.075161,0.000
3,LEAVE,Architecture and Engineering Occupations,2020,-0.516013,0.134353,0.000
4,LEAVE,Architecture and Engineering Occupations,2018,-0.299582,0.164799,0.069
...,...,...,...,...,...,...
355,CULTURE,Transportation and Material Moving Occupations,2021,1.845892,0.207550,0.000
356,CULTURE,Transportation and Material Moving Occupations,2022,1.351989,0.208825,0.000
357,CULTURE,Transportation and Material Moving Occupations,2020,0.548588,0.735181,0.456
358,CULTURE,Transportation and Material Moving Occupations,2018,0.825759,0.737997,0.263
359,CULTURE,Transportation and Material Moving Occupations,2023,1.039471,0.268258,0.000