In [3]:
import pandas as pd
import numpy as np
import os
from tqdm import tqdm

# Merge AI Skills

In [6]:
jobs_path = "../data/US_10M_SAMP_2018_2024.csv"

In [4]:
# processed data from thesis with AI skills labels
p_data = pd.read_parquet('/data/sant6443/thesis/data/us_10m_wham_nointernship_2019_2023.parquet.gzip')

In [7]:
all_data = pd.read_csv(jobs_path)

In [8]:
all_data = all_data[all_data['IS_INTERNSHIP']==False]

In [9]:
p_data = p_data[['ID','Has AI Skills', 'wfh_wham_prob', 'wfh_wham']]

In [10]:
all_data = all_data.merge(p_data, left_on='ID', right_on='ID', how='left')

In [11]:
all_data.groupby('Has AI Skills', dropna = False).size()

Has AI Skills
NaN      9491231
False     376596
True        5089
dtype: int64

In [12]:
all_data['YEAR'] = pd.to_datetime(all_data['POSTED']).dt.year

In [13]:
all_data.groupby('YEAR').size()

YEAR
2018    1261511
2019    1315041
2020    1329114
2021    1669520
2022    1851776
2023    1485795
2024     960159
dtype: int64

In [14]:
all_data[all_data['Has AI Skills'].isnull()].groupby('YEAR').size()

YEAR
2018    1261511
2019    1249433
2020    1262765
2021    1585613
2022    1759199
2023    1412690
2024     960020
dtype: int64

In [15]:
len(all_data)

9872916

In [16]:
pd.set_option('display.max_columns', None)

In [17]:
all_data.head()

,ID,CITY_NAME,COUNTY_NAME,STATE_NAME,NAICS_2022_2,NAICS_2022_2_NAME,MIN_EDULEVELS_NAME,EMPLOYMENT_TYPE,EMPLOYMENT_TYPE_NAME,IS_INTERNSHIP,REMOTE_TYPE,REMOTE_TYPE_NAME,SKILLS,SKILLS_NAME,POSTED,LAST_UPDATED_DATE,ONET,ONET_NAME,ONET_2019,ONET_2019_NAME,SOC_2021_2_NAME,SOC_2021_2,MIN_YEARS_EXPERIENCE,COMPANY,COMPANY_NAME,COMPANY_RAW,SALARY,EXPIRED,DURATION,Has AI Skills,wfh_wham_prob,wfh_wham,YEAR
0,dbd9da50520e4ed0864427c9d58bdf4673c704ad,"Portland, OR","Multnomah, OR",Oregon,56,Administrative and Support and Waste Managemen...,High school or GED,1,Full-time (> 32 hours),False,0,[None],"[\n ""KS124DX6G31F5M9ZHNGC"",\n ""ESA2046B83319...","[\n ""Warehousing"",\n ""Lifting Ability"",\n ""...",2019-02-20,2024-05-17,53-7062.00,"Laborers and Freight, Stock, and Material Move...",53-7062.00,"Laborers and Freight, Stock, and Material Move...",Transportation and Material Moving Occupations,53-0000,NaN,48422725,Staffmark,Staffmark,37440.0,2019-04-26,NaN,NaN,NaN,NaN,2019
1,725cb718e8d0bfe4260d95537839a35ddf781959,"Tustin, CA","Orange, CA",California,56,Administrative and Support and Waste Managemen...,No Education Listed,1,Full-time (> 32 hours),False,0,[None],"[\n ""KS440M674RBW55227V0R""\n]","[\n ""Site Security""\n]",2019-02-20,2024-03-26,33-9032.00,Security Guards,33-9032.00,Security Guards,Protective Service Occupations,33-0000,NaN,838753,Absolute Security Agency,Absolute Security,30160.0,2019-04-22,NaN,NaN,NaN,NaN,2019
2,c99cf3ae6b7917c8d802b0397287f3cc0401af4b,"Richmond, VA","Richmond City, VA",Virginia,56,Administrative and Support and Waste Managemen...,No Education Listed,1,Full-time (> 32 hours),False,0,[None],"[\n ""KS1218W78FGVPVP2KXPX"",\n ""KS1287M692W39...","[\n ""Management"",\n ""Punctuality"",\n ""Sorti...",2019-02-20,2024-06-17,49-3023.00,Automotive Service Technicians and Mechanics,49-3023.00,Automotive Service Technicians and Mechanics,"Installation, Maintenance, and Repair Occupations",49-0000,NaN,32850008,Loomis,Loomis,NaN,2019-05-30,NaN,NaN,NaN,NaN,2019
3,62716bc7b6f10618f957b7851767b69e99168265,"New York, NY","New York, NY",New York,99,Unclassified Industry,No Education Listed,1,Full-time (> 32 hours),False,0,[None],"[\n ""KS1208X76FB40ZXZXY03"",\n ""ES6978BEA5407...","[\n ""Advertising Campaigns"",\n ""Digital Adve...",2019-02-20,2024-06-17,11-1021.00,General and Operations Managers,11-1021.00,General and Operations Managers,Management Occupations,11-0000,NaN,0,Unclassified,Recruiter From Aggregation,NaN,2019-05-05,NaN,False,0.001,0.0,2019
4,ff7641b30a88da7e6e6fbca3c01e0751982b2ec2,"Watkinsville, GA","Oconee, GA",Georgia,56,Administrative and Support and Waste Managemen...,No Education Listed,1,Full-time (> 32 hours),False,0,[None],"[\n ""BGS57B070457D0268BF2"",\n ""KS122HN73YRF1...","[\n ""Pre-Trip And Post-Trip Vehicle Inspectio...",2019-02-20,2023-12-14,53-3032.00,Heavy and Tractor-Trailer Truck Drivers,53-3032.00,Heavy and Tractor-Trailer Truck Drivers,Transportation and Material Moving Occupations,53-0000,3.0,36914990,Advanced Disposal Services,Advanced Disposal,NaN,2019-05-04,NaN,NaN,NaN,NaN,2019

In [18]:
all_data.to_parquet('../data/us_10m_nointernship_2018_2024.parquet.gzip', compression='gzip')

In [19]:
# prev_all_data = pd.read_parquet('../data/us_10m_nointernship__ai_skills.parquet.gzip')

In [20]:
# prev_all_data[prev_all_data['wfh_wham'].isna()].groupby('YEAR').size()

In [ ]:
# del prev_all_data

:

# Missing WHAM

In [21]:
wham_data = pd.read_csv('../data/ID_CNTRY_ALL_WHAM.csv')

In [22]:
wham_us = wham_data[wham_data['country2'] == 'US']

In [23]:
wham_us

,id,country,wfh_wham_prob,wfh_wham,country2
896559,2f66d987cc63932c6fa4a01d294a9cb13142e228,UK,0.006,0.0,US
904421,631129ec881670a0be488b8b21897c301cb709df,US,0.002,0.0,US
904422,01e412252eae2d2d1b28419e29b6b52ff4bcc531,US,0.003,0.0,US
904423,46765c192d1005981bd7a8f150cb6f380abe0d8d,US,0.011,0.0,US
904424,5e77607deac0e65103a67cb57aa9609ef8c69b88,US,0.994,1.0,US
...,...,...,...,...,...
1834267,6d2ed51e4e6947c8a87430f9ad8a91abc58b48ff,US,0.001,0.0,US
1834268,2163c0e012d3e674d283cc8aa67e618e550375d4,US,0.002,0.0,US
1834269,a285d08ef1ac38075b8e72df597797eb44437711,US,0.005,0.0,US
1834270,436fe22e7495ff3b5f8fdd8e10d5dc82b868c0b3,US,0.001,0.0,US
1834271,92ec36369f0dcb85e10dc00abcffc5499e0824c4,US,0.007,0.0,US

In [24]:
# fill nas in all_data wfh_wham_prob and wfh_wham with the data in wham_us
all_data = all_data.merge(wham_us[['id','wfh_wham_prob','wfh_wham']], left_on='ID', right_on='id', how='left', suffixes = ('', '_wham'))

In [25]:
all_data['wfh_wham_prob'] = all_data['wfh_wham_prob'].combine_first(all_data['wfh_wham_prob_wham'])

In [26]:
all_data['wfh_wham'] = all_data['wfh_wham'].combine_first(all_data['wfh_wham_wham'])

In [27]:
all_data[all_data['wfh_wham_prob'].isna()].groupby('YEAR').size()

YEAR
2018    1261037
2019    1246370
2020    1258931
2021    1580157
2022    1753201
2023    1407708
2024     958775
dtype: int64

In [28]:
all_data.head()

,ID,CITY_NAME,COUNTY_NAME,STATE_NAME,NAICS_2022_2,NAICS_2022_2_NAME,MIN_EDULEVELS_NAME,EMPLOYMENT_TYPE,EMPLOYMENT_TYPE_NAME,IS_INTERNSHIP,REMOTE_TYPE,REMOTE_TYPE_NAME,SKILLS,SKILLS_NAME,POSTED,LAST_UPDATED_DATE,ONET,ONET_NAME,ONET_2019,ONET_2019_NAME,SOC_2021_2_NAME,SOC_2021_2,MIN_YEARS_EXPERIENCE,COMPANY,COMPANY_NAME,COMPANY_RAW,SALARY,EXPIRED,DURATION,Has AI Skills,wfh_wham_prob,wfh_wham,YEAR,id,wfh_wham_prob_wham,wfh_wham_wham
0,dbd9da50520e4ed0864427c9d58bdf4673c704ad,"Portland, OR","Multnomah, OR",Oregon,56,Administrative and Support and Waste Managemen...,High school or GED,1,Full-time (> 32 hours),False,0,[None],"[\n ""KS124DX6G31F5M9ZHNGC"",\n ""ESA2046B83319...","[\n ""Warehousing"",\n ""Lifting Ability"",\n ""...",2019-02-20,2024-05-17,53-7062.00,"Laborers and Freight, Stock, and Material Move...",53-7062.00,"Laborers and Freight, Stock, and Material Move...",Transportation and Material Moving Occupations,53-0000,NaN,48422725,Staffmark,Staffmark,37440.0,2019-04-26,NaN,NaN,NaN,NaN,2019,NaN,NaN,NaN
1,725cb718e8d0bfe4260d95537839a35ddf781959,"Tustin, CA","Orange, CA",California,56,Administrative and Support and Waste Managemen...,No Education Listed,1,Full-time (> 32 hours),False,0,[None],"[\n ""KS440M674RBW55227V0R""\n]","[\n ""Site Security""\n]",2019-02-20,2024-03-26,33-9032.00,Security Guards,33-9032.00,Security Guards,Protective Service Occupations,33-0000,NaN,838753,Absolute Security Agency,Absolute Security,30160.0,2019-04-22,NaN,NaN,NaN,NaN,2019,NaN,NaN,NaN
2,c99cf3ae6b7917c8d802b0397287f3cc0401af4b,"Richmond, VA","Richmond City, VA",Virginia,56,Administrative and Support and Waste Managemen...,No Education Listed,1,Full-time (> 32 hours),False,0,[None],"[\n ""KS1218W78FGVPVP2KXPX"",\n ""KS1287M692W39...","[\n ""Management"",\n ""Punctuality"",\n ""Sorti...",2019-02-20,2024-06-17,49-3023.00,Automotive Service Technicians and Mechanics,49-3023.00,Automotive Service Technicians and Mechanics,"Installation, Maintenance, and Repair Occupations",49-0000,NaN,32850008,Loomis,Loomis,NaN,2019-05-30,NaN,NaN,NaN,NaN,2019,NaN,NaN,NaN
3,62716bc7b6f10618f957b7851767b69e99168265,"New York, NY","New York, NY",New York,99,Unclassified Industry,No Education Listed,1,Full-time (> 32 hours),False,0,[None],"[\n ""KS1208X76FB40ZXZXY03"",\n ""ES6978BEA5407...","[\n ""Advertising Campaigns"",\n ""Digital Adve...",2019-02-20,2024-06-17,11-1021.00,General and Operations Managers,11-1021.00,General and Operations Managers,Management Occupations,11-0000,NaN,0,Unclassified,Recruiter From Aggregation,NaN,2019-05-05,NaN,False,0.001,0.0,2019,NaN,NaN,NaN
4,ff7641b30a88da7e6e6fbca3c01e0751982b2ec2,"Watkinsville, GA","Oconee, GA",Georgia,56,Administrative and Support and Waste Managemen...,No Education Listed,1,Full-time (> 32 hours),False,0,[None],"[\n ""BGS57B070457D0268BF2"",\n ""KS122HN73YRF1...","[\n ""Pre-Trip And Post-Trip Vehicle Inspectio...",2019-02-20,2023-12-14,53-3032.00,Heavy and Tractor-Trailer Truck Drivers,53-3032.00,Heavy and Tractor-Trailer Truck Drivers,Transportation and Material Moving Occupations,53-0000,3.0,36914990,Advanced Disposal Services,Advanced Disposal,NaN,2019-05-04,NaN,NaN,NaN,NaN,2019,NaN,NaN,NaN

In [29]:
all_data.drop(columns=['id', 'wfh_wham_prob_wham', 'wfh_wham_wham'], inplace=True)

In [31]:
all_data.to_parquet('../data/us_10m_nointernship_2018_2024.parquet.gzip', compression='gzip')

In [4]:
all_data = pd.read_parquet('../data/us_10m_nointernship_2018_2024.parquet.gzip')

In [5]:
all_data.head()

,ID,CITY_NAME,COUNTY_NAME,STATE_NAME,NAICS_2022_2,NAICS_2022_2_NAME,MIN_EDULEVELS_NAME,EMPLOYMENT_TYPE,EMPLOYMENT_TYPE_NAME,IS_INTERNSHIP,...,COMPANY,COMPANY_NAME,COMPANY_RAW,SALARY,EXPIRED,DURATION,Has AI Skills,wfh_wham_prob,wfh_wham,YEAR
0,dbd9da50520e4ed0864427c9d58bdf4673c704ad,"Portland, OR","Multnomah, OR",Oregon,56,Administrative and Support and Waste Managemen...,High school or GED,1,Full-time (> 32 hours),False,...,48422725,Staffmark,Staffmark,37440.0,2019-04-26,NaN,None,NaN,NaN,2019
1,725cb718e8d0bfe4260d95537839a35ddf781959,"Tustin, CA","Orange, CA",California,56,Administrative and Support and Waste Managemen...,No Education Listed,1,Full-time (> 32 hours),False,...,838753,Absolute Security Agency,Absolute Security,30160.0,2019-04-22,NaN,None,NaN,NaN,2019
2,c99cf3ae6b7917c8d802b0397287f3cc0401af4b,"Richmond, VA","Richmond City, VA",Virginia,56,Administrative and Support and Waste Managemen...,No Education Listed,1,Full-time (> 32 hours),False,...,32850008,Loomis,Loomis,NaN,2019-05-30,NaN,None,NaN,NaN,2019
3,62716bc7b6f10618f957b7851767b69e99168265,"New York, NY","New York, NY",New York,99,Unclassified Industry,No Education Listed,1,Full-time (> 32 hours),False,...,0,Unclassified,Recruiter From Aggregation,NaN,2019-05-05,NaN,False,0.001,0.0,2019
4,ff7641b30a88da7e6e6fbca3c01e0751982b2ec2,"Watkinsville, GA","Oconee, GA",Georgia,56,Administrative and Support and Waste Managemen...,No Education Listed,1,Full-time (> 32 hours),False,...,36914990,Advanced Disposal Services,Advanced Disposal,NaN,2019-05-04,NaN,None,NaN,NaN,2019

In [7]:
all_data.head()

,ID,CITY_NAME,COUNTY_NAME,STATE_NAME,NAICS_2022_2,NAICS_2022_2_NAME,MIN_EDULEVELS_NAME,EMPLOYMENT_TYPE,EMPLOYMENT_TYPE_NAME,IS_INTERNSHIP,...,COMPANY,COMPANY_NAME,COMPANY_RAW,SALARY,EXPIRED,DURATION,AI ROLE,wfh_wham_prob,wfh_wham,YEAR
0,dbd9da50520e4ed0864427c9d58bdf4673c704ad,"Portland, OR","Multnomah, OR",Oregon,56,Administrative and Support and Waste Managemen...,High school or GED,1,Full-time (> 32 hours),False,...,48422725,Staffmark,Staffmark,37440.0,2019-04-26,NaN,None,NaN,NaN,2019
1,725cb718e8d0bfe4260d95537839a35ddf781959,"Tustin, CA","Orange, CA",California,56,Administrative and Support and Waste Managemen...,No Education Listed,1,Full-time (> 32 hours),False,...,838753,Absolute Security Agency,Absolute Security,30160.0,2019-04-22,NaN,None,NaN,NaN,2019
2,c99cf3ae6b7917c8d802b0397287f3cc0401af4b,"Richmond, VA","Richmond City, VA",Virginia,56,Administrative and Support and Waste Managemen...,No Education Listed,1,Full-time (> 32 hours),False,...,32850008,Loomis,Loomis,NaN,2019-05-30,NaN,None,NaN,NaN,2019
3,62716bc7b6f10618f957b7851767b69e99168265,"New York, NY","New York, NY",New York,99,Unclassified Industry,No Education Listed,1,Full-time (> 32 hours),False,...,0,Unclassified,Recruiter From Aggregation,NaN,2019-05-05,NaN,False,0.001,0.0,2019
4,ff7641b30a88da7e6e6fbca3c01e0751982b2ec2,"Watkinsville, GA","Oconee, GA",Georgia,56,Administrative and Support and Waste Managemen...,No Education Listed,1,Full-time (> 32 hours),False,...,36914990,Advanced Disposal Services,Advanced Disposal,NaN,2019-05-04,NaN,None,NaN,NaN,2019

In [8]:
all_data.to_parquet('../data/us_10m_nointernship_2018_2024.parquet.gzip', compression='gzip')

# Body

In [ ]:
# file_path = 'OII_US_POST_BODY.csv'

# # Get the total file size in bytes
# file_size = os.path.getsize(file_path)

# # Define the chunk size (number of rows per chunk)
# chunk_size = 10000

# # Initialize an empty list to store chunks
# data = []

# # Track the number of bytes read
# bytes_read = 0

# # Use tqdm to display the progress based on file size
# with tqdm(total=file_size, unit='B', unit_scale=True, desc="Loading CSV by file size") as pbar:
#     for chunk in pd.read_csv(file_path, chunksize=chunk_size):
#         data.append(chunk)
#         # Estimate bytes read so far based on chunk size
#         bytes_read += chunk.memory_usage(deep=True).sum()
#         # Update the progress bar with the number of bytes read
#         pbar.update(bytes_read - pbar.n)  # Ensure only new bytes are updated

# # Combine all chunks into a single DataFrame
# df = pd.concat(data, ignore_index=True)

In [ ]:
# body = pd.read_csv('../data/OII_US_POST_BODY.csv')

:

In [70]:
# os.path.getsize('../data/OII_US_POST_BODY.csv')

42189594287

In [10]:
import pickle

In [11]:
with open('../data/ai_skill_ids.pkl', 'rb') as f:
    ai_skill_ids = pickle.load(f)

In [12]:
ai_skill_ids

['ESAA77F0192404022E6E',
 'ES85AFFFA8A800AA4183',
 'ES7A4A3108C91C3F1FA0',
 'KS120HN74DS7P7PZF5YG',
 'KS120BV70XSJ6K0VQ6S5',
 'KS120BV6SR75RBKQH0G3',
 'KS7K2A142LYPQ2Q5N1Q6',
 'KS8V94BPPMIAWFLCKAHX',
 'KS120NP6J9YGDMN22JGF',
 'KS1251W5YWWBQML40R1V',
 'KS121YL65WGC33FY3HZQ',
 'KS1233K70C24NF12YG0N',
 'ES15B4B78CE4AACB7C59',
 'KS123RD5VV5WNJLMNH3J',
 'KS1227Q6JV6422C87ZWJ',
 'ES2E76FA3B9FA0476A56',
 'ES3D672758CB8F565C26',
 'ES39A0A16CDFBA2513AE',
 'ESCFF5FDB56CA2D4D461',
 'KSYCVNF7JZ2WR6LZUF9O',
 'ES2DCA677488DDF61152',
 'ES5CC048D272E45D3BAE',
 'KS1271Z6ZP3RPMKFFCK7',
 'KS120Y46KRD66D2SZNC6',
 'KS1275V6DZ2L59VVKR17',
 'KS356BMWWAJ8MKV2TE7R',
 'KS127LW6D7WX0VCCSPVW',
 'KS128006SHHBNZBR2DQZ',
 'ES869C48CA74A6643EC0',
 'KS1280Y78Z7S6RND0SL6',
 'KSWXHT30GQY9B4QSXC5O',
 'ESEBE7F9DAD5C5E6ADE9',
 'KSIJUG1D2NW7T16XO96D',
 'KS1289Z6HTNVK1WM0WFY',
 'KS128FT5XK7FS63H8GL2',
 'KSJ2QBJ158RE1QN9D3AZ',
 'KS440G0737QHPRYSJH4C',
 'KS440GD6P1YQJXPMT0W2',
 'KS440GH5YRZFQDHSFKVC',
 'ESBD03499053871E7AD9',
 'KS4413Q6MBGFCJV0LXC5',
 'ESDF8AE073A25208E767',
 'ES708E114D6101ACB618',
 'KSYMJOZ8SL2197CK9UAU',
 'ESD2E015633809B06EA7',
 'ES2133DA6434CF028833',
 'ESB17C5AF46AFE08157D',
 'ESE482BE10DF9CD13AE0',
 'KSAS8LK1JG2Y0OLN4C53',
 'ESBAAA6244437165D77B',
 'ESFE93CC6681F6A89148',
 'KS120NM6L2KDLC2Z9DND',
 'KS120NN6SBW45D10MY36',
 'ESBD14A88C96CEF6B04C',
 'ES1E2CB20570CC2A253A',
 'ESF5943639E2E815A6F4',
 'ES53E6EA8285F66F0CE7',
 'ES4EBB7783C15000E24A',
 'ES2BB25DB544B26CD7AA',
 'ES7D62D76A51080FBD2A',
 'ES3E181DDDBC374119D5',
 'KSBZ9LW988KC56I219SP',
 'ES444F7110B700C46A8C',
 'ES1F68481E34111AB230',
 'KS122ZH71HN3JMGYNBS7',
 'ESB3C965DAF0075A5C19',
 'ES1A0545B3AA7D600CCE',
 'KS7GT1F0QQOV7R7VGXQL',
 'KSQQSY7DG7KE6EUJGXS9',
 'ES52274D181DA23B7CF1',
 'KS441R26FF6RF17KLYD7',
 'ES23C862B4C3053AB824',
 'ESAC03E3F28A716D359E',
 'ES621714B943488C07C8',
 'ESD5C3FF77F38D04C794',
 'ES7E661995FDFAA3C497',
 'ESD54FC029413CFCA935',
 'KS124HT6VKLQNKPPQGMC',
 'KSFHF2FU8HN39495VYLU',
 'ES2DCA677488DDF61152',
 'ES7649EF3746BDC3C8CA',
 'ES7A460DFF81957229AF',
 'KS1261Z68KSKR1X31KS3',
 'KS125S466GJGQXS1W0JM',
 'ES2933FAEF72CE4E2840',
 'ESD9FA18BDE2BAA43E6B',
 'ESD4651059C6EA47E547',
 'KS126237283GZN8NX5P6',
 'KS1262461WCYHBPTT2NB',
 'ES178620CD884136502E',
 'KS126XH6P88H3G6N5DC8',
 'ES24F12E3B60C11D1237',
 'KS1271Z6JS5110PHSPC6',
 'ESA0975524BD1E6C40FA',
 'KS12791657JTS84RWLVQ',
 'KS120M36164Y2LMZ1NKC',
 'ESC6A63BE9B2D7791666',
 'KS128006L3V0HM2B26N5',
 'KSC293HOHNRGC3SHFW40',
 'KSAP4YQTVOS4ZSBNVSRY',
 'KSON1G92ZK13FWTOZ1OT',
 'KS4LL1EBNO7YQ6BSVNIW',
 'ESD67838331142BE19DF',
 'KS440V371JNBV33SG2B7',
 'KS4412R60NGTMD1785Z8',
 'KS2GHRCYA6TRT29F1HOO',
 'KSAX11W5X1N5MG072JDV',
 'KS441BW6SPKJGQ31RGW7',
 'KS8BEQTZC350RBPS03RB',
 'ESFFB6109F270A30945C',
 'ES2FF46EB7E3CD026AFA',
 'KS441MT5ZYPPFK3GC968',
 'ES87C8CE0638526451E1',
 'KSMRJNAVEU39AZTC20S6',
 'KSMUBZFCHO7RG88TFU2G']