In [1]:
import pandas as pd
import numpy as np
import os
from tqdm import tqdm

# Merge AI Skills

In [2]:
jobs_path = "../data/OII_US_10M_POSTS_V2.csv"

In [3]:
# processed data from thesis with AI skills labels
p_data = pd.read_parquet('/data/sant6443/thesis/data/us_10m_wham_nointernship_2019_2023.parquet.gzip')

In [4]:
all_data = pd.read_csv(jobs_path)

In [5]:
all_data = all_data[all_data['IS_INTERNSHIP']==False]

In [6]:
p_data = p_data[['ID','Has AI Skills', 'wfh_wham_prob', 'wfh_wham']]

In [7]:
all_data = all_data.merge(p_data, left_on='ID', right_on='ID', how='left')

In [8]:
all_data.groupby('Has AI Skills', dropna = False).size()

Has AI Skills
False    9810164
True      133852
NaN      1637310
dtype: int64

In [9]:
all_data['YEAR'] = pd.to_datetime(all_data['POSTED']).dt.year

In [10]:
all_data.groupby('YEAR').size()

YEAR
2018    1637310
2019    1704282
2020    1735298
2021    2164896
2022    2402338
2023    1937202
dtype: int64

In [12]:
all_data[all_data['Has AI Skills'].isnull()].groupby('YEAR').size()

YEAR
2018    1637310
dtype: int64

In [9]:
len(all_data)

11581326

In [11]:
pd.set_option('display.max_columns', None)

In [12]:
all_data.head()

,ID,CITY_NAME,COUNTY_NAME,STATE_NAME,NAICS_2022_2,NAICS_2022_2_NAME,MIN_EDULEVELS_NAME,EMPLOYMENT_TYPE,EMPLOYMENT_TYPE_NAME,IS_INTERNSHIP,REMOTE_TYPE,REMOTE_TYPE_NAME,SKILLS,SKILLS_NAME,POSTED,LAST_UPDATED_DATE,ONET,ONET_NAME,ONET_2019,ONET_2019_NAME,SOC_2021_2_NAME,SOC_2021_2,MIN_YEARS_EXPERIENCE,COMPANY,COMPANY_NAME,COMPANY_RAW,Has AI Skills,wfh_wham_prob,wfh_wham,YEAR
0,b5e9360ab429758bc6e8e259fcf66234d3163dcf,"Brentwood, TN","Williamson, TN",Tennessee,62,Health Care and Social Assistance,Master's degree,1,Full-time (> 32 hours),False,0,[None],"[\n ""KS121Z26S4VJLQ1WXN21"",\n ""KS7G4YT72YHJ3...","[\n ""Customer Service"",\n ""Collections"",\n ...",2019-12-05,2024-03-26,29-1051.00,Pharmacists,29-1051.00,Pharmacists,Healthcare Practitioners and Technical Occupat...,29-0000,8.0,47183298,Premise Health,Premise Health,False,0.001,0.0,2019
1,eff8c5c87b50735a4684ebc33d41d1b36ff46aa8,"Smyrna, TN","Rutherford, TN",Tennessee,72,Accommodation and Food Services,High school or GED,1,Full-time (> 32 hours),False,0,[None],"[\n ""KS126DB6T061MHD7RTGQ"",\n ""KS121Z26S4VJL...","[\n ""Merchandising"",\n ""Customer Service"",\n...",2019-12-05,2023-11-03,37-2011.00,"Janitors and Cleaners, Except Maids and Housek...",37-2011.00,"Janitors and Cleaners, Except Maids and Housek...",Building and Grounds Cleaning and Maintenance ...,37-0000,NaN,40582235,Carrols Corporation,Carrols Corporation,False,0.001,0.0,2019
2,b8b974adf881aa6c934392d71ad46dff810dcb34,"Denver, CO","Denver, CO",Colorado,52,Finance and Insurance,Bachelor's degree,1,Full-time (> 32 hours),False,0,[None],"[\n ""KS123Z75WFFSZPXNH04Q"",\n ""ES76F4F346AF3...","[\n ""Firewall"",\n ""Automotive Service Excell...",2019-12-05,2024-03-26,15-1252.00,Software Developers,15-1252.00,Software Developers,Computer and Mathematical Occupations,15-0000,5.0,4808322,Bank of America,Bank of America,False,0.002,0.0,2019
3,65a1fb796d6e098151727adeb2ace5e810361b87,"Chicago, IL","Cook, IL",Illinois,71,"Arts, Entertainment, and Recreation",Bachelor's degree,1,Full-time (> 32 hours),False,0,[None],"[\n ""KS121Z26S4VJLQ1WXN21"",\n ""KS7G747655VG2...","[\n ""Customer Service"",\n ""Prioritization"",\...",2019-12-05,2024-03-26,15-2051.01,Business Intelligence Analysts,15-2051.01,Business Intelligence Analysts,Computer and Mathematical Occupations,15-0000,2.0,24818297,Cwt,CWT,False,0.006,0.0,2019
4,1513ec98d6d7b3ffda588c9834a9ac2e47f8921b,"Plano, TX","Collin, TX",Texas,31,Manufacturing,Bachelor's degree,1,Full-time (> 32 hours),False,0,[None],"[\n ""KSQPGV2XZO8UMNCC49LK"",\n ""KS123YJ6KVWC9...","[\n ""Detail Oriented"",\n ""Financial Statemen...",2019-12-05,2024-01-10,13-2011.00,Accountants and Auditors,13-2011.00,Accountants and Auditors,Business and Financial Operations Occupations,13-0000,3.0,39511702,Keurig Dr Pepper,Keurig Dr Pepper,False,0.001,0.0,2019

In [13]:
all_data.to_parquet('../data/us_10m_nointernship__ai_skills.parquet.gzip', compression='gzip')

In [27]:
prev_all_data = pd.read_parquet('../data/us_10m_nointernship__ai_skills.parquet.gzip')

In [28]:
prev_all_data[prev_all_data['wfh_wham'].isna()].groupby('YEAR').size()

YEAR
2018    1637310
2019      45122
2020      33499
2021      12485
2022      14631
2023      12041
dtype: int64

In [ ]:
del prev_all_data

:

# Missing WHAM

In [14]:
wham_data = pd.read_csv('../data/ID_CNTRY_ALL_WHAM.csv')

In [16]:
wham_us = wham_data[wham_data['country2'] == 'US']

In [17]:
wham_us

,id,country,wfh_wham_prob,wfh_wham,country2
896559,2f66d987cc63932c6fa4a01d294a9cb13142e228,UK,0.006,0.0,US
904421,631129ec881670a0be488b8b21897c301cb709df,US,0.002,0.0,US
904422,01e412252eae2d2d1b28419e29b6b52ff4bcc531,US,0.003,0.0,US
904423,46765c192d1005981bd7a8f150cb6f380abe0d8d,US,0.011,0.0,US
904424,5e77607deac0e65103a67cb57aa9609ef8c69b88,US,0.994,1.0,US
...,...,...,...,...,...
1834267,6d2ed51e4e6947c8a87430f9ad8a91abc58b48ff,US,0.001,0.0,US
1834268,2163c0e012d3e674d283cc8aa67e618e550375d4,US,0.002,0.0,US
1834269,a285d08ef1ac38075b8e72df597797eb44437711,US,0.005,0.0,US
1834270,436fe22e7495ff3b5f8fdd8e10d5dc82b868c0b3,US,0.001,0.0,US
1834271,92ec36369f0dcb85e10dc00abcffc5499e0824c4,US,0.007,0.0,US

In [19]:
# fill nas in all_data wfh_wham_prob and wfh_wham with the data in wham_us
all_data = all_data.merge(wham_us[['id','wfh_wham_prob','wfh_wham']], left_on='ID', right_on='id', how='left', suffixes = ('', '_wham'))

In [20]:
all_data['wfh_wham_prob'] = all_data['wfh_wham_prob'].combine_first(all_data['wfh_wham_prob_wham'])

In [21]:
all_data['wfh_wham'] = all_data['wfh_wham'].combine_first(all_data['wfh_wham_wham'])

In [26]:
all_data[all_data['wfh_wham_prob'].isna()].groupby('YEAR').size()

YEAR
2018    1636658
2019      45122
2020      33499
2021      12485
2022      14631
2023      12041
dtype: int64

In [29]:
all_data.head()

,ID,CITY_NAME,COUNTY_NAME,STATE_NAME,NAICS_2022_2,NAICS_2022_2_NAME,MIN_EDULEVELS_NAME,EMPLOYMENT_TYPE,EMPLOYMENT_TYPE_NAME,IS_INTERNSHIP,REMOTE_TYPE,REMOTE_TYPE_NAME,SKILLS,SKILLS_NAME,POSTED,LAST_UPDATED_DATE,ONET,ONET_NAME,ONET_2019,ONET_2019_NAME,SOC_2021_2_NAME,SOC_2021_2,MIN_YEARS_EXPERIENCE,COMPANY,COMPANY_NAME,COMPANY_RAW,Has AI Skills,wfh_wham_prob,wfh_wham,YEAR,id,wfh_wham_prob_wham,wfh_wham_wham
0,b5e9360ab429758bc6e8e259fcf66234d3163dcf,"Brentwood, TN","Williamson, TN",Tennessee,62,Health Care and Social Assistance,Master's degree,1,Full-time (> 32 hours),False,0,[None],"[\n ""KS121Z26S4VJLQ1WXN21"",\n ""KS7G4YT72YHJ3...","[\n ""Customer Service"",\n ""Collections"",\n ...",2019-12-05,2024-03-26,29-1051.00,Pharmacists,29-1051.00,Pharmacists,Healthcare Practitioners and Technical Occupat...,29-0000,8.0,47183298,Premise Health,Premise Health,False,0.001,0.0,2019,NaN,NaN,NaN
1,eff8c5c87b50735a4684ebc33d41d1b36ff46aa8,"Smyrna, TN","Rutherford, TN",Tennessee,72,Accommodation and Food Services,High school or GED,1,Full-time (> 32 hours),False,0,[None],"[\n ""KS126DB6T061MHD7RTGQ"",\n ""KS121Z26S4VJL...","[\n ""Merchandising"",\n ""Customer Service"",\n...",2019-12-05,2023-11-03,37-2011.00,"Janitors and Cleaners, Except Maids and Housek...",37-2011.00,"Janitors and Cleaners, Except Maids and Housek...",Building and Grounds Cleaning and Maintenance ...,37-0000,NaN,40582235,Carrols Corporation,Carrols Corporation,False,0.001,0.0,2019,NaN,NaN,NaN
2,b8b974adf881aa6c934392d71ad46dff810dcb34,"Denver, CO","Denver, CO",Colorado,52,Finance and Insurance,Bachelor's degree,1,Full-time (> 32 hours),False,0,[None],"[\n ""KS123Z75WFFSZPXNH04Q"",\n ""ES76F4F346AF3...","[\n ""Firewall"",\n ""Automotive Service Excell...",2019-12-05,2024-03-26,15-1252.00,Software Developers,15-1252.00,Software Developers,Computer and Mathematical Occupations,15-0000,5.0,4808322,Bank of America,Bank of America,False,0.002,0.0,2019,NaN,NaN,NaN
3,65a1fb796d6e098151727adeb2ace5e810361b87,"Chicago, IL","Cook, IL",Illinois,71,"Arts, Entertainment, and Recreation",Bachelor's degree,1,Full-time (> 32 hours),False,0,[None],"[\n ""KS121Z26S4VJLQ1WXN21"",\n ""KS7G747655VG2...","[\n ""Customer Service"",\n ""Prioritization"",\...",2019-12-05,2024-03-26,15-2051.01,Business Intelligence Analysts,15-2051.01,Business Intelligence Analysts,Computer and Mathematical Occupations,15-0000,2.0,24818297,Cwt,CWT,False,0.006,0.0,2019,NaN,NaN,NaN
4,1513ec98d6d7b3ffda588c9834a9ac2e47f8921b,"Plano, TX","Collin, TX",Texas,31,Manufacturing,Bachelor's degree,1,Full-time (> 32 hours),False,0,[None],"[\n ""KSQPGV2XZO8UMNCC49LK"",\n ""KS123YJ6KVWC9...","[\n ""Detail Oriented"",\n ""Financial Statemen...",2019-12-05,2024-01-10,13-2011.00,Accountants and Auditors,13-2011.00,Accountants and Auditors,Business and Financial Operations Occupations,13-0000,3.0,39511702,Keurig Dr Pepper,Keurig Dr Pepper,False,0.001,0.0,2019,NaN,NaN,NaN

In [30]:
all_data.drop(columns=['id', 'wfh_wham_prob_wham', 'wfh_wham_wham'], inplace=True)

In [31]:
all_data.to_parquet('../data/us_10m_nointernship__ai_skills.parquet.gzip', compression='gzip')

# Body

In [ ]:
# file_path = 'OII_US_POST_BODY.csv'

# # Get the total file size in bytes
# file_size = os.path.getsize(file_path)

# # Define the chunk size (number of rows per chunk)
# chunk_size = 10000

# # Initialize an empty list to store chunks
# data = []

# # Track the number of bytes read
# bytes_read = 0

# # Use tqdm to display the progress based on file size
# with tqdm(total=file_size, unit='B', unit_scale=True, desc="Loading CSV by file size") as pbar:
#     for chunk in pd.read_csv(file_path, chunksize=chunk_size):
#         data.append(chunk)
#         # Estimate bytes read so far based on chunk size
#         bytes_read += chunk.memory_usage(deep=True).sum()
#         # Update the progress bar with the number of bytes read
#         pbar.update(bytes_read - pbar.n)  # Ensure only new bytes are updated

# # Combine all chunks into a single DataFrame
# df = pd.concat(data, ignore_index=True)

In [ ]:
# body = pd.read_csv('../data/OII_US_POST_BODY.csv')

:

In [70]:
# os.path.getsize('../data/OII_US_POST_BODY.csv')

42189594287