In [2]:
import pandas as pd

In [3]:
posts_df = pd.read_csv('/Users/alejandracastaneda/Documents/Backup/beyond-salary-mb/data/OII_US_10M_POSTS_MAY26_SUBSAMPLE.csv')

In [5]:
pd.set_option('display.max_columns', None)  # Show all columns

In [6]:
posts_df.head()

,ID,POSTED,TITLE_RAW,COMPANY,COMPANY_NAME,MIN_EDULEVELS_NAME,EMPLOYMENT_TYPE_NAME,MIN_YEARS_EXPERIENCE,SALARY,REMOTE_TYPE_NAME,CITY_NAME,STATE_NAME,NAICS_2022_6,NAICS_2022_6_NAME,ONET,ONET_NAME,BENEFIT_NAME,BENEFIT_SUBCATEGORY_NAME,BENEFIT_CATEGORIES_NAME,YEAR,QUARTER
0,cc25bf7987491446b2c7f735c28c65605df5fc61,2021-11-30,Senior Medical Review Nurse Analyst (RN),99495737,WPS Health,Bachelor's degree,Full-time (> 32 hours),4.0,NaN,Remote,"Jacksonville, FL",Florida,524114,Direct Health and Medical Insurance Carriers,29-1141.00,Registered Nurses,"[\n ""Paid Time Off (PTO)"",\n ""401(k) Plans"",...","[\n ""Paid Time Off (PTO)"",\n ""401(k) Plans"",...","[\n ""Paid Leave"",\n ""Retirement and Savings""...",2021,4
1,f31e97e70d4dede03a6598532ad915a13755ecf0,2021-11-30,Senior Product Owner - Medicaid/LTSS,6915630,Humana,Bachelor's degree,Full-time (> 32 hours),5.0,NaN,[None],"Jersey City, NJ",New Jersey,524114,Direct Health and Medical Insurance Carriers,15-1299.09,Information Technology Project Managers,[],[],[],2021,4
2,b625146166c02402312a679240abb908cd113c15,2022-05-10,"Clinical Supervisor, Substance Use Disorders -...",37614618,Central City Concern,No Education Listed,Full-time (> 32 hours),5.0,100000.0,[None],"Portland, OR",Oregon,624190,Other Individual and Family Services,11-9111.00,Medical and Health Services Managers,"[\n ""Paid Time Off (PTO)"",\n ""403(b) Tax-She...","[\n ""Paid Time Off (PTO)"",\n ""403(b) Tax-She...","[\n ""Paid Leave"",\n ""Retirement and Savings""...",2022,2
3,948882b652a32dfe2f2cf3dec27d3690181ac30a,2022-05-10,Seasonal Landscaper,41454246,HEI Hotels & Resorts,No Education Listed,Full-time (> 32 hours),NaN,NaN,[None],"Waltham, MA",Massachusetts,721110,Hotels (except Casino Hotels) and Motels,37-3011.00,Landscaping and Groundskeeping Workers,"[\n ""401(k) Plans"",\n ""Vision Insurance"",\n ...","[\n ""401(k) Plans"",\n ""Vision Insurance"",\n ...","[\n ""Retirement and Savings"",\n ""Insurance"",...",2022,2
4,a61e73a98166933c51df646c2181852954124070,2022-05-10,Endoscopy Registered Nurse PRN,39850046,St. David's Healthcare Partnership,Associate degree,Full-time (> 32 hours),1.0,NaN,[None],"Austin, TX",Texas,622110,General Medical and Surgical Hospitals,29-1141.00,Registered Nurses,"[\n ""Paid Time Off (PTO)"",\n ""401(k) Plans"",...","[\n ""Paid Time Off (PTO)"",\n ""401(k) Plans"",...","[\n ""Paid Leave"",\n ""Retirement and Savings""...",2022,2

# Benefit Categories

In [30]:
posts_df['BENEFIT_CATEGORIES_NAME'].value_counts()

BENEFIT_CATEGORIES_NAME
[]                                                                                                                                                                                                                                                                                   50501
[\n  "Work-Life Balance"\n]                                                                                                                                                                                                                                                           3466
[\n  "Education and Career Development"\n]                                                                                                                                                                                                                                            1997
[\n  "Supplemental Pay"\n]                                                                                                                                                                                                                                                            1648
[\n  "Paid Leave"\n]                                                                                                                                                                                                                                                                  1285
                                                                                                                                                                                                                                                                                     ...
[\n  "Paid Leave",\n  "Paid Leave",\n  "Paid Leave",\n  "Retirement and Savings",\n  "Health and Wellness Benefits",\n  "Insurance",\n  "Insurance",\n  "Insurance",\n  "Insurance"\n]                                                                                                   1
[\n  "Education and Career Development",\n  "Retirement and Savings",\n  "Supplemental Pay",\n  "Insurance",\n  "Insurance",\n  "Insurance",\n  "Insurance",\n  "Insurance"\n]                                                                                                           1
[\n  "Paid Leave",\n  "Paid Leave",\n  "Retirement and Savings",\n  "Education and Career Development",\n  "Retirement and Savings",\n  "Insurance",\n  "Insurance",\n  "Other Benefits"\n]                                                                                              1
[\n  "Paid Leave",\n  "Education and Career Development",\n  "Insurance",\n  "Work-Life Balance",\n  "Work-Life Balance"\n]                                                                                                                                                              1
[\n  "Paid Leave",\n  "Paid Leave",\n  "Paid Leave",\n  "Education and Career Development",\n  "Retirement and Savings",\n  "Retirement and Savings",\n  "Supplemental Pay",\n  "Health and Wellness Benefits",\n  "Insurance",\n  "Insurance",\n  "Insurance",\n  "Insurance"\n]        1
Name: count, Length: 4782, dtype: int64

In [32]:
posts_df['BENEFIT_SUBCATEGORY_NAME'].value_counts()

BENEFIT_SUBCATEGORY_NAME
[]                                                                                                                                                                                                                       50501
[\n  "Flexible Work Schedules"\n]                                                                                                                                                                                         3027
[\n  "Bonuses/Stipends"\n]                                                                                                                                                                                                1521
[\n  "Professional Development"\n]                                                                                                                                                                                        1296
[\n  "401(k) Plans"\n]                                                                                                                                                                                                    1016
                                                                                                                                                                                                                         ...
[\n  "401(k) Plans",\n  "Professional Development",\n  "Bonuses/Stipends",\n  "Flexible Work Schedules",\n  "Discounts/Reimbursements"\n]                                                                                    1
[\n  "Paid Time Off (PTO)",\n  "Medical Leave",\n  "Financial Aid/Assistance",\n  "Professional Development",\n  "Other Retirement and Savings",\n  "Dental Insurance",\n  "Vision Insurance",\n  "Life Insurance"\n]        1
[\n  "Paid Time Off (PTO)",\n  "Sick Leave",\n  "401(k) Plans",\n  "Professional Development",\n  "Health Insurance",\n  "Relocation Assistance"\n]                                                                          1
[\n  "Paid Time Off (PTO)",\n  "401(k) Plans",\n  "Legal Services"\n]                                                                                                                                                        1
[\n  "Sick Leave",\n  "Flexible Work Schedules",\n  "Dental Insurance",\n  "Disability Insurance"\n]                                                                                                                         1
Name: count, Length: 9448, dtype: int64

In [39]:
# get a list of unique benefit subcategories
benefit_subcategories = posts_df['BENEFIT_SUBCATEGORY_NAME'].unique()
print(benefit_subcategories)

['[\n  "Paid Time Off (PTO)",\n  "401(k) Plans",\n  "Bonuses/Stipends",\n  "Health Insurance",\n  "Dental Insurance"\n]'
 '[]'
 '[\n  "Paid Time Off (PTO)",\n  "403(b) Tax-Sheltered Annuity Plans",\n  "Other Retirement and Savings",\n  "Dental Insurance",\n  "Vision Insurance",\n  "Disability Insurance"\n]'
 ...
 '[\n  "Paid Time Off (PTO)",\n  "Sick Leave",\n  "Dental Insurance",\n  "Vision Insurance",\n  "Life Insurance",\n  "Parental Leave"\n]'
 '[\n  "Paid Time Off (PTO)",\n  "Dental Insurance",\n  "Vision Insurance",\n  "Relocation Assistance"\n]'
 '[\n  "Sick Leave",\n  "Flexible Work Schedules",\n  "Dental Insurance",\n  "Disability Insurance"\n]']

In [45]:
benefit_subcategories = [str(x).strip() for x in benefit_subcategories if pd.notnull(x)]
# remove \n
benefit_subcategories = [x.replace('\n', '') for x in benefit_subcategories]
print(benefit_subcategories)
benefit_subcategories = [x for x in benefit_subcategories if x != 'nan' and x != 'None' and x != '']
print(benefit_subcategories)
# benefit_subcategories = set(benefit_subcategories)
# print(benefit_subcategories)

['[  "Paid Time Off (PTO)",  "401(k) Plans",  "Bonuses/Stipends",  "Health Insurance",  "Dental Insurance"]', '[]', '[  "Paid Time Off (PTO)",  "403(b) Tax-Sheltered Annuity Plans",  "Other Retirement and Savings",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance"]', '[  "401(k) Plans",  "Vision Insurance",  "Life Insurance"]', '[  "Paid Time Off (PTO)",  "401(k) Plans",  "Employee Stock Options (ESOs)",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance",  "Life Insurance",  "Discounts/Reimbursements"]', '[  "Paid Time Off (PTO)",  "401(k) Plans",  "Health and Wellness Programs",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance",  "Life Insurance"]', '[  "Paid Time Off (PTO)",  "Health Insurance"]', '[  "Paid Time Off (PTO)",  "Financial Aid/Assistance",  "Professional Development",  "401(k) Plans",  "Other Retirement and Savings",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Flexible Work Schedules"]', '[  "Paid Time Off (PTO)",  "401(k) Plans",  "Bonuses/Stipends"]', '[  "Paid Time Off (PTO)",  "Sick Leave",  "401(k) Plans",  "Life Insurance",  "Parental Leave"]', '[  "Paid Time Off (PTO)",  "401(k) Plans",  "Professional Development",  "Health and Wellness Programs",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Flexible Work Schedules",  "Life Insurance",  "Discounts/Reimbursements"]', '[  "Health and Wellness Programs",  "Paid Time Off (PTO)"]', '[  "Paid Time Off (PTO)",  "401(k) Plans",  "Employee Stock Options (ESOs)",  "Bonuses/Stipends",  "Health Insurance",  "Dental Insurance",  "Vision Insurance"]', '[  "Financial Aid/Assistance",  "401(k) Plans",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Life Insurance"]', '[  "401(k) Plans",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Flexible Work Schedules",  "Discounts/Reimbursements"]', '[  "Other Retirement and Savings",  "Health and Wellness Programs",  "Bonuses/Stipends",  "Health Insurance",  "Flexible Work Schedules",  "Transportation",  "Disability Insurance",  "Life Insurance",  "Critical Illness Insurance",  "Legal Services"]', '[  "Dental Insurance",  "Vision Insurance",  "Life Insurance"]', '[  "Paid Time Off (PTO)",  "401(k) Plans",  "Health Insurance",  "Transportation",  "Life Insurance"]', '[  "Paid Time Off (PTO)",  "401(k) Plans",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance",  "Life Insurance"]', '[  "Paid Time Off (PTO)",  "Financial Aid/Assistance",  "401(k) Plans",  "Other Retirement and Savings",  "Dental Insurance",  "Vision Insurance",  "Life Insurance"]', '[  "Dental Insurance",  "Vision Insurance"]', '[  "Discounts/Reimbursements"]', '[  "Paid Time Off (PTO)",  "Dental Insurance",  "Vision Insurance"]', '[  "Paid Time Off (PTO)",  "401(k) Plans",  "Health and Wellness Programs",  "Bonuses/Stipends",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Life Insurance",  "Discounts/Reimbursements",  "Parental Leave"]', '[  "Health and Wellness Programs"]', '[  "Health and Wellness Programs",  "Financial Aid/Assistance",  "401(k) Plans"]', '[  "Paid Time Off (PTO)",  "401(k) Plans",  "Other Retirement and Savings",  "Health and Wellness Programs",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance",  "Life Insurance"]', '[  "Paid Time Off (PTO)",  "401(k) Plans",  "Dental Insurance",  "Vision Insurance",  "Life Insurance"]', '[  "Paid Time Off (PTO)",  "401(k) Plans",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Life Insurance"]', '[  "Professional Development",  "Leadership Development",  "Life Insurance",  "Employee Stock Options (ESOs)"]', '[  "Paid Time Off (PTO)",  "401(k) Plans",  "Health Insurance",  "Dental Insurance"]', '[  "Transportation"]', '[  "Financial Aid/Assistance",  "Professional Development",  "401(k) Plans",  "Employee Stock Options (ESOs)",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance"]', '[  "Flexible Work Schedules"]', '[  "Paid Time Off (PTO)",  "Sick Leave"]', '[  "Professional Development"]', '[  "Paid Time Off (PTO)",  "401(k) Plans",  "Professional Development",  "Other Retirement and Savings",  "Health and Wellness Programs",  "Dental Insurance",  "Vision Insurance",  "Child/Elder Care",  "Life Insurance"]', '[  "Paid Time Off (PTO)",  "401(k) Plans",  "Flexible Work Schedules",  "Discounts/Reimbursements"]', '[  "Paid Time Off (PTO)",  "401(k) Plans",  "Employee Stock Options (ESOs)",  "Health and Wellness Programs",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Life Insurance"]', '[  "Paid Time Off (PTO)",  "Other Retirement and Savings"]', '[  "401(k) Plans"]', '[  "Flexible Work Schedules",  "Professional Development",  "Discounts/Reimbursements"]', '[  "Paid Time Off (PTO)",  "401(k) Plans",  "Employee Stock Options (ESOs)",  "Life Insurance",  "Parental Leave"]', '[  "Paid Time Off (PTO)",  "Health Insurance",  "Discounts/Reimbursements"]', '[  "Paid Time Off (PTO)",  "Health Insurance",  "Dental Insurance",  "Vision Insurance"]', '[  "Paid Time Off (PTO)",  "401(k) Plans",  "Professional Development",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Parental Leave"]', '[  "Paid Time Off (PTO)",  "Sick Leave",  "Life Insurance"]', '[  "Life Insurance"]', '[  "Paid Time Off (PTO)",  "Financial Aid/Assistance",  "401(k) Plans",  "Health and Wellness Programs",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance",  "Life Insurance"]', '[  "Paid Time Off (PTO)",  "Dental Insurance",  "Vision Insurance",  "Life Insurance"]', '[  "Paid Time Off (PTO)",  "Flexible Work Schedules",  "Dental Insurance",  "Vision Insurance"]', '[  "Bonuses/Stipends"]', '[  "Paid Time Off (PTO)"]', '[  "Paid Time Off (PTO)",  "Sick Leave",  "Financial Aid/Assistance",  "Other Retirement and Savings",  "Health and Wellness Programs",  "Life Insurance"]', '[  "Sick Leave",  "Dental Insurance",  "Vision Insurance",  "Life Insurance"]', '[  "Relocation Assistance"]', '[  "Paid Time Off (PTO)",  "401(k) Plans",  "Professional Development",  "Other Retirement and Savings",  "Bonuses/Stipends",  "Health Insurance",  "Disability Insurance",  "Life Insurance"]', '[  "Paid Time Off (PTO)",  "401(k) Plans",  "Health and Wellness Programs",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Life Insurance"]', '[  "Dental Insurance",  "Employee Stock Options (ESOs)"]', '[  "401(k) Plans",  "Life Insurance"]', '[  "401(k) Plans",  "Health Insurance",  "Flexible Work Schedules"]', '[  "401(k) Plans",  "Health Insurance"]', '[  "Paid Time Off (PTO)",  "Discounts/Reimbursements",  "Parental Leave"]', '[  "Paid Time Off (PTO)",  "Financial Aid/Assistance",  "Professional Development",  "401(k) Plans",  "403(b) Tax-Sheltered Annuity Plans",  "Health Insurance",  "Dental Insurance"]', '[  "Paid Time Off (PTO)",  "401(k) Plans",  "Professional Development",  "Employee Stock Options (ESOs)",  "Dental Insurance",  "Discounts/Reimbursements"]', '[  "Sick Leave",  "401(k) Plans",  "Health and Wellness Programs",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance",  "Transportation"]', '[  "Health and Wellness Programs",  "Paid Time Off (PTO)",  "Flexible Work Schedules",  "Employee Stock Options (ESOs)"]', '[  "Health and Wellness Programs",  "Paid Time Off (PTO)",  "Health Insurance",  "Vision Insurance"]', '[  "Paid Time Off (PTO)",  "401(k) Plans",  "Employee Stock Options (ESOs)",  "Health and Wellness Programs",  "Health Insurance",  "Life Insurance"]', '[  "Financial Aid/Assistance",  "401(k) Plans",  "Other Retirement and Savings",  "Employee Stock Options (ESOs)",  "Health and Wellness Programs",  "Health Insurance",  "Flexible Work Schedules",  "Vision Insurance",  "Critical Illness Insurance",  "Employee Programs",  "Parental Leave"]', '[  "Paid Time Off (PTO)",  "401(k) Plans",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Transportation"]', '[  "Paid Time Off (PTO)",  "401(k) Plans",  "Other Retirement and Savings",  "Employee Stock Options (ESOs)",  "Health Insurance",  "Dental Insurance",  "Vision Insurance"]', '[  "Bonuses/Stipends",  "Flexible Work Schedules"]', '[  "Paid Time Off (PTO)",  "Sick Leave",  "Other Retirement and Savings",  "Health Insurance",  "Dental Insurance"]', '[  "Paid Time Off (PTO)",  "Sick Leave",  "401(k) Plans",  "Dental Insurance",  "Vision Insurance",  "Life Insurance",  "Parental Leave"]', '[  "Paid Time Off (PTO)",  "401(k) Plans",  "Health and Wellness Programs",  "Bonuses/Stipends",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance",  "Life Insurance",  "Flexible Work Schedules",  "Employee Programs",  "Parental Leave"]', '[  "Paid Time Off (PTO)",  "Financial Aid/Assistance",  "401(k) Plans",  "Dental Insurance",  "Vision Insurance"]', '[  "Paid Time Off (PTO)",  "401(k) Plans",  "Health Insurance",  "Dental Insurance",  "Vision Insurance"]', '[  "Leadership Development"]', '[  "Paid Time Off (PTO)",  "Floating Holidays",  "401(k) Plans",  "Health and Wellness Programs",  "Dental Insurance",  "Vision Insurance",  "Life Insurance"]', '[  "Paid Time Off (PTO)",  "Life Insurance"]', '[  "Mentorships"]', '[  "Paid Time Off (PTO)",  "Professional Development",  "Other Retirement and Savings",  "Health and Wellness Programs",  "Health Insurance",  "Life Insurance",  "Employee Programs"]', '[  "Employee Stock Options (ESOs)"]', '[  "Bonuses/Stipends",  "Professional Development",  "Discounts/Reimbursements"]', '[  "Paid Time Off (PTO)",  "Sick Leave",  "401(k) Plans",  "Professional Development",  "Employee Stock Options (ESOs)",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance",  "Life Insurance"]', '[  "Paid Time Off (PTO)",  "Volunteer Time Off (VTO)",  "401(k) Plans",  "Professional Development",  "Leadership Development",  "Bonuses/Stipends",  "Flexible Work Schedules",  "Dental Insurance",  "Vision Insurance",  "Transportation",  "Life Insurance"]', '[  "401(k) Plans",  "Professional Development",  "Bonuses/Stipends",  "Dental Insurance",  "Vision Insurance"]', '[  "Paid Time Off (PTO)",  "Sick Leave",  "Financial Aid/Assistance",  "Bonuses/Stipends",  "Flexible Work Schedules",  "Dental Insurance",  "Vision Insurance",  "Life Insurance"]', '[  "Paid Time Off (PTO)",  "401(k) Plans",  "Health and Wellness Programs",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Flexible Work Schedules",  "Life Insurance",  "Parental Leave"]', '[  "Paid Time Off (PTO)",  "401(k) Plans",  "Employee Stock Options (ESOs)",  "Flexible Work Schedules",  "Dental Insurance",  "Vision Insurance",  "Life Insurance"]', '[  "Paid Time Off (PTO)",  "Other Retirement and Savings",  "Health and Wellness Programs",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance",  "Life Insurance",  "Discounts/Reimbursements"]', '[  "Paid Time Off (PTO)",  "401(k) Plans"]', '[  "Paid Time Off (PTO)",  "401(k) Plans",  "Professional Development",  "Other Retirement and Savings",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Transportation"]', '[  "Paid Time Off (PTO)",  "Financial Aid/Assistance",  "401(k) Plans",  "Leadership Development",  "Other Retirement and Savings",  "Health and Wellness Programs",  "Relocation Assistance",  "Life Insurance",  "Parental Leave"]', '[  "Bonuses/Stipends",  "Health Insurance"]', '[  "Paid Time Off (PTO)",  "Financial Aid/Assistance",  "Professional Development",  "401(k) Plans"]', '[  "Paid Time Off (PTO)",  "Financial Aid/Assistance",  "401(k) Plans",  "Bonuses/Stipends",  "Health Insurance",  "Dental Insurance",  "Vision Insurance"]', '[  "Paid Time Off (PTO)",  "Sick Leave",  "401(k) Plans",  "Other Retirement and Savings",  "Health and Wellness Programs",  "Health Insurance",  "Dental Insurance",  "Disability Insurance",  "Parental Leave"]', '[  "Paid Time Off (PTO)",  "401(k) Plans",  "Dental Insurance",  "Vision Insurance"]', '[  "Paid Time Off (PTO)",  "Discounts/Reimbursements"]', '[  "401(k) Plans",  "Bonuses/Stipends",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance",  "Life Insurance",  "Flexible Work Schedules"]', '[  "Paid Time Off (PTO)",  "401(k) Plans",  "Professional Development",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Flexible Work Schedules"]', '[  "Paid Time Off (PTO)",  "Financial Aid/Assistance",  "401(k) Plans",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance",  "Life Insurance"]', '[  "Paid Time Off (PTO)",  "Sick Leave",  "Bereavement/Mental Health Leave",  "401(k) Plans",  "Professional Development",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Life Insurance"]', '[  "Paid Time Off (PTO)",  "Financial Aid/Assistance",  "401(k) Plans",  "Health and Wellness Programs",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance",  "Life Insurance"]', '[  "Paid Time Off (PTO)",  "Employee Stock Options (ESOs)",  "Health and Wellness Programs",  "Dental Insurance",  "Vision Insurance",  "Life Insurance"]', '[  "401(k) Plans",  "Professional Development",  "Other Retirement and Savings",  "Health and Wellness Programs",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Life Insurance",  "Discounts/Reimbursements"]', '[  "Financial Aid/Assistance",  "401(k) Plans",  "Employee Stock Options (ESOs)",  "Dental Insurance",  "Vision Insurance",  "Parental Leave"]', '[  "Paid Time Off (PTO)",  "401(k) Plans",  "Other Retirement and Savings",  "Health and Wellness Programs",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Life Insurance"]', '[  "Paid Time Off (PTO)",  "401(k) Plans",  "Other Retirement and Savings",  "Health and Wellness Programs",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance"]', '[  "Financial Aid/Assistance",  "Health Insurance",  "Flexible Work Schedules",  "Employee Programs"]', '[  "Paid Time Off (PTO)",  "Financial Aid/Assistance",  "401(k) Plans",  "Employee Stock Options (ESOs)",  "Transportation",  "Life Insurance",  "Parental Leave"]', '[  "Paid Time Off (PTO)",  "Bereavement/Mental Health Leave",  "401(k) Plans",  "Other Retirement and Savings",  "Dental Insurance",  "Disability Insurance",  "Life Insurance"]', '[  "Paid Time Off (PTO)",  "401(k) Plans",  "Professional Development",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance",  "Life Insurance"]', '[  "401(k) Plans",  "Dental Insurance",  "Vision Insurance",  "Discounts/Reimbursements"]', '[  "Paid Time Off (PTO)",  "Health Insurance",  "Disability Insurance"]', '[  "Medical Leave",  "Relocation Assistance"]', '[  "Paid Time Off (PTO)",  "401(k) Plans",  "Health and Wellness Programs",  "Bonuses/Stipends",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance",  "Life Insurance",  "Flexible Work Schedules",  "Parental Leave"]', '[  "Health Insurance",  "Disability Insurance"]', '[  "Paid Time Off (PTO)",  "Sick Leave",  "401(k) Plans",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Life Insurance"]', '[  "Paid Time Off (PTO)",  "Sick Leave",  "Employee Stock Options (ESOs)",  "Health and Wellness Programs",  "Bonuses/Stipends",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Life Insurance"]', '[  "Health Insurance"]', '[  "Health and Wellness Programs",  "Bonuses/Stipends",  "Health Insurance",  "Transportation",  "Disability Insurance",  "Life Insurance"]', '[  "Sick Leave",  "Other Retirement and Savings"]', '[  "Professional Development",  "Dental Insurance",  "Vision Insurance"]', '[  "401(k) Plans",  "Bonuses/Stipends",  "Flexible Work Schedules",  "Dental Insurance",  "Vision Insurance"]', '[  "Paid Time Off (PTO)",  "401(k) Plans",  "Health and Wellness Programs",  "Dental Insurance",  "Vision Insurance",  "Life Insurance",  "Discounts/Reimbursements",  "Employee Programs",  "Parental Leave"]', '[  "Paid Time Off (PTO)",  "401(k) Plans",  "Professional Development",  "Employee Stock Options (ESOs)",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance",  "Life Insurance",  "Flexible Work Schedules"]', '[  "Paid Time Off (PTO)",  "Flexible Work Schedules"]', '[  "401(k) Plans",  "Flexible Work Schedules",  "Discounts/Reimbursements"]', '[  "Sick Leave",  "Floating Holidays"]', '[  "Disability Insurance"]', '[  "Flexible Work Schedules",  "Discounts/Reimbursements"]', '[  "Paid Time Off (PTO)",  "Financial Aid/Assistance",  "401(k) Plans",  "Other Retirement and Savings",  "Dental Insurance",  "Vision Insurance",  "Life Insurance",  "Parental Leave"]', '[  "Paid Time Off (PTO)",  "401(k) Plans",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Flexible Work Schedules",  "Life Insurance",  "Relocation Assistance"]', '[  "Paid Time Off (PTO)",  "Financial Aid/Assistance",  "401(k) Plans",  "Employee Stock Options (ESOs)",  "Health Insurance"]', '[  "Paid Time Off (PTO)",  "Financial Aid/Assistance",  "Professional Development",  "Parental Leave"]', '[  "Health Insurance",  "Dental Insurance",  "Vision Insurance"]', '[  "Paid Time Off (PTO)",  "Financial Aid/Assistance",  "401(k) Plans",  "Mentorships",  "Bonuses/Stipends",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Life Insurance"]', '[  "401(k) Plans",  "Health Insurance",  "Dental Insurance"]', '[  "Paid Time Off (PTO)",  "Other Retirement and Savings",  "Health and Wellness Programs",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance",  "Life Insurance",  "Flexible Work Schedules",  "Transportation",  "Discounts/Reimbursements"]', '[  "Bonuses/Stipends",  "Dental Insurance",  "Vision Insurance"]', '[  "Paid Time Off (PTO)",  "Sick Leave",  "401(k) Plans",  "Health Insurance",  "Dental Insurance",  "Life Insurance",  "Parental Leave"]', '[  "Sick Leave",  "401(k) Plans"]', '[  "Financial Aid/Assistance",  "401(k) Plans",  "Health Insurance",  "Dental Insurance",  "Relocation Assistance"]', '[  "401(k) Plans",  "Bonuses/Stipends",  "Vision Insurance",  "Life Insurance",  "Discounts/Reimbursements"]', '[  "Paid Time Off (PTO)",  "401(k) Plans",  "Health and Wellness Programs",  "Vision Insurance",  "Disability Insurance",  "Life Insurance",  "Discounts/Reimbursements"]', '[  "Health Insurance",  "Other Retirement and Savings"]', '[  "Health and Wellness Programs",  "Paid Time Off (PTO)",  "Health Insurance",  "401(k) Plans"]', '[  "401(k) Plans",  "Discounts/Reimbursements"]', '[  "Paid Time Off (PTO)",  "Floating Holidays",  "401(k) Plans",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance",  "Life Insurance",  "Relocation Assistance"]', '[  "Paid Time Off (PTO)",  "401(k) Plans",  "Other Retirement and Savings",  "Dental Insurance",  "Vision Insurance"]', '[  "Professional Development",  "Health Insurance",  "Dental Insurance"]', '[  "Paid Time Off (PTO)",  "Bonuses/Stipends",  "Professional Development"]', '[  "Health Insurance",  "Discounts/Reimbursements"]', '[  "Flexible Work Schedules",  "Professional Development",  "Health Insurance"]', '[  "Paid Time Off (PTO)",  "401(k) Plans",  "Discounts/Reimbursements"]', '[  "Paid Time Off (PTO)",  "401(k) Plans",  "Other Retirement and Savings",  "Employee Stock Options (ESOs)",  "Health Insurance",  "Dental Insurance",  "Life Insurance",  "Legal Services"]', '[  "Paid Time Off (PTO)",  "457(b) Deferred Compensation Plans",  "403(b) Tax-Sheltered Annuity Plans",  "Other Retirement and Savings",  "Bonuses/Stipends"]', '[  "Bonuses/Stipends",  "Financial Aid/Assistance"]', '[  "Paid Time Off (PTO)",  "Financial Aid/Assistance",  "Dental Insurance",  "Vision Insurance",  "Employee Programs"]', '[  "Paid Time Off (PTO)",  "Sick Leave",  "401(k) Plans",  "Ot

In [47]:
sorted(set(benefit_subcategories))

['[  "401(a) Plans",  "Other Retirement and Savings",  "Dental Insurance",  "Vision Insurance",  "Life Insurance"]',
 '[  "401(a) Plans",  "Other Retirement and Savings"]',
 '[  "401(k) Plans",  "401(a) Plans",  "Other Retirement and Savings",  "Employee Stock Options (ESOs)"]',
 '[  "401(k) Plans",  "403(b) Tax-Sheltered Annuity Plans",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance",  "Life Insurance"]',
 '[  "401(k) Plans",  "403(b) Tax-Sheltered Annuity Plans",  "Health and Wellness Programs",  "Bonuses/Stipends",  "Health Insurance",  "Dental Insurance",  "Vision Insurance"]',
 '[  "401(k) Plans",  "403(b) Tax-Sheltered Annuity Plans",  "Other Retirement and Savings",  "Health and Wellness Programs",  "Health Insurance",  "Dental Insurance",  "Vision Insurance"]',
 '[  "401(k) Plans",  "457(b) Deferred Compensation Plans",  "403(b) Tax-Sheltered Annuity Plans",  "Health and Wellness Programs",  "Dental Insurance",  "Vision Insurance",  "Life Insurance"]',
 '[  "401(k) Plans",  "457(b) Deferred Compensation Plans",  "403(b) Tax-Sheltered Annuity Plans",  "Health and Wellness Programs",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance",  "Life Insurance"]',
 '[  "401(k) Plans",  "457(b) Deferred Compensation Plans",  "Dental Insurance",  "Vision Insurance",  "Life Insurance"]',
 '[  "401(k) Plans",  "457(b) Deferred Compensation Plans",  "Other Retirement and Savings",  "Bonuses/Stipends",  "Relocation Assistance"]',
 '[  "401(k) Plans",  "457(b) Deferred Compensation Plans",  "Other Retirement and Savings",  "Health and Wellness Programs",  "Health Insurance",  "Flexible Work Schedules",  "Life Insurance",  "Discounts/Reimbursements"]',
 '[  "401(k) Plans",  "Bereavement/Mental Health Leave"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance",  "Discounts/Reimbursements"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance",  "Life Insurance",  "Discounts/Reimbursements"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance",  "Life Insurance",  "Relocation Assistance"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance",  "Life Insurance",  "Transportation",  "Parental Leave"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance",  "Life Insurance"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Dental Insurance",  "Vision Insurance",  "Discounts/Reimbursements"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Dental Insurance",  "Vision Insurance",  "Life Insurance"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Dental Insurance",  "Vision Insurance",  "Parental Leave"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Dental Insurance",  "Vision Insurance",  "Relocation Assistance",  "Life Insurance"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Dental Insurance",  "Vision Insurance",  "Relocation Assistance"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Dental Insurance",  "Vision Insurance",  "Transportation",  "Discounts/Reimbursements"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Disability Insurance",  "Critical Illness Insurance",  "Discounts/Reimbursements"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Disability Insurance",  "Life Insurance",  "Critical Illness Insurance"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Flexible Work Schedules",  "Dental Insurance",  "Vision Insurance",  "Life Insurance",  "Parental Leave"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Flexible Work Schedules",  "Dental Insurance",  "Vision Insurance",  "Life Insurance"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Flexible Work Schedules",  "Dental Insurance",  "Vision Insurance"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Flexible Work Schedules",  "Discounts/Reimbursements",  "Employee Programs"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Flexible Work Schedules",  "Life Insurance",  "Discounts/Reimbursements",  "Employee Programs"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Health Insurance",  "Dental Insurance",  "Disability Insurance",  "Life Insurance"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Health Insurance",  "Dental Insurance",  "Disability Insurance"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Health Insurance",  "Dental Insurance",  "Flexible Work Schedules"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Health Insurance",  "Dental Insurance",  "Life Insurance",  "Discounts/Reimbursements"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Health Insurance",  "Dental Insurance",  "Life Insurance",  "Parental Leave"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Health Insurance",  "Dental Insurance",  "Life Insurance"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Health Insurance",  "Dental Insurance",  "Transportation",  "Parental Leave"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance",  "Discounts/Reimbursements"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance",  "Life Insurance",  "Flexible Work Schedules"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance",  "Life Insurance",  "Transportation",  "Parental Leave"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance",  "Life Insurance"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Discounts/Reimbursements"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Flexible Work Schedules",  "Discounts/Reimbursements",  "Employee Programs"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Flexible Work Schedules",  "Discounts/Reimbursements"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Flexible Work Schedules",  "Life Insurance",  "Transportation"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Flexible Work Schedules",  "Life Insurance"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Flexible Work Schedules",  "Transportation"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Flexible Work Schedules"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Life Insurance"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Parental Leave"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Relocation Assistance"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Transportation",  "Discounts/Reimbursements"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Transportation",  "Parental Leave"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Transportation"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Health Insurance",  "Dental Insurance",  "Vision Insurance"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Health Insurance",  "Flexible Work Schedules",  "Discounts/Reimbursements"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Health Insurance",  "Flexible Work Schedules",  "Life Insurance"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Health Insurance",  "Flexible Work Schedules",  "Transportation"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Health Insurance",  "Life Insurance",  "Discounts/Reimbursements"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Health Insurance",  "Vision Insurance",  "Life Insurance",  "Parental Leave"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Health Insurance",  "Vision Insurance",  "Life Insurance"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Transportation",  "Dental Insurance",  "Life Insurance"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Transportation",  "Dental Insurance",  "Vision Insurance"]',
 '[  "401(k) Plans",  "Bonuses/Stipends",  "Vision Insurance",  "Life Insurance",  "Discounts/Reimbursements"]',
 '[  "401(k) Plans",  "Dental Insurance",  "Disability Insurance",  "Life Insurance"]',
 '[  "401(k) Plans",  "Dental Insurance",  "Disability Insurance"]',
 '[  "401(k) Plans",  "Dental Insurance",  "Discounts/Reimbursements"]',
 '[  "401(k) Plans",  "Dental Insurance",  "Employee Stock Options (ESOs)"]',
 '[  "401(k) Plans",  "Dental Insurance",  "Leadership Development",  "Vision Insurance"]',
 '[  "401(k) Plans",  "Dental Insurance",  "Life Insurance",  "Other Retirement and Savings"]',
 '[  "401(k) Plans",  "Dental Insurance",  "Life Insurance"]',
 '[  "401(k) Plans",  "Dental Insurance",  "Other Retirement and Savings"]',
 '[  "401(k) Plans",  "Dental Insurance",  "Parental Leave"]',
 '[  "401(k) Plans",  "Dental Insurance",  "Relocation Assistance",  "Disability Insurance",  "Life Insurance"]',
 '[  "401(k) Plans",  "Dental Insurance",  "Relocation Assistance",  "Disability Insurance"]',
 '[  "401(k) Plans",  "Dental Insurance",  "Relocation Assistance",  "Vision Insurance",  "Disability Insurance"]',
 '[  "401(k) Plans",  "Dental Insurance",  "Transportation",  "Disability Insurance",  "Life Insurance",  "Discounts/Reimbursements"]',
 '[  "401(k) Plans",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance",  "Discounts/Reimbursements"]',
 '[  "401(k) Plans",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance",  "Life Insurance",  "Critical Illness Insurance"]',
 '[  "401(k) Plans",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance",  "Life Insurance",  "Discounts/Reimbursements"]',
 '[  "401(k) Plans",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance",  "Life Insurance",  "Parental Leave"]',
 '[  "401(k) Plans",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance",  "Life Insurance",  "Transportation"]',
 '[  "401(k) Plans",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance",  "Life Insurance"]',
 '[  "401(k) Plans",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance",  "Transportation",  "Parental Leave"]',
 '[  "401(k) Plans",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance"]',
 '[  "401(k) Plans",  "Dental Insurance",  "Vision Insurance",  "Discounts/Reimbursements"]',
 '[  "401(k) Plans",  "Dental Insurance",  "Vision Insurance",  "Employee Programs"]',
 '[  "401(k) Plans",  "Dental Insurance",  "Vision Insurance",  "Employee Stock Options (ESOs)"]',
 '[  "401(k) Plans",  "Dental Insurance",  "Vision Insurance",  "Fitness Centers/Gyms"]',
 '[  "401(k) Plans",  "Dental Insurance",  "Vision Insurance",  "Life Insurance",  "Discounts/Reimbursements"]',
 '[  "401(k) Plans",  "Dental Insurance",  "Vision Insurance",  "Life Insurance",  "Employee Programs"]',
 '[  "401(k) Plans",  "Dental Insurance",  "Vision Insurance",  "Life Insurance",  "Parental Leave"]',
 '[  "401(k) Plans",  "Dental Insurance",  "Vision Insurance",  "Life Insurance"]',
 '[  "401(k) Plans",  "Dental Insurance",  "Vision Insurance",  "Mental Health"]',
 '[  "401(k) Plans",  "Dental Insurance",  "Vision Insurance",  "Other Retirement and Savings"]',
 '[  "401(k) Plans",  "Dental Insurance",  "Vision Insurance",  "Parental Leave"]',
 '[  "401(k) Plans",  "Dental Insurance",  "Vision Insurance",  "Relocation Assistance",  "Life Insurance"]',
 '[  "401(k) Plans",  "Dental Insurance",  "Vision Insurance",  "Relocation Assistance"]',
 '[  "401(k) Plans",  "Dental Insurance",  "Vision Insurance",  "Transportation",  "Life Insurance",  "Employee Programs"]',
 '[  "401(k) Plans",  "Dental Insurance",  "Vision Insurance",  "Transportation",  "Life Insurance",  "Legal Services"]',
 '[  "401(k) Plans",  "Dental Insurance",  "Vision Insurance"]',
 '[  "401(k) Plans",  "Dental Insurance"]',
 '[  "401(k) Plans",  "Disability Insurance",  "Employee Stock Options (ESOs)"]',
 '[  "401(k) Plans",  "Disability Insurance",  "Life Insurance",  "Employee Stock Options (ESOs)"]',
 '[  "401(k) Plans",  "Disability Insurance",  "Life Insurance",  "Other Retirement and Savings"]',
 '[  "401(k) Plans",  "Disability Insurance",  "Life Insurance"]',
 '[  "401(k) Plans",  "Disability Insurance",  "Other Retirement and Savings"]',
 '[  "401(k) Plans",  "Disability Insurance"]',
 '[  "401(k) Plans",  "Discounts/Reimbursements",  "Disability Insurance",  "Life Insurance"]',
 '[  "401(k) Plans",  "Discounts/Reimbursements",  "Employee Programs"]',
 '[  "401(k) Plans",  "Discounts/Reimbursements",  "Employee Stock Options (ESOs)"]',
 '[  "401(k) Plans",  "Discounts/Reimbursements",  "Floating Holidays"]',
 '[  "401(k) Plans",  "Discounts/Reimbursements",  "Life Insurance",  "Employee Stock Options (ESOs)"]',
 '[  "401(k) Plans",  "Discounts/Reimbursements",  "Life Insurance",  "Other Retirement and Savings"]',
 '[  "401(k) Plans",  "Discounts/Reimbursements",  "Other Retirement and Savings",  "Employee Stock Options (ESOs)"]',
 '[  "401(k) Plans",  "Discounts/Reimbursements",  "Other Retirement and Savings"]',
 '[  "401(k) Plans",  "Discounts/Reimbursements",  "Parental Leave"]',
 '[  "401(k) Plans",  "Discounts/Reimbursements",  "Vision Insurance",  "Life Insurance"]',
 '[  "401(k) Plans",  "Discounts/Reimbursements",  "Vision Insurance",  "Other Retirement and Savings"]',
 '[  "401(k) Plans",  "Discounts/Reimbursements",  "Vision Insurance"]',
 '[  "401(k) Plans",  "Discounts/Reimbursements"]',
 '[  "401(k) Plans",  "Employee Programs",  "Other Retirement and Savings"]',
 '[  "401(k) Plans",  "Employee Programs"]',
 '[  "401(k) Plans",  "Employee Stock Options (ESOs)",  "Bonuses/Stipends",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance",  "Life Insurance",  "Relocation Assistance"]',
 '[  "401(k) Plans",  "Employee Stock Options (ESOs)",  "Bonuses/Stipends",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance",  "Life Insurance"]',
 '[  "401(k) Plans",  "Employee Stock Options (ESOs)",  "Bonuses/Stipends",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance"]',
 '[  "401(k) Plans",  "Employee Stock Options (ESOs)",  "Bonuses/Stipends",  "Dental Insurance",  "Vision Insurance",  "Discounts/Reimbursements"]',
 '[  "401(k) Plans",  "Employee Stock Options (ESOs)",  "Bonuses/Stipends",  "Dental Insurance",  "Vision Insurance",  "Life Insurance",  "Discounts/Reimbursements"]',
 '[  "401(k) Plans",  "Employee Stock Options (ESOs)",  "Bonuses/Stipends",  "Dental Insurance",  "Vision Insurance",  "Life Insurance",  "Parental Leave"]',
 '[  "401(k) Plans",  "Employee Stock Options (ESOs)",  "Bonuses/Stipends",  "Dental Insurance",  "Vision Insurance",  "Life Insurance"]',
 '[  "401(k) Plans",  "Employee Stock Options (ESOs)",  "Bonuses/Stipends",  "Dental Insurance",  "Vision Insurance"]',
 '[  "401(k) Plans",  "Employee Stock Options (ESOs)",  "Bonuses/Stipends",  "Flexible Work Schedules",  "Dental Insurance",  "Vision Insurance"]',
 '[  "401(k) Plans",  "Employee Stock Options (ESOs)",  "Bonuses/Stipends",  "Flexible Work Schedules",  "Transportation"]',
 '[  "401(k) Plans",  "Employee Stock Options (ESOs)",  "Bonuses/Stipends",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance",  "Life Insurance"]',
 '[  "401(k) Plans",  "Employee Stock Options (ESOs)",  "Bonuses/Stipends",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Life Insurance",  "Discounts/Reimbursements"]',
 '[  "401(k) Plans",  "Employee Stock Options (ESOs)",  "Bonuses/Stipends",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Life Insurance"]',
 '[  "401(k) Plans",  "Employee Stock Options (ESOs)",  "Bonuses/Stipends",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Transportation",  "Life Insurance",  "Discounts/Reimbursements",  "Parental Leave"]',
 '[  "401(k) Plans",  "Employee Stock Options (ESOs)",  "Bonuses/Stipends",  "Health Insurance",  "Disability Insurance"]',
 '[  "401(k) Plans",  "Employee Stock Options (ESOs)",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance",  "Life Insurance",  "Legal Services"]',
 '[  "401(k) Plans",  "Employee Stock Options (ESOs)",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance",  "Life Insurance",  "Relocation Assistance"]',
 '[  "401(k) Plans",  "Employee Stock Options (ESOs)",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance",  "Life Insurance"]',
 '[  "401(k) Plans",  "Employee Stock Options (ESOs)",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance"]',
 '[  "401(k) Plans",  "Employee Stock Options (ESOs)",  "Dental Insurance",  "Vision Insurance",  "Life Insurance",  "Parental Leave"]',
 '[  "401(k) Plans",  "Employee Stock Options (ESOs)",  "Dental Insurance",  "Vision Insurance",  "Life Insurance"]',
 '[  "401(k) Plans",  "Employee Stock Options (ESOs)",  "Dental Insurance",  "Vision Insurance",  "Parental Leave"]',
 '[  "401(k) Plans",  "Employee Stock Options (ESOs)",  "Dental Insurance",  "Vision Insurance",  "Relocation Assistance"]',
 '[  "401(k) Plans",  "Employee Stock Options (ESOs)",  "Dental Insurance",  "Vision Insurance",  "Transportation",  "Parental Leave"]',
 '[  "401(k) Plans",  "Employee Stock Options (ESOs)",  "Disability Insurance",  "Parental Leave"]',
 '[  "401(k) Plans",  "Employee Stock Options (ESOs)",  "Flexible Work Schedules",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance",  "Life Insurance"]',
 '[  "401(k) Plans",  "Employee Stock Options (ESOs)",  "Flexible Work Schedules",  "Dental Insurance",  "Vision Insurance",  "Legal Services"]',
 '[  "401(k) Plans",  "Employee Stock Options (ESOs)",  "Health Insurance",  "Dental Insurance",  "Disability Insurance",  "Life Insurance"]',
 '[  "401(k) Plans",  "Employee Stock Options (ESOs)",  "Health Insurance",  "Dental Insurance",  "Disability Insurance"]',
 '[  "401(k) Plans",  "Employee Stock Options (ESOs)",  "Health Insurance",  "Dental Insurance",  "Flexible Work Schedules"]',
 '[  "401(k) Plans",  "Employee Stock Options (ESOs)",  "Health Insurance",  "Dental Insurance",  "Life Insurance",  "Employee Programs"]',
 '[  "401(k) Plans",  "Employee Stock Options (ESOs)",  "Health Insurance",  "Dental Insurance",  "Life Insurance"]',
 '[  "401(k) Plans",  "Employee Stock Options (ESOs)",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance",  "Life Insurance",  "Employee Programs"]',
 '[  "401(k) Plans",  "Employee Stock Options (ESOs)",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance",  "Life Insurance",  "Parental Leave"]',
 '[  "401(k) Plans",  "Employee Stock Options (ESOs)",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance",  "Life Insurance"]',
 '[  "401(k) Plans",  "Employee Stock Options (ESOs)",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Disability Insurance"]',
 '[  "401(k) Plans",  "Employee Stock Options (ESOs)",  "Health Insurance",  "Dental Insurance",  "Vision Insurance",  "Flexible Work Schedules",  "Discounts/Reimbursements"]',

In [49]:
sorted(set(
    sub.strip()
    for val in posts_df['BENEFIT_SUBCATEGORY_NAME'].dropna()
    for sub in str(val).split('\n')
    if sub.strip()
))

['"401(a) Plans"',
 '"401(a) Plans",',
 '"401(k) Plans"',
 '"401(k) Plans",',
 '"403(b) Tax-Sheltered Annuity Plans"',
 '"403(b) Tax-Sheltered Annuity Plans",',
 '"457(b) Deferred Compensation Plans"',
 '"457(b) Deferred Compensation Plans",',
 '"457(f) Supplemental Retirement Plans",',
 '"Bereavement/Mental Health Leave"',
 '"Bereavement/Mental Health Leave",',
 '"Bonuses/Stipends"',
 '"Bonuses/Stipends",',
 '"Child/Elder Care"',
 '"Child/Elder Care",',
 '"Company Events"',
 '"Company Events",',
 '"Critical Illness Insurance"',
 '"Critical Illness Insurance",',
 '"Dental Insurance"',
 '"Dental Insurance",',
 '"Disability Insurance"',
 '"Disability Insurance",',
 '"Discounts/Reimbursements"',
 '"Discounts/Reimbursements",',
 '"Employee Programs"',
 '"Employee Programs",',
 '"Employee Stock Options (ESOs)"',
 '"Employee Stock Options (ESOs)",',
 '"Financial Aid/Assistance"',
 '"Financial Aid/Assistance",',
 '"Fitness Centers/Gyms"',
 '"Fitness Centers/Gyms",',
 '"Flexible Work Schedules"',
 '"Flexible Work Schedules",',
 '"Floating Holidays"',
 '"Floating Holidays",',
 '"Health Insurance"',
 '"Health Insurance",',
 '"Health and Wellness Applications"',
 '"Health and Wellness Applications",',
 '"Health and Wellness Programs"',
 '"Health and Wellness Programs",',
 '"Health and Wellness Stipends"',
 '"Health and Wellness Stipends",',
 '"Jury Duty Leave"',
 '"Jury Duty Leave",',
 '"Leadership Development"',
 '"Leadership Development",',
 '"Legal Services"',
 '"Legal Services",',
 '"Life Insurance"',
 '"Life Insurance",',
 '"Medical Leave"',
 '"Medical Leave",',
 '"Mental Health"',
 '"Mental Health",',
 '"Mentorships"',
 '"Mentorships",',
 '"Mobile Plans/Devices"',
 '"Mobile Plans/Devices",',
 '"Other Retirement and Savings"',
 '"Other Retirement and Savings",',
 '"Paid Time Off (PTO)"',
 '"Paid Time Off (PTO)",',
 '"Parental Leave"',
 '"Personal Leave"',
 '"Personal Leave",',
 '"Professional Development"',
 '"Professional Development",',
 '"Relocation Assistance"',
 '"Relocation Assistance",',
 '"Sabbatical Leave",',
 '"Sick Leave"',
 '"Sick Leave",',
 '"Transportation"',
 '"Transportation",',
 '"Unemployment Insurance"',
 '"Unemployment Insurance",',
 '"Unpaid Leave"',
 '"Unpaid Leave",',
 '"Vision Insurance"',
 '"Vision Insurance",',
 '"Volunteer Time Off (VTO)"',
 '"Volunteer Time Off (VTO)",',
 '[',
 '[]',
 ']']

# Skills

In [7]:
skills_df = pd.read_csv('/Users/alejandracastaneda/Documents/Backup/beyond-salary-mb/data/OII_US_10M_SKILLS_MAY26_SUBSAMPLE.csv')

In [8]:
skills_df.head()

,ID,SKILL_ID,SKILL_NAME,SKILL_SUBCATEGORY_NAME,SKILL_CATEGORY_NAME
0,0fa8945cc2a78a1e40489ac0fcde084b894c7539,ES899BA440FA3441F22A,Workflow Management,Process Improvement and Optimization,Business
1,03b182f31e753fdcbc3b5fc9c6d6db7aed544882,KS1218W78FGVPVP2KXPX,Management,Business Management,Business
2,e02f4968e7b68084f737757b08667c439f11c06f,BGS8CFA33B3D9B49C56C,Concrete Forming,Concrete and Masonry,Architecture and Construction
3,0fa8945cc2a78a1e40489ac0fcde084b894c7539,BGSEE1E1C4671622F63B,Sales Support,Sales Management,Sales
4,610ec9ca254142cf3f3160d9688cf2f31e90e114,ES15B16B907D759C1EC2,Shipping And Receiving,General Shipping and Receiving,"Transportation, Supply Chain, and Logistics"

In [12]:
skills_df['SKILL_SUBCATEGORY_NAME'].value_counts()
# FIND SKILL SUBCATEGORY THAT CONTAINS AI
skills_df[skills_df['SKILL_SUBCATEGORY_NAME'].str.contains('AI', case=False, na=False)]['SKILL_SUBCATEGORY_NAME'].unique()

array(['Fundraising and Crowdsourcing', 'Promotions and Campaigns',
       'First Aid', 'Employee Training', 'Training Programs',
       'Vehicle Repair and Maintenance', 'Retail Sales',
       'Construction Painting', 'Roads and Drainage',
       'Equipment Repair and Maintenance', 'Supply Chain Management',
       'Facility Management and Maintenance',
       'General Repairs and Maintenance',
       'Artificial Intelligence and Machine Learning (AI/ML)',
       'Appliance Repair and Maintenance',
       'Insurance and Warranty Claims Processing', 'Rail Transportation',
       'Coaching and Athletic Training', 'Mainframe Technologies',
       'Air Quality and Emissions', 'Air Transportation',
       'Computer-Aided Manufacturing', 'Blockchain'], dtype=object)

In [25]:
pd.set_option('display.max_rows', 100)

In [26]:
# filter skills to subcategory Artificial Intelligence and Machine Learning (AI/ML)
ai_ml_skills = skills_df[skills_df['SKILL_SUBCATEGORY_NAME'] == 'Artificial Intelligence and Machine Learning (AI/ML)']
ai_ml_skills['SKILL_NAME'].head(100)

1832                              Artificial Intelligence
1919                                     Machine Learning
2253                                              Chatbot
2273                               Intelligent Automation
2375                                     Machine Learning
2774                              Artificial Intelligence
2881                   Generative Artificial Intelligence
3349                                        Deep Learning
3350                                     Machine Learning
3650                                     Machine Learning
3789                              Artificial Intelligence
3924                                              Chatbot
3936                                  Supervised Learning
3939                                        Deep Learning
3946                                     Machine Learning
3947                              Artificial Intelligence
3952                                   Feature Extraction
3958                          Machine Learning Algorithms
6135                           Artificial Neural Networks
8585                                   Automation Systems
9880                              Artificial Intelligence
10854                             Artificial Intelligence
11362                  Generative Artificial Intelligence
12878                             Artificial Intelligence
18799                  Generative Artificial Intelligence
18800                                       Bot Framework
19140                             Artificial Intelligence
19417                             Artificial Intelligence
19421                                    Machine Learning
19551                  Generative Artificial Intelligence
19891                             Artificial Intelligence
20292                                    Machine Learning
21422                  Generative Artificial Intelligence
22303    Machine Learning Model Monitoring And Evaluation
23188                                    Machine Learning
23220                          Artificial Neural Networks
24723                                    Machine Learning
24729                                 Intelligent Control
25535                       Scikit-Learn (Python Package)
25682                                    Machine Learning
25684                         Machine Learning Algorithms
26219                                  Automation Systems
27161                                    Machine Learning
27618                                    Machine Learning
27683                                    Machine Learning
27721                              Text Retrieval Systems
30337                                    Machine Learning
30502                                       Deep Learning
30503                                    Machine Learning
30506                             Artificial Intelligence
30507                       Long Short-Term Memory (LSTM)
31653                             Artificial Intelligence
32954                                    Machine Learning
32969                             Artificial Intelligence
33107                                  Systems Automation
33339                                      Responsible AI
33410                                           Claude AI
33456                             Automated Data Cleaning
35624                   Automated Planning And Scheduling
35891                  Generative Artificial Intelligence
36012                             Artificial Intelligence
36881                              Text Retrieval Systems
37555                             Artificial Intelligence
37796                                    Machine Learning
38428                             Artificial Intelligence
40369                                    Machine Learning
40901                                    Machine Learning
41336                             Artificial Intelligence
41338                                    Machine Learning
45754                                    Machine Learning
46060                                             Chatbot
46307                                          Agentic AI
46322                                    Machine Learning
46458                             Artificial Intelligence
46955                             Artificial Intelligence
47170                                      Responsible AI
47181                              Intelligent Automation
47731                             Artificial Intelligence
47928                   Automated Planning And Scheduling
48096                                  Systems Automation
49247                          Data Version Control (DVC)
50492                                Cognitive Automation
52144                  Generative Artificial Intelligence
52912                                 Feature Engineering
54167                                    Machine Learning
54667                                  Systems Automation
55245                                    Machine Learning
55251                            Applied Machine Learning
56021                             Artificial Intelligence
56135                                    Machine Learning
56515                             Artificial Intelligence
57338                             Artificial Intelligence
57866                             Artificial Intelligence
58287                                    Machine Learning
58297                             Artificial Intelligence
58299                         Machine Learning Algorithms
58300                          Artificial Neural Networks
58519                             Artificial Intelligence
58522                                    Machine Learning
61287                                    Machine Learning
Name: SKILL_NAME, dtype: object

In [27]:
# check if the word prompt is in ai ml skills
ai_ml_skills[ai_ml_skills['SKILL_NAME'].str.contains('prompt', case=False, na=False)]['SKILL_NAME'].unique()

array(['Prompt Engineering'], dtype=object)

In [9]:
skills_df['SKILL_CATEGORY_NAME'].value_counts()

SKILL_CATEGORY_NAME
Physical and Inherent Abilities                191350
Business                                       154947
Health Care                                    151529
Information Technology                         146746
Media and Communications                       101959
Law, Regulation, and Compliance                 68278
Finance                                         64769
Sales                                           64436
Administration                                  59570
Customer and Client Support                     44284
Transportation, Supply Chain, and Logistics     39341
Maintenance, Repair, and Facility Services      33638
Analysis                                        31619
Marketing and Public Relations                  26111
Science and Research                            24430
Engineering                                     24386
Education and Training                          22845
Manufacturing and Production                    21002
Hospitality and Food Services                   18041
Architecture and Construction                   18039
Human Resources                                 14811
Public Safety and National Security             11835
Design                                           8079
Economics, Policy, and Social Studies            6961
Social and Human Services                        5085
Environment                                      4794
Energy and Utilities                             3934
Property and Real Estate                         2388
Agriculture, Horticulture, and Landscaping       1771
Performing Arts, Sports, and Recreation          1632
Personal Care and Services                       1415
Name: count, dtype: int64

# Occupations

In [50]:
posts_df.columns

Index(['ID', 'POSTED', 'TITLE_RAW', 'COMPANY', 'COMPANY_NAME',
       'MIN_EDULEVELS_NAME', 'EMPLOYMENT_TYPE_NAME', 'MIN_YEARS_EXPERIENCE',
       'SALARY', 'REMOTE_TYPE_NAME', 'CITY_NAME', 'STATE_NAME', 'NAICS_2022_6',
       'NAICS_2022_6_NAME', 'ONET', 'ONET_NAME', 'BENEFIT_NAME',
       'BENEFIT_SUBCATEGORY_NAME', 'BENEFIT_CATEGORIES_NAME', 'YEAR',
       'QUARTER'],
      dtype='object')

In [51]:
posts_df[['ONET', 'ONET_NAME']]

             ONET                                       ONET_NAME
0      29-1141.00                               Registered Nurses
1      15-1299.09         Information Technology Project Managers
2      11-9111.00            Medical and Health Services Managers
3      37-3011.00          Landscaping and Groundskeeping Workers
4      29-1141.00                               Registered Nurses
...           ...                                             ...
99855  53-3032.00         Heavy and Tractor-Trailer Truck Drivers
99856  29-1217.00                                    Neurologists
99857  29-2031.00    Cardiovascular Technologists and Technicians
99858  29-1141.00                               Registered Nurses
99859  41-1011.00  First-Line Supervisors of Retail Sales Workers

[99860 rows x 2 columns]

In [52]:
posts_df[['NAICS_2022_6_NAME', 'NAICS_2022_6']]

                                       NAICS_2022_6_NAME  NAICS_2022_6
0           Direct Health and Medical Insurance Carriers        524114
1           Direct Health and Medical Insurance Carriers        524114
2                   Other Individual and Family Services        624190
3               Hotels (except Casino Hotels) and Motels        721110
4                 General Medical and Surgical Hospitals        622110
...                                                  ...           ...
99855  Process, Physical Distribution, and Logistics ...        541614
99856                                  National Security        928110
99857             General Medical and Surgical Hospitals        622110
99858             General Medical and Surgical Hospitals        622110
99859        Clothing and Clothing Accessories Retailers        458110

[99860 rows x 2 columns]